### ISSUE TITLE
Dark-mode button does not work on first press

### ISSUE THREAD

**Issue by fabiansiegel** [ransome1/sleek#10]
on the very first press after installation, the dark-dark mode button does not do anything.

afterwards it works, it can be reproduced by deleting ~/.config/sleek

this is probably due to this:

```
  if(switchTheme) {
    switch (theme) {
      case "dark":
        theme = "light";
        break;
      case "light":
        theme = "dark";
        break;
      case "system":
        theme = "light";
        break;
    }
```
which means: if system is already light, nothing changes. I'm not sure how to fix this bug.

Electron documentation says this:

> The usage of this property should align with a classic "dark mode" state machine in your application where the user has three options.
> 
>     Follow OS --> themeSource = 'system'
>     Dark Mode --> themeSource = 'dark'
>     Light Mode --> themeSource = 'light'
>

**Comment by ransome1** [comment]
For now I fixed it by defining theme to "light" on first start. Works fine, but isn't good enough yet.

I think Electron offers a method that will tell me the OS' specific setting. I will look it up and put a fix into the next release.

**Comment by fabiansiegel** [comment]
according to https://www.electronjs.org/docs/api/native-theme#nativethemethemesource
"shouldUseDarkColors" should indicate what theme to use (even if set to system). 

If set to "system", the theme changes when changing the system theme. (at least according to this:
https://github.com/electron/electron/issues/21899 , I could not find much in the documentation apart from https://www.electronjs.org/docs/api/native-theme#event-updated )

**Comment by ransome1** [comment]
Thanks for the hint.

I already fixed it using the shouldUseDarkColors method and it will be part of 0.6.0. From now on sleek will adjust to the OS setting, but only until the dark mode switch used for the first time. From there on the dark mode setting will be persisted and overwrite the OS' default.
