### ISSUE TITLE
Call for testing v1.0.0 (Pre-Release)

### ISSUE THREAD

**Issue by ransome1** [ransome1/sleek#101]
## Call for testing
I'm spending quite some time refactoring the code. Almost 10% have been reduced and together with some further tweaks, sleeks should now be even faster parsing the todo list and building the GUI.

This release is work in progress. Nevertheless I want to encourage you to use this in production and share your feedback.

Please don't expect fancy new features, this is an update on reducing technical depths. But on a side note, there are two little new features. You can now filter by priority in the filter drawer and sleek can interpret some markdown syntax like bold and italic text as well as markdown specific links.

Download it here: https://github.com/ransome1/sleek/releases/tag/v1.0.0

**Comment by shulist** [comment]
Got this error upon opening in Win10:
![Sleek100_JavaError](https://user-images.githubusercontent.com/6595819/115095018-b40b2880-9eed-11eb-9620-6a830bef752c.JPG)

This only occurred on first opening.

**Comment by shulist** [comment]
In the ToDo.txt test file there is a line:

`(B)->Submit TPS report \this task has no priority, no space after priority\`

Which should not show up with a priority as there is no space after the (B) so it should be listed without priority. For some reason when loaded into Sleek it is re-formatted as

`(B) ->Submit TPS report \this task has no priority, no space after priority\`

Which does get formatted with a priority. According to the spec this is incorrect.

**Comment by ransome1** [comment]
> In the ToDo.txt test file there is a line:
> 
> `(B)->Submit TPS report \this task has no priority, no space after priority\`
> 
> Which should not show up with a priority as there is no space after the (B) so it should be listed without priority. For some reason when loaded into Sleek it is re-formatted as
> 
> `(B) ->Submit TPS report \this task has no priority, no space after priority\`
> 
> Which does get formatted with a priority. According to the spec this is incorrect.
> 
> @ransome1 I suspect this is also connected to the java parsing and to the issue over at [jsTodoTxt ](https://github.com/jmhobbs/jsTodoTxt/issues/5)?

You're right, that doesn't seem right and it could indeed be caused by jsTodoTxt. I'll take a look into sleeks code first, before we forward it to them. Thanks for pointing it out.

**Comment by ransome1** [comment]
> Got this error upon opening in Win10:
> ![Sleek100_JavaError](https://user-images.githubusercontent.com/6595819/115095018-b40b2880-9eed-11eb-9620-6a830bef752c.JPG)
> 
> This only occurred on first opening.

This doesn't look like a programmatic issue within sleek, but more like a file permission issue. Is it possible that the file was beeing changed or accessed by another app right in that moment when sleek tried to open it?

**Comment by SteOtt** [comment]
Hello,
I experience a strange behaviour when adding a task that has context- and/or project-tags before adding the description text (this is the case when you create a task based on another template-task):
At each letter I type the tags in the filter bar at the left are filtered on the description text and the input window shows a project or context tag.
For example shows the attached screenshot the state of sleek after I've created a task based on "Aufgabe1" after typing the text "pr".
![image](https://user-images.githubusercontent.com/17461591/115259262-03419b00-a132-11eb-8b30-816a713612e9.png)

**Comment by ransome1** [comment]
> Hello,
> I experience a strange behaviour when adding a task that has context- and/or project-tags before adding the description text (this is the case when you create a task based on another template-task):
> At each letter I type the tags in the filter bar at the left are filtered on the description text and the input window shows a project or context tag.
> For example shows the attached screenshot the state of sleek after I've created a task based on "Aufgabe1" after typing the text "pr".
> ![image](https://user-images.githubusercontent.com/17461591/115259262-03419b00-a132-11eb-8b30-816a713612e9.png)

Thanks for your feedback, I appreciate it and will look into it. Should be fixed in the next release.

**Comment by ransome1** [comment]
v1.0.0 has been released. @SteOtt, I added your issue to my backlog.
