### ISSUE TITLE
sleek docker

### ISSUE THREAD

**Issue by uGeek** [ransome1/sleek#103]
It would be great to create a sleek docker as if it were a service. Access a url where the service is. I could access from all my devices, including my mobile, without having to use a synchronization tool.

Great app.
Thanks

**Comment by ransome1** [comment]
@uGeek , sounds interesting, but I have zero idea how docker container work ;) Do you have any experience on how to approach this and would like to help this project by consulting or even working on a docker recipe?

**Comment by uGeek** [comment]
I have no idea. I'm going to ask if someone would know how to build it

**Comment by ransome1** [comment]
@uGeek , any news?

**Comment by uGeek** [comment]
I have been told to use guacamole, just like the linuxserver.io community does with its dockers, but I don't know how to build it

**Comment by ransome1** [comment]
I think there won't be any progress (at least from my side) and I'm closing here to clean up the issue list.
