### ISSUE TITLE
Notification setting on when sleek opens 

### ISSUE THREAD

**Issue by velardevines** [ransome1/sleek#104]
Notification setting reset to on when opening Sleek.

Steps to reproduce:
. Open Sleek
. Open settings and turn off Notifications
. Close Sleek
. Open Sleek 
. Open settings and notice that Notifications are On

Running Sleek v 1.0.1 on ARM processor installed using Flakpak

![Screenshot 2021-04-22 9 19 24 AM](https://user-images.githubusercontent.com/13563674/115740967-8d654b80-a34c-11eb-82ff-a3474b53f4be.png)

**Comment by ransome1** [comment]
@velardevines , found it and fixed it. Thanks for pointing it out.

**Comment by ransome1** [comment]
https://github.com/ransome1/sleek/releases/tag/v1.0.2
