### ISSUE TITLE
Filtering: make it possible to select more than one priority / context / project

### ISSUE THREAD

**Issue by freder** [ransome1/sleek#108]
let's say I wanted to see all items with priority A _and_ B -- as far as I can tell, that's currently not possible.

related to #107 I suppose.

**Comment by ransome1** [comment]
I agree, this would be a follow up the https://github.com/ransome1/sleek/issues/107. I added it to sleek roadmap for v1.1

**Comment by zerodat** [comment]
I have a possible solution to this feature request, which I will describe in more detail under #132.  I call it a "filter query language".

**Comment by Saturo78** [comment]
I think "pri = A or pri = B" works.
Shouldn´t it?

**Comment by zerodat** [comment]
Yes, you are exactly right, @Saturo78.  The filter query language lets you match multiple priorities, contexts, projects very easily as you indicated.  For instance, all of the following should work (and I believe that they do):
* `pri = A or pri = B`
* `pri >= A and pri <= B`
* `(A) or (B)`
* `@context1 or @context2`
* `+p1 or +p2 or +p3`
and so on.

**Comment by ransome1** [comment]
@freder : Can we close here?
