### ISSUE TITLE
Upgrade electron dependency to latest

### ISSUE THREAD

**Issue by intrepidsilence** [ransome1/sleek#112]
**Is it an actual bug?**
This one rides the line between bug and feature request. I would like to know how large the effort will be to upgrade the electron dependency to a recent (if not the latest) version. v6 is quite old. It would be nice to be able to build this for macOS on M1 Apple Silicon, but versions of electron in v6 are not available for that platform (obviously).

**Did you check if the bug has already been reported?**
Yes, not reported yet as far as I could see.

**Describe the bug**
Cannot complete "yarn install" due to missing version of electron for macOS M1 Apple Silicon. Recent versions of electron support M1.

**To Reproduce**
Run "yarn install" on macOS on M1.   Get the following output:

```
Downloading tmp-32668-0-electron-v6.1.12-darwin-arm64.zip
Error: GET https://github.com/electron/electron/releases/download/v6.1.12/electron-v6.1.12-darwin-arm64.zip returned 404
/Users/spurlock/Downloads/sleek-1.0.3/node_modules/jest-electron/node_modules/electron/install.js:53
  throw err
  ^

Error: Failed to find Electron v6.1.12 for darwin-arm64 at https://github.com/electron/electron/releases/download/v6.1.12/electron-v6.1.12-darwin-arm64.zip
    at Request.<anonymous> (/Users/spurlock/Downloads/sleek-1.0.3/node_modules/nugget/index.js:169:61)
    at Request.emit (node:events:365:28)
    at Request.onRequestResponse (/Users/spurlock/Downloads/sleek-1.0.3/node_modules/request/request.js:1059:10)
    at ClientRequest.emit (node:events:365:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:621:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:127:17)
    at TLSSocket.socketOnData (node:_http_client:487:22)
```

**Expected behavior**
"yarn install" should be able to complete.

**Desktop (please complete the following information):**
 - OS: macOS 11.3 on M1 Apple Silicon
 - Version of sleek: 1.0.3 source
 - Source: Github

**Comment by ransome1** [comment]
@intrepidsilence , sleek is using Electron 12.0.5, I don't know why yarn wants to install v6. For whatsoever reason it is mentioned in the yarn.lock file. Can you try deleting that file and do the `yarn install` again?

**Comment by ransome1** [comment]
@intrepidsilence , i stumbled about the solution to your issue. In package.json there is a "devDependency" named "jest-electron", which is depending on Electron 6. 

You can try to install the modules like this `yarn install --production`

This should skip installing the devDependencies.

**Comment by intrepidsilence** [comment]
@ransome1 Sorry this took so long for me to get back to.  I tried it:

```
yarn install --production
yarn install v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > jest-electron@0.1.11" has incorrect peer dependency "jest@^24.0.0".
[4/4] 🔨  Building fresh packages...
✨  Done in 9.46s.
```

**Comment by intrepidsilence** [comment]
As a side-related question to this bug, what are you using to compile for macOS? Can you turn on cross-compile for Universal binaries?

**Comment by ransome1** [comment]
@intrepidsilence, that looks like a success, I would say. Were you able to build?

As for your question: I use Github CI, which provides a MacOS environment in which Electron Builder compiles the Mac app and puts it into the dmg container.

Let me take a quick look into Electron Builders' documentation if we can configure it to build for different architectures too. Based on your initial bug report I assume your Mac is having an arm64 architecture?

**Comment by ransome1** [comment]
@intrepidsilence, can you check this test release, if the universal binaries (two were built) work on your M1 Mac? https://github.com/ransome1/sleek/releases/tag/v1.0.3-3

**Comment by intrepidsilence** [comment]
I tested the test release. It runs and is indeed native Apple Silicon in the universal binary. I noticed there are two macOS downloads so I grabbed both the zip and the dmg. They both run. They also both have an issue where they do not seem to have the normal keyboard shortcuts for macOS like CMD+Q to Quit the app. Quit doesn't even show up in the App Menu. I have to right-click on the Dock icon and select quit there. So, this bug report can be closed but  guess another one needs to be opened?

**Comment by intrepidsilence** [comment]
@ransome1 - Also, as always, thank you for the continued efforts and such fast turn-around.

**Comment by ransome1** [comment]
> I tested the test release. It runs and is indeed native Apple Silicon in the universal binary. I noticed there are two macOS downloads so I grabbed both the zip and the dmg. They both run. They also both have an issue where they do not seem to have the normal keyboard shortcuts for macOS like CMD+Q to Quit the app. Quit doesn't even show up in the App Menu. I have to right-click on the Dock icon and select quit there. So, this bug report can be closed but guess another one needs to be opened?

Hi @intrepidsilence, is it only the CMD+Q shortcut that doesn't work, or are you having difficulties with the other shortcuts as well?

**Comment by intrepidsilence** [comment]
@ransome1 It looks worse than the but it is hard to tell everything.  However, I do have more info.

When I run the app it opens a window correctly. The sleep menu item then has these options:
Open todo.txt CMD+O
Create todo.txt
Close  CMD+W

If I close the window with the top windows gadget close button the window disappears but sleek is still running in the Dock (small dot under it).

If I clock the sleek icon in the doc I get a new window, but this time not rendered correctly (empty and white instead of dark theme) and an error modal pops up:
```
A JavaScript error occurred in the main process

Uncaught Exception:
TypeError: Object has been destroyed
at IpcMainImpl.<anonymous> (/Applications/sleek.app/Contents/Resources/app.asar/src/main.js:525:20)
at IpcMainImpl.emit (events.js:327:22)
at Object.<anonymous> (electron/js2c/browser_init.js:161:9692)
at Object.emit (events.js:315:20)
```

If I close the error modal requestor, in the sleek menu item I now see the following items:
Open todo.txt CMD+O
Create todo.txt
Close  CMD+Q

Hope this helps.
