### ISSUE TITLE
Closing maximized window shouldn't set window size

### ISSUE THREAD

**Issue by samuelznewton** [ransome1/sleek#113]
**Is your feature request related to a problem? Please describe.**
Related to [issue 110](https://github.com/ransome1/sleek/issues/110).  Per that issue's discussion, my understanding is that this issue is specific to Linux.

Closing a maximized window in [development release 1.0.3](https://github.com/ransome1/sleek/releases/tag/v1.0.3) sets the window size for future launches to be the size of the screen.  I'm guessing this behavior was probably added as a try at keeping a window maximized in 1.x, but with the fix made in 1.0.3, this behavior is no longer needed and, in my opinion, is undesirable.

**Describe the solution you'd like**

It would be nice if closing a maximized window didn't set the window size.  Try these two things and see the difference between them:

- open 1.0.3
- make the window size somewhat small
- maximize it
- restore it down

At this point, the window size is the "somewhat small" size you had it at before.  This is good.  Now, try this instead:

- maximize it
- close it
- reopen it
- restore it down

At this point, the window is the same size as a maximized window, though it isn't maximized.  It would be nice if, at this point, the window size still went back to the "somewhat small" size from before.

My guess is that making this change would involve only 1 or 2 changes in the code, but if it turns out to be a very involved process, this certainly isn't a super-high-priority thing worth refactoring all your code over.

**Comment by ransome1** [comment]
Hi @samuelznewton. Can you check the reuploaded 1.0.3 if this works like expected?

https://github.com/ransome1/sleek/releases/tag/v1.0.3

**Comment by samuelznewton** [comment]
Yes, that's got it!  Thank you so much!
