### ISSUE TITLE
macOS: 'select all' (cmd-a) does not work in an input field

### ISSUE THREAD

**Issue by freder** [ransome1/sleek#114]
**Is it an actual bug?**
I believe so

**Describe the bug**
on the mac, when the text cursor is in an input field, the 'select all' (cmd-a) shortcut does not seem to work. works in the linux version (ctrl-a).

**To Reproduce**
1. cmd-n to create a new task
2. type s.th. into the input field
3. do cmd-a and see that nothing happens

**Do you see any error entries in sleeks developer tools?**
no

**Expected behavior**
should select all text

**Desktop (please complete the following information):**
 - OS: macOs 10.14.6
 - Version of sleek: 1.0.3
 - Source: Github

**Comment by ransome1** [comment]
Hi @freder. I don't have a Mac at hand, so can I ask you to check if "select all" is working in this pre-release: https://github.com/ransome1/sleek/releases/tag/v1.0.3

**Comment by freder** [comment]
with that one it works 👍

**Comment by ransome1** [comment]
@freder, one thing I got to ask you. In https://github.com/ransome1/sleek/issues/88 we're developing a "Minimize to tray and run in background" function. I can only test it on my Windows VM and my Linux system, but not on MacOS.

If you have some time, it would be of great help if you could give it a try and let me know if it works as you would expect it from Mac application. Feel free to post your feedback in https://github.com/ransome1/sleek/issues/88

It needs to be activated in the settings window.
