### ISSUE TITLE
Choice of browser to open links in (not just system default)—or run outside of Electron?

### ISSUE THREAD

**Issue by codingthat** [ransome1/sleek#115]
**Did you check if a similar feature request has already been reported?**
yes

**Is your feature request related to a problem? Please describe.**

I have a system default browser that I do not wish to change, but also do not wish to use when opening links from within todo items in Sleek.

**Describe the solution you'd like**

It would be great if there were an option to specify which app (even just a textbox for a command—nothing fancy) would be used to open links.  Or multiple ones, which you could then choose from when right-clicking a URL.

However, even better (for me) would be if it were possible to run Sleek in an actual browser tab (and the back end as just a normal Node.js app, with or without the proposed Docker containerization), instead of a whole separate Electron app.  But I know that's possibly a large can of worms to open.  (If not / if you have tips on how to do this successfully, that would be a fantastic workaround for me!  :) )

**Describe alternatives you've considered**

It's of course possible to work around this by opening/editing an item, highlighting, copying, switching to the preferred browser, opening a new tab, and pasting, but that's many extra steps for what (in my case) is a common operation.

**Comment by codingthat** [comment]
I see if I try `yarn run pack` and then opening `./src/index.html` I get `render.js:627 TypeError in function undefined: Cannot read property 'send' of undefined`.  On further inspection it looks like `window.api.send` is probably an Electron call, rather than the app having a front end that calls an actual Node.js back end, which I had falsely assumed was the setup.  So I'm guessing the "run Sleek in a browser" option isn't very feasible without significant changes.

**Comment by ransome1** [comment]
Hi @codingthat. sleek is deeply integrated with the Electron framework. It would be possible to convert it to a web app by removing all the Electron API integrations, the context isolation and so forth. All in all it would be quite some work to do so.

As for your feature request I can see that it makes sense for your specific use case, but it would be one more setting that would have to be developed and integrated into the UI without bloating it. And quite frankly, I don't think a lot of users would use it, as most stick to their default browser. I am not even sure, if the Electron framework would be able to ask the OS for all available browsers and then send links only to a specific one.

We can put your request on the "Up for discussion" column and mark it with "help wanted" in case anybody would like to contribute to sleek by developing it. But I'm afraid, I can't work on your feature request as the backlog is growing each day and there still are some technical depths to take care of too.

**Comment by shulist** [comment]
I just checked about five Win10 apps I use regularly that open browser links directly from the app and in all cases they only open the default browser. This seems to be normal behavior. In no cases do they offer the option of using an alternative app. IMHO I think this is a very low priority FR.

**Comment by codingthat** [comment]
Fair enough.  To be honest, my solution has been to simply use mindstream instead, since I can run it in my browser of choice.

**Comment by shulist** [comment]
@YMan84 I'm not sure of what you're asking for. In my version of Sleek **by default** it uses the Win10 default system browser.
