### ISSUE TITLE
Don't include completed items in task count(?)

### ISSUE THREAD

**Issue by freder** [ransome1/sleek#116]
**Did you check if a similar feature request has already been reported?**
✔

**Is your feature request related to a problem? Please describe.**
for me the badge count represents items that need attention, which completed items do not.

![Screenshot 2021-05-04 at 17 50 19](https://user-images.githubusercontent.com/724844/117035427-98cd5500-ad04-11eb-9c89-d7001af9f77e.png)

**Comment by ransome1** [comment]
Hi @freder. I disagree on this one, as the filter will apply also to the completed todos. If you don't want to have the completed todos to be counted, you can simply hide the completed todos by using the shortcut (Ctrl Or CMD + H) or by using the view drawer in the navigation.
