### ISSUE TITLE
Feature Request: Pin context(s) and project(s) to sidebar

### ISSUE THREAD

**Issue by dansauve** [ransome1/sleek#12]
It would be nice to be able to pin individual context(s) and/or project(s) to the sidebar. 

Ideally, this would be defined per context or per project.

**Comment by ransome1** [comment]
Hi @dansauve.

I'm not sure if I understand this completely. Could you clarify it a bit more?

If, with pinning, you mean putting the important project and contexts to the beginning to the filter list, you could do this my naming them starting with numbers, as the sorting is alphanumerically. e.g. "@001_context1".

**Comment by jason-mehmel** [comment]
@dansauve What @ransome1 suggested is what I do. I add a '1' to my contexts and projects if I want them to be at the top of the list.
This way, I also get the same behaviour in my other todo.txt apps, such as Simpletask, which I use on my phone.

**Comment by dansauve** [comment]
My request is probably complicating things, and without knowing what the roadmap is for the app it's hard to say if this is a good idea or not, but here goes...

The core request is options to configure the sidebar, by which I mean the thin grey bar on the left (with "+" icon, "show filters", "open todo.txt file", etc options). 

1) I'd like to "pin" specific items to the sidebar, like context and projects, so that I have 1-click to access them. I do not want to have to use the 'filter' mode. 

and 

2) Further, for me personally there's no value in having the "open todo.txt file", "toggle dark mode", and "help" button. Options to fully customer that left sidebar would be great.

This would add a lot of complication to the app though and may be outside

Right now, I'm using Amazing Marvin to accomplish something similar. It's overkill for my needs.

**Comment by ransome1** [comment]
The idea is not too bad and should be doable in general. I'm not sure though how to implement it UX wise without complicating the app too much.

With contexts and projects you mean single contexts or projects, not the category itself, right?

**Comment by ransome1** [comment]
@dansauve I added your request to the backlog and let you know if and when I will find the time to work on this feature.
