### ISSUE TITLE
"split of undefined" error and duplicating data file

### ISSUE THREAD

**Issue by amigo421** [ransome1/sleek#120]
Getting this error regularly but still can't find the conditions to reproduce

![image](https://user-images.githubusercontent.com/3259933/117404505-b5d77300-af12-11eb-8588-934fd6821320.png)

and app creates a number of empty files (sometimes - tens , sometimes - hundreds)
![image](https://user-images.githubusercontent.com/3259933/117404597-dc95a980-af12-11eb-8078-4be587474dd6.png)

I see "enable logging" setting, if I enable this, where can I find log file? 

app has been downloaded from Microsoft Store, OS: latest Windows 10 build

by the way: Ctrl+Shit+l as well as Alt+About doesn't work for me to show dev tools....

**Comment by ransome1** [comment]
Hi @amigo421 . That looks interesting. There is literally no function in sleek that would create duplicates and add something like (1) to the filename. So I was thinking that maybe it could be a permission issue on your system.

But anyway, can I ask you to check this latest pre release and tell me if you're having the same issue, when handling the exact same todo.txt file? https://github.com/ransome1/sleek/releases/tag/v1.0.3

There is a portable .exe, so you don't need to install anything.

**Comment by amigo421** [comment]
thank you for clarification, 

then seems that another app does this , there is an utility which keep up to date this (within other directory tree) file with my backup storage.

not sure but seems the issue happens when I wake up windows from sleeping.

please do no investigate/close issue 1-2 days, I'm going to perform more intense checks

**Comment by ransome1** [comment]
Thanks for your feedback and keep me posted. Because if it is an issue with sleek after all, we need to reproduce and fix it.

**Comment by amigo421** [comment]
yes, I'm okay

**Comment by amigo421** [comment]
you provided portable version doesn't work more: today morning I've started my laptop and opened this - I see white screen after the starting. closed and repeat a few times, the same problem.
version from store works fine.

**Comment by ransome1** [comment]
Hi @amigo421 . Could you please press the `Alt` button, select `About` and then the developer tools, like here:
![image](https://user-images.githubusercontent.com/11188741/117567194-481a7b00-b0bb-11eb-8b24-46640d6e2732.png)

I'm curious if you can spot any Errors in the developer tools.

**Comment by amigo421** [comment]
@ransome1 duplicated block of projects and contexts is still there,
other issues seems are not there, but I'll play with tomorrow
I could open dev tools , but I'm not familiar with electron development and javascript (I'm c++ dev)
but if you could tell me key points to look at, logs, variables would be helpful
anyway I'll look at the code and properties deeper, tomorrow

**Comment by ransome1** [comment]
Ok, so 3 of the 4 issues are gone and only the one with the double filter categories remains, correct?

The issue you're describing is not new to me, I had fixed it in the past, but for whatsoever reason it reappeared now :( I'm not sure if you will find any error entries in the developer console for this issue.

So let me ask you, do the duplicate filter categories are present all the time or only in specfic situations? Like when you add or delete a todo, or if you switch between files?

**Comment by ransome1** [comment]
@amigo421, I just downloaded the portable again. I'm not having any issues on my Windows 10 VM, but that doesn't mean too much. At this point one other cause for the white screen could be something in your user-preferences.json file, in which sleek stores your settings.

What you could try is to close sleek, backup and the whole folder `C:\Users\User\AppData\Roaming\sleek` (could vary on your system, if it is not there search for "user-preferences.json" which is the main config file of sleek) and then restart sleek. It's a long shot but we should at least consider trying.

**Comment by amigo421** [comment]
you are right - at the moment of the starting it doesn't exist,
it only happens when I change e.g. due date for some task.

also , for me, looks I got one of the cases when todo (2).txt created in addition to primary todo.txt:

- first of all let me describe how it works : I use your app on windows laptop where also works the app which sync folder tree with cloud storage. when I'm away from desktop , I'm using android todo.txt app which doesn't require an external sync as supports builtin webdav support. 
- today morning , I've added a few tasks for today from my android phone, then
- when I wake up my computer (pay the attention - wake up but no a start, I mean that sleek was  started previously and seems tried to continue the work after wake up)
- immediately after wake up, I saw two files on the disk : todo.txt with newest tasks synced from phone->cloud->comp and todo (2).txt which contains old (yesterday) data , edited in sleek.

from my perspective it looks like:
1. sleek doesn't track external changes/update datatime of the file on the drive to load that?
2. or/and tries to overwrite existing file but some library function which you use to save, inside "sees' that file has newer version o nthe disk and save a copy. I believe that your code doesn't have such functionality but it can perform some library/SDK function.

**Comment by ransome1** [comment]
@amigo421, I can't say this with 100% certanty, but I don't think that sleek produces the todo (2).txt file. What tool are you using to sync the files between computers? Is this Dropbox or something similar? And do you have access to the logs of this syncing tool? One idea I have in mind is, that this tool is creating the todo (2).txt file, because it is not able to write to the original todo.txt file. Is this a possibility?

**Comment by amigo421** [comment]
I'll check the logs but as I said above it's not possible because
- todo (2).txt - contains yesterday's changes made in sleek
- todo.txt - contains today's changes went from mobile/cloud. 
if todo (2).txt would be created by sync tool then this file contains latest changes but it's not so

sync tool is not a dropbox but similar

**Comment by ransome1** [comment]
If sleek cannot write to a file, it will throw an error. At no point in the code sleek is adviced to duplicate the todo file and append " (2)" to it.

But maybe I don't fully understand your case. Please help me understand. What you do is:
1. You add a todo in sleek and it get's written to the file successfully
2. Now some time later you use a mobile app on your phone and create a new todo
3. Some time later you check your computer and you see, that the new todo from step 1., that has been created by sleek, is gone and has been moved to todo (2).txt, correct?
4. In sleek you now see only the new todo from step 3., which has been added on your phone?

Question: In step 2. so on your phone, do you already see the new todo from step 1. (created with sleek)?

**Comment by amigo421** [comment]
the steps are little bit different, but today morning, I've tried to reproduce as yesterday but no duplicated files on the moment,
the only filters group was duplicated 5 times.
regarding the conflict with synced from cloud:

- sleek overwritten latest changes from cloud, are you really not checking the data file on the disk can be changed externally? 


My steps were:
1. You add/edit/delete  a todos in sleek during the day and it get's written to the file successfully
2. I left from desktop and slept this with running sleek 
all the time of workday , dropbox-like service sync the changes to cloud.
3. During the evening , I continue the work with todo.txt file but now in cloud and from mobile app (with auto-save to cloud)
4. Next day, I've wake up my laptop with running sleek as well as sync service.
5. Sleep contains non-synced data, yesterday's snapshot which I saw before sleep Windows. at the same time I saw two files on the disk : todo.txt - contains all latest changes (from cloud/mobile) and todo (2).txt - with only yesterday's sleek's changes.

but today, no duplicated files - seems sleek just overwrote my latest (from cloud/mobile) data in a single file ((

**Comment by ransome1** [comment]
`the only filters group was duplicated 5 times.`

Does this happen in a specific situation? Like when you open sleek, or after you created a new todo or edited an old one?

`but today, no duplicated files - seems sleek just overwrote my latest (from cloud/mobile) data in a single file ((`

sleek does not overwrite your data, unless you actively save something within sleek.

`sleek overwrote latest changes from cloud, are you really not checking the data file on the disk can be changed externally?`

I am not sure if I understand this. What sleek does is, it has a path to a file stored and when you open sleek, it uses a nodejs method named `fs.watch` that from now on will watch this specific file (in your case the todo.txt) for changes. When the file has been changed, it reloads the content from the file. 

```
todo (2).txt - contains yesterday's changes made in sleek
todo.txt - contains today's changes went from mobile/cloud.
if todo (2).txt would be created by sync tool then this file contains latest changes but it's not so
```
Do you think this can be the scenario?
When you did your changes in the cloud/mobile, the previous changes from sleek **were not synced**. Means they were not available in the todo.txt file, when you started working in the cloud. Now you did your changes in the cloud and your syncing service had to compare two different files: The old one from sleek and the new one from the cloud. I assume the service cannot (and should not just blindly) merge those two different files. Instead it takes the new one as the new todo.txt and makes a copy of the old one (I assume it is comparing timestamps), so the data does not get merged.

Three angles you could pursue:
1. When, in your scenario, you are opening the todo.txt file in the cloud, please double check if the changes from sleek are already in the file. This has to be the case.
2. Try deactivating any auto save, unless you really know what it does and retry your scenario.
3. There might be other todo.txt apps, that use a file watcher. If you have some time left, please try them out and check if those apps do handle it differently or if you are running into the same issues.

_As a side note: I am AFK for two weeks now, but please post all information you can find out so we can continue working on this after I am back._

**Comment by ransome1** [comment]
Hi @amigo421. While trying to fix another file watcher releated issue, I replaced the old file watcher implementation with a different one. A pre-release can be downloaded here: https://github.com/ransome1/sleek/releases/tag/v1.0.4-1

I can not say at all, if this solves your issue, but it cannot hurt to try it out. Please let me know.

**Comment by amigo421** [comment]
thank you for the update, I'm going to try

**Comment by amigo421** [comment]
> <strong>TypeError</strong> in function generateItems: Cannot read property 'split' of undefined
![image](https://user-images.githubusercontent.com/3259933/120065738-9e0b8e80-c07b-11eb-900f-c1a007bda407.png)
![image](https://user-images.githubusercontent.com/3259933/120065746-a95eba00-c07b-11eb-8fb5-147ae4b1ead2.png)

hey , the problem is still there.
