### ISSUE TITLE
1.0.3 Flatpak non-functional

### ISSUE THREAD

**Issue by samuelznewton** [ransome1/sleek#121]
The latest Flathub release (1.0.3) shows a mostly-blank screen with non-functional buttons.  Pressing Alt will bring up the menu bar as expected, though the only working options as far as I can tell are "Close", "GitHub", and thankfully "Developer tools"
![image](https://user-images.githubusercontent.com/57228129/117512384-1edfda80-af55-11eb-8ca0-30d6174727ef.png)

Note that the current 1.0.3 AppImage version works just fine.

Console shows:
```
[ERROR: render.js:975] Uncaught SyntaxError: Export 'translations' is not defined in module

[WARNING] DevTools failed to load SourceMap: Could not parse content for file:///app/sleek/resources/app.asar/src/css/style.css.map: Unexpected end of JSON input
```

 - OS: Pop!_OS 20.10
 - sleek: 1.0.3
 - Source: Flathub

**Comment by ransome1** [comment]
@samuelznewton , thanks for reporting. The fix is already in the pipeline and should be distributed soon.

**Comment by samuelznewton** [comment]
Thank you so much!  The current release works great! :D
