### ISSUE TITLE
Too many notifications received

### ISSUE THREAD

**Issue by rzelnik** [ransome1/sleek#122]
Each time I create a new task with due date set to today or tomorrow, I receive recurring "Due to" notifications from sleek for each task again and again (10+ per task), even if I turned notifications off in the app settings. 

**To Reproduce**
1. Create a new task, set "Due to" to today or tomorrow
2. Check the notifications tray, see recurring notifications
3. Click on Settings > Notifications > switch to "turn off"
4. Create a new task, set "Due to" to today or tomorrow
5. Check the notifications tray, see recurring notifications

**Do you see any error entries in sleeks developer tools?**
No errors.

**Expected behavior**
It should create one notification per task or no notifications while they are turned off.

**Screenshots**
![sleek-settings](https://user-images.githubusercontent.com/610651/117604123-dd1d8280-b154-11eb-9de8-0fa16ec95797.jpg)
![sleek-notifications](https://user-images.githubusercontent.com/610651/117604130-e0b10980-b154-11eb-9832-fce75956d9ea.jpg)

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.04
 - Version of sleek: 1.0.3
 - Source: Snap Store

**Comment by ransome1** [comment]
Hi @rzelnik, I'm not able to reproduce it. But let me ask you a couple of questions first:
1. Do all the notifications pop up at once, directly after you created it, or does each one popup after you do other things in sleek, like reloading it, completing todos, etc.?

2. Can you please turn off the notifications in settings and check your user data, which is located in this file: `/home/[YOUR USER NAME]/snap/sleek/current/.config/sleek/user-preferences.json`. And check what the `notifications` entry says? Please also check the entry, when notifications are turned on.

3. After you see all those notifications, can you check theabove mentioned user-preferences.json, what values the entry `dismissedNotifications` contains?

**Comment by rzelnik** [comment]
1. Do all the notifications pop up at once, directly after you created it, or does each one popup after you do other things in sleek, like reloading it, completing todos, etc.?

The notifications appear at once, immediately after saving the new task .

2. Can you please turn off the notifications in settings and check your user data, which is located in this file: `/home/[YOUR USER NAME]/snap/sleek/current/.config/sleek/user-preferences.json`. And check what the `notifications` entry says? Please also check the entry, when notifications are turned on.

In both cases I see "notifications":true.

3. After you see all those notifications, can you check theabove mentioned user-preferences.json, what values the entry `dismissedNotifications` contains?

dismissedNotifications":[824322678,-734409592,780721888,-471205857,-628959975,13353531,1587882835,-1199532651,-1346624329,-681993339,562771143,1935450331,1742335906,-1689379714,-556973330,-318807812,-1418209612,-541631922,-330281008,685644092,-1111307266,-1317075986,-72311504,938239127,853453518,882082670,825796764,1777509182,-471205858,-1199532652,938239126,1742335905,-1689379715,-318807813,-330281009,-1111307267,-72311505,882082669,1777509181,-1591017373,308019158,-1658359907,-107456899,-118930095,1172452977,910711821,-1071864714,1386708671,-1920803899,-2124869712,-1809352529,-237786540,723827478,-724244284,-238795126,-492875021,-724244285,-1591017374,-1071864715,-1658359908,-107456900,-118930096,1172452976,910711820,-238795127,-2124869713,308019157,723827477,-1910345479,756518524,1950491040,-975924153,247295891,235822695,-1507499513,1540553143,-885579412,-1143600975,-1928619731,231279126,-626469006,-741292284,-741292283,-448939987,918724738,-1862614319],

**Comment by ransome1** [comment]
@rzelnik, does the notifications entry really say `off` or do you mean `false`?

Do you see any pattern if you say  _sometimes_. Is this somehow reproduceable?

Can you send me the user-preferences.json file by mail? ransome@uber.space?

Also, it doesn't fix anything but can you please quit sleek, backup the folder `/home/[YOUR USER NAME]/snap/sleek/current/.config/sleek/` and then delete it? You will have to readd the todo.txt afterwards, but I'm curious about if this solves anything. 

At this point I have no idea what is happening. My best guess is, that sleek can't write to the user-preferences.json or at least not every time it wants to.

**Comment by rzelnik** [comment]
@ransome1 yes, sorry, you are right, in the user-preferences entry the value is `false`, not `off`. I will edit the previous comment to prevent confusion.

Sometimes: in the first trial I switched both **Notifications** and **Minimize to the tray bar** to `false`. After clicking on **Minimize...**, the application immediately restarted and the **Notifications** value remained `true`. I tried to reproduce but on the next trials the **Notifications** setting was stored well, even in combination with **Minimize**/restart.

**Comment by ransome1** [comment]
For whatsoever reason sleek can't write to the preferences from time to time. As if there is an issue with the permission on the user-preferences file. But it's wild guessing on my side.

Let's try something else. If you installed it from Snap Store, the user preferences are stored within the Snap folder. To eliminate this particularity of Snap, you could use the latest AppImage (https://github.com/ransome1/sleek/releases/tag/v1.0.3). This will create the user preferences file outside the snap folder. Can you please tell if you are having the same issues with the AppImage?

Also: Did you try to delete the `/home/[YOUR USER NAME]/snap/sleek/current/.config/sleek/ folder` and check if the issue persists?

**Comment by rzelnik** [comment]
I tried flatpak, deb, AppImage. All worked well, just the deb version didn't show the Sleek app icon but some generic app icon instead. Otherwise it also worked well. Then I reinstalled the snap version. The issue occured again. Then I removed the `/home/[YOUR USER NAME]/snap/sleek/current/.config/sleek/` folder and now the also snap version also works as expected: one notification when notifications turned on, no notification when turned off. Thank you for your help.

**Comment by ransome1** [comment]
Hi @rzelnik , that is good to hear. It still puzzles me and I hope this is not a bug that I havn't understood yet. If you have a backup of the user-preferences.json and you feel comfortable with sharing it, please send it to me by mail. It does not contain any sensitive information.

**Comment by rzelnik** [comment]
I am sorry, I don't have a backup.
