### ISSUE TITLE
Trailing plus sign shouldn't be removed

### ISSUE THREAD

**Issue by 9z0** [ransome1/sleek#128]
For example, `(A) My C++ todo` becomes `(A) My C todo`.
It is removed even if string is  ``` `escaped` ```
This shouldn't happen.

**Comment by ransome1** [comment]
Hi @9z0, I created a new todo based on your example `(A) My C++ todo` on a Windows 10 VM and my Linux production machine and on both the todo is created correctly
![image](https://user-images.githubusercontent.com/11188741/119941267-a8049300-bf90-11eb-9a99-0008108f9f60.png)

What version, OS, language settings, keyboard layout, etc. are you on?

**Comment by ransome1** [comment]
Thanks @9z0 , I can reproduce it. It looks like a minor regex issue with the todo.txt parsing library. I passed it on to the project, so it can be fixedm where it should be fixed.

**Comment by ransome1** [comment]
Will be fixed once upstream is ready to go: https://github.com/jmhobbs/jsTodoTxt/pull/30

**Comment by ransome1** [comment]
Hi @9z0 . Could you please double check if this issue is solved in https://github.com/ransome1/sleek/releases/tag/v1.0.6?

**Comment by 9z0** [comment]
Fixed!
