### ISSUE TITLE
Better (or customizable) monospace font

### ISSUE THREAD

**Issue by 9z0** [ransome1/sleek#133]
The default Monospace is not the best free fixed-width font available by a long margin :)

An option to name an installed font would be nice.

On a related note, perhaps an optional light gray shading to the monospace code block?

Thanks!

OS: Windows

**Comment by ransome1** [comment]
#@9z0, What is the `default Monospace` and which `code block` are you referring to? I think I don't understand the issue.

Customizable fonts have been discussed in https://github.com/ransome1/sleek/issues/71#issuecomment-804304441 already. I'm afraid sleek won't be that customizable.

**Comment by 9z0** [comment]
Enter this:
```
(A) Text `example`
```
Inspect "example" with devtools. > `<code>example</code>`
See font-family under Styles:
```
code, pre {
    font-family: monospace;
}
```

**Comment by 9z0** [comment]
> 
> 
> @9z0, ah ok, you're using html tags in your todos.

I am not. That's the inspector :)

**Comment by 9z0** [comment]
I don't know how feasible the following is, but some Electron apps take advantage of the nature of Electron and allow the user to have their own CSS/JS code to run on statup.

This allows deep customization potential of the UI/behavior without having to burden the developer with providing these options formally within the app.

This issue for example would be be a good candidate for this.

What do you think?

**Comment by ransome1** [comment]
I can't say I have ever looked into this option. Do you have any experience with it and would be willing to work on it? I wouldn't have any issues with it, as long as the basic version of sleek maintains its look and feel. 

So those who really want to customize it more deeply would have the option to do so, without sleeks settings and UI being bloated further more.

**Comment by 9z0** [comment]
I have experience as a user with limited knowledge of HTML/CSS/JS.

Such a system is used by, for example, [Joplin](https://github.com/joplin) and [Notable](https://github.com/notable).

You don't need to provide a UI for editing the code like they do. Just tell the user what file to edit.

**Comment by ransome1** [comment]
The actual monospace font issue should be fixed in https://github.com/ransome1/sleek/releases/tag/v1.0.5. Can you please check it and close here? Thanks.

**Comment by 9z0** [comment]
It is and it looks significantly better. Thanks.

About the user CSS/JS code. Should I make another issue for it as we close this issue or will you keep it in mind or what?

**Comment by ransome1** [comment]
@9z0, I'm afraid I can't pursue this myself as I need to spend the little time I have on critical fixes or features that benefit the majority of users.

What we can do though is creating a feature request and tag it with "help wanted". If we provide a proper description I would not be surprised if another developer will pick it up and contribute it to the project.
