### ISSUE TITLE
Collision between project/context button class and builtin classes

### ISSUE THREAD

**Issue by 9z0** [ransome1/sleek#134]
**Describe the bug**

**To Reproduce**
- Create a todo: `(A) Test +lorem +ipsum +input`

**Expected behavior**
- Side bar project buttons should be about the same size.

**Actual behavior**
- `input` button is full width.

**Desktop:**
 - Windows 10, sleek 1.0.4, from GitHub.

**Notes**
- This is apparently because each button is given an HTML class name of "button {project_name}".
- If {project_name} is the same as an already existing class (like those provided by electron*), it inherits its style.
- Proposed solution: add a prefix/suffix to the class derived from the project name (or drop it, since all the buttons are the same so `button` class should be enough).

\* See for example under `resources/app.asar/node_modules/bulma/sass/elements`

**Comment by ransome1** [comment]
Another good one. Fix will be part of the final v1.0.5

**Comment by ransome1** [comment]
@9z0 has been released with https://github.com/ransome1/sleek/releases/tag/v1.0.5.

Can you please close this issue, if it works as expected?
