### ISSUE TITLE
Recurrence intervals for months and years could be more accurate.

### ISSUE THREAD

**Issue by zerodat** [ransome1/sleek#136]
Hi, @ransome1!  Just learned about **sleek** a few days ago, and I'm enjoying using it.  Thanks for making it!

One issue I've noticed is that sleek treats recurrence intervals of months as 30 days and years as 365 days.  Those aren't as accurate as they could be, since months vary from 28 to 31 days and there are leap years too.  Some other todo.txt tools do this better (for instance, [topydo](https://github.com/topydo/topydo), a CLI tool written in Python).

I have a fix to do this a little better, and will submit a PR soon.

**Comment by ransome1** [comment]
Thanks @zerodat , any help on sleek is highly appreciated!

**Comment by ransome1** [comment]
@zerodat , will be released with 1.0.5. Thanks for your contribution!
