### ISSUE TITLE
Archiving done tasks!

### ISSUE THREAD

**Issue by jason-mehmel** [ransome1/sleek#14]
This one is a feature request, something that occurred to me as we were dealing with the problem of completed tasks.

Simpletask Android does this via an 'archive' option, taking all the completed tasks and putting them in a done.txt file in the same local folder.

It would be awesome for Sleek to be able to do this as well! And even better, if it wouldn't overwrite the done.txt that Simpletask creates, so that whatever tasks completed in either don't overwrite the other.

Here's Simpletask's Github: https://github.com/mpcjanssen/simpletask-android

**Comment by ransome1** [comment]
I have been reading about the done.txt principals and it makes sense, especially if you're handling large files. Does Simpletask simply move the completed todos directly into the done.txt, once it has been marked as completed? And back into the todo.txt file, when you mark the todo as in progress again?

And what happens, if you have two different todo files in one folder? Does Simpletask use two different done.txt files?

**Comment by jason-mehmel** [comment]
I'm not 100% on the functionality of how Simpletask manages it, but I'll do my best based on usage!

Simpletask moves completed tasks to a done.txt file _**after**_ an archive request is made in the app. So they aren't moved to done.txt automatically every time a task is completed. The command is listed there as 'archive.'

There isn't any method to move tasks back to todo.txt once they're in done.txt.

I'm not sure about having two different todo files in one folder... I've never tested that! You might poke over at https://gitter.im/mpcjanssen/simpletask-android to ask if it's ever come up?

My **guess** would be that Simpletask probably isn't checking which done.txt would belong to which todo.txt... there would just be one done.txt and it would keep putting completed tasks at the bottom of the text file.

(I think if someone was going to maintain two different todo.txt files, maybe one for personal and one for work... then it would probably be best practice to have them in different folders too, but I digress...)

My feeling is that done.txt isn't a place to **automatically** put completed tasks, it's a place to _archive_ the tasks you've completed once the number of completed tasks feels like it needs cleaning. That's what I like about the Simpletask functionality.

(Also, it keeps the data somewhere outside of your current task list but still accessible if you wanted to audit the tasks later!)

That said, I could see some benefit in an automatic archiving of done tasks, maybe monthly? As an option? You can either trigger the archive whenever you want, or have it repeated at whatever frequency seems useful for the user. My initial request or hope would just be for a method to do it manually, but talking through this gave me some more ideas. (If manual is easy, then I'm fine if you stop there!)

**Comment by ransome1** [comment]
I see. That's pretty basic and implementing a button, that will only transfer finished todos from the todo file to a done.txt in the same folder, would be an easy exercise.

You have Simpletask on your Android phone, right? Could you please just check real quick, what happens if you transfer todos from two different todo files to the archive? It probably puts them into the same done.txt.

Automation could be step number two.

**Comment by jason-mehmel** [comment]
(An important note: Simpletask did have an option for 'auto archive' in it's settings that was switched on when I began this test. When auto archiving was on, it was writing each completed task to the done.txt file. I then turned it off and kept testing.)

Okay! I played with it in a test folder. I created a todo.txt and a todo-trial.txt.

Both todo.txt and todo-trial.txt appended their completed tasks to the done.txt file... and it didn't overwrite the file from one to the other.

A note about the auto-archiving option, it actually caused a bit of a problem. Dropbox ended up creating 'conflicted copy' versions of done.txt because I think the app was writing to the file at the same time as it was syncing? This was because I was tapping 'done' on a lot of tasks in a row very quickly. Whereas when I turned that off and then used the archive button, no problems came up.

Also, auditing those conflicted copies shows at least one task that was only reflected in one of the conflicted copies. If I hadn't checked, I might not have noticed, and would have lost that record after deleting the conflicted copies.

 So there might be a reason **not** to auto-archive on every completed task.

I don't want to distract us from the feature at hand, but it felt worth mentioning as it was connected to the idea of how often to transfer files to done.txt

**Comment by ransome1** [comment]
Ok, let's start then with a manual archiving function, represented by a button. 

Right now I am working on technical depths and this feature would follow right after that.

**Comment by ransome1** [comment]
Hi @jason-mehmel .

I just completed a first draft for that function and pushed it to Snaps Edge Channel: `sudo snap install --edge sleek`

So far I only worked on the function itself, not on how to implement that button into the user interface. So I just placed it under the search bar for testing purposes. If you have a good idea, let me know.

Can I ask you to check that version and give me feedback, if this is working as expected?

**What it does:**
Once the button has been pressed, sleek will separate completed and incompleted todos based on your selected todo.txt file.

Second it will check if there is a done.txt file in the same folder than your todo.txt. In case there is no done.txt, it will be created and filled with your completed todos. 

If a done.txt already exists, it will be read and compared with the completed todos that you're going to archive. Only todos, that are not already present in your done.txt will be moved. Like this there won't be any duplicates in your done.txt. At least none, that have been written by sleek.

Once archiving is completed, sleek will write the incompleted todos to your selected todo.txt file.

**Comment by jason-mehmel** [comment]
I played around with it!

It **didn't** create a done.txt when I tried removing the done.txt and then trying archiving. Here's what I got from the console:

Error in archiveTodos(): Error: ENOENT: no such file or directory, open '/home/jason/Dropbox/TODO/test/done.txt'

When there is a done.txt file present, it does write to that file, but with some errors? (I'm having a hard time duplicating them consistently, but here's some of what I pasted out of my done.txt file. It looks like it's sometimes bundling the done lines together into one line. At one point I noticed it elsewhere in the file than at the end.)

(I was copying the tasks back and forth between my done and todo files, so maybe sleek got confused when I had a task in todo.txt that had the same date twice in there... the double date info is probably when it records the completion? I just tried a cleaner version of the file with just one date and didn't get the same error as below.)

One other thing I've noticed, it may be connected to this change, when I complete a task in sleek, it's writing the completed task to the top of the file in todo.txt. Not a problem, necessarily (it looks like it's not overwriting anything) but I thought I'd mention it.

Line error example follows, first one shows two tasks on one line:

x 2021-01-11 2021-01-11 testing the done functionality 3 +testing @1_testingx 2021-01-11 2021-01-11 testing the done functionality 1 +testing @1_testing
x 2021-01-11 2021-01-11 testing the done functionality 2 +testing @1_testing
x 2021-01-11 2021-01-11 testing testing +1testing @1testing

**Comment by ransome1** [comment]
Hey @jason-mehmel . Sorry that sounds like an early development version got stuck in the Edge Channel. Could you try to update? It should be revision 191 now.

**Comment by jason-mehmel** [comment]
Aha! It looks like done.txt is being created now, as it should be. And the archiving looks like it's working both for a new file and appended to a created file.

I also tested it with two different todo.txt files in the same folder, and it's all writing to the same done.txt file!

**Comment by ransome1** [comment]
Has been released as part of 0.8.0
