### ISSUE TITLE
Call for testing: Cluster based loading of the todo list

### ISSUE THREAD

**Issue by ransome1** [ransome1/sleek#143]
**Call for testing**

As the rendering of todo entries is the most resource hungry task in sleek, users with large todo.txt files might be having performance issues, particulary on older hardware. This pre-release introduces a cluster based rendering, where not all items will be rendered at once. Instead the todos are splitted into clusters which will be loaded one at a time once the windows scroll bar has hit the bottom.

@9z0, @jason-mehmel, you guys are handling these huge todo files, right? It would be really lovely to hear about your experiences with this pre-release, please feel free to share your feedback.

**Comment by 9z0** [comment]
First snag: not working :)

I scroll with the mouse wheel, try PgDn, End, it doesn't load more that what was originally shown!

Win10

**Comment by jason-mehmel** [comment]
Question: do I need to download the pre-release separately? If so, do I
just snag it from Github? (Might be obvious but I want to double-check!)

~Jason
pronouns: he / him / his
***@***.*** | www.jasonmehmel.com

**Comment by ransome1** [comment]
@jason-mehmel, sorry, I forgot to add the link: https://github.com/ransome1/sleek/releases/tag/v1.0.5-4

**Comment by jason-mehmel** [comment]
No problem! Thank you! I will try to test this ASAP.

~Jason
pronouns: he / him / his
***@***.*** | www.jasonmehmel.com

**Comment by ransome1** [comment]
@9z0, I assume you downloaded the 1.0.5-4? I just downloaded it on my Win10 VM and it seems to be working with either scrolling, PgDn, and End.

**Comment by 9z0** [comment]
After you clicked a filter with dozens of todos?

**Comment by ransome1** [comment]
Yes

**Comment by 9z0** [comment]
I find no error in the console (other than a blocked matomo network request.
I diffed the old vs new render.js and I am trying to figure out the changes but my JS knowledge is not helping me much. :/

**Comment by ransome1** [comment]
Can you give me some detail on what exactly is happening on your sleek? Are just a couple of todos loading and then no more will be reloaded (when you reach the end of the view) or do simply all your todos load at once, as before?

**Comment by 9z0** [comment]
After opening the app (or clicking any filter) the first 25 todos are shown. They semm responsive (edit box loads, etc) but nothing more loads on scrolling. No errors on console. Just these:
```
Success: Table templates set up
render.js:962 Table build: nnn ms
render.js:158 Info: Hide onboarding
```

**Comment by ransome1** [comment]
Interesting. Can you check if by any chance you have a zoom setting other than 100% and if so, could you please reset it to 100% and try again? I have a gut feeling.

**Comment by 9z0** [comment]
Bullseye!

**Comment by ransome1** [comment]
Thanks, I'll look into it.

**Comment by ransome1** [comment]
@9z0, does https://github.com/ransome1/sleek/releases/tag/v1.0.5-5 solve this issue also on your side, when zoom is not 100%?

**Comment by ransome1** [comment]
Assuming the function itself works stable, you should experience a whole different performance if this feature is working as expected.

I was comparing the last official build 1.0.4 with the latest development build 1.0.5-5 on a todo file with around 500 entries.
**App start up time on 1.0.4**
![image](https://user-images.githubusercontent.com/11188741/120176986-3171ca80-c208-11eb-8993-5c6e9b24d922.png)

**App start up time on 1.0.5-5**
![image](https://user-images.githubusercontent.com/11188741/120176932-2159eb00-c208-11eb-92bf-f245dbf551cf.png)

**Selecting a filter with more than 100 todos behind on 1.0.4**
![image](https://user-images.githubusercontent.com/11188741/120177134-5fefa580-c208-11eb-97c5-ac10d95935fe.png)

**Selecting a filter with more than 100 todos behind on 1.0.5-5**
![image](https://user-images.githubusercontent.com/11188741/120177216-77c72980-c208-11eb-8722-35b63623cb36.png)

So if you're not experiencing any changes there might still be something wrong and I would love to reproduce it. Because I think this can be a small but very significant enhancement for any user, that is handling more than let's say 50 todos.

**Comment by 9z0** [comment]
I can confirm that it works with <100% zoom and that it is significantly more responsive. 👍

Two areas for improvement:
1. More of a bug: scroll down any list, change the rendered list (click another filter for example). Expected: show the new list from the top. Actual: keeps the scroll position from the old list which is not relevant.
2. In search bar: delay starting the rendering process until a certain time (300ms?) has passed since the last keystroke. This means no rendering on every character, but when the user actually pauses/stops.

**Comment by ransome1** [comment]
@9z0, I was able to fix 1., but I don't understand your describtion in 2.

**Comment by 9z0** [comment]
The events that trigger the **process** rereading/filtering the todo.txt and displaying the matching todos. Mainly:
1. Clicking on a context/project button.
2. Typing into the search bar.

If you want to search for a word of 6 characters (e.g. "urgent"), typing it will trigger that process 6 times (one for each character). This causes a delay (even with lazy loading, although smaller).

My suggestion is: set a small timeout after the key stroke (starting with the first character):
- If the timeout passes, start the process.
- If I type a second character before the timeout ends, cancel the timeout and start a new one (for the second character).
- And so on.

In practice, if I type "urgent" reasonably quickly, the process will happen only once after the last character.

**Comment by ransome1** [comment]
Ok, thanks for clarifying, now I understand. I don't really witness any delay myself, but of course I believe you and it might be bad UX particulary on older hardware. I added this as a future enhancement to my backlog.

**Comment by 9z0** [comment]
The number of todos probably has something to do with it as well. :)

It is a [standard behavior](https://davidwalsh.name/javascript-debounce-function) in many places, particularly when resource management matters. You will find it everywhere.

Anyway, I will be waiting for it. :)

**Comment by ransome1** [comment]
This has been released with https://github.com/ransome1/sleek/releases/tag/v1.0.5.

If any issue pops up, we will reopen this issue.
