### ISSUE TITLE
Keyboard Caret jumps to find during new/edit

### ISSUE THREAD

**Issue by nutnutwin** [ransome1/sleek#145]
**Is it an actual bug?**
Yes

**Did you check if the bug has already been reported?**
Yes

**Describe the bug**
When New/Edit ToDo and Press Shift+Tab
Keyboard Caret would focus on Searchbar, which is really weird

**To Reproduce**

**Do you see any error entries in sleeks developer tools?**

**Expected behavior**
Stay on New/Edit, jump to "Cancel"

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - Version of sleek 1.0.5-5
 - Source: Github
   https://github.com/ransome1/sleek/releases/tag/v1.0.5-5

@ransome1 hi, just found a bug in the newest version

**Comment by ransome1** [comment]
@nutnutwin a modal jail for tabindexing has been introduced with https://github.com/ransome1/sleek/releases/tag/v1.0.6-2

It should work with all modals in sleek, please feel free to give it some testing.

**Comment by nutnutwin** [comment]
> 
> 
> @nutnutwin a modal jail for tabindexing has been introduced with https://github.com/ransome1/sleek/releases/tag/v1.0.6-2
> 
> It should work with all modals in sleek, please feel free to give it some testing.

Works Perfectly! Thank you! 
@ransome1

**Comment by ransome1** [comment]
@nutnutwin this enhancement actually created a glitch in the auto complete container. In 1.0.6-2 you're not able to select the filters using the tab key. Its fixed in the next release, though.

**Comment by nutnutwin** [comment]
@ransome1 you fix bugs faster than I can report them. 
Will try the new version
Thank you

**Comment by ransome1** [comment]
Next release will be 1.0.6, the 1.0.6-3 pre release  doesn't contain the fix yet.

**Comment by 9z0** [comment]
There is another keyboard issue that I'll just  report here. Ctrl+Enter (submit todo) doesn't work. It does with the numpad Enter but not the main Enter key.

**Comment by ransome1** [comment]
@nutnutwin , does the later one still is present in https://github.com/ransome1/sleek/releases/tag/v1.0.6?

@9z0 I only have a laptop at hand, so no numpad. The Ctrl+Enter combination works fine here. Next month I might be able to test it with a keyboard. Is this still an issue in v1.0.6 as well?

**Comment by nutnutwin** [comment]
@ransome1 the tab focus on project/priority is Fixed 

Thank you.

**Comment by 9z0** [comment]
> @9z0 I only have a laptop at hand, so no numpad. The Ctrl+Enter combination works fine here. Next month I might be able to test it with a keyboard. Is this still an issue in v1.0.6 as well?

Unfortunately, yes.

**Comment by ransome1** [comment]
@9z0, I added your finding to my backlog and am closing here, as the topic is a different one.

**Comment by 9z0** [comment]
I noticed that Ctrl+Enter works if you wait a second between clicking `Ctrl` and `Enter`:
- Click `Ctrl` and keep it down.
- Wait a second or so.
- Click `Enter`

Also, if you do so while the cursor is at the end of a project like `+project|`, it shows the popup list but with only that project.

**Comment by 9z0** [comment]
The Ctrl+Enter issue seems to be solved with the latest 1.0.8! 👍

**Comment by ransome1** [comment]
@9z0 thank you for your feedback!
