### ISSUE TITLE
New Task Inherit? previous Recurrence

### ISSUE THREAD

**Issue by nutnutwin** [ransome1/sleek#146]
**Is it an actual bug?**
Yes

**Did you check if the bug has already been reported?**
Yes

**Describe the bug**
New ToDo Inherit previous designated Recurrence

**To Reproduce**
- Create a ToDo with Recurrence(eg. Daily), Save
- Create a second ToDo, this time it comes with Daily Recurrence(should be "no recurrence")
- ↑even if "Save" is not pressed(instead, Cancel is pressed), this bug can be reproduced 100%

**Do you see any error entries in sleeks developer tools?**
While sleek is open press Ctrl + Shift + I which will open the developer tools. If the shortcut doesn't work, press the Alt key, select the tab "About" and select the developer tools. In the dev tools select the tab "Console" and check if any error entries are written, while you provoke the bug.

**Expected behavior**
every new task come with Recurrence cleared(or set as default, in future versions)

**Screenshots**

**Desktop (please complete the following information):**
- OS: Windows 10 20H2
- Version of sleek 1.0.5-5
- Source: Github
- https://github.com/ransome1/sleek/releases/tag/v1.0.5-5

@ransome1 found another bug, reproduced on 2 PCs

**Comment by zerodat** [comment]
I can reproduce this.  It is a misleading UI problem, but doesn't seem to affect the task that is actually created.  When you start sleek the recurrence description in the edit task pop-up is `No recurrence`.  0nce you a select a task with a recurrence (say, `Monthly`) in it (open the edit task pop-up), then the recurrence value displayed gets "stuck" at `Monthly`.  If you create a new task, it doesn't get a recurrence value though.  So the UI indicator is lying to you.  It should say `No recurrence` and it will behave as if there is no recurrence unless you open the chooser and press one of the buttons again.

**Comment by ransome1** [comment]
@zerodat don't bother about it, it's already fixed and part of the next release ;)

On opening the modal form (add/edit) only the date picker gets reset, not the recurrence.

**Comment by nutnutwin** [comment]
@ransome1 thx!

**Comment by zerodat** [comment]
Thanks, @ransome1 !

**Comment by ransome1** [comment]
@nutnutwin, the fix has been released with https://github.com/ransome1/sleek/releases/tag/v1.0.5

Can you please check it and close this issue, if the issue is fixed?

**Comment by nutnutwin** [comment]
@ransome1 it is fixed, will close
