### ISSUE TITLE
Windows - reload replaced/updated todo.txt

### ISSUE THREAD

**Issue by D3JA5U** [ransome1/sleek#15]
Hi @ransome1,

I am a simple user, not a coder. I discovered your Sleek program for Windows a few days ago. I really like the look and feel of it - nicely done!

I am using SimpleTask (Cloudless) on Android with SyncThing to keep shared files updated between laptop (Windows), phone (Android) and a tablet (Android).

SyncThing replaces the todo.txt file that is currently open by the ToDo applications. This does not seem to be a problem for the Android apps, as they apparently simply reload the todo.txt on the fly or I can use a menu option to refresh the currently open file.

Sleek falls back to its start screen once the open todo.txt is replaced. It does reload the updated file eventually but it took from 30 to 90+ seconds during my tests and a few times it did not reload the todo.txt at all and simply stayed at the start screen.

In case I am not the only one with this issue, can the interval of file update checks be increased? Or a third button be added to the start screen to quickly refresh the most recently open todo.txt?

Thank you.

**Comment by ransome1** [comment]
Hi @D3JA5U.

That is interesting, because I too am using Syncthing and am not experiencing that problem. But let me see, if I can setup the file watcher to to wait a bit, before trying to reload the file. That should solve this problem.

If everything goes well, this will be part of the next release. 

If that doesn't solve the problem, maybe the button you mentioned might be a solution. Then sleek would not reload itself, but simply show a reload button, once a change on the file has been detected.

**Comment by D3JA5U** [comment]
Thank you for your quick response.
If it is working for you it could be an issue on my system only. 
I noticed that once Sleek falls back to its start screen and I want to (re-) open my todo file it always starts at the %user% folder, not the one where the previously used todo.txt resides but I assume that is working as intended.
Should not make a difference but I have the todo.txt on a second internal hard drive on the laptop. Will test this later by moving everything to C:

**Comment by ransome1** [comment]
@D3JA5U, I implemented a simple interval of 60 seconds, before the file is reread after it has changed. If you like, I'll upload it and you could check, if this solves the problem on your side. I am just not sure about the interval. For the general user experience the shorter the better I guess.

Are you using the exe file from Github's release page?

**Comment by ransome1** [comment]
Can I ask you something? When you look at the file in your Explorer and if you then change it in Simpletask, do you actually see it disappear and reemerge in Explorer?

**Comment by D3JA5U** [comment]
Version 0.6.0 was downloaded from this page. Today I deleted all folders related to Sleek 0.6.0 and the corresponding SyncThing pairs on all devices. I then downloaded version 0.7.0 from this page and I set up new folders and pairs in SyncThing for all devices. 

Now, I am happy to report that all is working as expected. Sync is being done within seconds of changing a todo list item on any of my three devices :)

To your question: I actually do not see the todo.txt file disappear/reemerge during sync. Looks like it is not changing in Windows Explorer or it is happening so fast that I can not catch it.

**Comment by ransome1** [comment]
Oh really? I haven't uploaded the version with the timer yet :) Did you change anything on your setup?

**Comment by D3JA5U** [comment]
A newer version of your program and I am running it from C: drive now. I used Sleek to create a new todo.txt file. The previous todo.txt I had started in Notepad++. Maybe it was corrupted somehow but the Android devices had no issues with it. The rest is the same as before.

**Comment by D3JA5U** [comment]
To close this topic off - likely a glitch/issue on my side. It is working perfectly on 0.7.0. Thank you @ransome1 for swiftly responding to an average Joe trying out your sleek code 👍
