### ISSUE TITLE
Security - setuid chrome-sandbox

### ISSUE THREAD

**Issue by jcz1** [ransome1/sleek#150]
Hello.

In latest version (1.0.5) there is a setuid binary file /opt/sleek/chrome-sandbox owned by root.
chmod is in postinst script (Debian package):

...
# SUID chrome-sandbox for Electron 5+
chmod 4755 '/opt/sleek/chrome-sandbox' || true
...

There are some discussions about it and i think there is no need to use setuid anymore.

https://bugs.chromium.org/p/chromium/issues/detail?id=598454
https://forum.unity.com/threads/why-does-chrome-sandbox-need-root-rights-suid-set.365818/

I changed mod to 0755 and use firejail for sandboxing now. No prob.

**Comment by ransome1** [comment]
Hi @jcz1, please help me understanding the issue a bit better. After running the Debian package from Github release page, you find '/opt/sleek/chrome-sandbox' to be owned by root with chmod 4755, correct? And on your Debian this prevents sleek from starting up?

The only thing I found are actually workaround on user side: https://github.com/electron/electron/issues/17972#issuecomment-516957971

In general I am not sure what I can do about this in sleek itself. My first thought was this most likely to be an upstream issue as electron-builder, Electron or Chromium.

`There are some discussions about it and i think there is no need to use setuid anymore.`
I can't really comment on this. But even if, I think this is something which will be done somewhere upstream?

If you have more insights on this issue, please feel free to share.

**Comment by jcz1** [comment]
setuid => root permissions. My Debian didn't prevented sleek from starting, but i did :) I don't want external packages with setuid. Specially if it is not necessery. 

Thanks for electron link. There is:

"When CLONE_NEWUSER is unavailable, Chromium falls back to using a different sandboxing mechanism that requires a helper binary that is setuid to root."

Now i found kernel.unprivileged_userns_clone is 1 in Debian unstable, but 0 in stable. So it seems it is too early to make a change. Or it is upstream (electron) problem (kernel.unprivileged_userns_clone detection).

Btw there is extra sandbox Debian package for Chromium: https://packages.debian.org/buster/chromium-sandbox and Chromium is working without it (unstable).

I suggest to close this now. Anyway thanks for this project, i like it because it is live. Thanks for discussion :)
