### ISSUE TITLE
MacOS Icon sizing

### ISSUE THREAD

**Issue by AdamBD** [ransome1/sleek#156]
![image](https://user-images.githubusercontent.com/1134525/120861077-69259d00-c58f-11eb-893d-8d51146e585e.png)

Just a small cosmetic ask. You can see the size ratio of the icon is non-standard with default OSX icons. Anyway to scale this down a bit?

**Comment by ransome1** [comment]
@AdamBD, thanks for reporting. I like fine tuning the details. This will be part of the next release.

**Comment by ransome1** [comment]
@AdamBD I updated the dock icon in https://github.com/ransome1/sleek/releases/tag/v1.0.6-1 but I can't test it due to a lack of Apple hardware. I would appreciate if you could take a look if the new icon is working well.

**Comment by AdamBD** [comment]
![image](https://user-images.githubusercontent.com/1134525/120931143-0223f780-c6f9-11eb-9d24-a45f252bb569.png)

Unfortunately its still a larger ration : /

**Comment by ransome1** [comment]
Interesting, I just checked it on one of those new Mac book Pro in 13 inch and the icon had a padding around it. But i have to add that i checked on v1.0.6-3. Can I ask you to check the latest release real quick?

**Comment by ransome1** [comment]
Hi @AdamBD , could you please double check the https://github.com/ransome1/sleek/releases/tag/v1.0.6

I got my hands on a Mac again and there it looked like this:
![image](https://user-images.githubusercontent.com/11188741/121809612-bf64a100-cc5d-11eb-9732-40aa1efce2f5.png)

I would really be confused if this differs from other Macs.

**Comment by AdamBD** [comment]
@ransome1 looks good! Thanks :)
