### ISSUE TITLE
An option to use an existing task as a template

### ISSUE THREAD

**Issue by wsdfhjxc** [ransome1/sleek#16]
An option named Template could be added to the three-dots context menu. It would result in opening a pre-filled dialog to create a new task, with its content being identical to the original task (due dates, contexts, tags, etc.), but with the original description being replaced by "__________", so that it could be easily double-clicked and overwritten by the user with a new description.

I think such feature can be quite useful, well, at least it is for me. And what do you think about that?

I could even give a try at implementing it and sending a pull request, if you wish so.

**Comment by ransome1** [comment]
Hi @wsdfhjxc I do like the idea, it's not hard on the interface, might be useful to some and I am reworking the more menu at the moment anyway (It's a little static right now). I could easily add this feature, once I refined the more menu. Of course I more than appreciate your offer :)

There is one thing though I am unsure about and that would be the naming "Template. You and me get the meaning, but I am not sure if all users will guess what this button would do. When I read your idea I was thinking that it's basically a "Duplicate" function. So my suggestion would be to name it Duplicate or something a little more self-explanatory like "Use as template". But then again I am not native english and maybe you got a better idea on naming?

**Comment by ransome1** [comment]
Also: Would it be useful if after the window with the duplicate appears, to highlight the "__________" only? Javascript should be able to accomplish this.

**Comment by wsdfhjxc** [comment]
Yes, "Use as template" would be the most suitable label for this action.

And the suggestion about automatic selection of the placeholder description is very clever :ok_hand: .

So, I have it all sorted out in my fork already. But since you plan to rework some related things, I suppose I have to keep it for myself for the time being. However, if you want to take a look at the changes, just tell me, and I'll create a pull request.

**Comment by ransome1** [comment]
I didn't realise you are already working on it, that's great. If you're feature is stable, feel free to send me your pull request and I'll merge it. Even if the rewritten more menu won't be finished until next release, your feature would be part of it.

Thanks for your work!
