### ISSUE TITLE
[Windows] Escape while using Google Japanese IME cancel New/Edit Window

### ISSUE THREAD

**Issue by nutnutwin** [ransome1/sleek#161]
**Is it an actual bug?**
Yes

**Did you check if the bug has already been reported?**
Yes

**Describe the bug**
When typing Japanse using Google Japanese Input
> https://en.wikipedia.org/wiki/Google_Japanese_Input
or other non-alphabetical language using IME(eg. Chinese)
Escape is usually used to cancel the IME floating window, which shows the possible choices for input. 
(works in most other apps like vscode, in Command Palette ...

in sleek, Escape while IME window exist would close the New/Edit Window

**To Reproduce**
- Open New/Edit ToDo window
- Switch to Google Japanese Input(will help if you need)
- Type something to show the IME window
- Press Escape

**Do you see any error entries in sleeks developer tools?**
no

**Expected behavior**
Cancel the IME Window, but leave the New/Edit Window

in 1.0.6-3 Beta, both IME and New/Edit Window are closed

**Screenshots**
![20210606_Sun -220201](https://user-images.githubusercontent.com/34512273/121664742-c4511580-cae2-11eb-8ee9-1e8a8b967ccb.png)
Attachment shows New ToDo Window, and IME window to pick words
From there if Escape is pressed, both windows disappear

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version of sleek 1.0.6-3
 - Source: Github

**Comment by ransome1** [comment]
@nutnutwin , I am reproducing it the right way in this screencast?

https://user-images.githubusercontent.com/11188741/122544157-ceb46780-d02c-11eb-8af5-8cf3188a830b.mp4

In the end I press Escape and it only closes the IME layer. If this is the right behavior, could you please check the 1.0.6-1, if it works also on your system like this?

**Comment by nutnutwin** [comment]
@ransome1 
Hi, the screenshot you posted, is how I would love it. 
On previous problematic version, 
- Microsoft Japanese IME works
- Google Japanese IME does not work

on 1.0.6-1 released today, both works

Thank you so much

**Comment by nutnutwin** [comment]
@ransome1 

due to limited time I only tested Stable Releases
It seems the degression happened between 1.1.6〜1.1.7
2022, March

```
1.1.3
	➤Works Fine
1.1.5
	➤Works Fine
1.1.6
	➤Works Fine
1.1.7
	➤Degression
```

**Comment by ransome1** [comment]
@nutnutwin could you please check if this occurs in `2.0.1`?

**Comment by ransome1** [comment]
I switched my input language to Japanese and was able again to open the IME window. Pressing `escape` does close it. Only another press on escape will close the dialog window. I hope it works like this on your end as well. If not, please re-open here and I will take another look at it.

https://github.com/ransome1/sleek/assets/11188741/667c7423-be2c-4f95-8915-1ba6e8a38f5b
