### ISSUE TITLE
Showing "projects" at the beginning of ToDo

### ISSUE THREAD

**Issue by nutnutwin** [ransome1/sleek#163]
**Did you check if a similar feature request has already been reported?**
Yes

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
- Showing Projects at the beginning of the ToDo, so I can tell which project the Todo belong to, 
without going to the end of line
- Alternatively Showing the Project as a Second line, so they are shown on the begining of line

**Describe alternatives you've considered**

Thank you @ransome1

**Comment by ransome1** [comment]
Hi @nutnutwin . Is this a duplicate of https://github.com/ransome1/sleek/issues/135 ? Of not can it be merged with your idea somehow?

**Comment by nutnutwin** [comment]
@ransome1 
Sorry for the mistakes
I merged Sorting into #135, and kept this issue

**Comment by ransome1** [comment]
Hi @nutnutwin , I understand your use case, as you propably have a big focus on projects on your work, right? But I don't think I support the idea of putting projects at the beginning of the todo line. In my opintion tags should always follow the content itself. Like other todo.txt apps do it as well. Or even the issue list here on Github. This is something learned by most users and part of an expectation driven approach to usability.

The issue with the new line for projects (and why not contexts would be my next question) is, that it would add significant row height to each todo with an assigned prject. I think this would affect the usabilty deeply as users now would have to scroll a lot more. There are some users with 500+ todos which would not appreciate this, I think. 

What you're propably looking for is the second group criteria ;) It's on the roadmap, but I can't give you a timeline for this yet.

Is the "sort by Projects" setting a workaround for you?

**Comment by nutnutwin** [comment]
@ransome1 thank you for understanding
I am happy the two critieria is being considered

Yes projects/tag on beginning is not good for everyone

If you dont mind I would close this issue?

**Comment by ransome1** [comment]
@nutnutwin I don't mind :)

**Comment by nutnutwin** [comment]
@ransome1 Thank you
