### ISSUE TITLE
<strong>TypeError</strong> in function undefined: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by caclob** [ransome1/sleek#164]
I get this error on start up of Sleek. <strong>TypeError</strong> in function undefined: Cannot read property 'push' of undefined

![image](https://user-images.githubusercontent.com/81861094/122349818-e5838d00-cf4c-11eb-984a-bb3afcdf7271.png)

**Comment by ransome1** [comment]
@caclob , can you please use the pre defined bug template and provide the minimum amount of information that is needed? Thank you.
