### ISSUE TITLE
Add Coding project directories as source for TODO items

### ISSUE THREAD

**Issue by JordyScript** [ransome1/sleek#165]
Programmers will often leave TODO comments scattered throughout their code when they have a coding project. Ideally you have one source of truth and don't duplicate TODO items in both your code and a separate todo.txt file. Using sleek as a UI frontend for managing TODO comments in coding projects would be a really handy feature. 

Describing some parameters for an implementations: 
1. Coding projects can consist of multiple files grouped together in a shared parent directory with optional subdirectories. Therefore, functionality should be added to add a directory as the source of multiple TODO files, similarly to how multiple TODO files have been made possible by #9 . Sleek would then recursively descend into this directory and look for all relevant files.

2. Coding projects can hold files that are not directly relevant to the developer and these should be ignored (even if they contain todos). Such files are commonly specified in a .gitignore file. Therefore files and directories specified in .gitignore should be ignored.

3. Comment styles vary by programming language with most languages using either: 

    hash style `# TODO: Example Comment` 

    or:
    slash style `// TODO: Example Comment` `/* TODO: Example Comment */`
    but other styles exist such as well.

    Therefore, various commenting styles should be expected based on the extension of the file in question, or possibly a universal regular expression could be used to recognize comments in any language. Only comments that start with TODO: should be imported into the sleek UI, other comments should be ignored.

4. Ideally, TODO comments should not only be read into Sleek, but also be updatable from Sleek's UI, so Sleek should keep track of the filename, line number, and original string in order to securely patch the source code/script files when making changes to the todo item from the Sleek UI.

    If TODO comments are updated from sleek and there were no changes in the source file, then the original string can be replaced by the updated string with a simple find and replace in the original source code/script file assuming there are no duplicate/identical TODO's in different places in the same file, otherwise a specific line can be altered.

    If TODO comments are updated in the source file outside of sleek, or comments move places because the surrounding lines are edited in a text editor or IDE, then simply scanning the file again will suffice to have an up to date record of each item. A refresh button for directories added to sleek for monitoring (as mentioned in point 1) is also neccessary, or sleek could keep track of the filenames and hashes and automatically poll for changes every so often. (the automatic solution is preferable)

5. Handcrafted TODO comments in source files don't typically follow the full spec of todo.txt, but it should just be possible to take the entire string and prepend / append  the relevant sections (priority, creation date, start date, due date, project, context) upon first discovery and then update the source file with the well formed TODO. 

6. TODO comments found in projects directories added in this way should all automatically have the name of the project root directory added as a project (e.g. +mobile-app, if you added a directory `mobile-app` with source files) if that is not already in the TODO string.

 The most high performance / fastest and most feature complete way to quickly recursively search text files in directories while respecting .gitignore files that I know of is ripgrep, a rust command line utility. Perhaps this could be used in the backend and its output used to get the necessary information from the source files in question.

What do you all think?

**Comment by ransome1** [comment]
That would be a win for me as I do leave exactly this kind of comment in my code ;) If it is a feature that would benefit many or attract new users, would be another question. Opinions on this suggestion are most welcome, I will at least think about it.

**Comment by 9z0** [comment]
While the idea is useful, I have to say it seems significantly outside the scope of the todo.txt format and philosophy.

I feel bad raining on your parade, but I wouldn't want the purpose of the app to be diluted. 😕 We don't have that many good todo.txt apps and I wouldn't want the development of Sleek to be sidetracked/bogged down.

However, if @ransome1 thinks it must be done, then maybe in a more general-purpose fork/sibling of Sleek?

---

In the mean time, there is a very good VS Code extension (which uses ripgrep btw!) that is built around this idea is [Todo Tree](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree) (GitHub [repo](https://github.com/Gruntfuggly/todo-tree)).


![](https://github.com/Gruntfuggly/todo-tree/raw/master/resources/screenshot.png)

**Comment by JordyScript** [comment]
Thank you for your feedback.

> While the idea is useful, I have to say it seems significantly outside the scope of the todo.txt format and philosophy.

I see it exactly the opposite way: this is not a violation of the todo.txt philosophy but its proper application. The todo.txt format works so well for use in source code because source code is plain text, and the reason the TODO comments have to reside in your code and not in a separate file is because they benefit from the context of the surrounding code.

It is precisely this versatility of use cases and seamless integration across applications that the plain text format allows for and excels in that is at the core of the todo.txt philosophy.

While keeping todo's in your source code files is beneficial when you are already working on the code in your text editor / IDE, there is also a good reason why you would want to have your scattered TODO comments aggregated. When it comes to planning your work, your side projects, your whatever else you do, you benefit from having a single source of truth. One window that can give you an overview of every task you've committed to writing, regardless of where it is in your filesystem,  because the relevant context for that decision making process is not your code, but your other tasks /  the rest of your life.

> I feel bad raining on your parade

No need to :)  it's precisely this type of constructive criticism that allows projects to make the best decisions for their intended use.

> I wouldn't want the purpose of the app to be diluted / confused 

Just like people who use a single todo.txt file are not bothered by the addition of the feature to add multiple todo.txt files (resulting from issue #9 ). People wouldn't be bothered by the addition of a feature to add a directory with files out of which todo items are filtered. If you don't use it, it never gets in your way. We're just adding one more way to add plain text files that contain todo's in the todo.txt format.

> I wouldn't want the development of Sleek as a todo.txt app to be sidetracked/bogged down.

Initially some resources would have to be invested here, but i don't think the maintenance burden will be high because most of the heavy lifting can be done by the very performant and well maintained ripgrep. The glueing of functionality is a one time effort after which it should just keep working. You may even be the right person to help out with this given your experience building [Todo Tree](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree), if you so please.

> However, if @ransome1 thinks it must be done, then maybe in a more general-purpose fork/sibling of Sleek?

I think forks and fragmentation are potentially a bad thing for both developers and the community unless the original project is user hostile, in which case forking is a good thing for the community. 

The developer(s) of a project benefit form a larger (unified) community because it means more testing / bug reporting gets done by users and the small percentage of people who take the time to report bugs translates to higher absolute numbers of people. Also more funding / donations go to the original developers if they manage to keep their community together. Also the even lower percentage of people  who take the time to contribute code to the project and may potentially become core devs translates into higher absolute numbers if the community is not fragmented.

> In the mean time, a very good VS Code extension (which uses ripgrep btw!) that is built around this idea is Todo Tree (GitHub repo).

I'm a happy user. Never thought I'd run into you in the wild, but thank you for making a great extension! As a matter of fact, I'd continue to use your extension even if sleek adds the feature i suggest, because Sleek and Todo Tree fulfil different needs for me. While Todo Tree works great when I'm navigating and working inside one project, it doesn't give me an overview of all of my projects, let alone of non programming tasks I may want to include in my decision making when I'm planning what to do.

<hr>

Hopefully if @ransome1 gives the OK then we can discuss implementation details, cuz I do want to keep it as simple as possible. I'm definitely not suggesting including a database or anything. Plain text files remain the ground truth. There's just some internal runtime state to keep track of the origins of individual tasks which is not persistent across sessions, similarly to how you already need to keep track of task origins with multiple todo.txt files.

**Comment by JordyScript** [comment]
> That would be a win for me as I do leave exactly this kind of comment in my code ;) If it is a feature that would benefit many or attract new users, would be another question. Opinions on this suggestion are most welcome, I will at least think about it.

Thank you for your consideration! I've never done any electron development, or I would make a pull request. The most I can do in the short term is help with ideas and I do invest significant time thinking about this.

As the owner of the project, the ability to use this feature personally and any ensuing productivity gains seem like a good enough reason for implementing this feature if there are no overriding concerns. but of course it's important to properly consider it first.

**Comment by zerodat** [comment]
I tend to agree with @9z0 that this would be a bit outside the scope of sleek itself.  Having sleek scan a potentially large body of code with ripgrep on startup would delay startup and would still not guarantee that the list stays up to date.

Instead, why not implement a simple command line tool to scan a set of project directories and extract the TODO comments into a new todo.txt format file?  Then if sleek is extended to read multiple todo.txt files, you could have one such file for your TODO comment items, while keeping other todo items in a separate file.  If you work on linux, it would be simple to use a cron task to update the generated file automatically on whatever schedule you prefer.  This seems like a great way to reduce the complexity of sleek and still have the todo list generated from the code.  Writing such a tool in python or even in bash should be fairly easy.

**Comment by 9z0** [comment]
> this is not a violation of the todo.txt philosophy but its proper application. The todo.txt format works so well for use in source code...

I meant the philosophy of a simple text file just for todos, not the syntax itself. It was created precisely for the simplicity. I agree that the syntax could be used in other approaches like yours.

I also understand the need for a `// TODO` within their own context. I am just saying that monitoring a directory tree of files and scanning for certain lines to include based on certain matching keywords is NOT the todo.txt approach, even if such use deserves an GUI app.

---

> No need to :) it's precisely this type of constructive criticism that allows projects to make the best decisions for their intended use.

👍

---

> If you don't use it, it never gets in your way.

I agree with you, but see my next points.

> Initially some resources would have to be invested here, but i don't think the maintenance burden will be high

> forks and fragmentation

Theoretically, yes. And I do like apps with features (and have asked @ransome1 for features). The problem (as I have seen myself in many projects) is that:
- if  a single app/function A takes **1x** time/effort to cover need/approach X, and
- a single app/function B takes **1x** time/effort to cover need/approach Y,
- a single app/function C to cover both X and Y takes a LOT **more than 2x**.

Which is why I suggested a separate fork (by @ransome1 himself, if he decided to do it. I didn't mean another developer).

---

>given your experience building [Todo Tree](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree), if you so please.

That is definitely not me!

**Comment by JordyScript** [comment]
@zerodat said:
> Having sleek scan a potentially large body of code with ripgrep on startup would delay startup and would still not guarantee that the list stays up to date.

Scanning the directory can be done asynchronously and ripgrep is very performant, it's the fastest tool around for this task. Ripgrep will run in a separate process (or multiple processes for multiple folders) while regular todo.txt files are being parsed and loaded and the UI is being drawn, and in all but the most extreme cases it will have returned its output in a timely manner, which then becomes the equivalent to a regular todo.txt file except with a slightly different parsing stage (cuz of filenames and line numbers in the output).

And even if we had to wait in those extreme cases, it's up to the user to decide if they think having all of their tasks in one well designed UI is worth the additional loading time. Only people that opt in to scan project directories and have extreme volumes of code would have noticeable additional loading time and it may be worth it for them (bear in mind, node_modules and such would be skipped by ripgrep because of .gitignore). But the users with extreme volumes of code would notice delays in any tool they use and will simply have to accept that fact.

The list staying up to date is ensured by  (1) Sleek writing back changes to the source files (filename and line number are provided by ripgrep) and (2) loading source files afresh on each start up of Sleek (+ maybe a refresh button in the UI?). The design parameters I proposed initially can be simplified if we operate under the assumption that files won't be edited simultaneously in Sleek and a different editor (which is probably the same assumption that Sleek already makes when it comes to regular todo.txt files). 

> Instead, why not implement a simple command line tool to scan a set of project directories and extract the TODO comments into a new todo.txt format file? Then if sleek is extended to read multiple todo.txt files, you could have one such file for your TODO comment items, while keeping other todo items in a separate file. If you work on linux, it would be simple to use a cron task to update the generated file automatically on whatever schedule you prefer. This seems like a great way to reduce the complexity of sleek and still have the todo list generated from the code. Writing such a tool in python or even in bash should be fairly easy.

Thank you for the suggestion. I've thought of that approach, but I found it impractical for the following reason:

If the feature is added, then Sleek would write its changes directly to the relevant source code files, rather than an intermediate file, thus simplifying the process by syncing directly between source file and internal state. In its internal state, Sleek would know and keep track of:
1. source file path
2. line number (optional) 
3. original task string
4. updated task string

That means Sleek could easily:
1. find the original task string in the corresponding source file
2. and replace it with the updated task string

If you create an intermediate todo.txt file using a cron job, then Sleek would write an updated task to the intermediate file instead of the source code file the task originated from. Now, in order to persist the changes you made in Sleek you need to prevent the changes from being overwritten by the next run of the cron job. In order to do that, you need to write those changes back to the original source files. So, now you need to figure out what source file path the changed task string belongs to and what the original task string was before it was overwritten by Sleek, but without having a place to store this information safely and without the knowing cooperation of Sleek when it's writing to the intermediate todo.txt file. Good luck :disappointed_relieved: 

Such a solution is error prone and overly complex, to the point of being unworkable. Furthermore, such a solution would be inherently brittle, because it will depend on reading/writing behaviour that may change across versions of Sleek, potentially resulting in lost data after updates. 

Lastly, such a DIY solution would not benefit the other users of Sleek who might use and benefit from the functionality I proposed if it were implemented, but who may not even have realized that this is a feature they want, because they simply haven't thought of it.

**Comment by JordyScript** [comment]
> That is definitely not me!

Ooops ! instead of "a very good VS Code extension (which uses ripgrep btw!) that **is** built" i read "a very good VS Code extension (which uses ripgrep btw!) that **i** built"

> I meant the philosophy of a simple text file just for todos, not the syntax itself. It was created precisely for the simplicity. I agree that the syntax could be used in other approaches like yours.
> I also understand the need for a `// TODO` within their own context. I am just saying that monitoring a directory tree of files and scanning for certain lines to include based on certain matching keywords is NOT the todo.txt approach, even if such use deserves a GUI app.

Fair enough. I see decisions of where to store your tasks (e.g. in how many files, whether to include extra contextual information in a file which is not itself a task) as secondary to whether it is plain text and the syntax is followed. If someone wants to have one todo.txt file for work in which he includes a section of email addresses that aren't themselves a task, but are important context to certain tasks (e.g. sending quotes), and wants to have another todo.txt file for private matters in which he includes a list of films to watch that are not themselves a task, but are context to certain tasks (e.g. planning a party), then I think they are in line with the philosophy. Source code is similar to me, just the ratio of context / task is higher. The aggregation and filtering is then simply one way of choosing to work with the todo.txt format.


> Theoretically, yes. [but the sum difficulty of maintaining orthogonal features can be greater than the difficulty of its parts]

It can be depending on how much tension exists between the separate features. In my mind adding the feature I requested could be as simple as only adding a conditional preprocessing step. I'll explain one potential approach:

1. Run ripgrep on the project folder designated by the user if the source is a folder, not a file.
2. Use the output of ripgrep as a virtual filesystem out of which Sleek draws the filenames and associated tasks. 
 
ripgrep output looks as follows:
```
filename1
matching line 1
matching line 2

filename2
matching line 1
matching line 2

[etc.]
```
Split it on double newline to get filename + tasks groupings.
```
filename1
matching line 1
matching line 2
```
Split that one newline and separate the first line from the remaining lines to get filename + tasks

3. Then proceed like normal, as if you have read the file from a regular todo.txt file and write any changes to the corresponding original file using a find + replace.

If Sleek is implemented much differently from how I imagine, then it could get as complicated as having an entirely separate parallel pipeline without any overlap with the existing pipeline. I guess @ransome1 will be the best judge of how complicated this will get in practice.

> Which is why I suggested a separate fork (by @ransome1 himself, if he decided to do it. I didn't mean another developer).

Thanks for clarifying. That's certainly an option to weigh.

**Comment by zerodat** [comment]
Well, @JordyScript , I guess this is a matter of personal taste.  I have large bodies of code that I wouldn't want to scan on startup of an interactive tool.  Also, I don't think I would really want sleek to make changes to source files.  It seems to me that the editor (say, VSCode) is a better tool for finding and updating those TODO comments in the code, and marking them as done once you are finished.  You are likely editing that code anyway to implement the TODO.

So (again, a matter of personal taste), I would use those TODOs in sleek as only a way of keeping track of my outstanding development commitments and deciding what to work on next, not as a code-aware tool in its own right.  Can you give us some examples of the type of changes that you would make to those TODO tasks from within sleek if you had your proposed feature?

**Comment by JordyScript** [comment]
>  Can you give us some examples of the type of changes that you would make to those TODO tasks from within sleek if you had your proposed feature?

Basically, the usage I envision is the planning phase of the tasks and the changes that you would make to the metadata associated with tasks in that process.  So that would include changes to priority, due date, adding/removing contexts and projects, for example. For changing the actual task description it would usually be done in the text editor / IDE environment because those changes likely depend on the context which is absent in sleek, but it occasionally can be done from sleek (if you can reword something, fix a typo, whatever). Creating new tasks, however, would exclusively happen inside of the IDE/text editor environment. 

During the planning stage you don't necessarily have your text editor/IDE open yet because you've not actually gotten to the point of executing your tasks, but are deciding what to do and when to do it. (and even if you did have your IDE open, then you still wouldn't be able to see all of your tasks across projects like the proposed Sleek feature would allow for)

**Comment by JordyScript** [comment]
Okay, I've had a look through the source code and played with the app some more. 

My understanding of how Sleek handles multiple todo.txt files was wrong. You can only view one file at a time, whereas I was hoping you would be able to view your todo's form all files at once.

My understanding of how it reads and writes files was also wrong. File reading is done by a filesystem watcher that reloads the UI with a fresh read from the file upon change. File writing is a complete overwrite of the old file with all tasks when a single task is changed.

So in order to implement my proposed functionality, it would be closer to the worst case scenario than the best case scenario that I mentioned in my previous comment. Which is to say, an entirely separate pipeline would be added that shares little in common with how things are currently done. Or, the app logic itself would need to be redesigned in order to have a more generic solution to the problem of reading/writing todo's that works for single file, multi-file, and project directory with source code. This would then also make it possible to view the contents of multiple todo.txt files at once.

If you wish to keep Sleek as simple as possible, then I  fully respect that decision. I do think the complexity would increase if we did choose to implement the functionality I proposed.

Ripgrep and Sed are enough to get the job done in terms of finding all todo's in a source tree and patching only the specific comments that were changed. 

A hash on the output of ripgrep, triggered by a filesystem watcher monitoring the directory, could be used to check if any relevant comments changed and refresh the UI with the updated comments.

filename + line number  + original comment could be used to patch only the comment that was changed using sed. 

ripgrep and sed (in some cases) would need to be bundled with the software for this to work, but this should be possible on all platforms.

I've written the necessary cli commands for this to work, but the question is now: does @ransome1 want this. The app's logic would have to be rewritten, but if @ransom1 wants this, I can discuss the necessary changes / the new logic.

**Comment by ransome1** [comment]
I have to admit having misunderstood your initial proposal and only realized it after zerodat mentioned a possible workaround. Initially I thought  this workaround was what you were looking for: A periodically read of a code base and transfer to a separate todo.txt file managed by sleek.

As you saw yourself, sleek is a simple application that only watches one file at a time. This eliminates lots of complexity, is surprisingly performant and works quite well in general.

Although the implementation of your idea doesn’t sound like rocket science, it would still be a major feature. sleek would be watching a huge code directory, needs to be married with ripgrep or similar, needs to be significantly rewritten to be able to handle multiple file watchers, needs various adjustments to the GUI and would need to replace single lines in many sensitive files. In particular the last point is the one I am uncomfortable with.

Beside significant amount of development hours, I am not sure if it would actually be the best solution to approach the problem. As mentioned by 9z0 there seem to be extensions that do this tasks directly within the developers environment. As for Atom, which I use, I stumbled upon a module which does collect all lines starting with „//TODO:“ presents them as actual todos in a nice looking panel. So if there are little extensions in many editors already, I am not fully convinced this would either be a USP for devs or a feature the typical sleek user would want.

**Comment by JordyScript** [comment]
Thank you, @ransome1, for your consideration. I've given my best case for the proposed feature, but with your judgment on the matter I'll consider this issue settled then.

After this discussion, however, I'm firmly convinced that an app that implements this feature can be built much more easily than I anticipated. I have to credit you and your project for inspiring me to develop this idea. And thanks to @9z0 and @zerodat for the critical review as well, without which I possibly would not have looked into this deeply enough to come up with an MVP implementation.

Your project is indeed wonderfully simple, and I intend to build an app that is equally elegant and simple but which is built on a different foundation so that it can do the job I want it to do. I may even take some UI/UX design cues from you, cuz you really did make a beautiful app. I hope you will give it a try when I open source it and give me some feedback, and maybe you can point other users that look for similar functionality to my app, seeing as you won't implement this yourself. (@9z0 and @zerodat , you're also welcome to try and give feedback of course)

Until I've built my app, I'll remain a happy user of Sleek. I'll post a link in this issue when I've open sourced it. If you and the other participants are done discussing this issue, then you can close it for the time being. I should be able to still comment here once I've published the app.

**Comment by ransome1** [comment]
@JordyScript thanks a lot, I appreciate your words and I more than welcome your decision to fork sleek and work on the idea (which I still think is pretty good). If you need feedback let me know, I will support you where ever I can. Maybe this is going to be more simple than we thought and can be married with the GUI neatlessly.

**Comment by 9z0** [comment]
@JordyScript Look into this command line tool: https://github.com/jakewarren/fixme

**Comment by JordyScript** [comment]
Thanks for the recommendation! I've been a bit busy lately, so have yet to make a serious attempt at implementing (I've played around a bit to get a feel for it, but nothing worth publishing yet). This tool looks useful though it lacks the interactivity I'm looking for. It's helpful to see how others have gone about implementing similar solutions.
