### ISSUE TITLE
Leftover merge tokens in index.html line 307

### ISSUE THREAD

**Issue by zerodat** [ransome1/sleek#166]
Looks like some git merge tokens are left over in index.html at line 307-311?

```
    305               <div id="recurrencePicker" class="field">
    306                 <div class="control has-icons-left">
    307 <<<<<<< HEAD
    308                   <input id="recurrencePickerInput" class="input" tabindex="0" readonly>
    309 =======
    310                   <input id="recurrencePickerInput" class="input" readonly tabindex="-1">
    311 >>>>>>> develop
    312                   <a href="#" class="icon is-left" tabindex="-1">
    313                     <i class="fas fa-redo"></i>
    314                   </a>
    315                 </div>
```

**Comment by ransome1** [comment]
Thanks for pointing it out @zerodat 

It's long gone on my local branch and just a leftover in the remote ones. Or did you see it within an actual release as well?

**Comment by zerodat** [comment]
Thanks, @ransome1 .  Sorry if it is a false alarm.  No I found it on the head of the master branch, not in the release which is one commit back.  I generally build the master branch when I'm experimenting.

**Comment by ransome1** [comment]
@zerodat the leftover is now gone also on remote. By accident or do you use a code scanning tool for this?

**Comment by zerodat** [comment]
@ransome1 I didn't have a tool to find this.  I just noticed it because this particular html appears in the UI, so the merge tokens are very visible if you open that dialog.  Thanks for cleaning that up!  Maybe I should stick to the latest release tag, but I like to get up to date before starting any new development.

**Comment by ransome1** [comment]
@zerodat Hi, is there anyway I can get in touch with you by mail or Signal?

**Comment by zerodat** [comment]
Certainly.  This is Robin, correct?  If you send me your email address, I
will reply from my Gmail address.
