### ISSUE TITLE
Can't Alt+Tab when Minimize to Tray enabled in Windows

### ISSUE THREAD

**Issue by veesar** [ransome1/sleek#170]
**Is it an actual bug?**
Yes

**Did you check if the bug has already been reported?**
Yes. It has not been reported.

**Describe the bug**
In Windows 10, trying to Alt+Tab into sleek is not possible when 'Minimize to the tray bar' setting is enabled. The app is not listed in open apps. It is also hidden by minimizing-into-tray when Alt+Tabbing "out" of the app.

**To Reproduce**
1. Enable 'Minimize to the tray bar' in Settings
2. Restart sleek
3. Press Alt+Tab to go to another open app
4. Press Alt+Tab again
5. Sleek is not available as an open app to navigate into

**Do you see any error entries in sleeks developer tools?**
No

**Expected behavior**
Keep app "active" so Alt+Tab allows to get back to it. 

**Screenshots**
![image](https://user-images.githubusercontent.com/74916913/122698731-8633be80-d265-11eb-869a-f83ed0bd02d1.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Version of sleek: 1.0.6-2
 - Source: Github
 - Tried with both sleek-1.0.6-2-win.exe and sleek-1.0.6-2-win-Setup.exe

**Comment by ransome1** [comment]
@veesar , thanks for reporting, it's been added to the backlog.

**Comment by veesar** [comment]
Thanks. Just to add to this, in Windows applications "minimize to tray" is normally triggered using the Close button. The minimize button hides the app to the taskbar. Here, both close and minimize move the app to the system tray.  
Let me know if this should be a separate issue?

**Comment by ransome1** [comment]
@veesar I'm fine with using this one for general task bar improvements in Windows, as I would work on both at the same time anyway.

**Comment by gdevenyi** [comment]
This same bug applies in Linux. I still expect a taskbar entry when the setting is minimize to tray. Right now, I can't at a glance see if the window is on the workspace I'm on, and can't easily raise it if it's covered by other windows.

**Comment by ransome1** [comment]
@veesar can I ask you to check if this problem still occurs in the [latest developer preview of 2.0](https://github.com/ransome1/sleek/releases/tag/v2.0.0-dev11)?

> This same bug applies in Linux. I still expect a taskbar entry when the setting is minimize to tray. Right now, I can't at a glance see if the window is on the workspace I'm on, and can't easily raise it if it's covered by other windows.

@gdevenyi could you specify again please, what the expected behavior is? On macOS and Windows it is my understanding, that when sleek is minimized to tray, there is not suppose to be a dock (I guess this is what you mean with taskbar?) icon. I'm not sure if there is this one specifically expected behavior since the different desktop environments might handle it in different ways.

**Comment by gdevenyi** [comment]
At the time I reported this, turning on "minimize to tray" removed the window entry for sleek in the task list even when the window was open. Now the window entry is present when open, and gone when minimized to tray.

For me, this works correctly now.
