### ISSUE TITLE
Calendar View

### ISSUE THREAD

**Issue by elegantepictetus** [ransome1/sleek#171]
**Did you check if a similar feature request has already been reported?**
Yes

**Is your feature request related to a problem? Please describe.**
Yes, It is easy to plan your week ahead, knowing which days you are free.

**Describe the solution you'd like**
A calendar view that helps to plan ahead.
![Screenshot_20210622-064052_Todotxt](https://user-images.githubusercontent.com/82261576/122847490-69f75680-d325-11eb-9a2d-c900c27ac119.jpg)

**Describe alternatives you've considered**
I use the calendar view on the mobile app Todo.txt for android and sync todo.txt via dropbox.

**Comment by ransome1** [comment]
@elegantepictetus. Thanks for the suggestion. I personally never use a calendar view as it never increases my productivity. In fact I don't even  use the calendar within the calendar app on my android phone ;) Instead I use the the list of tasks that are due next. 

So I personally will propably not work on this. But we can leave this feature request open and mark it as "help wanted". It's not unlikely somebody will pick it up and implement it in a clean way.

I hope you're not too disappointed, but let me point out this is a small side project with very limited ressources and quite a backlog already.

**Comment by zerodat** [comment]
@ransome1,  I am amazed at the amount of excellent work you do on sleek!  You call it a side project, but you are supporting a very nice UI on many platforms, and you are very responsive to all of our ideas and issues.  It's fun to contribute to sleek because you are so engaged and enthusiastic.  Thanks from all of us, and keep up the great work!

**Comment by 9z0** [comment]
Hear! hear!

**Comment by g3434343** [comment]
I think the view below looks great for sleek but I think the event list should be at the left. This is a screenshot of Elementary OS mail app.
![image](https://user-images.githubusercontent.com/81695893/127041554-9d019b93-35a7-4a02-b19e-ba64d750e12d.png)

**Comment by Diagon** [comment]
@ransome1 Hi, first of all, thanks for an amazing tool!

I would like to contribute this feature to sleek. I can handle implementation on my own, however, making a proper calendar requires some extra data that does not currently exist in sleek:
 - Date needs to be extended to include time i.e. due:2021-12-02-12-00-00
 - Additional key:value pairs for scheduling i.e. start:2021-12-02-12-00-00 end:2021-12-02-13-00-00

Will you be willing to consider these changes to format?

**Comment by aubreyz** [comment]
> I would like to contribute this feature to sleek. I can handle implementation on my own, however, making a proper calendar requires some extra data that does not currently exist in sleek:
> * Date needs to be extended to include time i.e. due:2021-12-02-12-00-00
> * Additional key:value pairs for scheduling i.e. start:2021-12-02-12-00-00 end:2021-12-02-13-00-00

I know I am saying the same thing a lot, but I think it is vital to
a) Keep within the todo.txt specification or at least do things which will work relatively seamlessly in other apps now and in the future that use the specification. 
b) Not to blur the distinction between a diary app and a todo list app - certainly there is an element of overlap, but they serve very different purposes. Having the ability for existing standard due or end dates to display in a calendar format is fine, but that is as far as it should go. 

Sleek has the potential to be the best desktop todo.txt app (well it sort of is already, but most of the competition is poor), but that requires keeping eyes on the ball.

**Comment by Diagon** [comment]
Extra key:value pairs are well within [todo.txt specification](https://github.com/todotxt/todo.txt#additional-file-format-definitions), and Sleek already uses such extensions for due date and threshold. 

I can't speak of how seamlessly it would work with other clients, but if handling extra metadata is implemented correctly, there should be no issues.

**Comment by prb01** [comment]
As an alternative to a calendar view within the app, what about creating an integration with Google Calendar? Could setup day events if a task includes a due-date.

**Comment by dnngll** [comment]
> As an alternative to a calendar view within the app, what about creating an integration with Google Calendar? Could setup day events if a task includes a due-date.

I love the idea. For the time being I'd like to recommend "Simpletask" for Android. There's a setting that does exactly that:

![image](https://github.com/ransome1/sleek/assets/12801866/7ecf2cf5-5bff-4670-bd3d-38314ea7c5b5)

Just make sure your todo.txt is synced to your Android device
