### ISSUE TITLE
ENV for custom todo.txt files for command line usage

### ISSUE THREAD

**Issue by dflock** [ransome1/sleek#173]
**Did you check if a similar feature request has already been reported?**
Yes, I couldn't see anything.

**Is your feature request related to a problem? Please describe.**
I have several todo.txt files, for different projects that are checked into their respective git repos - and one general todo.txt file in my home dir. Sleek does a good job of allowing you to switch between todo files when the app is running - but when it starts, it always opens the last open todo.txt file from the last instance of sleek that was closed.

**Describe the solution you'd like**
I tend to run multiple instances of sleek on different workspaces, for different projects. I'd like to be able to launch sleek and point to the todo.txt file on the command line.

**Describe alternatives you've considered**
Apart from just using a text editor instead (which I do alongside sleek), I'm not sure how else you'd implement this.

**Comment by ransome1** [comment]
Hi @dflock , are you also able to set environment variables in your different workspaces? With some minor adjustments I could expose a variable to you in which you can add a custom file path, which then overwrites the ones in the config file.

**Comment by dflock** [comment]
That would allow me to create multiple shortcuts/menu entries/scripts like this:

```console
$ VAR=value; /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=sleek com.github.ransome1.sleek
```

so, yes that would work, I think.

**Comment by ransome1** [comment]
We can test this real quick: Can you try setting `NODE_ENV` to `development`? If you open sleek with this env the Chromium developer tools should be opening automatically. If this works we can do the env approach for the custom file.

**Comment by dflock** [comment]
Doing it the usual way _didn't_ work, but using the flatpak `--env` option _did_ work!

```console
$ /usr/bin/flatpak run --env=NODE_ENV='development' --branch=stable --arch=x86_64 --command=sleek com.github.ransome1.sleek
```

**Comment by ransome1** [comment]
Very well, I'll let you know once the custom file env is available.

**Comment by dflock** [comment]
Thanks!

**Comment by 9z0** [comment]
Related: drag and drop a file onto sleek.exe (or using command `sleek.exe <file>` should also open that file instead of the latest one in `user-preferences.json`.

**Comment by ransome1** [comment]
Hi @dflock a custom env has been added in https://github.com/ransome1/sleek/releases/tag/v1.0.9-rc.1

Once `SLEEK_CUSTOM_FILE` has been set to a file path (eg `/home/USER/todo.txt`), sleek will be forced working with it. Manual changes on the selected file using the GUI will be ignored.

I would appreciate your feedback on if this is working as expected especially with several instances of sleek running.

**Comment by dflock** [comment]
I've played around with this and I can't get it to work, sadly. I tried it using the AppImage, because afaik the RC's aren't available as flatpaks. Trying this from "outside" the AppImage didn't seem to work, in either form:

```console
$ SLEEK_CUSTOM_FILE=~/todo/todo.txt ~/Applications/sleek-1.0.9-rc.2_4c57a18aed01ff974c016c48ea932d63.AppImage

$ export SLEEK_CUSTOM_FILE=~/todo/todo.txt; ~/Applications/sleek-1.0.9-rc.2_4c57a18aed01ff974c016c48ea932d63.AppImage
```

I then tried mounting the AppImage:

```console
$ ~/Applications/sleek-1.0.9-rc.2_4c57a18aed01ff974c016c48ea932d63.AppImage --appimage-mount
qt5ct: using qt5ct plugin
/tmp/.mount_sleek-jvYWyM
```

then running sleek directly in another console and trying various things:

```console
$ cd /tmp/.mount_sleek-jvYWyM

$ SLEEK_CUSTOM_FILE=~/todo/todo.txt ./sleek
$ SLEEK_CUSTOM_FILE=~/todo/todo.txt; ./sleek
$ export SLEEK_CUSTOM_FILE=~/todo/todo.txt; ./sleek
$ export SLEEK_CUSTOM_FILE=/home/duncan/todo/todo.txt; ./sleek
```

Whatever I do, I just get this:

![image](https://user-images.githubusercontent.com/47756/125137329-4ff99a00-e0c1-11eb-9a6f-b0e92a4a2fe3.png)

I'm not sure if I'm doing this correctly or not?

**Comment by zerodat** [comment]
@ransome1, if you want to enable the use of a command-line arg for the file name, you could just do this in `startFileWatcher`:

```javascript
      if(process.argv.length > 1 && fs.existsSync(process.argv[1])) {
        file = process.argv[1];
      }
```
after (or instead of) the ENV code:
```javascript
      if(process.env.SLEEK_CUSTOM_FILE && fs.existsSync(process.env.SLEEK_CUSTOM_FILE)) {
        file = process.env.SLEEK_CUSTOM_FILE;
      }
```
I tested this in my build and it seems to work fine.

**Comment by ransome1** [comment]
@zerodat thanks I'll give it a try. Does the env also not work on your side?

@dflock Van I assume that printenv | less shortly before you start sleek lists the env?

**Comment by zerodat** [comment]
@ransome1 the env var setting works for me in my appimage build, like this:
```bash
$ SLEEK_CUSTOM_FILE=~/somefile.txt sleek-1.0.9-rc.2.AppImage
```
and also like this with an exported env var
```bash
$ export SLEEK_CUSTOM_FILE=~/somefile.txt
$ printenv | grep SLEEK
SLEEK_CUSTOM_FILE=/home/zerodat/somefile.txt
$ sleek-1.0.9-rc.2.AppImage
```
Both will open `somefile.txt` on startup.  And with the code I suggested, this will also work:
```bash
$ sleek-1.0.9-rc.2.AppImage ~/somefile.txt
```

**Comment by ransome1** [comment]
Thanks @zerodat , I will add your proposed code as well in the next release so we have two ways to enforce  custom files.

**Comment by dflock** [comment]
If I do the above, using the downloaded sleek 1.0.9-rc2. AppImage, which I've mounted, I get the same result - i.e. it doesn't open the todo file:

```console
$ cd /tmp/.mount_sleek-jvYWyM
$ export SLEEK_CUSTOM_FILE=/home/duncan/todo/todo.txt
$ printenv | grep SLEEK
PWD=/tmp/.mount_sleek-jvYWyM
SLEEK_CUSTOM_FILE=/home/duncan/todo/todo.txt

$ ./sleek
User preferences located at: /home/duncan/.config/sleek/user-preferences.json
Success: Translation loaded for: en
Success: Window events setup
```

**Comment by ransome1** [comment]
I've never manually mounted an AppImage. I just execute those containers. Is it possible that the env are not available when you mount the AppImage?

**Comment by zerodat** [comment]
@ransome1, I tried mounting my AppImage and running `./sleek` there, and the SLEEK_CUSTOM_FILE env var still worked for me.

@dflock I wonder what linux version/distro/shell you are using?

**Comment by dflock** [comment]
> I've never manually mounted an AppImage. I just execute those containers. Is it possible that the env are not available when you mount the AppImage?

I tried it both ways and it doesn't work either way:

```console
$ export SLEEK_CUSTOM_FILE=/home/duncan/todo/todo.txt
$ printenv | grep SLEEK
SLEEK_CUSTOM_FILE=/home/duncan/todo/todo.txt

$ ~/Applications/sleek-1.0.9-rc.2_4c57a18aed01ff974c016c48ea932d63.AppImage
```

This is using the @ransome1 RC2, not the @zerodat branch, btw.

> I wonder what linux version/distro/shell you are using?

```console
➜ neofetch --disable packages --off --print-config

duncan@duncan-desktop 
--------------------- 
OS: Xubuntu 20.04.2 LTS x86_64 
Kernel: 5.4.0-77-generic 
Uptime: 23 hours, 55 mins 
Shell: bash 5.0.17 
Resolution: 1920x1080, 1920x1080, 1920x1080 
DE: Xfce 4.16 
WM: Xfwm4 
WM Theme: Arc-Dark 
Theme: Arc-Dark [GTK2/3] 
Icons: Papirus-Dark [GTK2/3] 
Terminal: kitty 
CPU: Intel i7-6700K (8) @ 4.200GHz 
GPU: Intel HD Graphics 530 
Memory: 28125MiB / 64206MiB 
```

**Comment by zerodat** [comment]
Hmmm.  Very puzzling, @dflock .  I am running a similar environment,  based on Ubuntu 20.04 and using kitty.  Just to be sure we are trying the same thing, I have just downloaded a new copy of https://github.com/ransome1/sleek/releases/download/v1.0.9-rc.2/sleek-1.0.9-rc.2.AppImage, then:

```bash
$  chmod +x sleek-1.0.9-rc.2.AppImage 
$ export SLEEK_CUSTOM_FILE=~/src/t1_todo.txt 
$ ./sleek-1.0.9-rc.2.AppImage
User preferences located at: /home/zerodat/.config/sleek/user-preferences.json
Checking for update
Success: Translation loaded for: en
libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed
Success: Window events setup
Success: Filewatcher is watching: /home/zerodat/src/t1_todo.txt
Update for version 1.0.9-rc.2 is not available (latest version: 1.0.9-rc.2, downgrade is disallowed).
No update
checkForUpdatesAndNotify called, downloadPromise is null
```
and it opens the `t1_todo.txt` file upon starting up.  So it works for me and not for you, which seems quite puzzling given our similar linux environments.  The main difference is that you have xfce and I have cinnamon as our DE, but I wouldn't expect that to matter in this case.

**Comment by dflock** [comment]
I had [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher) installed, which I thought might be messing this up, so I uninstalled it. It still doesn't work for me though, no idea why.

```console
$ wget https://github.com/ransome1/sleek/releases/download/v1.0.9-rc.2/sleek-1.0.9-rc.2.AppImage
$ chmod +x sleek-1.0.9-rc.2.AppImage
$ export SLEEK_CUSTOM_FILE=~/todo/todo.txt
$ printenv | grep SLEEK
SLEEK_CUSTOM_FILE=/home/duncan/todo/todo.txt

$ ./sleek-1.0.9-rc.2.AppImage

User preferences located at: /home/duncan/.config/sleek/user-preferences.json
Checking for update
Success: Translation loaded for: en
Success: Window events setup
Update for version 1.0.9-rc.2 is not available (latest version: 1.0.9-rc.2, downgrade is disallowed).
No update
checkForUpdatesAndNotify called, downloadPromise is null
```

I haven't restarted since I uninstalled AppImageLauncher, so maybe that's it?

Either way, I don't normally use the AppImage for Sleek - I run the flatpak version. I'm only using the AppImage here because there wasn't a flatpak build for the RC, afaik. If this works for @zerodat I would say go for it and I'll try it out in the flatpak v1.0.9 build?

**Comment by ransome1** [comment]
@dflock I will also adapt @zerodat s proposed code so you will be able to append the file name in terminal.

I'll let you know when 1.0.9 is being pushed to Flatpak. Thanks to zerodat threshold function this could be quite soon.

**Comment by ransome1** [comment]
@zerodat I removed your code as it generated glitches when starting sleek with `yarn start`. Because then the arg is `.` (dot) which will then be persisted and tricks the start up into an infinite loop. 

@dflock if it is not super urgent, let's wait a bit for the 1.0.9 Flatpak release and try if it works on your side. If not we'll look at the command line appendix again.

**Comment by zerodat** [comment]
@ransome1, oops, yes I only tested with the AppImage, so didn't try the electron "unbundled app" case.  The following code works for both:

```javascript
      if (process.defaultApp) {
        // electron "unbundled" app -- have to skip "electron" and script name arg eg: "."
        args = process.argv.slice(2);
      } else
        args = process.argv.slice(1);  // skip app name only, eg: "sleek"
      if(args.length > 0 && fs.existsSync(args[0])) {
        file = args[0];
      }
```

**Comment by ransome1** [comment]
@zerodat I can confirm it's working well :) Will be part of 1.0.9, thanks again.

**Comment by ransome1** [comment]
@dflock both, the command line parameter as well as the custom env are included in the v1.0.9, which should be distributed any minute. Please give us a quick feedback if this is working on your side.

**Comment by zerodat** [comment]
Working for me.  Thanks.

**Comment by ransome1** [comment]
@dflock I just tested the command line feature, but it didn't work with the Flatpak.

With the env though it seems to be working:
```
$ export SLEEK_CUSTOM_FILE=/home/ransome/Sync/Documents/sleek.txt
$ flatpak run com.github.ransome1.sleek
```

Hope it's working in your environment as well.

**Comment by dflock** [comment]
Yep, the env var is working for me!!

`/usr/bin/flatpak run --env=SLEEK_CUSTOM_FILE="~/dev/duncanlock.net/.todo.txt" --branch=stable --arch=x86_64 --command=sleek com.github.ransome1.sleek`

Thanks everyone!
