### ISSUE TITLE
Text lost when changing new todo from single line to multi-line

### ISSUE THREAD

**Issue by Oroumov** [ransome1/sleek#176]
Hi there !
Totally love this new tool to take a fresh start with todotxt files.. That's fantastic work, and so much more "actual" and modern than the other existing ones.. !
I'll report a few things that I've noticed, trying to break them up into individual "bugs".

So here goes the first one : the text lost when changing a new todo from single line to multi-line.
**Steps to reproduce the behavior**
1. Create a new Todo item (which you've never saved before), type a few things.
2. Switch to multi-line.
3. Multi-line happens but what you've typed is gone :)
(Note : if you are editing a previously created and saved single-line todo, it doesn't happen.)

**Expected behavior**
Of course the text should not disappear when changing from single to multi line.

Stay tuned for more !
Cheers,
O.

**Comment by ransome1** [comment]
@Oroumov , thanks for reporting bugs and glitches, I'll look into it as soon as I find the time.

**Comment by ransome1** [comment]
Hi @Oroumov. Could you please check if this still happens in https://github.com/ransome1/sleek/releases/tag/v1.1.2-rc.1?

**Comment by ransome1** [comment]
This had been fixed in https://github.com/ransome1/sleek/releases/tag/v1.1.2
