### ISSUE TITLE
Context/Project tags not working properly when used alone on a line in a multi-line item

### ISSUE THREAD

**Issue by Oroumov** [ransome1/sleek#177]
Hi again!
Here we go with another one :)

**Steps to reproduce the behavior**
1. Create a multi-line todo item with some content
2. If some lines contain strictly one tag (and no other text), this tag is treated as plain text and doesn't show up properly.
3. If some lines contain multiple tags (but still no other text), the first tag is treated as plain text and doesn't show up properly, the others are showing fine.

**Expected behavior**
Any tag used in any location of the multi-line todo item should be identified.

Cheers,
O.

**Comment by ransome1** [comment]
@Oroumov I just tried to reproduce it but failed. Could you check if this still happens in 1.2.6?

While reproducing this, I found another bug. When you put plain text in the 1st line, then switch to the second line, trigger the auto complete container and choose from it, the first line will be erased. I'll work on that bug as part of this thread, if that is alright with you.

**Comment by ransome1** [comment]
@Oroumov @clayreimann if you like you can check the latest developer preview. It contains a new implementation of the multi line text field. As with the old implementation, the new one was quite tricky. The described use case of this feature request should be available.

You can download the release here: https://github.com/ransome1/sleek/releases/tag/v2.0.0-dev17

Feel free to share your feedback in this thread or in the corresponding discussion: https://github.com/ransome1/sleek/discussions/551

**Comment by ransome1** [comment]
Released as part of 2.0.0. If it is not working as expected we can re-open here.
