### ISSUE TITLE
Better handling of single-line vs multi-line, and corresponding shortcuts.

### ISSUE THREAD

**Issue by Oroumov** [ransome1/sleek#178]
Hi !

Now for a feature request regarding the way items are created and edited.

I've noticed that :
- when you create an item, it will open either as single line or multi line depending on the last edited item. It's confusing because
* in case of single line, Enter and Ctrl-Enter means Save and Close
* in case of multi line, Enter means go to next line, and Ctrl-Enter means Save and Close

- when you edit an item : 
* if it's already a single-line content, it will open in single line or multi line edit box depending on the last edited item
* if it's already a multi line content, well it opens in multi line by default

This can become confusing quite quickly, and you have to look at what kind of box you're looking at to know what Enter is going to actually do, or if you should mouse over the "multi-line" option to make it big first.

**Describe the solution you'd like**
I think the most simple solution would be to remove the manual switch from single to multi, and all items behave in only one way: 
- New items (or Edited items that currently have only one line) MAY show as single line first (for aesthetics) [or for even more simplicity there are simply no single line boxes anymore]
- Enter is always a way to add a new line (and if the item was single line so far then it simply becomes multi-line)
- Ctrl-Enter is always Save and Close

Cheers,
O.

**Comment by ransome1** [comment]
@Oroumov can be tested in the latest pre-release: https://github.com/ransome1/sleek/releases/tag/v2.0.4-rc.4

Hoping for your feedback on it.

**Comment by ransome1** [comment]
I think this has been implemented a long time ago, closing here.
