### ISSUE TITLE
Sleek in portable mode ?

### ISSUE THREAD

**Issue by Oroumov** [ransome1/sleek#181]
Hi, 
A suggestion around sleek installation:
I'm really bad at programming languages so this might be a stupid question given the technology choices you have made for sleek, but is there a possibility that sleek could be available in a portable mode ? I work in a very controlled environment (nothing fancy, but company-restricted machines), and I fear it might become impossible to install...

Cheers,
O.

**Comment by ransome1** [comment]
@Oroumov I assume you're on Windows? If so there are two builds that can be considered portable:
As one file: https://github.com/ransome1/sleek/releases/download/v1.0.8/sleek-1.0.8-win.exe
As a zipped archive: https://github.com/ransome1/sleek/releases/download/v1.0.8/sleek-1.0.8-win.zip

I don't know much about Windows, but as far as my knowledge goes, these two are considered portable.

**Comment by Oroumov** [comment]
I had missed the zipped archive, my bad ! It's indeed working with no installation, that's great 👍 
Thanks !
