### ISSUE TITLE
"Visible todos" should not take into account properly hidden (h:1) items

### ISSUE THREAD

**Issue by Oroumov** [ransome1/sleek#182]
Hi,

I'm wondering between bug and feature request, could be both but as it's confusing users I'd side more with bug I think... feel free to contradict me :)

**Describe the bug**
If users have created items with the h:1 tag to hide them AND intentionally selected in the options that "Hidden todos" is unchecked (=really hidden), then they should not be counted in the "Visible todos" counter or the user believes a search/filter is still active.
Example : if we have 3 items and 1 hidden item
- We should not see "Visible todos 3 of 4" when "Hidden todos" is unchecked (=really hidden)

**Expected behavior**
With same example : if we have 3 items and 1 hidden item
- We should see either nothing (if all 3 non-hidden items are visible), or "Visible todos X of 3" (but not 4) if a search/filter is activated

Cheers,
O.

**Comment by ransome1** [comment]
@Oroumov can be tested here: https://github.com/ransome1/sleek/releases/tag/v2.0.0-dev9
