### ISSUE TITLE
Todotxt Rule 3 about context/project place is broken

### ISSUE THREAD

**Issue by Oroumov** [ransome1/sleek#183]
**Describe the bug**
If you write the item:
"Ask Dad how the +GarageCleaning project is doing @home"
It ends up like this:
"Ask Dad how the  project is doing +GarageCleaning @home" (notice the double space where +GarageCleaning was surgically removed)

This breaks todotxt holy rule # 3 :)))
"Rule 3: Contexts and Projects may appear anywhere in the line after priority/prepended date."

**Expected behavior**
No change of the input order

Cheers,
O.

**Comment by ransome1** [comment]
Hi @Oroumov . Is this a possible duplicate of https://github.com/ransome1/sleek/issues/68?

**Comment by Oroumov** [comment]
You're absolutely right, I missed #68, I'm sorry..
Case closed :)
Thanks for your time !
