### ISSUE TITLE
[Feature request] Support for others date formats

### ISSUE THREAD

**Issue by fealv** [ransome1/sleek#184]
The app uses the standard format yyyy-mm-dd, but a lot of countries uses different standards. In my country, for example, the format is dd/mm/yyyy, and it becomes a bit unconfortable and confused to use this other.

![image](https://user-images.githubusercontent.com/60493079/123516543-05186500-d673-11eb-9cef-d3d7b46f2ed9.png)

**Comment by rzelnik** [comment]
Also the date picker should show the month in the user's native local format.

**Comment by ransome1** [comment]
The default date format for the todo.txt is ISO 8601 and any change of that would need to be discussed upstream with the authors of the format.

The thing we can discuss in the context of sleek would probably be an optional formatting of the output date according to a users local setting. Which I can add to the backlog, but please don't expect this to happen any time soon as it is not an issue of high priority. 

Whereas though the input dates format would need to stay ISO 8601.

**Comment by rzelnik** [comment]
Good point. We don't need to change the todo.txt format. I believe that the request was meant to localize the output date formatting. And yes, I agree that this is a low priority task.

One big advantage of the ISO 8601 date format is that it orders the time data by the proper "weight" (year first, month second, day third, etc.), so they can be then easily sorted by timeline.

**Comment by fealv** [comment]
Yes, as @rzelnik said, I don't think it's needed to change the todo.txt, only the option to change the output format to the user. And I also agree that it's not a high priority task.
