### ISSUE TITLE
Move dark mode button

### ISSUE THREAD

**Issue by 9z0** [ransome1/sleek#188]
Changing the theme is not something you do very frequently. I suggest it be moved to the settings or with the lower buttons (settings, help).

**Comment by ransome1** [comment]
@9z0 I agree, there is no need for this function at this position and it is available in the view drawer, the app menu and as a keyboard shortcut. It will be removed from navigation in the next release.

**Comment by ransome1** [comment]
@9z0 has been removed in v1.0.8: https://github.com/ransome1/sleek/releases/tag/v1.0.8
