### ISSUE TITLE
due date selection should offer "in one week" etc.

### ISSUE THREAD

**Issue by koppor** [ransome1/sleek#19]
As user, I want to add TODOs quickly. Thus, I also want to choose a due-date quickly. If I want to achieve something in three months or this year, I don't want to choose the exact date (e.g., 2020-12-31). Could the date picker offer following as dropdown?

- today
- tomorrow
- weekend
- next week
- in one month
- this year

**Comment by ransome1** [comment]
Added to backlog, but hasn't the highest priority. If anybody wants to contribute a PR, it would be very much appreciated.

**Comment by ransome1** [comment]
@koppor, @weisserd, would you mind helping me detailing out the concept behind this one. The options should be simple, consistant with each other, and somehow what the average user would be expected from a todo app. I want to avoid to build a none generic soltion that only serves a small percentage of sleeks users. 

Giving it some quick thoughts I would think of the following:
- Today
- Tomorrow
- Next week (date right now + 7 days)
- Next month (date right now + 1 month)
- Next year (date right now + 1 year)

I'm having difficulties understanding the proposed `weekend` (which due date represents a weekend? ;)) and `this year` (really no clue about this one)

**Comment by weisserd** [comment]
@ransome1 Thanks for your question.

My intention for the question/suggestion comes from the background of being a long time "Remember The Milk" user which has switched. There it was possible, to define a due date with "Natural Speech". - see https://www.rememberthemilk.com/help/answer/basics-basics-dateformat 

From a technical and detailed functional perspective I would love to be able to write something after the `due:` command in sleek. And something would preferably be everything that sugar.js supports - https://sugarjs.com/dates/#/Parsing 

So a concrete example would be (sorry for German interface):
![image](https://user-images.githubusercontent.com/459157/120814894-9ce0d280-c54f-11eb-94d1-4d96ab429636.png)

**Comment by ransome1** [comment]
Kein Problem ;)

I'm looking at sugar.js and I'm getting kind of excited. If we can restrict sugar.js to only focus on calculations that are based on whole days and not on hours (e.g. in one hour), this could be really something interesting. 

It might not be @koppor initial idea, but is still great and could maybe even get combined with it: In addition to sugar.js we could define a shortlist of "most common" selections that a user might have in the context of creating a todo and build 4 to 5 buttons right next to the due date picker.

I will give sugar.js a longer look later and see what can be done.

**Comment by weisserd** [comment]
Depending on your implementation it might be enough to let sugarjs do the parsing and then format the parsed date to provide the date (without time information).

**Comment by weisserd** [comment]
A simple example would be: https://codepen.io/weisserd/pen/gOmeEga

**Comment by ransome1** [comment]
@weisserd , the sole implementation looks straight forward. Which is good.

The tricky part is the regex. In sleek we need to intercept a big string, tear it apart and make sure that something within the string like `due:next wednesday` (or all the other possible combinations) will be reliably identified as something that we can pass on to sugar.js. For the todo.txt attributes, the jsTodoTxt library does the job.

But thinking about the brain damaging pain I experienced working on the auto complete function (here, spaces didn't even played a role ...), makes me nervous ;) 

Of course there is also the chance that I'm thinking too complicated at this point.

**Comment by weisserd** [comment]
I might think to simplistic but I would consider writing a `DueExtension` (https://github.com/jmhobbs/jsTodoTxt#implementing-your-own) which doesn't have a RegExp but puts the value from the `due`-key into the SugarJS-parse function. And if the result is a valid date it is considered valid. 

On my opinion, this allows a simpler implementation and might be useful for further i18n in order to support more languages later on (e.g. due:übermorgen).

**Comment by ransome1** [comment]
I dont think its too simplistic, it might be the best way to go as we would stick to a function that is already been used.

Just a suggestion, but if you know your way around JS I would be more than happy if you would support me on this and contribute on sleek with a PR. Just an idea ;)

**Comment by weisserd** [comment]
Good idea 😉 - @ransome1 I just sent you an e-mail with some more questions.

**Comment by ransome1** [comment]
Hi @weisserd , your contribution has just been released with 1.0.6: https://github.com/ransome1/sleek/releases/tag/v1.0.6

I added some GIFs in the help section for education purposes. There will still be some finetuning on that content, but I hope the GIF on your implementation helps users to understand this pretty cool enhancement.

@koppor : Not the feature you asked for, but if you're a keyboard type of person, you should give it a try.

**Comment by ransome1** [comment]
In my opinion the Sugar implementation is a proper substitute and due to the missing feedback of @koppor , I suggest to close this FR to clean up the issue list. If you have a feedback at some point, please feel free to share it here. We can re open, if necessary.
