### ISSUE TITLE
UI and Cosmetic Improvement Suggestions

### ISSUE THREAD

**Issue by 9z0** [ransome1/sleek#190]
Checklist:

- [ ] [Alway show total number of todos](#issuecomment-875092358).
- [ ] [URL popup on hover](#issuecomment-875092358).
- [ ] [Better external link indicator](#issuecomment-875108905)
- [ ] [Link open/copy behavior](#issuecomment-875108905)
- [ ] [Categorize projects/contexts alphabetically when too many.](#issuecomment-907879709)
- [ ] [Better visual distinction between selected and unselected states of priority icons in the filter drawer.](#issuecomment-927224177)
- [x] [Proportional number bubbles.](#issuecomment-875092358).
- [x] [Smaller search help button](#issuecomment-875095717).
---

> > I like the new UI. Very nice. The number bubble should be smaller/scale with the button, especially with the priority buttons.
> 
> The bubbles should be smaller in the just released v1.0.8.

Not when compact mode is on. This is because the priority icons themselves are smaller, so the bubbles cover them.

**Comment by 9z0** [comment]
Steps:
- have > 25 priority A todos
- have any number of other priority todos
- sort by priority

Expected: priority **heading** (B), (C) etc is shown before their todos.

Actual: further headings are not loaded on lazy loading.

**Comment by 9z0** [comment]
For todos with `[Text](URL)` Markdown links, Show URL on hover.

**Comment by 9z0** [comment]
Always show the total number of todos (even without filters).

**Comment by ransome1** [comment]
> Not when compact mode is on. This is because the priority icons themselves are smaller, so the bubbles cover them.

This is solved in the next release.

> Steps:
> 
> * have > 25 priority A todos
> * have any number of other priority todos
> * sort by priority
> 
> Expected: priority **heading** (B), (C) etc is shown before their todos.
> 
> Actual: further headings are not loaded on lazy loading.

This sounds like a bug I would say, can I ask you to create a bug report on it?

As for the rest, let's please aggregate those suggestions in one post and please add more explanation. I have no idea what `Always show the total number of todos (even without filters)` means and I can only guess what `For todos with [Text](URL) Markdown links, Show URL on hover.` means in detail.

**Comment by 9z0** [comment]
> This is solved in the next release.

👍. Maybe compact mode/zoom levels should be derived from the default view so that everything scales together?



> This sounds like a bug I would say, can I ask you to create a bug report on it?

#192

> I have no idea what `Always show the total number of todos (even without filters)` means
I was referencing [this](1#issuecomment-851050973) (last paragraph). Currently, there is no way to know how many todos you have (unless you apply a filter and see the "Visible todos x of y").


> and I can only guess what `For todos with [Text](URL) Markdown links, Show URL on hover.` means in detail.

If you have a Markdown-syntax URL in a todo, there is no way to know what the URL is until you open the todo. I suggest that hovering with the cursor on the link text (in the list of todos) should show the actual link in a small popup (similar to what happens when you hover over the due icon).

**Comment by 9z0** [comment]
- Search bar help button: Make the clickable area of it smaller.

Reason: It gets clicked by mistake when trying to put the blinking cursor at the beginning of search query. A dead (unclickable) buffer between the button and the beginning of the search field should help with that.

**Comment by 9z0** [comment]
* Markdown links: Replace external link icon with a blue box around the text/thick blue underline or something else _that doesn't take space_.

The current icon:
- takes space, especially with multiple links in the same todo.
- is a bit confusing visually; being separate from the link text and at equal distances from both preceding and following text.
- doesn't specify where exactly the link text begins (the link text looks the same as any regular text before it).

![links](https://user-images.githubusercontent.com/78097210/124671391-adb99680-deb5-11eb-85a0-1067650c56a6.png)

**Comment by ransome1** [comment]
![image](https://user-images.githubusercontent.com/11188741/124715346-301c7780-df03-11eb-94a0-32b58bd26fdb.png)

I got to say this is pretty cool :)

**Comment by ransome1** [comment]
@9z0 the priority bubbles in compact mode should be proportional again in https://github.com/ransome1/sleek/releases/tag/v1.0.9-rc.1

**Comment by 9z0** [comment]
> I got to say this is pretty cool :)

In what way? 🙂

**Comment by ransome1** [comment]
@9z0 because the new Github task list feature is pretty handy and I've had never seen it in aciton before.

Anyhow. I couldn't the old issue in which you asked for the empty state enhancement on the filter categories. It has been added to the second release candidate for 1.0.9. Even with showEmptyFilters off the categories will be shown. It's not the sleekest visualization yet, but enough to give it some proper testing. So feel free to help me test it :) https://github.com/ransome1/sleek/releases/tag/v1.0.9-rc.2

**Comment by 9z0** [comment]
Yes, it is. You can even arrange them by dragging and check them with a click.


> I couldn't the old issue in which you asked for the empty state enhancement on the filter categories. 
?? If you mean you couldn't find it, it is [here](107). It is working fairly well, and I can finally stop pulling my hair!

**Comment by 9z0** [comment]
A suggestion to help those with many projects/contexts

If the number of projects is above a certain number (say, 100), view them in the side bar split alphabetically:
```
-
[?] [1_important] [2021] ...
A
[alpha] [art] ...
B
...
```

**Comment by 9z0** [comment]
Filter drawer: Highlighted (selected) priority icons look very similar to unhighlighted. Perhaps either increase shade difference or show selected with a border?
