### ISSUE TITLE
Priority headings are not shown on lazy loading

### ISSUE THREAD

**Issue by 9z0** [ransome1/sleek#192]
Steps:

* have > 25 priority A todos
* have any number of other priority todos
* sort by priority
 
**Expected behavior**: priority **heading** (B), (C) etc is shown before their todos.

**Actual behavior**: further headings are not loaded on lazy loading. Nothing separates the last (A) todo from the first (B) todo.

**Comment by ransome1** [comment]
Hi @9z0 . Can I ask you to take a quick look at this pre release if it solves this issue on your side?

https://github.com/ransome1/sleek/releases/tag/v1.1.2-rc.1

**Comment by 9z0** [comment]
Seems fixed 👍
