### ISSUE TITLE
Open minimized

### ISSUE THREAD

**Issue by asakura42** [ransome1/sleek#195]
I find useful to add programs in my .xprofile to autostart them with the system. Could you add some option or flag to open app minimized? Maybe it can help: https://github.com/electron/electron/issues/6893#issuecomment-300463668

**Comment by ransome1** [comment]
I briefly looked into it and the solution behind that link requires at least one more node module to be installed (and I don#t know how many dependencies this one has). As I want to keep sleek slim this is not the way to go. I'll keep looking for a soltion the Electron API provides already.

Also a quick question: Can you describe what you exactly you expect from an app that opens minized in terms of if it's completely hidden or shown as an icon in the tray bar, etc.

For feature requests please always use the template and provide detailed information. If you have a loose idea, it might be better to start a [discussion](https://github.com/ransome1/sleek/discussions) first.

**Comment by asakura42** [comment]
>use the template
Okay, I'll use it in future.

Personally I often autostart programs with line in `.xprofile` as xinit user. For example, `blueman-applet &` opens blueman and keeps its icon in tray. I found that very useful. So application is working but it doesn't clutter my desktop with new windows till I really need it. Of course, I can just write `sleek &` in `.xprofile`, but by default application starts in window, that is not very convenient.

I think that some flag for sleek will be good idea like `sleek --tray` which will open sleek not in window mode but in tray, waiting for opening. It's nice thing to preload sleek for notification daemon et cetera.
