### ISSUE TITLE
Make sleek version number more prominent in GUI

### ISSUE THREAD

**Issue by zerodat** [ransome1/sleek#198]
At first I couldn't find the sleek version number in the GUI, but eventually I found it at the bottom of the "about" tab of the Settings dialog.  It might be nice to make this more prominent and easier to find.

Possible solutions:
* Could you add the version number to the title bar?  Where right now it says "todo.txt - sleek" could it say "todo.txt - sleek v1.0.8" for example?
* Or you could put it under the word "sleek" in left-side toolbar, or make it a tooltip that appears when you hover the cursor over the word "sleek"?
* If not that, at least make it more prominent in the About tab, by putting "Sleek v1.0.8" at the top of that page?

Thanks for considering this suggestion, @ransome1 !

**Comment by 9z0** [comment]
> Or you could put it under the word "sleek" in left-side toolbar

👍

**Comment by ransome1** [comment]
The GUI is meant to help users perform the intended task of managing todos. All visible GUI elements need to support this task and everything that is not needs to be either removed or moved to a place where it doesn't distract users.

The version number is important for developers or for users that have an issue with sleek and need to report on that number. That is way less than a percent of all sleek users. The rest is most likely interested in that number. Especially not popping up in the main view.

When I usually look for a version number, I first click on the About tab in the top menu. This is a bit tricky in sleek as it is hidden per default. I would assume that a user who is looking for that number might want to click on the question mark / help button in the lower bottom of the navigation bar. So a good place might be somewhere around that part. But either not always visible or a bit more prominent in the help window. I'm going to look for a solution next week.

**Comment by zerodat** [comment]
Yes, @ransome1 I would normally look for this in the About menu of most apps.  In sleek, I first went to the "?" button at the lower left of the nav bar.  Could you move the About tab from the settings panel to be the first thing you see in the "?" panel, and then add the version information at the top of that tab?  This would be what many users would expect.  Then the Settings panel would be only settings.

By the way, I think that the version information is more important to the average user than you might think.  It is not only useful when reporting bugs.  In the modern world, software is constantly changing in functionality and security.  Accurate documentation should indicate in which versions new features exist, and the user will want to know if he has a late enough version to use the documented feature.  Similarly, when reading about bugs that have been found, users will want to know whether their version is likely to have the bug or the fix.  So more like 25% than 1% of users, I would guess. :smile:

**Comment by ransome1** [comment]
@zerodat a click on help should open actual help not the about page.

But I'll think about something ;)

**Comment by 9z0** [comment]
I suggest adding some 200ms to the hover implementation in rc4.

I also agree with @zerodat that:
- the version information should be more prominent. Put it bold, big, top and center in the About tab.
- the About tab itself should be under help as per the convention (Help menu > About). I still keep looking for sleek version there by habit!

**Comment by ransome1** [comment]
@zerodat , @9z0 the `About` tab has been moved to the `Help` modal, the version number has been moved up and the hover delay has been added in https://github.com/ransome1/sleek/releases/tag/v1.0.9

**Comment by zerodat** [comment]
Thank you, @ransome1 !

**Comment by 9z0** [comment]
Thank you for the changes!

A couple of small cosmetic issues:
- Semi transparent background to the popup (I have many context/projects).
- The delay should be enough. I'd do away with the fade in.

Thanks

**Comment by 9z0** [comment]
Thank you for the changes!

A couple of small cosmetic issues for your consideration:
- Semi transparent background to the popup (I have many context/projects).
- The delay should be enough. I'd do away with the fade in.

Thanks
