### ISSUE TITLE
setting weekday as due is unintuitive

### ISSUE THREAD

**Issue by trend-1** [ransome1/sleek#199]
**Is it an actual bug?**
don't know

**Did you check if the bug has already been reported?**
yes

**Describe the bug**
Setting a due date in the form of a weekday (friday, saturday, sunday etc.) gives sometimes an unexpected result.

**Today it is Friday**  
- I create a new todo with due date tomorrow in the form of `due:saturday` 
- I expect it to be in the list under the first upcoming Saturday (and it is)

**Today is still Friday**  
- I create a new todo with due date the day after tomorrow in the form of `due:sunday`
- I expect it to be in the list under the first upcoming Sunday (and it is not)
- It is under the last Sunday, showing up overdue.

Is this the way it is supposed to be or not?  
And if so what is the logic behind this?

**Comment by ransome1** [comment]
@weisserd I'm not at the keyboard atm. Could you maybe take a look at this?

**Comment by zerodat** [comment]
I can confirm that the bug happens to me too, using sleek 1.0.8.   Creating a new todo with `due:sunday` right now (on friday) will give a due date of the past sunday 2021-07-04, when the likely intent is to get next sunday 2021-07-11.  It works if you say `due:next sunday`.

This seems to just be a design feature of the `sugar` date package, as you can see by typing saturday and sunday into the test box at [Sugar - Home](https://sugarjs.com/dates/).

**Comment by ransome1** [comment]
@zerodat Thanks for pointing this out. I'm not sure if its wise creating a workaround in sleek for something that has been designed differently in upstream. Maybe it would be better to report this to Sugar. @weisserd what do you think?

**Comment by weisserd** [comment]
There is already a parameter to specify the parsing of ambiguous dates in sugar. As soon as I have a computer reachable I'll try to test it and come up with a fix.

**Comment by weisserd** [comment]
Please give the PR ransome1/sleek#200 a test - this should parse ambiguous dates as being in the future.

**Comment by zerodat** [comment]
I tested your change and it works for me @weisserd .  Thanks!

**Comment by ransome1** [comment]
@weisserd , @zerodat , @trend-1 this can be tested in https://github.com/ransome1/sleek/releases/tag/v1.0.9-rc.3

@weisserd thanks for the PR.

**Comment by ransome1** [comment]
Thanks guys for your support here. I think this has been solved and can be closed.
