### ISSUE TITLE
✨ add support for custom done.txt filename in settings

### ISSUE THREAD

**Issue by lukas-runge** [ransome1/sleek#201]
**Did you check if a similar feature request has already been reported?**
Yes - I found none.

**Is your feature request related to a problem? Please describe.**
It's kinda related to a problem as I tried to use sleek for my todo.txt and done.txt files and failed because I am not able to configure the proper name.

**Describe the solution you'd like**
As stated in the title above it would be cool to either change default paths in the settings or alternatively get propted for a done.txt path as well when configuring a new todo.txt location.

**Describe alternatives you've considered**
I cloned the repo and changed the hardcoded path in `todo.mjs` to match my hardcoded path and recompiled the project to ba able to use my fix personally.

**Comment by archphile** [comment]
This feature will be very useful for many of us.

Currently setting up a **todo.txt** means that the file for done will be named **todo_done.txt**. 

I am currently in need of the standard filenames (**todo.txt** and **done.txt**) so that I can use these files with other software too (ex. simpletask on android).

I really wish that such an option will be added in the near future.

Thanks,
Mike

**Comment by jt196** [comment]
+1 here, came looking for this. Running todo.txt on Android and a VSCode plugin, need some consistent filenaming!

**Comment by ivysrono** [comment]
I use Simpletask on android too.

**Comment by gdevenyi** [comment]
A side mention here of a sort-of bug. The popup describing what will happen when you archive todos shows the wrong filename:
![image](https://user-images.githubusercontent.com/3001850/142040870-18f5c9c5-6fda-47db-813a-89c327e2b1d9.png)

As per the rest of this thread, file name is actually `todo_done.txt`

**Comment by khuongduybui** [comment]
Also I'm using Markdown so my `todo.md` should be archived into `done.md`. My TODO is inside Obsidian so having everything in Markdown makes the most sense.

**Comment by ransome1** [comment]
Let's not close here, I'm working on this as part of 2.0.

**Comment by 18107** [comment]
A workaround for now could be to add a symlink redirecting to the correct file. `ln -s done.txt todo_done.txt` worked for me on lInux.

**Comment by ransome1** [comment]
@lukas-runge @18107 @khuongduybui @ivysrono @jt196 can be tested in https://github.com/ransome1/sleek/releases/tag/v2.0.0-dev13. Use right mouse click on the file tabs and you'll find an option to change the done file location for each corresponding todo file.
