### ISSUE TITLE
🎨⚡ feedback on the gui refresh

### ISSUE THREAD

**Issue by lukas-runge** [ransome1/sleek#202]
**Did you check if a similar feature request has already been reported?**
Yes - I couldn't see one.

**Is your feature request related to a problem? Please describe.**
I really loved the old design of v1.0.7.0 which still is the version downloadable from Microsoft Store. I liked the less rounding and the smaller A, B, C markers as well as the grey checkboxes. I found it looking pretty slick. Just looked more professional / less playful to me, which helps me focus on the actual tasks shown to me.

**Describe the solution you'd like**
A way of dealing with this without making anyone unhappy could be to introduce a theming system. So everybody can use a theme of his likeing.

**Describe alternatives you've considered**
Alternatively I could just fork off the old version and only pull the changes I appreciate and make my own build 🤣

**Comment by ransome1** [comment]
Hi @lukas-runge . Thanks for your feedback. As it is the case with most design decisions, there will always be a significant part of the users who will dislike what is changing. I can very much relate to this but I am hoping that the majority enjoys the new playfulness.

There is a another feature request asking for manual config files of which a custom CSS option will be the most likely candicate to get developed at some point: https://github.com/ransome1/sleek/issues/151

This can be an option for you in the future, but until then it might not be the worst idea to fork sleek and customized it as you mentioned.

I hope you don't mind me closing this issue to keep the issue list limited to feature requests and bugs. But again your feedback is very much appreciated!
