### ISSUE TITLE
Wrong notification upon adding due dates

### ISSUE THREAD

**Issue by dummifiedme** [ransome1/sleek#204]
**Is it an actual bug?**
If I add a task and later change the due date, it will push in a notification saying this task is "Due Today" while for example, this task is actually due on 2021-07-20!
![image](https://user-images.githubusercontent.com/68785729/125223182-f96ea480-e2e8-11eb-9175-4008ef93a98f.png)

**Did you check if the bug has already been reported?**
I couldn't find such a mention.

**Describe the bug**
The notification on windows shows "Due Today" everytime I add a new due date to my tasks. Irrespective of it being due today.

**To Reproduce**
1. Go to todo.txt (not in sleek, but append the txt file)
2. add `due:<date>` on any task.
3. Sleek will push a notification

**Do you see any error entries in sleeks developer tools?**
nope

**Expected behavior**
It should either send a notification suggesting it is due on the actual date, or no show anything at all.

**Screenshots**
This notification
![image](https://user-images.githubusercontent.com/68785729/125223455-6e41de80-e2e9-11eb-8bb3-8635b6996b2c.png)
for this task
![image](https://user-images.githubusercontent.com/68785729/125223527-8b76ad00-e2e9-11eb-94e0-18cf966f6837.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Version of sleek: 1.0.8
 - Source: Github exe

**Comment by ransome1** [comment]
Hi @dummifiedme . Thanks for reporting this. So far I havn't had any luck reproducing it. I tried to it the way you described it on a Windows 10 VM:
1. Added a file to sleek
2. Added a todo in sleek with no due date
3. edited that todo file in an external editor and added a due date in the future (not today and not tomorrow)

No notification is showing on my side. In sleek the filewatcher adds the due date right away and no notification is shown.

Is it possible that this is somehow caused by a specific date/timezone setting in your OS?

@9z0: You are on Windows, if I recall correctly. Can I ask you to reproduce this?

**Comment by dummifiedme** [comment]
> 
> 
> Hi @dummifiedme . Thanks for reporting this. So far I havn't had any luck reproducing it. I tried to it the way you described it on a Windows 10 VM:
> 
>     1. Added a file to sleek
> 
>     2. Added a todo in sleek with no due date
> 
>     3. edited that todo file in an external editor and added a due date in the future (not today and not tomorrow)
> 
> 
> No notification is showing on my side. In sleek the filewatcher adds the due date right away and no notification is shown.
> 
> Is it possible that this is somehow caused by a specific date/timezone setting in your OS?
> 
> @9z0 : You are on Windows, if I recall correctly. Can I ask you to reproduce this?

I am trying to replicate it and I too am not able to. But I can promise you, it was happening! For 5 tasks! And they were kind of repeating.

**Comment by ransome1** [comment]
I believe you, don't worry. Do you have those exact todos saved somewhere? Maybe in a todo.txt file, that you could share?

**Comment by dummifiedme** [comment]
> 
> 
> I believe you, don't worry. Do you have those exact todos saved somewhere? Maybe in a todo.txt file, that you could share?
Sadly, I deleted it. I was only trying it for the first time and those were really dummy tasks, so got rid of them.
Though currently I don't really know how will I manage my subtasks, I dropped the idea of using it for now as well. But thought, I should share the bug and I did :grin:

If I ever encounter it again, I will attach again.

**Comment by ransome1** [comment]
@dummifiedme I'm going to close here. If it happens again we will reopen this issue and just continue to debug it.

**Comment by dummifiedme** [comment]
Apologies

**Comment by ransome1** [comment]
@dummifiedme no need to apologize ;) I've seen quite some bug reports here that were not reproduceable but at some point somebody was able to do so and it turned out to be a bug after all. So let's keep our eyes open.
