### ISSUE TITLE
Open file from Dropbox

### ISSUE THREAD

**Issue by Saturo78** [ransome1/sleek#206]
for my workflow it would be really helpful if i could open the textfile from my droxbox.
Would it be possible to implement a sync function?

**Comment by ransome1** [comment]
Hi @Saturo78. Thanks for your suggestion. It sure would be possible to implement some kind of API connection to Dropbox and exchange the todo.txt files. But I want to be honest here: I disagree with how Dropbox handle their users privacy and it's a closed source environment. I don't have a good feeling about connecting with it sleek, which is 100% open.

As a workaround (and for most users this might be the common use case) you can just sync your todo.txt in your Dropbox to your local computer and use it locally. In the past some users had issues with Dropbox's sync mechanism in combination with sleeks old file watcher. But this has already been solved. It should work flawlessly.

I hope you're not too dissapointed.

**Comment by Saturo78** [comment]
Unfortunately i have no rights to install software on the computer. So i could not set up a dropbox sync folder.
I have sleek installed from the Microsoft App Store.

So i have to store the files locally without having the posibility to access them via mobile ore have to use another solution with sync functionality.

Thanks

**Comment by ransome1** [comment]
I added it to the long term [backlog](https://github.com/ransome1/sleek/projects/3), so the idea doesn't get lost. But please don't expect this to come any time soon, if at all. Again I disagree with how Dropbox positions itself and see this feature request as a general request for online synchronisation.

**Comment by luixal** [comment]
What about syncing from an standard http link? Obviously, privacy may not be the best, but If you don't really care about your task's privacy, you could load files from almost any cloud (dropbox, gDrive, oneDrive, github...).

**Comment by luixal** [comment]
Hey @ransome1 , has I would like to load my tasks remotely*, I've been playing around with Github Gists as they seem to be a good way to go:

- free and "dev-friendly" service
- plain text files
- private by default
- can be shared easily

Saving new tasks is quite direct, I just put the new code on the `writeToFile` event function and worked like a charm. Problem comes when loading data. As it's using a local file, data is loaded when the `add` or `change` methods of the file watcher are fired.

I can add kind of a cronned job that loads gists' file content and uses the same `mainWindow.webContents.send("refresh", [content])`, but I don't know if it makes sense to you. It can be used for other sync methods (other clouds/services).

 What do you think?

<br>
--

*In my case remotely isn't the same than syncing a file to local storage. I would like to port some of your views to a chrome extension and dealing with a locally storage file can be a headache.
