### ISSUE TITLE
Interpret #tag as tag

### ISSUE THREAD

**Issue by Saturo78** [ransome1/sleek#208]
with the todo.txt android app not only +project and @context are interpreted but also #tag as tag.
It would be really helpful if sleek could work in the same way and it could be also filtered for tags.

**Comment by ransome1** [comment]
Hi @Saturo78 thanks for your proposal. I myself don't see a big value in adding another filter mechanism in sleek. It adds weight to the GUI and is not part of the basic todo.txt syntax. 

As this is more a loose idea than a precise feature request, it might be a good idea to open up a general [discussion](https://github.com/ransome1/sleek/discussions) about it, so we can discuss is before making anything more precise out of it.

**Comment by Saturo78** [comment]
Today i use +Projects and @persons tho whom the tasks are assigned and i would like to have a third option for locations, departments or other tags.

I will try if #tag works for me with the standard filter options.
