### ISSUE TITLE
Recurring tasks are not set to done when marked complete

### ISSUE THREAD

**Issue by Saturo78** [ransome1/sleek#209]
I have an issue with recurring tasks.
I have ste it to every business day and when i complete the task it is correctly set for the next business day but also keeps open for the actual day. So i have to delete it manually.

**Comment by ransome1** [comment]
Hi @Saturo78 . Can you please use the bug template and provide a detailed describtion and examples. Thank you.

**Comment by zerodat** [comment]
Also @Saturo78 if possible could you test this using the new release 1.0.9 (released today)?

**Comment by Saturo78** [comment]
**Is it an actual bug?**
Or can it be a specific behavior of sleek that others would not consider a bug? In this case a feature request can be better suited: https://github.com/ransome1/sleek/issues/new?assignees=&labels=&template=feature_request.md&title=
Yes.

**Did you check if the bug has already been reported?**
Please do so first: https://github.com/ransome1/sleek/issues
Yes, i have searched github and also reddit and found nothing.
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. add new Task: 2021-07-15 New Task due:2021-07-15 rec:b
2. Click on mark as done
3. See error: There ist the new task on the next workday but also the old one on the actual day.

**Do you see any error entries in sleeks developer tools?**
While sleek is open press Ctrl + Shift + I which will open the developer tools. If the shortcut doesn't work, press the Alt key, select the tab "About" and select the developer tools. In the dev tools select the tab "Console" and check if any error entries are written, while you provoke the bug.

**Expected behavior**
Click on done creates new taks and closes the old one

**Screenshots**
If applicable, add screenshots to help explain your problem.
could not help

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version of sleek [1.0.7]
 - Source: Windows Store

**Comment by Saturo78** [comment]
> 
> 
> Also @Saturo78 if possible could you test this using the new release 1.0.9 (released today)?

I could only install from the Microsoft Appstore. There i get verson 1.07. Sorry.

**Comment by ransome1** [comment]
@Saturo78 the Windows Store release will be coming tomorrow. I need to update the Screenshots first, as the design has been changed a little.

**Comment by zerodat** [comment]
@Saturo78 I tried your example in 1.0.7 and I don't get the problem.  The old task is marked done (shown in gray, checked) and the new task is created with due date of 2021-07-16.
![Screenshot from 2021-07-15 09-27-50](https://user-images.githubusercontent.com/81216634/125824267-ed6d745d-5b82-474a-af31-94db649bcebc.png)

**Comment by Saturo78** [comment]
To me it looks like this issue:

https://github.com/ransome1/sleek/issues/169

**Comment by zerodat** [comment]
Ah, good call @Saturo78 .  If it is that bug, you should not see it once you get 1.0.9, because I fixed this after 1.0.7.   It had to do with sleek not correctly recognizing when two tasks are the same.

**Comment by Saturo78** [comment]
I think with version 1.09 this issue is solved.

¡Muchas gracias!

**Comment by ransome1** [comment]
@Saturo78 the v1.0.9 has been release today in Windows Store as well.

**Comment by aurisnoctis** [comment]
This problem is there / back in version 1.2.2-rc.2
![Selection_20220702_22:26:51](https://user-images.githubusercontent.com/8195964/177015440-08ce814b-c2e9-491a-aa97-dcab3cf518cc.png)

**Comment by ransome1** [comment]
@aurisnoctis thanks for pointing it out. It can be a side effect of the recent work on the file handling in https://github.com/ransome1/sleek/issues/370
