### ISSUE TITLE
Keyboard shortcut to toggle viewing Deferred Todos 

### ISSUE THREAD

**Issue by velardevines** [ransome1/sleek#210]
**Did you check if a similar feature request has already been reported?**
Please do so first: https://github.com/ransome1/sleek/issues

Yes, feature has not been requested. 

**Is your feature request related to a problem? Please describe.**

I consider this an ease of use feature request. 

**Describe the solution you'd like**

Would you consider adding a keyboard shortcut to toggle the "Threshold date in the future" setting: 

![image](https://user-images.githubusercontent.com/13563674/125840895-1b693347-abfc-460c-933a-14799a219372.png)

**Describe alternatives you've considered**

Only alternative of which I am aware is to click back and forth between the different views to toggle the setting as needed.

**Comment by ransome1** [comment]
@velardevines any suggestion for a shortcut? I would propose `T` but as we're following the todotxt.net shortcuts (https://github.com/benrhughes/todotxt.net) that would be occupied already.

@amariusz @zerodat

**Comment by velardevines** [comment]
Thanks for asking @ransome1. I like T also. Is there any reason Sleek cannot deviate slightly from todotxt.net keyboard shortcuts? Do you think Sleek would ever use T for the same action used by todotxt.net which is "T: append text to selected tasks"?

However, if you decide T is not available as a shortcut key, then how about S for "Show/hide Todos with Threshold Dates"? S is also easy to find on the keyboard. 

@amariusz @zerodat

**Comment by ransome1** [comment]
We don't necessarily need to stick to todotxt.net. In fact many of its shortcuts can't be applied on sleek anyway as the GUI works differently. 

So I guess the only issues with `T` can be either that the majority of the users associate something else with it (I don't) or if a new feature is being introduced in the near future that might need the `T` shortcut more urgently than this one. I can't think of one yet though. Let's wait for @amariusz and @zerodat feedback as they mostly introduced and actually developed this feature and if they don't object we go with `T`.

**Comment by amariusz** [comment]
I don't object with 't' :)

Of course I'd prefer having an option to customize shortcuts and would probably end up modifying them. 

As I understand this is not a keyboard-centric app. There's no option for example to use 'j'/'k' for list navigation and use 'x' for marking an item complete. For vast majority of users right hand will stay on mouse most of the time. So I guess I'd remap shortcuts focusing on left part of the keyboard.

Here are my quick thoughts

- lots of conventient ALT shortcuts are devoted to setting priorities (alt-[a-z]). 
  - alt-[1/2/3/4] would probably be enought as default for entering A/B/C/D priority.
  - some of ALT shortcuts could be used for example to increment/decrement threshold in isolation, due in isolataion and threshold along with due (I'd go for pairs e/r, d/f, c/v)
  - arrow-key shortcuts could act as alternatives - they are intuitive but not as ergonomic

- regarding main shortcuts I would probably
  - use 's' for focusing search box, not 'f'. Ctrl-f and '/' could be intuitive alternatives
  - 'f' for switching to filters, not 'b'
  - 'v' for switching to View (currently missing shortcut)
  - use 'r' for reload, not '.'
  - use 'c' for toggling completed items visibility, not 'h'
  - use 'h' for toggling hidden items visibility
  - assuming one would toggle light/dark at most twice a day I'd move it from 'd' to 't' or 'y'
It would be convenient if toggles in "View" have those single letter shortcuts displayed next to them (in parentheses or on within tooltips)

That would leave 'd' or 't' available for deferred items. 
So again, 't' is ok for me and I believe this should be user preference.

**Comment by ransome1** [comment]
I'm closing here as this has been added a while ago and I kind of forgot to report back here ;)

**Comment by ransome1** [comment]
> I don't object with 't' :)
> 
> Of course I'd prefer having an option to customize shortcuts and would probably end up modifying them.
> 
> As I understand this is not a keyboard-centric app. There's no option for example to use 'j'/'k' for list navigation and use 'x' for marking an item complete. For vast majority of users right hand will stay on mouse most of the time. So I guess I'd remap shortcuts focusing on left part of the keyboard.
> 
> Here are my quick thoughts
> 
> * lots of conventient ALT shortcuts are devoted to setting priorities (alt-[a-z]).
>   
>   * alt-[1/2/3/4] would probably be enought as default for _toggling_ A/B/C/D priority.
>   * some of ALT shortcuts could be used for example to increment/decrement threshold in isolation, due in isolataion and threshold along with due (I'd go for pairs e/r - threshold, d/f - due, c/v - both)
>   * arrow-key shortcuts could act as alternatives - they are intuitive but not as ergonomic
> * regarding main shortcuts I would probably
>   
>   * use 's' for focusing search box, not 'f'. Ctrl-f and '/' could be intuitive alternatives
>   * 'f' for switching to filters, not 'b'
>   * 'v' for switching to View (currently missing shortcut)
>   * use 'r' for reload, not '.'
>   * use 'c' for toggling completed items visibility, not 'h'
>   * use 'h' for toggling hidden items visibility
>   * assuming one would toggle light/dark at most twice a day I'd move it from 'd' to 't' / 'y' / 'b'
>     It would be convenient if toggles in "View" have those single letter shortcuts displayed next to them (in parentheses or on within tooltips)
>   * use '1'/'2'/'3'/'4' in future for switching to `named views` / `saved filters` / `custom perspectives`
> 
> That would leave 'd' or 't' available for deferred items. So again, 't' is ok for me and I believe this should be user preference.

@amariusz Thanks for this input. It's a good start on creating a well thought out keyboard concept. I'll check up with you again as soon as there is more work done on redefining the keyboard shortcut system.
