### ISSUE TITLE
Mark today in the date picker

### ISSUE THREAD

**Issue by Saturo78** [ransome1/sleek#213]
**Did you check if a similar feature request has already been reported?**
Yes.

**Is your feature request related to a problem? Please describe.**
When adding a new task for today i alway have to look to the calendar.

**Describe the solution you'd like**
It would be very nice if there is a colored marker on today in the date picker like you might know it from other software.

![grafik](https://user-images.githubusercontent.com/71584438/125990714-e845aaf9-5d6b-4462-923b-a9cc19ab2884.png)

![grafik](https://user-images.githubusercontent.com/71584438/125990853-a271c4c8-300f-483f-adf4-697d29f4d6d4.png)

**Comment by ransome1** [comment]
@Saturo78 todays date is highlighted already. It's probably not distinct enough.

I can check if I can put a bit more contrast in the highlighting.

**Comment by ransome1** [comment]
@Saturo78 in thihs pre release the date picker colors have been improved: https://github.com/ransome1/sleek/releases/tag/v1.1.0-rc.1

- A pre selected date has the blue background
- Todays date has a light grey background
- Hovering or focusing cells will create a blue border

![image](https://user-images.githubusercontent.com/11188741/126030007-7e6cbbb5-ab95-4092-9580-c59c9ce6bf41.png)
![image](https://user-images.githubusercontent.com/11188741/126030011-25547292-1cf7-4de7-9faa-a163f7a812bf.png)

**Comment by Saturo78** [comment]
Now its Perfect for me.
Thanks a lot!

**Comment by ransome1** [comment]
You're welcome. I'm going to close this one for you ;)
