### ISSUE TITLE
Option to use contexts and projects as part of the sentence

### ISSUE THREAD

**Issue by Toffanelly** [ransome1/sleek#216]
**Did you check if a similar feature request has already been reported?**
Yes

**Is your feature request related to a problem? Please describe.**
Sleek treats contexts and projects only as tags and not as words that are part of a sentence.

![image](https://user-images.githubusercontent.com/1621227/126033309-09b2831e-4103-4aec-8cef-68ccf6385165.png)

**Describe the solution you'd like**
Having the option in the settings to leave them as in-line tags. Ideally it would look like this:

![yoga](https://user-images.githubusercontent.com/1621227/126033425-98ab4665-7984-46f7-8d79-f976feb4e46b.png)

**Describe alternatives you've considered**
Even just leaving the tags "as-written" would improve the readability of such tasks:

![Yoga2](https://user-images.githubusercontent.com/1621227/126033571-1d5dab32-854e-4351-91a4-de4b09b4bd67.png)

Thank you for your wonderful work, I hope my suggestions can be of help.

**Comment by ransome1** [comment]
Hi @Toffanelly , is this a duplicate of https://github.com/ransome1/sleek/issues/68?

**Comment by Toffanelly** [comment]
Yes! Sorry, I did check open issues before posting but didn't notice that one. I assume the answer remains the same so I'll wait for the jsTodoTxt implementation. Thanks
