### ISSUE TITLE
Filter for + or @ should find exact string

### ISSUE THREAD

**Issue by Saturo78** [ransome1/sleek#222]
**Did you check if a similar feature request has already been reported?**
yes

**Is your feature request related to a problem? Please describe.**
filter string +wa also shows entries for +waiting even if there is a space after (+wa )

**Describe the solution you'd like**
if i filter for + and @ only the tasks with the exact search string should be shown.

**Describe alternatives you've considered**
no idea

**Comment by 9z0** [comment]
@Saturo78 
Put them in quotes: `+"waiting"`. I think this is better a [config file option](151).

**Comment by zerodat** [comment]
Yes, @Saturo78 this is the way that the search works, unless you add a double quote at the end to force an exact match.  You don't have to put quotes on both sides, although you can if you like.  So `+wa"` will match only the `wa` project, not `waiting`.

Originally it was designed for exact matches only, but I changed it to the looser matching method to make it more convenient for the search box and "as-you-type" filtering.

**Comment by Saturo78** [comment]
Muchas gracias por el consejo @9z0, @zerodat!
This works for me very well!

**Comment by ransome1** [comment]
@Saturo78 could you please close issues, once they have been resolved? Thanks.
