### ISSUE TITLE
TypeError in function undefined: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by EloiSanchez** [ransome1/sleek#223]
**Is it an actual bug?**
It is not breaking the program, but it is a recurrent error

**Did you check if the bug has already been reported?**
I did, but it was not solved due to lack of information.  #164

**Describe the bug**
An error appears on launch. The notification of error can be closed and I don't see any malfunction of the application. The bug does not reappear

**To Reproduce**
1. Turn on computer
2. Sleek automatically starts-up
3 See error

**Do you see any error entries in sleeks developer tools?**
Yes, I am not into software depeloping so I have no idea what it is that I should post here. I will just paste a screenshot. If anything else is needed let me know.
![image](https://user-images.githubusercontent.com/79266117/126313237-c9fd3896-fd7e-4111-9a57-85ee50fd878e.png)

**Expected behavior**
The error not appearing, I guess.

**Screenshots**
The notification error is the following
![image](https://user-images.githubusercontent.com/79266117/126313382-223c0d11-ba3b-4fcf-b420-075acece98c0.png)

**Desktop (please complete the following information):**
 - OS: Pop!_OS 20.04 LTS
 - Version of sleek: v1.0.6
 - Source: Flathub

**Comment by ransome1** [comment]
@EloiSanchez does this also happen on a more recent release like 1.0.9 which should be on Flathub as well?

**Comment by EloiSanchez** [comment]
I confirm that the error does not occur in the updated version 1.0.9
Thanks!
