### ISSUE TITLE
visual indication for threshold dates (similar to due dates)

### ISSUE THREAD

**Issue by dlaidig** [ransome1/sleek#224]
**Did you check if a similar feature request has already been reported?**
Yes. Although I did not read every comment for #193 in detail, from a quick glance I did not find any discussion regarding this sub-aspect.

**Is your feature request related to a problem? Please describe.**
In the task list, there is absolutely no indication if a task has a threshold date (t:2021-07-20). The threshold date is only visible when editing the task.

From what I can see, all other information that is removed from the task text (priority, contexts, projects, recurrence, h:1) is visualized in some way in the task list.

**Describe the solution you'd like**
An icon should be shown similar to due dates. When hovering over the icon, a tooltip should appear that shows the threshold date (like for due dates).

Like Simpletask, sleek uses a clock icon for due dates. To be consistent, I suggest to use a clock with an arrow for threshold dates. See the following screenshot of Simpletask:

![simpletask_icons](https://user-images.githubusercontent.com/3208721/126325501-c9f3b5a5-a35f-4534-a8f9-0b4934f0403f.jpeg)

On a slightly off-topic note, it would be helpful if, in addition to the ISO date, a fuzzy relative date could be shown in the tooltip ("one week ago", "in two days", ...). This obviously applies to due dates as well.

**Comment by dlaidig** [comment]
Not sure how the current status is in the stable version and in 2.0, but I'm still very much interested in this... :)

(I think now in the stable version, tasks with a threshold date show a clock icon without any tooltip and clicking on it opens a dialog that first suggests to define a due date. It is totally not clear that no due date is set yet but a threshold date is set. This really seems quite confusing to me and so far I have always just defaulted to editing the task as plain text. Some clear indication which dates are set would be quite useful.)

**Comment by dlaidig** [comment]
That's really quite nice. I'm looking forward to v2.0! :)

**Comment by ransome1** [comment]
It currently looks like this. That might be a more helpful visualisation, than just icons. What do you think?
![Bildschirmfoto 2023-08-28 um 15 35 49](https://github.com/ransome1/sleek/assets/11188741/871e0524-d116-48f1-b2b9-b353dd1e52a9)

**Comment by dlaidig** [comment]
It's quite verbose but I agree that it is more helpful than icons (which almost nobody will understand).

One minor detail: I find that the nested boxes add quite a bit of visual clutter and use unnecessary space. Maybe displaying them like the badges that are common on GitHub readme files is a good idea (see https://shields.io/)? ![https://img.shields.io/badge/Threshold-2023--08--29-lightgray](https://img.shields.io/badge/Threshold-2023--08--29-lightgray)

And one slightly unrelated idea: It would be quite cool if a tooltip would show something like "today", "yesterday", "in 5 days" or "27 days ago".

**Comment by CPUGPU** [comment]
I vote for compactness like dlaidig suggests.  I would even make it like that but just "T: 2023-08-20" instead of spelling out "Threshold".  High information density is important to me.

**Comment by warmwaffles** [comment]
Hover over tool tips could be used to add more clarity on stuff abbreviated. Food for thought.

**Comment by ransome1** [comment]
@dlaidig @CPUGPU @warmwaffles would be fine with me.
<img width="670" alt="Bildschirmfoto 2023-08-28 um 20 33 30" src="https://github.com/ransome1/sleek/assets/11188741/d736e30b-62f1-4625-96f4-3325061712cb">

The tool tip should be handled in a separate request, in order to keep focus on the requirement at hand.

**Comment by dlaidig** [comment]
Nice! 🤩 Besides the compactness, I really like that now it is basically just syntax highlighting.

> The tool tip should be handled in a separate request, in order to keep focus on the requirement at hand.

I created issue #511 for this. I hope you find it useful.

**Comment by ransome1** [comment]
Since the hovering tool tip has its own issue, I'm closing here.
