### ISSUE TITLE
Hungarian language file

### ISSUE THREAD

**Issue by balmag** [ransome1/sleek#225]
Hello guys, I would like to start translating the application into Hungarian. 
Can I ask for technical instructions?

**Comment by ransome1** [comment]
Hi @balmag. That's great, thanks for your support.

The easiest way is to just fork sleek, duplicate the english translation file (https://github.com/ransome1/sleek/blob/develop/src/locales/en/translation.json) to the hungarian specific location: https://github.com/ransome1/sleek/blob/develop/src/locales/hu/translation.json

Once you're done, you can send a pull request. If you're not familiar with Github you can also just download the english transaltion file, work on it locally and then send it to me by mail. 

I'll take care of the rest.

**Comment by balmag** [comment]
Thanks for the reply

**Comment by ransome1** [comment]
@balmag language has been added through another contribution and will be released in v1.1.2
