### ISSUE TITLE
Password-protect the app

### ISSUE THREAD

**Issue by g3434343** [ransome1/sleek#226]
*If your proposal is more a rough idea than a precise description of a feature, please consider starting a discussion instead: https://github.com/ransome1/sleek/discussions
Please only continue the feature request if you have a precise idea of what you're asking for and if you can provide specific details, use cases or examples. 

**Did you check if a similar feature request has already been reported?**
Yes. I did.

**Is your feature request related to a problem? Please describe.**
Currently, sleek can be opened by anyone.

**Describe the solution you'd like**
I use sleek at work. I don't like people checking my tasks. So I think sleek should be password protected. That's my suggestion.

**Describe alternatives you've considered**
I'm running sleek from an usb drive using BitLocker.

**Comment by nutnutwin** [comment]
Should the text be scrambled too? 
just a thought

**Comment by befedi** [comment]
Hi @g3434343,
a password protection of sleek would only protect the GUI of the app but your todo.txt on your USB drive would still be unprotected (unless the content of the file would be encrypted). Encrypting the todo.txt would not be a solution for me as I use a different app than sleek on my Smartphone. This app would need to support the same encryption method.

**Comment by aubreyz** [comment]
I agree with @befedi  -- encrypting the todo.txt file itself is against all the principles of the format,
and encrypting the app only is pointless. 

If people want encrypted data then they encrypt the file storage device itself (with Veracrypt or similar).

**Comment by ransome1** [comment]
I agree with the above said, if the file is located locally. And if sleek would encrypt the file as well, it would be useless to other apps. Though an interesting use case could be if sleek had an API integration to a cloud service where the todo.txt file would be hosted and never duplicated to the local file system. I am not sure though if many todo.txt users would be interested in pushing their todo data into a popular cloud that is no self hosted.

**Comment by aubreyz** [comment]
RClone would provide a good free mechanism for synching a file (via an encrypted cloud mechanism). Cryptomator is another possibility. Sleek needs to do what it does best and leave other things to the systems that do that best. 

I think we have to assume that Sleek is for people who are at least slight geeks and at least slightly sophisticated as a basis for good development.
