### ISSUE TITLE
Add done/not done or tick/cross possibility

### ISSUE THREAD

**Issue by EloiSanchez** [ransome1/sleek#231]
**Did you check if a similar feature request has already been reported?**
I have not found any open issues with this idea

**Is your feature request related to a problem? Please describe.**
It is not related to a problem

**Describe the solution you'd like**
Instead of simply marking the tasks as done, could it be possible to add a tick/cross like a done or not done task? I don't know if these is even compatible with the todo.txt format, but I would find it useful. I use sleek for university tasks and some assignments are optional. It would be nice for me specifically to have the tick/cross system as done/not done to track which tasks I actually do and not do.
Also, I have tasks that are like personal projects or reminders of something, for instance " (tick) (cross) Assist optional seminar at 17:00".

**Describe alternatives you've considered**
The alternative, if not compatible with the todo.txt format, would be to not implement it. It is not critical at all.

**Comment by ransome1** [comment]
Hi @EloiSanchez thanks for your request. I have to admit that I don't really know what tick/cross is referring to and therefor can't imagine what this would mean for the GUI or for the programming efforts.

As this is not todo.txt related, it could only be considered a candidate if it provides a big benefit for the majority of sleeks users.

I hope you're not too dissapointed.

**Comment by EloiSanchez** [comment]
Hi! So let me try to explain myself a bit better just so you understand what I meant.

Now once you add a task to sleek you can "only" remove it once you have done it. There is no possibility of not doing that task and save it as 'not done'. I think maybe it could be useful to have some option to make tasks optional and choosing whether you have finished them or not afterwards.

These tasks could have two buttons (instead of one as standard tasks have) to indicate if you have chosen to do them or not.
![image](https://user-images.githubusercontent.com/79266117/127662742-8a9440ee-a573-48dc-ac55-2f68cbfba956.png)
Like in the picture above, the top task including problems 1.1 to 1.4 is mandatory but the bottom one with problem 1.5 is optional. Hence, the second task has the option to mark it as done (the green tick) or not done (the red cross).

I hope now it is understood. If it can't be done is not that much of a problem, but I would find it occasionally useful.

Thanks for your time.

**Comment by zerodat** [comment]
@EloiSanchez you might be able to do this just using project/context tags and the filter query.  If you are marking tasks as +Optional then you could also add +Omitted for the ones you choose not to do.  Then to see your tasks that are not completed and not omitted, you would type the following into the search bar:

`not complete and not +Omitted`

Obviously that isn't quite as nice as a custom GUI, but it should let you find the ones you want.  You can also find all of the completed tasks in a similar way as long as sleek is set to show completed tasks.

**Comment by EloiSanchez** [comment]
I see. As you say, it is not as comfortable as having a dedicated GUI but it is a nice and easy workaround. If there is no intention to add the specific feature in the future the issue can be closed 👍🏻 

Thank you!
