### ISSUE TITLE
Toggle completed tasks in parameters when using shortcut

### ISSUE THREAD

**Issue by thewholelifetolearn** [ransome1/sleek#232]
**Is it an actual bug?**
Yes, it is a bug.

**Did you check if the bug has already been reported?**
Yes, I have searched through the issue list.

**Describe the bug**
When I toggle the completed task view through the keyboard shortcut, the parameter to hide or view the completed tasks doesn't toggle.

**To Reproduce**
Steps to reproduce the behaviour:
1. Have a list of completed tasks
2. In the parameters, the completed tasks is toggled off
2. Press "H" on the keyboard to hide the completed tasks
3. In the parameters, the completed tasks toggle button didn't change

**Do you see any error entries in sleeks developer tools?**
If I turn on the developer tools, the app turns white and I can't do anything.

**Expected behavior**
The toggle button in the parameters reflects the display.

**Screenshots**
![Completed tasks are visible](https://user-images.githubusercontent.com/823564/127154893-abbe1c64-e07d-420a-9289-36b40e0a9a28.jpg)
Completed tasks are visible
![Competed tasks are hidden](https://user-images.githubusercontent.com/823564/127154940-2b4c354f-7d52-487a-821a-3640f7d52676.jpg)
Completed tasks are hidden

**Desktop:**
 - OS: Windows 10
 - Version of sleek 1.0.9
 - Source: Github

**Comment by ransome1** [comment]
@thewholelifetolearn. This is also broken with the darkmode and deferred toggle, thanks for pointing it out. It is fixed and will be released with 1.1.1.

**Comment by ransome1** [comment]
Has been solved in 1.1.1
