### ISSUE TITLE
date picker for threshold dates (similar to due dates)

### ISSUE THREAD

**Issue by dlaidig** [ransome1/sleek#234]
**Did you check if a similar feature request has already been reported?**
Issue #224 (also opened by me) is related and is about displaying information in the task list. This issue is about adding/editing tasks.

**Is your feature request related to a problem? Please describe.**
The dialog to add new tasks or edit existing tasks does not have support for threshold dates/deferred tasks.

**Describe the solution you'd like**
Add a second date picker to the dialog that behaves exactly the same as the date picker for due dates (but for `t:` instead of `due:`).

**Describe alternatives you've considered**
An alternative would be to consider threshold dates a pro-feature that is not exposed too much in the GUI. Since calculating dates and typing them is quite annoying, I do not like this alternative. ;)

**Comment by mimmori** [comment]
+1

**Comment by aubreyz** [comment]
+10

**Comment by aubreyz** [comment]
+20?

**Comment by jcz1** [comment]
There is a shared form for due and threshold dates but it's pretty annoying if you use threshold dates only. You have to click to another tab every time even with editing existing task with existing threshold date. And if you forget to change tab, you have task with non-actual threshold and pointless due date. Proven many times :)

**Comment by ransome1** [comment]
Can already be tested in latest developer preview of 2.0.

**Comment by ransome1** [comment]
The current implementation looks like this:
![Image](https://github.com/ransome1/sleek/assets/11188741/ef1e8349-a495-49e8-8c7a-79b26578c064)

I'm not sure if this is the best solution, but it gets the job done. Share your opinions if you like.

**Comment by ransome1** [comment]
Available in latest developer preview.
