### ISSUE TITLE
Date Picker highlights old date when leaving the app opened for multiple days

### ISSUE THREAD

**Issue by m-legrand** [ransome1/sleek#235]
**To Reproduce**
1. Open the app on a date `d`
2. Leave it open until the day after `d+1`
3. Create a new task and click on the due date picker
4. Observe that `d` is highlighted instead of `d+1`

**Expected behavior**
I would expect `d+1` to be highlighted.

**Screenshots**
I forgot to take a screenshot before closing and reopening the app. Will do later if it happens again tomorrow.

**Desktop:**
 - OS: Windows 10
 - Version of sleek: 1.10
 - Source: Windows Store

**Comment by ransome1** [comment]
@m-legrand this behavior should not occur anymore in https://github.com/ransome1/sleek/releases/tag/v1.1.7

Can I ask you to give it a try?
