### ISSUE TITLE
Update date with shortcut doesn't change in datepicker

### ISSUE THREAD

**Issue by thewholelifetolearn** [ransome1/sleek#236]
**Is it an actual bug?**
Yes, the dates displayed
Or can it be a specific behavior of sleek that others would not consider a bug? In this case a feature request can be better suited: https://github.com/ransome1/sleek/issues/new?assignees=&labels=&template=feature_request.md&title=

**Did you check if the bug has already been reported?**
Please do so first: https://github.com/ransome1/sleek/issues

**Describe the bug**
When the due date is updated with keyboard shortcuts, the due date within the due field doesn't update.

**To Reproduce**
Steps to reproduce the behaviour:
1. Edit a task with a due date
2. Update the due date with the keyboard shortcuts
3. See that the date in the due field is the same as before

**Do you see any error entries in sleeks developer tools?**
Not available

**Expected behavior**
The due date should be updated the same way as the due date in the description field.

**Screenshots**
![due date discordance](https://user-images.githubusercontent.com/823564/127637889-f7caee54-4701-485b-86e8-a6b846ca1089.png)
due date discordance

**Desktop :**
 - OS: Windows 10
 - Version of sleek : 1.1.0
 - Source: Github

**Comment by ransome1** [comment]
@thewholelifetolearn : This has been improved in https://github.com/ransome1/sleek/releases/tag/v1.1.2-rc.3

**Comment by ransome1** [comment]
Has been released with 1.1.2
