### ISSUE TITLE
Recurring Tasks: next due date

### ISSUE THREAD

**Issue by Saturo78** [ransome1/sleek#239]
**Did you check if a similar feature request has already been reported?**
Yes, have found nothing.

**Is your feature request related to a problem? Please describe.**
I have a recurring task every monday. When i complete it on Monday, it is set for the next monday.
If the workload is to high and i move the task on tuesday, after complete the next task is set on tuesday.

**Describe the solution you'd like**
I would like to ask for a feature to specify if the next task is set from the origin due date or from the completion date.

OrgMode Example from https://orgmode.org/manual/Repeated-tasks.html#Repeated-tasks

++1w
   Marking this DONE shifts the date by at least one week, but also
   by as many weeks as it takes to get this date into the future.
   However, it stays on a Sunday, even if you called and marked it
   done on Saturday.

.+1m
   Marking this DONE shifts the date to one month after today.

**Comment by zerodat** [comment]
@Saturo78 if you specify the recurrence as `+1m` it will repeat in one month from the specified due date.  If you specify "1m" it will repeat in one month from today (the completion date).

**Comment by Saturo78** [comment]
@zerodat thanks for the advice.
This is not clear if you use the gui to setup the recurring task. Maybe this could be added in future?

**Comment by 9z0** [comment]
@zerodat I didn't know that! Thanks

**Comment by zerodat** [comment]
By the way, you can read about this in the wiki page [Recurring todos (rec:) · ransome1/sleek Wiki](https://github.com/ransome1/sleek/wiki/Recurring-todos-(rec:))

**Comment by alexb7217** [comment]
This would be a nice UI enhancement.

The docs @zerodat pointed to accomplish the functionality [e.g the paying the rent example](https://github.com/ransome1/sleek/wiki/Recurring-todos-(rec:)#strict-recurrences-based-on-due-date-instead-of-date-of-completion)

@Saturo78 makes a good point, the UI does not convey this feature. Imagine it might looks something like this, if implemented as UI:

![Screenshot from 2021-11-11 09-10-33](https://user-images.githubusercontent.com/58309818/141333387-c9359915-a53d-4138-bcf0-b9c575029b28.png)

... where a checkbox or similar sets the `+m` flag for a fixed type recurring date time.

**Comment by ransome1** [comment]
@Saturo78 @alexb7217 @zerodat @9z0 the checkbox has been added in the current developer preview of 2.0: https://github.com/ransome1/sleek/releases/tag/v2.0.0-dev3

I'd appreciate some support on testing the feature.

**Comment by ransome1** [comment]
Available in https://github.com/ransome1/sleek/releases/tag/v2.0.0-dev9
