### ISSUE TITLE
settings/about/version number not shown

### ISSUE THREAD

**Issue by donludovico** [ransome1/sleek#240]
Hi,

I am on Win 10 with Sleek version 1.1.0 (both versions show the issue: from Windows Store and the downloaded setup.exe). When I go to settings -> about, there is no version number shown.

It is a minor issue, but if someone wants to verify the version (especially when installing vom Win Store or without looking at the setup.exe file version), it would be nice to have the version shown there - especially as the text "Version:" is already there.
![grafik](https://user-images.githubusercontent.com/10374564/128351386-fa8d1f78-8599-4521-aa43-b0ea73111e8c.png)
(If have the German localization: "Über" = about

BR donludovico

**Comment by ransome1** [comment]
@donludovico thanks for pointing it out. It turned out that on Windows the the version number was noch extracted fast enough and undefined eventually. That should be fixed now and added to the next release.
