### ISSUE TITLE
Sleek tries to load non-existent files and errors out

### ISSUE THREAD

**Issue by JordyScript** [ransome1/sleek#241]
The following error occurs when you open up sleek and it tries to load a todo.txt file that cannot be found because it was deleted or moved

![image](https://user-images.githubusercontent.com/35542866/128606061-51ab01d2-1d86-4870-bc5e-646a73e09fa5.png)

Simply checking for the existence of the file before trying to open it would allow for a more helpful and less threatening error message, such as: "The todo file you have configured is no longer located at [path]. Did you move or delete it? Please add your Todo.txt file to manage with Sleek (again).

Of course you could also do a try catch for performance reasons, but checking for existence seems more straightforward. It's up to you to decide how to resolve it.

**Comment by ransome1** [comment]
@JordyScript I didn't add a specific error message but in case of a file not being found on the disc, sleek is suppose to load the onboarding window. Can you please check this pre release if this works on your side as well? https://github.com/ransome1/sleek/releases/tag/v1.1.2-rc.4

**Comment by JordyScript** [comment]
Seems to be fixed now! Thank you. Looks like another clean and functional release :)

The only "problem" left  is that when you click the "open todo.txt" icon that the now non-existent file still shows up in the list of files and is marked as being selected even though no tasks are visible in the UI (just the onboarding screen).

Of course you can just manually remove the old file, so it shouldn't be too big of an issue as long as the user recognizes why the file can't be viewed even though it's marked as selected. If the user is unaware of the removal or renaming of a Todo file (or one of its parent folders), it could be confusing and could lead to future bug reports that (or worse, users just giving up on using the app). 

Some form of checking for the existence of files and notifying the user of renamed or removed files/folders may still improve UX, but I'll leave it up to you whether it's worth the hassle of implementing it (maybe for the next point release).

**Comment by ransome1** [comment]
@JordyScript the easiest way would be to remove non existent files from the list and the tab bar automatically. And sending a notification once shouldn't be an issue. 

The only issue with this is, when users are trying to only temporarily rename a file and all of the sudden it is completely gone in sleek. Or if you use a syncing application like Dropbox or Syncthing, which briefly rename files as part of the syncing process. This could also produce a couple of issues. So as always it seems like a small improvement but comes with a lot of things to consider.

I think for now I will add a visual indication to each list entry and will remove the click on "Select". What do you think?

**Comment by JordyScript** [comment]
Those are important considerations. 

If the visual indication you are thinking of adding is self-explanatory or intuitively understandable to mean that the file is currently non-existent (or more generally, unavailable) and that is why it cannot be selected, then I think it is a good idea. If  a user comes across this situation, they should not be left wondering why the program is not doing what they want it to do. 

What visual indication were you thinking about? I can think of a something, but not sure if that's what you had in mind. Maybe greying out the path, and adding a warning triangle with a tooltip explaining the situation when you hover over it.

**Comment by ransome1** [comment]
@JordyScript in this pre release I added a more fine tuned handling if a file is being selected and not found on disk. The behaviour is
1. A notification will be send
2. the file list will be refreshed and files, that can not be found, will be removed
3. sleek will be refreshed

https://github.com/ransome1/sleek/releases/tag/v1.1.6-rc.3

**Comment by ransome1** [comment]
This has been released with v1.1.6. I'm closing here due to backlog maintenance.
