### ISSUE TITLE
Only showing todos with +Projects

### ISSUE THREAD

**Issue by raphtlw** [ransome1/sleek#243]
**Is it an actual bug?**
Yes

**Did you check if the bug has already been reported?**
Yes

**Describe the bug**
Even after resetting the filters and searching, the app only shows todos that have projects associated with them and doesn't show the ones without.

**To Reproduce**
1. Go to Sleek
2. Click on the filters button
3. Click on _reset filters and search_

**Do you see any error entries in sleeks developer tools?**
No

**Expected behavior**
The task list should show all my todos.

**Desktop (please complete the following information):**
 - OS: Pop!_OS 21.04
 - Version of sleek: 1.1.0
 - Source: Flathub

**Comment by ransome1** [comment]
Hi @raphtlw. What exactly is it you're experiencing? You don't see any todos that don't have a project? 

It might help if you post a couple of examples and screenhshots.

**Comment by ransome1** [comment]
I'm closing here due to lack of response. I still don't understand the issue. If this still is one, please report back here.
