### ISSUE TITLE
Save / Cancel buttons disappears on typing a new context or project

### ISSUE THREAD

**Issue by rzelnik** [ransome1/sleek#244]
When I type a new context or project, in a task window, the "No filters found" message overwrites the Save & Cancel buttons, so it is difficult to press them.

**To Reproduce**
1. Create a new task
2. Type a new/non-existing context or project
3. Try to click on Save

**Expected behavior**
The modal should change its height or it should have enough space so that the buttons should always be visible.

**Screenshots**
![screenshot](https://kancelaria.tvorivo.sk/index.php/s/LTJ46nbJimyJef5/preview "screenshot")

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.04
 - Version of sleek: 1.1.0
 - Source: Snap Store

**Comment by ransome1** [comment]
I think we could simply hide the container, if no contexts or projects are found. Would propably be the most practical solution.

**Comment by rzelnik** [comment]
I just realized that I can hide the container by pressing the escape button, or I can increase the superior container by pressing enter.

**Comment by ransome1** [comment]
@rzelnik Could you check https://github.com/ransome1/sleek/releases/tag/v1.1.3-rc.3 if this solves this issue? If there are no filters for contexts or projects the autocomplete container should now be hidden.

**Comment by rzelnik** [comment]
Yes, I confirm that now the "No filters found" error message doesn't appear and therefore doesn't create confusion.
