### ISSUE TITLE
Custom recurrence periods (e.g. rec:3d, rec:2w)

### ISSUE THREAD

**Issue by wsdfhjxc** [ransome1/sleek#25]
The existing recurrence period options are quite handy, but I think that the task recreation system would be much more useful if we could be more specific in regard to the periods. For example, a task could then not only be recurring daily, weekly, monthly or annually, but also every three days, every two weeks, and other combinations of numbers and the existing options.

The recurrence period picker menu could have an extra number spinner (e.g. from 1 up to 99, and default 1) that would act as a multiplier for the options listed there: ... day(s), ... week(s), ... month(s), ... year(s). Do you think that would be confusing, or not?

Also, if you agree with this feature request, I can give a try at implementing it, and then send a pull request.

**Comment by ransome1** [comment]
@wsdfhjxc . If this feature comes with a coherent interface, I think there is a good chance for it not to be confusing.

The only thing that would keep me from working on the feature is the response on the recurrence picker so far. Some kind users activated the error and event logging and looking at the numbers, there has been no noteable usage of that feature so far. But if this comes handy for you I will certainly not keep you from giving it a shot. Your last PR worked out really well :+1:

**Comment by archphile** [comment]
I have been using for years now the combo of simpletask on android and qtodotxt on my linux desktop. They both support custom recurring periods. Below it's a description of this implementation that works fine and covers almost all recurrence scenarios:

https://github.com/mpcjanssen/simpletask-android/blob/master/app/src/main/assets/index.en.md#extensions

I am only pasting it in case the devs here find it interesting. It would really nice if all todo.txt interfaces used the same scheme.

Thanks,
Mike

**Comment by ransome1** [comment]
@archphile thanks for the hint.

@wsdfhjxc, your enhancement works flawlessly! I hope you won't mind, but I replaced the increase and decrease buttons of the number input, with larger buttons, because I was having trouble clicking the native ones. There were too small. Also I added the daily, weekly, monthly and yearly labels in case the number of recurrence is 1. Like this we have less problems with the other languages. Please check it out and let me know if this works for you.

**Comment by wsdfhjxc** [comment]
@ransome1 Yeah, your improvement is great, I love it. Thank you very much!

As for Simpletask's recurrence-handling method, adopting it would be a "breaking" change for current users. So, I think that should be a separate request, in a potential issue related to bringing feature parity with Simpletask to sleek (if it's planned).

I'm going to close this issue, as the initial request has been fulfilled and the feature is in a usable state.
