### ISSUE TITLE
sleek-v1.1.0-windows(setup) signature not valid?

### ISSUE THREAD

**Issue by ccchan234** [ransome1/sleek#250]
hi,

as a paranoid I wish the .exe files are signed.

but my machine's check and also virustotal report this:
Signature verification
A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.

pls see if anything can be done. thanks

btw, others have wished the sort will include "todo txt body", which is also my wish and is reasonable.
suppose I list out a singer:song list, currently sleek only sort "priority, context, project, due date" and this doesn't fit.
allow sort by "todo txt body" is good (like markor), further allow sorting "key" in the key:value pair  (as singer:song)
will be good, further allow sort by the "value" in the pair will be excellent.

thanks

**Comment by ransome1** [comment]
Hi @ccchan234 thanks for your comment. I was digging into code signing certificates but discarded the idea as it's just too expensive for a private project like sleek. Plus you then we would need another certificate for the Mac files and so forth.

For a signed Windows build I would want to advice you to download sleek from Microsofts Windows App Store.

The Windows builds here are signed with a self signed certificate which of course is not accepted by any authority and will produce that warning. Maybe it helps to just remove the self signed certificate?

**Comment by ccchan234** [comment]
hi, thx for reply.

1. i got internet connected win10, so as you said i could dnld from windows store instead 

2. i got several airgap-ed win10 for security issue. it will be more smooth if you could publicly announce that the signature is invalid (e.g. in releases note), and is even better if a pgp file signature(better) and/or sha1/256 checksum of the file is provided. ofcoz this depend on the time you can provide.

thanks

**Comment by ransome1** [comment]
Ich would really love to work on sleek at the moment, but there is absolutely zero time. And when there will be again, there is quite a prioritised backlog. 

We can add this to the backlog but please don't expect any work on it soon.
