### ISSUE TITLE
The app should maintain single active instance

### ISSUE THREAD

**Issue by theperiscope** [ransome1/sleek#257]
**Is it an actual bug?**
Yes, it does not make sense to have multiple active instances with same icon and open files in the tray

**Did you check if the bug has already been reported?**
Yes

**Describe the bug**
It is possible to launch multiple instances of the app

**To Reproduce**
1. Pin Sleek icon to start for ease of access
2. Go to Start menu, click Slick
3. Go to Start menu, click Slick again
4. Go to Start menu, click Slick again
5. Actual Result: 3 icons in tray (setting enabled), Expected result: 1 icon in tray (perhaps bring app to front if already active)

**Do you see any error entries in sleeks developer tools?**
No

**Expected behavior**
Exactly one active instance in tray (perhaps bring app to front if already active)

**Screenshots**
![ORD 2021-08-31 092306](https://user-images.githubusercontent.com/1619363/131520121-b998c94d-c588-413d-9950-c07f009a0430.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro, latest updates
 - Version of sleek 1.1.1

**Comment by stianmandarin** [comment]
FYI, if you are on Linux, you can map Sleek to a shortcut, e.g. `CTRL-ALT-S` and have that exectute `wmctrl -xa Sleek || /usr/bin/sleek` which will look for an active instance, and focus on it if it exists, otherwise open Sleek as new instance.

**Comment by ransome1** [comment]
This particular issue has been solved and released in v1.1.6
