### ISSUE TITLE
Shortcuts trigger on focusing application

### ISSUE THREAD

**Issue by dbr** [ransome1/sleek#259]
**Describe the bug**
If a key is pressed which triggers Sleek to become the active application, that shortcut also triggers in Sleek

**To Reproduce**
1. Open sleek
2. Open a single terminal window
3. Exit the terminal with `ctrl+d`

The result is:
1. Terminal exits due to `ctrl+d` shortcut
2. The terminal app exits, and Sleek gains focus
3. Since `d` is still held down, Sleek noticies this and it triggers the `d` shortcut for "Toggle Dark mode"

**Do you see any error entries in sleeks developer tools?**
Nope, just `Success: Theme set to light` etc

**Expected behavior**
The `d` key pressed when another application is focused would be ignored by Sleek until it is re-pressed

**Screenshots**
![sleek_bug](https://user-images.githubusercontent.com/509/132442329-48519d7c-bef8-4ec7-a70d-e6dce7b1dcbc.gif)

**Desktop (please complete the following information):**
 - OS: Debian Buster
 - Version of sleek: 1.1.1
 - Source: Flathub

**Comment by ransome1** [comment]
Hi @dbr . Can I ask you to check this pre-release if this still happens on your side?

https://github.com/ransome1/sleek/releases/tag/v1.1.4-rc.2

**Comment by dbr** [comment]
Did a quick test and it seems to fix it, thanks!

**Comment by ransome1** [comment]
@dbr thanks for reporting back. I will include this fix into the next release.
