### ISSUE TITLE
Showing filters terms directly

### ISSUE THREAD

**Issue by Li-An** [ransome1/sleek#26]
Hello, what a great surprise ! I like very much todo.txt concept but stopped using it as I did not find an interface I liked. Your application is beautiful and very well designed. Thanks a lot. Alarm/Reminder management is very promising.

So the point I don’t like much is the way filters are shown. For the moment, we have to click once to see different filters. I would prefer they were shown directly in main window so we can filter in one click (as tags in CMS).

**Comment by ransome1** [comment]
Hi @Li-An . Thank you for your kind words.

As a short term workaround I could add a keyboard shortcut for toggling the filter drawer.

And on the long run we would need a smart UI concept. sleek aims to be simple and clean and by just putting the filters in main view it could raise quite some concern with users who for instance have a lot of contexts and projects. 

Let me think about it and if you have a good idea, feel free to share your thoughts.

**Comment by Li-An** [comment]
Thanks for your quick answer. I understand the problem. Maybe showing only the ten "best" filters ? I don’t know if it’s possible to add an option to show or not the filters on main window.

**Comment by wsdfhjxc** [comment]
As a partial solution, sleek could just remember the filter drawer's state (open/closed) and restore it at launch.

**Comment by ransome1** [comment]
@wsdfhjxc , simple and effective :1st_place_medal: 

@Li-An: Wherever this is heading, let me add @wsdfhjxc's suggestion into the next release. You can also adjust the width of the filter drawer, so it can be used always on and adjusted to your needs. What do you think?

**Comment by Li-An** [comment]
It seems to me that’s a good idea :-)

**Comment by ransome1** [comment]
Feel free to check out release 0.8.3 and let us know if this helps you: https://github.com/ransome1/sleek/releases/tag/v0.8.3

**Comment by Li-An** [comment]
Too bad, it does not work as I hoped. I hoped the list of todos and the filters together. For the moment I have to choose between filters and todos.

**Comment by ransome1** [comment]
@Li-An, I don't understand, could you please be more specific?

**Comment by Li-An** [comment]
OK, I missed the "Reinitialize filters" button. It seems OK now.

**Comment by ransome1** [comment]
@Li-An , I assume we can close this issue?
