### ISSUE TITLE
🐞Ask for confirm even if nothing is changed? 

### ISSUE THREAD

**Issue by nutnutwin** [ransome1/sleek#262]
**Is it an actual bug?**
Or can it be a specific behavior of sleek that others would not consider a bug? In this case a feature request can be better suited: https://github.com/ransome1/sleek/issues/new?assignees=&labels=&template=feature_request.md&title=
Yes

**Did you check if the bug has already been reported?**
Please do so first: https://github.com/ransome1/sleek/issues
Yes

**Describe the bug**
https://github.com/ransome1/sleek/issues/187#issuecomment-874424054
Confirmation is added↑ as described above, where new bug is introduced?
Please see below

**To Reproduce**
1. Open existing task
2. Modify nothing, click on space beyond the window
3. "This window will be closed and its contents cleared"
4. actually nothing happens

**Do you see any error entries in sleeks developer tools?**
While sleek is open press Ctrl + Shift + I which will open the developer tools. If the shortcut doesn't work, press the Alt key, select the tab "About" and select the developer tools. In the dev tools select the tab "Console" and check if any error entries are written, while you provoke the bug.

**Expected behavior**
The edit window simply disapper without any popups(as nothing is changed
If something is changed, then "changes would be lost" should be shown(contents are not cleared)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 20H2
 - Version of sleek 1.1.1
 - Source: Github

**Comment by nutnutwin** [comment]
@ransome1 I know you are very busy. 
I suppose it would be better to report this before it's forgotten...

**Comment by ransome1** [comment]
@nutnutwin also, can you check if this still happens on your side with https://github.com/ransome1/sleek/releases/tag/v1.1.2-rc.2?

**Comment by nutnutwin** [comment]
@ransome1 this one is fixed
will check #264 

Thank you! 
will close this
