### ISSUE TITLE
🐞Opening URL does not work in some cases? 

### ISSUE THREAD

**Issue by nutnutwin** [ransome1/sleek#264]
**Is it an actual bug?**
Yes

**Did you check if the bug has already been reported?**
Searched but found nothing

**Describe the bug**
[URL](C:\Temp\__TickTick_Feedback_SupportCenter.ahk)
does not open on click
while 
[URL](C:\Temp\TickTick_Feedback_SupportCenter.ahk)
can be opened. 

might be something to do with path/filename

**To Reproduce**
please refer to the above

**Do you see any error entries in sleeks developer tools?**

**Expected behavior**
both URL can be opened

**Screenshots**
nothing

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 20H2
 - Version of sleek 1.1.1
 - Source: Github

**Comment by ransome1** [comment]
I assume you are referring to the click in the link icon?

**Comment by nutnutwin** [comment]
> I assume you are referring to the click in the link icon?

yes
a Task containing
[URL](”https://www.reuters.com/“)
for example

in my case trying to call local files

**Comment by ransome1** [comment]
@nutnutwin could you please check if this still happens in https://github.com/ransome1/sleek/releases/tag/v1.1.2-rc.2?

**Comment by nutnutwin** [comment]
@ransome1 
hi, thank you for the work
I tried some url like 
[URL](C:\Users\nutnu\Desktop\nutnutwin_ahk\4_AlCarte\__Amazon_TKBB_tkっb_アマゾン定期便.ahk)

which contains Japanese Kana, Japanese Kanji, but no space in the url
and sleek didn't open anything after clicking

Thank you

**Comment by ransome1** [comment]
@nutnutwin What exactly is it you expect sleek to do? I'm a bit puzzled on this issue.

**Comment by ransome1** [comment]
@nutnutwin for the link parsing https://github.com/markedjs/marked is used. I checked the docs briefly and in case you want to open local files from within sleek, I'm afraid it only supports parsing of like http links then opened in a browser.

**Comment by nutnutwin** [comment]
@ransome1 well I never expected to open local files
I happened to be able to find some of the local files, and then I found I cannot open some files(like the once mentioned before)

as is mentioned in the doc, I cannot expect to open any local files in the first place. 

thank you for your help.
