### ISSUE TITLE
markdown in notification

### ISSUE THREAD

**Issue by trend-1** [ransome1/sleek#266]
I'm using sleek version: 1.1.1 on Windows 10. 

I noticed that *in the todo notifications, markdown is not parsed*. 

I don't know if that is easy to achieve. Would be nice. Otherwise not a big problem.

**Comment by ransome1** [comment]
I checked the Electron documentation again but there is no word mentioned about any styling of notifications. 

Plus on Linux and MacOS I can't recalls ever seeing a notification with styling. My guess is, it won't be possible. But if anybody can prove me wrong, we could dig deeper.

**Comment by trend-1** [comment]
I'm no techie so it was just an observation.  
Thought it was a sort of XML template that could be styled somewhat, hence my question.

I see that your kind of busy. So if you want to close the issue I'm fine with that.   
And  thanks for the quick reply!
