### ISSUE TITLE
Is it possible to show different title for different window? 

### ISSUE THREAD

**Issue by nutnutwin** [ransome1/sleek#268]
*If your proposal is more a rough idea than a precise description of a feature, please consider starting a discussion instead: https://github.com/ransome1/sleek/discussions
Please only continue the feature request if you have a precise idea of what you're asking for and if you can provide specific details, use cases or examples. 

**Did you check if a similar feature request has already been reported?**
Yes

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When showing(active) the main window, and New/Edit Window, 
I wish that sleek shows different window title so that I can distinguish between them

in order to create customized shortcut/sequence
for example Ctrl+Up as Ctrl+Alt+Up in New/Edit, Ctrl+Up as Main Window...

**Describe alternatives you've considered**
haven't thought of other alternative...yet

**Comment by nutnutwin** [comment]
@ransome1 BTW I am using autohotkey on windows. 
it can dertermine where the keyboard cursor focus is, by 
- active window
- "control"(don't know if it is the right word), in the window. 
  eg. in Native File Manager, focus on filelist shows as "DirectUIHWND2", while Filename rename shows as "Edit2"
  eg. in Excel, focus on Main Window, shows as "EXCEL71", Editing Cell shows as "EXCEL61"

Briefly, If I can tell where the Keyboard cursor is, I can do... just whatever I like to...
Thank you.

**Comment by ransome1** [comment]
@nutnutwin I read it several times, but I don't understand what the feature request is about :/
