### ISSUE TITLE
Sort completed tasks by completion date instead of due date

### ISSUE THREAD

**Issue by bluebirch** [ransome1/sleek#269]
When the list is sorted and grouped on due date, I think it would make sense to sort completed tasks on completion date. That way, completed tasks are grouped on the day they were completed insted of the day they should have been completed. So, for example, completing ta task with a due date yesterday, would move that task to today when marked complete.

That way, when sorting tasks on date, what I see for every day is what I should do (or should have done) and what I have actually done.

**Comment by velardevines** [comment]
Agree with this idea. It provides a quick way to remember where things are on the project. 

--Bill
