### ISSUE TITLE
Auto startup at Windows boot

### ISSUE THREAD

**Issue by ivysrono** [ransome1/sleek#277]
*If your proposal is more a rough idea than a precise description of a feature, please consider starting a discussion instead: https://github.com/ransome1/sleek/discussions
Please only continue the feature request if you have a precise idea of what you're asking for and if you can provide specific details, use cases or examples. 

**Did you check if a similar feature request has already been reported?**
yes

**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
I don't find auto startup option on MicrosoftStore sleek.

**Describe alternatives you've considered**
Add asuto startup option.

**Comment by AmmarHaddadi** [comment]
1. press windows logo key + R
2. write `shell:startup` then press enter
3. add sleek.exe shortcut to that folder

**Comment by AmmarHaddadi** [comment]
apparently the devs need to implement a launch command that launches the app minimized in system tray  , I couldn't find any way to do it my self 

> You can only minimize to the system tray if the application itself has that capability and tells you which switches to use in its command line to start it that way.
There are no Windows commands to minimize applications to the system tray.
https://www.tenforums.com/software-apps/190630-how-run-program-startup-minimized-system-tray.html

example (adding this to the launcher / shortcut): `sleek --hide`
