### ISSUE TITLE
Uncaught Exception: TypeError: Cannot read property 'isFocused'

### ISSUE THREAD

**Issue by mikeo85** [ransome1/sleek#278]
When Sleek app is enabled but no window is open on my MacOS Big Sur, periodically a message pops up as follows:

> **A JavaScript error occurred in the main process** 
> Uncaught Exception:
> TypeError: Cannot read property 'isFocused' of null
> at Timeout._onTimeout (/Applications/sleek.app/Contents/Resources/app.asar/src/main.js:779:54)
> at listOnTimeout (internal/timers.js:554:17)
> at processTimers (internal/timers.js:497:7)

![image](https://user-images.githubusercontent.com/33993323/136083625-9dc36322-6c30-4394-bf48-f53b3329a413.png)

This happens after I have closed the Sleek window (using the "x" button or CMD-W) but have not quit (CMD-Q) the app. The popup is not immediate -- usually takes a few minutes to appear. Additionally, if I ignore it for a while, the popup will immediately reappear multiple times back-to-back when I try to click "OK" to close it.

**Do you see any error entries in sleeks developer tools?**
I have to close the error message to be able to reopen a Sleek window, but here's what is present in developer tools when I do so:
![image](https://user-images.githubusercontent.com/33993323/136084415-94dbacb6-1451-4930-99d4-836cb8522a31.png)

**Expected behavior**
Sleek sits silently in the background in my task bar until I want to open the app again.

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur 11.6
 - Version of sleek: 1.1.1
 - Source: Used the ```sleek-1.1.1-mac.dmg``` download from GitHub. I had the same issue when installing using Homebrew.

**Comment by ransome1** [comment]
Hi @mikeo85 does this also happen with the latest release 1.1.2?

**Comment by ransome1** [comment]
Alright, I was able to reproduce it. It's going to be fixed in the next release :)
