### ISSUE TITLE
Clicking on a project or a context button should create a filter set to that project or context

### ISSUE THREAD

**Issue by agrudzinsky** [ransome1/sleek#282]
**Did you check if a similar feature request has already been reported?**
Yes

**Is your feature request related to a problem? Please describe.**
Use case: need to quickly see tasks related to the same project or context as the current task.

**Describe the solution you'd like**
Currently, clicking anywhere on a task opens it for edit. I propose creating a filter with selected project or context when a project or a context bubble is clicked within the task. This behavior would be similar to clicking on a label in Gmail or clicking on a project in Simpletask. Task edit should open after a click on the task text.

**Describe alternatives you've considered**
Currently, I have to create the filter manually. The feature would save the time considerably in this use case.

**Comment by ransome1** [comment]
@agrudzinsky could you please give https://github.com/ransome1/sleek/releases/tag/v1.1.3-rc.3 a quick look. This feature has been added here and needs some testing :)

**Comment by agrudzinsky** [comment]
It works! Thanks!

**Comment by Saturo78** [comment]
In the latest release the +Projects and @contexts are shown on the right side of the monitor.
In the previous versions they were shown directly after the todo. In my opinion this was the better way.

**Comment by Ecatonchiro** [comment]
The new functionality is really useful thanks for suggesting and even more to implement it.

**Comment by Ecatonchiro** [comment]
> 
> 
> In the latest release the +Projects and @contexts are shown on the right side of the monitor. In the previous versions they were shown directly after the todo. In my opinion this was the better way. The colors of +projects and @contexts were also better in the old version. Because of this i made a downgrade. :o(

I second this comment, on 1.1.3 the spacing is different (especially the clock icon) if you are on Windows, strangely enough I don't see this on Linux. However probably @Saturo78 your comment needs a separate ticket.

**Comment by agrudzinsky** [comment]
> 
> 
> > In the latest release the +Projects and @contexts are shown on the right side of the monitor. In the previous versions they were shown directly after the todo. In my opinion this was the better way. The colors of +projects and @contexts were also better in the old version. Because of this i made a downgrade. :o(
> 
> I second this comment, on 1.1.3 the spacing is different (especially the clock icon) if you are on Windows, strangely enough I don't see this on Linux. However probably @Saturo78 your comment needs a separate ticket.

I'm using the Windows version. I personally like the buttons on the right. I think it unclutters the contents of the tasks. The colors are OK too. I don't have a preference as long as they are non-obtrusive.

Having the projects and contexts clickable is, definitely, an improvement. This is my favorite todo application for now (I tend to change them quite often). 

Thanks a lot for the development and for the response!
