### ISSUE TITLE
Existing tasks disappear when from view when adding new ones

### ISSUE THREAD

**Issue by stianmandarin** [ransome1/sleek#286]
**Is it an actual bug?**
Yes.

**Did you check if the bug has already been reported?**
Yes

**Describe the bug**
Parts of the task list disappear when adding new tasks (sometimes also when completing tasks), requiring manual (`.`) sync of file.

**To Reproduce**
1. Add task
2. Watch parts of existing tasks disappear

**Do you see any error entries in sleeks developer tools?**
None.

**Expected behavior**
For tasks not to disappear from view.

**Screenshots**
See here: [imgur](https://imgur.com/a/HHCpY7g)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.6
 - Version of sleek 1.1.2
 - Source: Github

**Comment by ransome1** [comment]
Hey @dlaidig , @stianmandarin . Could you please give this pre release a quick look? https://github.com/ransome1/sleek/releases/tag/v1.1.3-rc.2

I hope it solves the issue. I will definetely give it a it more of testing too as I was having hard times reproducing it.

**Comment by dlaidig** [comment]
I did a quick test and could not reproduce the bug with this pre-release. :)

(With 1.1.2, it still happens quite reliably directly after starting and switching tabs a few times.)

**Comment by ransome1** [comment]
Glad to hear guys. It kind of was an ugly bug and I really wonder why I didn't see it myself. Thanks for reporting it.
