### ISSUE TITLE
[Filters] Saving of profile sets

### ISSUE THREAD

**Issue by aubreyz** [ransome1/sleek#288]
This is a feature request (thanks for a promising looking app): 

Simpletask on android is really the model for the best todo.txt app on any platform. There are a number of things to learn from that app, but the biggest is the saving of filters/views as sets that can be recalled.

Along those lines there is muddling of filters versus views in Sleek. Several of the toggles on the view menu are filters (how hidden tasks are shown, showing in relation to date) and should appear with the filters to make sense (and be recalled with them as well as view items like sort as part of profiles).

**Comment by aisbergde** [comment]
I am also using [simpletask-android](https://github.com/mpcjanssen/simpletask-android), and one of the most important feature is the ability to save and restore filters. Simpletask solution is really great: include something, revert filter (for better excuding), sorting.

**Comment by thePHTest** [comment]
+1 For being able to save filters. I'm also looking for a Windows desktop equivalent of simpletask android and this is the main missing feature right now. Couldn't find anything closer than sleek atm.

**Comment by ransome1** [comment]
@thePHTest @aisbergde @aubreyz I would like to merge this rather loose idea with this feature request: https://github.com/ransome1/sleek/issues/179

Let me know if you disagree and we will re-open here.

**Comment by ransome1** [comment]
@thePHTest @aisbergde @aubreyz there is progress on this topic over in https://github.com/ransome1/sleek/issues/179, including pre-releases to play around with an early draft of this feature.

**Comment by dnngll** [comment]
Hello @ransome1 ,

I am looking for what I think @aubreyz meant with "saving of filters/**views**" above. The saving of filters has been implemented beautifully in https://github.com/ransome1/sleek/issues/179 , but not the saving of "views".

I change the sort order of my todo very often. On Simpletask or todotxt.net, this can be done quickly via a quick setting (more advanced in Simpletask, more basic in todotxt.net). I would love to see this behavior in sleek as well. Is there a way you could implement different sorting-profiles? Similar to what was suggested in https://github.com/ransome1/sleek/issues/556 - just not by file.

Perfect would be to have shortcuts like in todotxt.net: CTRL-1 to CTRL-9 instantly change the (definable) sort order.

What do you think?
