### ISSUE TITLE
Start Date Functionality?

### ISSUE THREAD

**Issue by velardevines** [ransome1/sleek#29]
Hello, I've tried using start:yyyy-mm-dd but it seems to have no effect. I was hoping the task with a start date would be hidden until that date. Just curious, what functionality is build around the start date?

Thanks.

**Comment by ransome1** [comment]
Hi @velardevines . So far there is no functionality behind the start date. If you use sleek to add a new todo, the start date will be added automatically like mentioned here as the "creation date" https://github.com/todotxt/todo.txt.

Initially I thought it might become handy, if sleek would at some point create statistics on how long you needed to finish a task.

**Comment by ransome1** [comment]
As this is not an issue, I would like to close this thread. Nevertheless I added to my roadmap to think of possible use cases on what to do with the start date.
