### ISSUE TITLE
Feature request: Individuals options by todotxt file

### ISSUE THREAD

**Issue by Oroumov** [ransome1/sleek#292]
Hi Guys, 

Would it be possible to link somehow the todolist options to the file being viewed ?
I'd like to be able to navigate separate todotxt files with separate settings (for example, one sorted by due date and NOT showing the completed items, and in the other file, sort by Projects instead, and show completed items)
Of course, then there is the issue of how to identify a file uniquely (assuming even its name could change...) but I think that would be a very useful feature.

Cheers !

**Comment by aubreyz** [comment]
I think the real development issue is being able to save and recall viewing sets (sorts and filters)
See https://github.com/ransome1/sleek/issues/288

Not really to have a separate type of view per file. After all you will not want to view the same file in the same way always. I suppose it might be possible for the view for each file to be remembered once there is a system for saving views.

**Comment by Oroumov** [comment]
Agreed, if #288 is solved, then my request here is encompassed in it.
Closing this one, and I'll follow #288 :)
