### ISSUE TITLE
Better "AND"/"OR" filtering

### ISSUE THREAD

**Issue by 9z0** [ransome1/sleek#293]
This is in continuation of #132 about search-as-you-type.

Not only that implicit "AND" filtering should be the default, but the fact that it is not even _allowed_ is crazy to me!

I really hope we see this soon!

Thanks @ransome1 and @zerodat for your efforts.

**Comment by ransome1** [comment]
@zerodat maybe you could take a look at this if you have some time left. I don't want to mess with your work here ;)
