### ISSUE TITLE
Tab completion of contexts and projects

### ISSUE THREAD

**Issue by gdevenyi** [ransome1/sleek#294]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Right now, starting off a project or context will bring up the list underneath, however, tab results in a re-focus into the list, instead, if the completion is unique, it should simply fill it in.

**Describe alternatives you've considered**
Keep as-is

**Comment by ransome1** [comment]
Hi @gdevenyi . I'm not sure if I understand this behavior. Can you please be more specific or can you post a screen cast? Thanks a lot.

**Comment by gdevenyi** [comment]
I have a context @home, I start typing "@ho" and get the list of contexts which match the partial input under the input box. If I press <TAB> the focus moves to that list. Instead, if there's a single match, I'd like <TAB> to complete the context in the input box.

**Comment by ransome1** [comment]
Ok this I get and it makes sense and might be a good quick win for the next release. Thanks for this suggestion.

**Comment by gdevenyi** [comment]
The rc releases do this properly :+1:

**Comment by ransome1** [comment]
Thanks for your feedback!

**Comment by comminutus** [comment]
Perhaps I'm missing something here but I don't quite understand this improvement.  I was expect that when I type the first few letters of a context, I could hit tab or something else to complete the context name.  Instead, tab just moves to the list of contexts.  The list of contexts doesn't get filtered the more I type.  For example, if I have contexts "inbox", "calls", and "computer", if I type "@in" all of 3 of these contexts show up.  Instead, I'd expect only "inbox" to appear, and I ought to be able to just push tab or some other key to automatically fill in the context.

This would make it much quicker to add contexts to tasks.  Should I file a new issue or does this exist in some fashion that I'm missing?

**Comment by ransome1** [comment]
> I could hit tab or something else to complete the context name.

This is actually how it is intended, I mean if there is only one filter available. And that of course only makes sense when

> For example, if I have contexts "inbox", "calls", and "computer", if I type "@in" all of 3 of these contexts show up. 

this is not the case. It should be exactly like you assume. So this sounds more like a bug. Let me look into it.

**Comment by ransome1** [comment]
@comminutus this should be fixed in https://github.com/ransome1/sleek/releases/tag/v1.2.5

Please feel free to provide feedback on if this now works as expected.

**Comment by comminutus** [comment]
@ransome1 wow! fixed!  Thank you for such a fast response! 👏

**Comment by ransome1** [comment]
> @ransome1 wow! fixed!  Thank you for such a fast response! 👏

Thanks for reporting it!

**Comment by comminutus** [comment]
It looks like this is broken again.  Now whenever I hit tab to complete the context, it clears the entire text area.

**Comment by ransome1** [comment]
@comminutus Can you make sure you're on 1.2.8?

**Comment by comminutus** [comment]
@ransome1 my bad, I just updated and it's working fine.  I'm not sure what version I was on prior.  Thanks!

**Comment by ransome1** [comment]
You were probably on 1.2.7, which contained a nasty little bug that provoked what you were experiencing.
