### ISSUE TITLE
future thresshold recurrent task not repeated

### ISSUE THREAD

**Issue by zemua** [ransome1/sleek#297]
**Describe the bug**
When a threshold date is in the past or today, and the task is set as recurrent, the date is update in a new task after complete, but if the task date is in the future, it doesn't create any recurrence after complete and the task is lost.

**To Reproduce**
1.- add a new task: test rec:1d t:2021-10-1
2.- click on complete, a new task is created with due date as of tomorrow
3.- click on complete again, no new task is created
seeing the console, the program may try to create the recurrence before completing the task itself with the same date as the existing one, then both are removed

**Do you see any error entries in sleeks developer tools?**

t based on today plus rec: 2021-11-20 my testing rec:1d t:2021-11-18 todo.t is Sun Nov 21 2021 10:41:56 GMT+0100 (hora estándar de Europa central)
todos.mjs:274 Success: Changes written to file: /home/miguel/todotxt/todo.txt
render.js:812 Table build: 15.605000000097789 ms
render.js:134 Info: Hide onboarding
recurrences.mjs:61 t based on today plus rec: 2021-11-20 my testing rec:1d t:2021-11-21 todo.t is Sun Nov 21 2021 10:42:20 GMT+0100 (hora estándar de Europa central)
todos.mjs:274 Success: Changes written to file: /home/miguel/todotxt/todo.txt
render.js:812 Table build: 12.584999999962747 ms
render.js:134 Info: Hide onboarding

**Expected behavior**
After clicking on complete task another recurrence will remain in the list

**Screenshots**
Not applicable

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version of sleek: 1.1.3
 - Source: Snap Store

**Comment by ransome1** [comment]
@zerodat I can reproduce this, but I don't want to interfere with your work on the recurrences. If you find some time anytime soon, would you mind looking into this?

**Comment by zerodat** [comment]
@ransome1, sure, I will look into this as soon as I can.

**Comment by ransome1** [comment]
@zemua @zerodat I did a double check on 1.2.6 and think this is fixed. Do you guys agree and can we close here?

**Comment by zerodat** [comment]
@ransome1 I find that the bug is fixed both in 1.2.6 and 1.2.1.  Each time you mark the task as completed, it generates a new occurrence with threshold date of tomorrow.
