### ISSUE TITLE
Re-Arrange Tasks within or not within the same priority

### ISSUE THREAD

**Issue by SonamorN** [ransome1/sleek#298]
Before opening this feature request I've checked for similar open issues but couldn't find any and it seems that the functionality is not available within the app.

While there a couple of priorities which allows for some kind of arrangement of priority on some tasks, you might have tasks that fall within the same priority but you want to do task A first before doing task B but both fall within the same priority. After creation of the task, there doesn't seem to be a way to sort them, e.g. put task B on top of task A. 

Currently I am using priorities but that's not suitable.

**Comment by ransome1** [comment]
Hi @rNianios you can try achieving this with the use of the other todo.txt attributes.

Here is an example on how it could be done with the use of contexts which are sorted alphanumerically
<img src="https://user-images.githubusercontent.com/11188741/143749495-cb9e7559-6e6e-4030-8040-e9c2c2b2f27e.png" width="300" />

The sorting setup would look like this
<img src="https://user-images.githubusercontent.com/11188741/143750049-ece55efd-01dc-416d-8092-948684ee485e.png" width="300" />

**Comment by rNianios** [comment]
@ransome1 I am new to todo.txt and for certain do not know all the options :) so thanks for let me know about this attribute.

I've tested and it should be OK for my workflow. Thanks for you work here. I am not sure if you want to close this feature request or actually implement it, if possible. This is somethign totally up to you.

**Comment by ransome1** [comment]
There was another feature request for reordering todos using drag and drop. I think it got closed as this is way of working with todos in not a very typical way working according to todo.txt. Plus we would need a database to store information on where a todo needs to be sorted. This would ask for a lot work on this and I'm not sure if the benefit would justify it.

The other todo.txt apps I know (Simplenote on Android and SwiftTodo on iOS) do not support this kind of sorting neither. And I'm sure those projects had those discussions as well, which then lead to abandon the feature.

We can leave this feature request open as a reference for future development. But for that we would need more details on what this function is about. Your first post isn't really detailed on what would need to be done.

**Comment by aubreyz** [comment]
It is *very* important not to stray outside of the todo.txt framework and recognised extensions. However can I suggest a possibility that might work within that to allow individual tasks to contain a short list. If you allow some character e.g / to force a line break and bullet in the **display** of a task, you could also allow some method to change the order of items within that list (and underlying Todo text)

**Comment by mimmori** [comment]
Actually I think it is useful to add the possibility to further order the tasks with the same priority  (ex alphabetic).
It would be really useful for me to have an extra parameter in the sorting options in the view panel. This way you can use a prefix code to sort the list.

**Comment by ransome1** [comment]
@mimmori you can use contexts or projects that contain prefixes. Both are sorted alphanumerically. For instance I use a context named "00_asap" and have contexts on my second sorting level. Like this I group my todos according to their priority and push the most urgent ones up by assigning the prefixed context.

I'm not a fan of tons of switches and options, it messes up the UX in general.
