### ISSUE TITLE
Copy visible todos to clipboard

### ISSUE THREAD

**Issue by Ecatonchiro** [ransome1/sleek#299]
### Discussed in https://github.com/ransome1/sleek/discussions/290

**Did you check if a similar feature request has already been reported?**
I found only one request about "copy", however it was included in a long list of other features which took the priority. "Copy" was never implemented or discussed thoroughly. 

**Is your feature request related to a problem? Please describe.**
Currently Sleek cannot communicate with other applications. It is impossible to report project status for instance creating an email with the OPEN/CLOSED activities.

**Describe the solution you'd like**

- [ ] Sleek should allow to copy filtered regions of Todo.txt as **formatted text** on the clipboard that can be pasted into other applications.
- [ ] Sleek should include the OPEN/CLOSED **activities according to the filter** applied on the main page.
- [ ] Sleek should allow the common shortcut Ctrl/CMD-C (currently associated to "create new todo") to copy the activities into the system clipboard.
- [ ] Optionally, Sleek should include in the clipboard a header with the definition of each column (if an optional field is missing, Sleek should include a tab in that field, each field should be separated by a TAB to increase readability)

EXAMPLE - Pasting a filtered activity list - (applied filter: Project=MARKET_1, show completed, sort by due date, priority, project, context)
```
Status	closed_day	priority	started_day	task	Project	Context
			(A)	2021-10-11	Define Legal Plan for	+MARKET_1	@Attorney2 
			(B)	2021-10-22       Polish wording Agreement for       +MARKET_1     @Attorney3 
x	2021-10-29	(A)	2021-10-12	Set meeting with Legal	+MARKET_1	@Attorney1 
```

**Comment by ransome1** [comment]
@Ecatonchiro I gave it some quick thoughts and realised that we already have almost everything on board for this feature. Do you have some time to do some testing on an early prototype of this feature?

**Comment by Ecatonchiro** [comment]
@ransome1 happy to help, I can provide windows/Linux environment, I just need basic instructions on how to test a prototype since I am not a developer (e.g. pre-req as compilers, libraries etc). Thanks for your reaction!

**Comment by ransome1** [comment]
@Ecatonchiro you don't need any additional software. I built a pre-release which contains Windows binaries and an AppImage for Linux: https://github.com/ransome1/sleek/releases/tag/v1.1.4-rc.3

In this version the CMD/Ctrl + C shortcut has been replaced with the requested function. All visible (filtered) todos will be copied to clipboard: Each todo is separated by a line break and each attribute is separated by a tab stop.

Once the todos have been copied a message will appear and inform you about this.

Please feel free to give this proper testing and let me know if this is what you were looking for.

**Comment by Ecatonchiro** [comment]
@ransome1 it looks amazing already, I am testing on Windows so far, please give me some time (by Fri Dec 3rd) to test it on Linux and with multiple todos, and I will be back with a detailed report.

**Comment by ransome1** [comment]
> @ransome1 it looks amazing already, I am testing on Windows so far, please give me some time (by Fri Dec 3rd) to test it on Linux and with multiple todos, and I will be back with a detailed report. 

Great. Thanks a lot :)

**Comment by Ecatonchiro** [comment]
Hello @ransome1, first of all thanks for your sharp reaction, the prototype ticks already all the marks. 

### Executive report
Windows - small glitch when in dark-mode, the pop-up message is unreadable
Linux - Sleek doesn't copy to the clipboard


### Detailed report
**Windows**

- When in dark-mode, the text color within the pop-up message is tone on tone, hence not readable. Light mode has the correct text color. (correction)
- The copied todos keep the creation order as in the .txt. This is perfectly in line with the first requirements "Copy filtered regions of Todo.txt". (As per requirement)
            I would probably inform the users the order is the one in the .txt and not in the application, just to set the expectations.
- Closed activities switch the priority label from (A) to pri:A. Thus closed activities enclose pri:A within the task (Acceptable)
- Tasks with multiple projects and/or multiple contexts are nicely separated by comma, hence they perfectly land within the same TAB-separated field. (As per requirement)
- In case you consider to implement this feature, please consider to change the text in the help. Otherwise Ctrl/CMD C shortcut will keep referring to create a new todo.txt. (correction)


**Linux (Ubuntu 20.04.3 LTS - installed from sleek_1.1.4-rc.3_amd64.deb))**
When in dark-mode, the text color within the pop-up message is tone on tone, hence not readable. Light mode has the correct text color.
Despite the pop-up message, the clipboard remain unchanged (no copied todos to clipboard). (correction)


I cannot test on MacOS

**Comment by ransome1** [comment]
Thanks for your testing, good work. I'll take a look at it asap and see what I can do.

**Comment by ransome1** [comment]
@Ecatonchiro Thanks for your testing, I considered all your remarks.

Though I aligned the sorting order of the clipboard with the order in sleeks current list. Sorting todos according to the order in the file was not what I intended. sleek will also add the grouping header to the clipboard.

You can check it out in this last pre-release of 1.1.4: https://github.com/ransome1/sleek/releases/tag/v1.1.4-rc.5

**Comment by Ecatonchiro** [comment]
hello @ransome1 I will try this new rc and I will give you feedback by tomorrow (16 Dec) EOD. Thanks for your great work!

**Comment by Ecatonchiro** [comment]
hello @ransome1 I tested directly 1.1.5 on Windows and Ubuntu.
Everything works like a charm.
Thanks for implementing this functionality.
