### ISSUE TITLE
Feature: Watch todo.txt to allow using Sleek or todo.sh command line

### ISSUE THREAD

**Issue by mark-keaton** [ransome1/sleek#3]
I like the idea of being able to edit the `todo.txt` from the terminal or from Sleek.

Could it watch `todo.txt` for changes?

If you like the idea, I could maybe put in a PR.

**Comment by ransome1** [comment]
Sounds like good idea. A PR would be much appreciated!

**Comment by ransome1** [comment]
@mark-keaton, please check release 0.0.9, it contains a file watcher: https://github.com/ransome1/sleek/releases/tag/v0.0.9

Feel free to give it some testing and report back if it works or needs improvement.
