### ISSUE TITLE
Notification setting toggles on after closing and opening Sleek

### ISSUE THREAD

**Issue by velardevines** [ransome1/sleek#30]
The Notification setting does not remain toggled in the off position. 

Open Sleek - Notification toggle is on
Turn Notification setting off
Close Sleek
Open Sleek - check setting and Notification toggle is on

Sleek version 0.8.4 on Chromebook Linux Crostini and Chrome OS Version 88.0.4324.99

**Comment by ransome1** [comment]
Thanks @velardevines , you were right. I fixed it and it will be deployed as part of 0.8.5.

**Comment by velardevines** [comment]
Fast response!  Nice!

**Comment by ransome1** [comment]
https://github.com/ransome1/sleek/releases/tag/v0.8.5

**Comment by velardevines** [comment]
Issue corrected in v0.8.5.   Thank you. 

Bill

**Comment by ransome1** [comment]
Hi Bill. I'm closing this. Let me know if you find any other bugs.
