### ISSUE TITLE
UI: Due icon too close to text in compact view

### ISSUE THREAD

**Issue by DOFfactory** [ransome1/sleek#300]
**Describe the bug**
The icons in compact view are too close to the text

**To Reproduce**
1. Enable compact view
2. Observe

**Screenshots**
![image](https://user-images.githubusercontent.com/10846169/144207957-701698e6-71fb-4559-adbd-e9c9aec11264.png)
and with compact view disabled
![image](https://user-images.githubusercontent.com/10846169/144208045-857b308e-3a25-4043-b721-0c99ee31dd7e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version of sleek 1.1.3
 - Source: Github

**Comment by ransome1** [comment]
Thanks, good hint! This will be straightened out in the next release. If you find more UI issues, let me know!

**Comment by gdevenyi** [comment]
The icon in compact view is also vertically misaligned.

**Comment by ransome1** [comment]
I think I underestimated the issue here, as it was really ugly in compact mode. I fixed it and released it with v1.1.5: https://github.com/ransome1/sleek/releases/tag/v1.1.5

Let me know if you find more UI bugs, I consider fixing those as more important than adding new features.
