### ISSUE TITLE
Headline Tasks without due date missing?

### ISSUE THREAD

**Issue by Saturo78** [ransome1/sleek#313]
I was wondering if there wasn`t a headline over tasks with no due date?
In the actual version tasks without a due date are shown directly under the last tasks with due date.
Because of that you might think that all tasks have this last due date.

I think in some older version there was a headline "no due date set", "without due date" or something else?

**Comment by ransome1** [comment]
@Saturo78  you're right, there is suppose to be a group headline for todos with no due date. It will appear again in the next release.

**Comment by ransome1** [comment]
@Saturo78 I decided against a "speaking" separator row. Instead and for all sorting methods I added a white space row, which can be tested in https://github.com/ransome1/sleek/releases/tag/v1.1.6-rc.3
