### ISSUE TITLE
Won’t work at all on brand-new install

### ISSUE THREAD

**Issue by xebico** [ransome1/sleek#315]
I just installed sleek for the first time (1.1.6-rc.2). Running Windows 10, all the latest updates, plenty of storage space and memory.

Sleek installs without out a problem and the shortcut appears on my desktop. Running it brings up what I assume is the main screen (blank, buttons on the left), but none of the buttons do anything. 

No matter what I click, right-click, Ctrl-click, the screen remains blank. I reinstalled, running the installer as Administrator. No joy. Tried running the program as Administrator. Nothing. I tried the portable version — same.

I wish I could give more info, but all I have is a blank screen with icons: Add, Filter, Preferences, Open, Settings, and Help (at least that’s what I assume they are).

Any suggestions would be appreciated — thanks!

![sleek](https://user-images.githubusercontent.com/19582721/147421154-891ba395-dbcc-4338-973e-aced5f9acb46.jpg)

**Comment by ransome1** [comment]
Thanks for reporting it, I will look into it. 

Please use the official latest release 1.1.5 to solve this issue.

**Comment by ransome1** [comment]
@xebico the issue should also be fixed on the latest pre release 1.1.6-rc.2 (I reuploaded it): https://github.com/ransome1/sleek/releases/tag/v1.1.6-rc.2

Thanks again for reporting it.
