### ISSUE TITLE
Tray icon invisible on initial login on Ubuntu

### ISSUE THREAD

**Issue by serpro69** [ransome1/sleek#319]
**Is it an actual bug?**
Yes

**Did you check if the bug has already been reported?**
Yes

**Describe the bug**
On initial login, the tray icon is not visible. If I lock the desktop and unlock it, then I can see the icon in the tray.

**To Reproduce**
1. Enable 'Minimize to tray' (not sure if it matters, but I have it enabled) and make sure sleek is in the "Startup apps list"
2. Restart OS
3. Login 
4. Observe that icon in the tray is not visible (even though sleek is running)
5. Lock the screen
6. Unlock
7. The icon is now visible

**Do you see any error entries in sleeks developer tools?**
No

**Expected behavior**
Icon in the tray should be visible on initial login

**Screenshots**
can provide if needed

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04
 - Version of sleek: 1.1.3
 - Source: Flathub

**Comment by ransome1** [comment]
Hi @serpro69 . Can I assume you're on Gnome 40?

**Comment by serpro69** [comment]
Hi @ransome1 ,

Gnome version is 3.36.9

I can see other icons in the tray - keepassxc, discord, slack, to name a few.

**Comment by ransome1** [comment]
@serpro69 could you please check if this still occurs in the [latest developer preview of sleek 2.0](https://github.com/ransome1/sleek/releases/tag/v2.0.0-dev11)?

**Comment by serpro69** [comment]
Hi @ransome1 ,
I don't have a machine to reproduce this on atm, unfortunately.

**Comment by ransome1** [comment]
@serpro69 I set up an Ubuntu VM and succesfully tested it with the AppImage of the latest developer preview.

Feel free to re-open here, in case it doesn't work for you.
