### ISSUE TITLE
Clearing the due date no longer works

### ISSUE THREAD

**Issue by wsdfhjxc** [ransome1/sleek#32]
It seems that clicking the Clear button doesn't remove the due date from the text input field.

**Comment by ransome1** [comment]
Hi @wsdfhjxc. I tried to figure out how to change the behavior of the clear button but wasn't able to do that. Therefor I asked the developers of the date picker feature for support but didn't receive any answer so far: https://github.com/mymth/vanillajs-datepicker/issues/44

If you have an idea how to change the button, let me know.

**Comment by wsdfhjxc** [comment]
@ransome1 I'd be glad if you could take a look at #33. There's more than one fix there though.
