### ISSUE TITLE
Awkward display of lengthy entries that force a line break

### ISSUE THREAD

**Issue by matterharz** [ransome1/sleek#320]
**Is it an actual bug?**
It's what I would consider to be a visual bug.

**Did you check if the bug has already been reported?**
Yes.

**Describe the bug**
Title and screeshot below pretty much say it all. It happens in normal view as well as in compact view.

**Expected behavior**
I expected the display to be in line with single-line entries, that is circle*, priority icon and context/project "pills" + due/rec icons on the same line. Or to be more precise, not have an extra line dedicated to each.

I don't see any benefit of the current behavior. You could fit several more entries in that same space without it being visual overload.

*Why a circle -- that can be confused with a radio button-- and not a check box? (For recurring tasks even some variation on that  check box might be good idea.)

**Screenshots**
![Screenshot 2022-01-05 162551](https://user-images.githubusercontent.com/76849821/148243159-6457fa0a-2837-4354-82da-bb20a7ec0cbb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version of sleek: 1.1.5
 - Source: Windows Store + portable .zip from Github

**Comment by ransome1** [comment]
@matterharz this is simply a css bug not a wanted behaviour and it should work in this pre release: https://github.com/ransome1/sleek/releases/tag/v1.1.6-rc.3

**Comment by matterharz** [comment]
Much better, thanks.

It still seems though as if the prio icons have their own line for no reason (unlike single-lline entries). Also, the remaining icons and pills are sort of piled up at the end of line which looks untidy and incoherent:
![Screenshot 2022-01-14 025437](https://user-images.githubusercontent.com/76849821/149438208-d0a65f98-ec09-4942-9069-4141ed414918.png)

This would make sense if they were arranged in a column at the end of each row across all the entries (though problematic for very short ones) but each entry, multi-line or not, seems to place them in a random spot. Adding them all to the last line, directly behind the last word of each entry seems more reasonable to me. It also saves space since you don't have rather early line-breaks like in the screenshot above.

**Comment by ransome1** [comment]
> This would make sense if they were arranged in a column at the end of each row across all the entries (though problematic for very short ones) but each entry, multi-line or not, seems to place them in a random spot. Adding them all to the last line, directly behind the last word of each entry seems more reasonable to me. It also saves space since you don't have rather early line-breaks like in the screenshot above.

Implementing your proposal as a general rule would only benefit longer todos with lots of tags. Users who use short entries and few tags could be disadvantaged by this as every todo would then occupy more height. If I find some time anytime soon, I can check if there is a CSS way to straighten this out if a todos needs more space. If you by any chance have knowledge on CSS you could contribute to sleek by solving this.

**Comment by matterharz** [comment]
> Implementing your proposal as a general rule would only benefit longer todos with lots of tags. Users who use short entries and few tags could be disadvantaged by this as every todo would then occupy more height.

I agree. Just noticed (the structure of) my post was ambiguous. My proposal would simply be this: add icons and pills to the end of each entry *as if* they were just regular text.

Unfortunately, I can't help you out with this since I have no knowledge of CSS (or any mark-up or programming language) whatsoever.
