### ISSUE TITLE
rec + due icons vertically misaligned in compact view

### ISSUE THREAD

**Issue by matterharz** [ransome1/sleek#321]
**Is it an actual bug?**
It's a small visual bug.

**Did you check if the bug has already been reported?**
Yes.

**Describe the bug**
Title + screenshot say it all.

**To Reproduce**
1. Add entry with rec + due 
2. Enable compact view

**Screenshots**
Normal view:
![normal view](https://user-images.githubusercontent.com/76849821/148251340-9ede5f1c-9b3f-4625-b382-58ae5bef8e68.png)

Compact view:
![Screenshot 2022-01-05 171944](https://user-images.githubusercontent.com/76849821/148251646-bea52e72-b177-417c-99d6-387e840a1044.png)

**Desktop:**
- OS: Windows 10
- Version of sleek: 1.1.5
- Source: Windows Store + portable .zip from Github

**Comment by matterharz** [comment]
Just noticed this was already mentioned [here](https://github.com/ransome1/sleek/issues/300#issuecomment-989988993) without being adressed. But as far as I know there's no ticket yet.

**Comment by ransome1** [comment]
@matterharz should be fixed in https://github.com/ransome1/sleek/releases/tag/v1.1.6-rc.3

**Comment by matterharz** [comment]
Looks good to me.

Minor quibble, though (not worthy of a separate issue, I think): Are these icons from the same set? They seem to have different line thickness.

**Comment by ransome1** [comment]
@matterharz unfortunately those icons differ in line thickness, although they belong to the same group of icons. They belong to the free icon set of https://fontawesome.com. It might be possible that the pro version offers more aligned icons (visually wise) but as for the free version we need to live with a compromise.
