### ISSUE TITLE
State of toggle switch not immediately recognizable in Dark Mode

### ISSUE THREAD

**Issue by matterharz** [ransome1/sleek#322]
**Is it an actual bug?**
It's a visual bug.

**Did you check if the bug has already been reported?**
Yes.

**Describe the bug**
While light-grey and almost-black work well enough in Light Mode since they're both darker than the background, the shades of grey used in Dark Mode are confusing since the background color sneaks in between the two shades. The first time I used Dark Mode I actually had to remind myself that the ON position is usually on the right.

**Proposed solution**
Simply use an actual color for the ON position (why not the purple from the app icon/logo?) in **both** Light and Dark Mode.

**Screenshots**

Light Mode
![Screenshot 2022-01-05 192626](https://user-images.githubusercontent.com/76849821/148269795-d39c11f1-7af8-4153-88c1-b157953e6c39.png)

Dark Mode
![Screenshot 2022-01-05 192710](https://user-images.githubusercontent.com/76849821/148269825-b3cd9be3-61bc-4d5e-b169-d5b53eb8076a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version of sleek: 1.1.5
 - Source: Windows Store, + portable .zip from Github

**Comment by ransome1** [comment]
@matterharz thanks for reporting this. Purple and green are reserved for contexts and projects. For most interaction elements we have blue as tertiary color. I added blue for the active state of the toggle for bright and dark mode and it can be tested in this pre release: https://github.com/ransome1/sleek/releases/tag/v1.1.6-rc.3

**Comment by matterharz** [comment]
Perfect. (Am I allowed to close issues? Please re-open if that's not acceptable.)
