### ISSUE TITLE
Flathub release is outdated

### ISSUE THREAD

**Issue by dlaidig** [ransome1/sleek#327]
The version of the flatpak available on https://flathub.org/apps/details/com.github.ransome1.sleek is still stuck at 1.1.3, last updated on November 7, 2021, while the current release is 1.1.6.

It would be great to have the latest version available via flathub. :)

**Comment by Ecatonchiro** [comment]
Same on Microsoft Store, last published 1.1.4

**Comment by ransome1** [comment]
@dlaidig the Flathub build process is a mystery to me. Currently it crashes for reasons I just can't comprehend. I recently opened up a ticket for the Flathub guys, let's see where this is heading. I'll keep you posted. 

@Ecatonchiro As for Windows, the v1.1.6 is currently in review at Microsoft and will be available soon.

**Comment by Ecatonchiro** [comment]
> @Ecatonchiro As for Windows, the v1.1.6 is currently in review at Microsoft and will be available soon.

1.1.6 is now available on MS store, thanks for your reply

**Comment by ransome1** [comment]
The Flathub issue is hopefully being discussed and solved here: https://github.com/flathub/com.github.ransome1.sleek/issues/2

**Comment by ransome1** [comment]
@dlaidig release v1.1.6 has just been published and should be available to your installer soon. Could you please give me a feedback if installation works on your side?

**Comment by dlaidig** [comment]
I just successfully updated to v1.1.6. :)

Thanks!
