### ISSUE TITLE
adjust location of context menu when at bottom of screen

### ISSUE THREAD

**Issue by snoblenet** [ransome1/sleek#328]
**Is it an actual bug?**
It's a UI glitch. Closer to a bug than to a feature request.

**Did you check if the bug has already been reported?**
[Yes](https://github.com/ransome1/sleek/issues?q=contextual) i checked. (No it has not been reported.) 👍 

**Describe the bug**
When you right click on the bottom-most task when the Sleek window extends to the bottom of the screen, part of the contextual menu is not visible.

**To Reproduce**
1. Expand the Sleek window to fill your screen
2. Ensure you have enough tasks to fill the Sleek window
3. Right click on the bottom-most task
4. See UI glitch

**Do you see any error entries in sleeks developer tools?**
n/a

**Expected behavior**
The contextual menu should pop up not down so it is entirely visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/62277/150285671-61526c50-2c1a-4d1a-aeb2-21bdffedaf97.png)

**Desktop:**
 - OS: Mac OS X 12.1
 - Version of sleek: 1.1.6
 - Source: homebrew

**Comment by ransome1** [comment]
Thanks for reporting this, I'll take a look at it and will try to fix this with the next release.

**Comment by ransome1** [comment]
Has been fixed and is available in 1.2.6
