### ISSUE TITLE
Date picker doesn't change due:date within a todo

### ISSUE THREAD

**Issue by Ecatonchiro** [ransome1/sleek#330]
**Describe the bug** 
Since the introduction of the data picker from the todo list (1.1.6).
I noticed the data picker within a todo stopped writing in the todo.
Strangely enough this effect appears from the second todo (existing or new) you want to manipulate.

**To Reproduce**
- open a todo, or create a new todo, from the data picker select a day, save
- open a todo or create a new todo, now the data picker won't affect the existing due:date, or won't introduce a due: date in the todo.

**Expected behavior**
Data picker should work also within a todo

**Comment by ransome1** [comment]
@Ecatonchiro I followed the steps you described but couldn't reproduce it. Can you maybe recheck and be more specific on how you provoke the date picker not to work any longer? Thanks.

**Comment by Ecatonchiro** [comment]
I cannot reproduce anymore, I believe I can close. False positive, sorry.

**Comment by Ecatonchiro** [comment]
@ransome1 

Eventually I managed to reproduce the occurrence.
I usually push my uncompleted todos to "today" or to the future. I don't like to see past days in my list.
I happens that when opening old todos the data picker shows two dates (one in blue, one in grey).
In this situation "sometimes" the data picker doesn't change the due:date in the todo.
In the video it happens at frame 00:30, when you can see the data picker with 2022-01-23 while the todo is left with 2022-01-22. 

I hope this helps,
 

https://user-images.githubusercontent.com/93349201/150695770-5c70da6a-4c8c-4fa7-9505-24fc297fbd8c.mp4

**Comment by ransome1** [comment]
@Ecatonchiro tha ja for reporting this. I'll check it as soon as find some time!

**Comment by ransome1** [comment]
@Ecatonchiro can I ask you to check if you can still reproduce this behaviour in this pre release? https://github.com/ransome1/sleek/releases/tag/v1.1.7-rc.1

**Comment by Ecatonchiro** [comment]
@ransome1 please give me 1 week to test it, so far it looks good, however since I couldn't find a precise method to reproduce the occurrence, I prefer to use the new version regularly for 1 week and report back to you.

**Comment by Ecatonchiro** [comment]
@ransome1 from my first day of utilization I just noticed that the data picker is consistent in having the "today" and "current due date" on the calendar, I didn't experience any hiccup while changing dates, so it seems the data picker is always updating the "due:" field in the todo, however I also noticed the direct data picker on the todo list doesn't work anymore with 1.1.7

**Comment by ransome1** [comment]
@Ecatonchiro good call. I didn't see that the picker in the actual list stopped working. It's going to be fixed in the next release.

But besides that everything is now working as expected?

**Comment by Ecatonchiro** [comment]
@ransome1 so far so good, but please give me few more days so I can test more conditions

**Comment by Ecatonchiro** [comment]
@ransome1 I dare to say it is fixed now, I worked with Sleek continuously in the past 3 days and it never missed a change in the due:date within a todo.
