### ISSUE TITLE
Date picker not refreshing current date highlight

### ISSUE THREAD

**Issue by M4he** [ransome1/sleek#331]
**Describe the bug**
The date picker for selecting the due date highlights the day when Sleek was initially started but doesn't update the highlight marker even if Sleek is kept open for days/weeks.
This is confusing because the highlight should serve as a means of orientation in the calendar in my opinion.

**To Reproduce**
1. Open Sleek
2. Keep Sleek running for longer than a day
3. Attempt to create a new task
4. Click the due date selector
5. The day when Sleek was started is highlighted, not the current date

**Expected behavior**
The current date in the current week and month should be highlighted, i.e. the date picker should refresh its "current" day marker when the picker popup appears.

**Screenshots**
![Sleek_date_picker_stuck](https://user-images.githubusercontent.com/1408105/150847702-0cdb8211-83d0-4955-a391-8332a9b627f1.png)
(Sleek started on Jan 16th but screenshot was taken on Jan 24th, using the German version)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version of sleek 1.1.6
 - Source: Github AppImage

**Comment by M4he** [comment]
Maybe it has to do with the `beforeShowDay` API of the widget? [This SO entry](https://stackoverflow.com/a/14484895) seems to hint at the [API documentation of `beforeShowDay`](https://api.jqueryui.com/datepicker/#option-beforeShowDay) which expects an array with specific values to be returned in all cases. The [current implementation](https://github.com/ransome1/sleek/blob/f3dc451809ff8df32570225686ebacbe3058e7e4/src/js/datePicker.mjs#L74) doesn't seem to adhere to this specification.

I haven't tried though and I'm not that well versed in JS, so pardon my ignorance in case it isn't related.

**Comment by Ecatonchiro** [comment]
I believe this can be somehow connected with [this](https://github.com/ransome1/sleek/issues/330).

**Comment by ransome1** [comment]
@M4he Could you please check real quick if this is connected to https://github.com/ransome1/sleek/issues/330 and if we can combine the two issues?

**Comment by M4he** [comment]
I had a look at #330 but that seems to be a different issue altogether. That issue is about the date picker selection not being applied when a date is clicked as far as I can tell. What I encounter is the initialization of the date picker not updating the "today" highlight (in the picker widget, not in the actual todo) when opened.

**Comment by ransome1** [comment]
@M4he this should be fixed in https://github.com/ransome1/sleek/releases/tag/v1.1.7-rc.1

Let me know if this works for you. Currently I can only test on MacOS, not on Linux and Windows.

you can reproduce this bug by just switching dates in your OS settings. Or at least this worked for me.

> Maybe it has to do with the `beforeShowDay` API of the widget? [This SO entry](https://stackoverflow.com/a/14484895) seems to hint at the [API documentation of `beforeShowDay`](https://api.jqueryui.com/datepicker/#option-beforeShowDay) which expects an array with specific values to be returned in all cases. The [current implementation](https://github.com/ransome1/sleek/blob/f3dc451809ff8df32570225686ebacbe3058e7e4/src/js/datePicker.mjs#L74) doesn't seem to adhere to this specification.
> 
> I haven't tried though and I'm not that well versed in JS, so pardon my ignorance in case it isn't related.

That's not exactly the right api documentation. This one is for the module used in sleek: https://mymth.github.io/vanillajs-datepicker/#/api

But anyway the api didn't really gives us a proper option to reset the current day. Instead now the datepicker will be destroyed and recreated everytime it is opened. It doesn't seem to impact sleeks performance, so this might be a proper solution for this issue.

**Comment by M4he** [comment]
Confirmed, v1.1.7-rc.1 fixes this. Thank you!
