### ISSUE TITLE
Switch between todo files

### ISSUE THREAD

**Issue by Samet-MohamedAmin** [ransome1/sleek#34]
It would be helpful to have the ability register many todo files, each file with global context, and to easily switch between todo files.

**Comment by ransome1** [comment]
Hi @Samet-MohamedAmin, have you checked the folder menu item? After adding the first file, you can add more files and switch between them.

![image](https://user-images.githubusercontent.com/11188741/106205928-94eadd80-61bf-11eb-9f95-42c349872d21.png)

**Comment by Samet-MohamedAmin** [comment]
Oh I missed that !

**Comment by Samet-MohamedAmin** [comment]
My bad ! I missed that..
