### ISSUE TITLE
Add option to automatically match system theme dark/light mode

### ISSUE THREAD

**Issue by shbach** [ransome1/sleek#340]
Currently sleek has a light and a dark theme. A nice addition to that is the option to automatically match the system theme dark/light mode. e.g. if system is currently using "dark" theme, sleek should also use the dark theme.

**Comment by ransome1** [comment]
@shbach That is a good point. sleek actually detects the OS current setting for dark mode on its first start. But then that is being persisted right away and won't change again, before the user toggles it.

For future development I think we should let sleek always adjust to the OS preference until a user actively uses the dark mode toggle. Another option I will think about is to replace the toggle with a select box in which users can select between `light`, `dark` and `system default`

I'll keep you posted when there is been progress on this. At the moment I'm only refactoring code and there is little feature development.

**Comment by ransome1** [comment]
@shbach this can be tested in https://github.com/ransome1/sleek/releases/tag/v1.1.8-rc.4

**Comment by ransome1** [comment]
@shbach More fine tuning has been done in: https://github.com/ransome1/sleek/releases/tag/v1.1.8-rc.5

**Comment by shbach** [comment]
@ransome1 Just tested it and it works! Only thing is that it requires me to restart the app. Ideally, it will change between dark/light without requiring a restart of the app. I have my system set up to change between light and dark depending on the time of day.

**Comment by ransome1** [comment]
A restart is not required for this to change. What OS are you on?

**Comment by mshuflin** [comment]
@shbach on MacOS it updates immediately, no restart required

**Comment by ransome1** [comment]
@shbach @mshuflin I also checked my Windows 11 VM and it works. So this might be a Linux issue, I'm going to check XFCE and Gnome later today.

**Comment by shbach** [comment]
Yeah I'm on Linux (Gnome).

**Comment by ransome1** [comment]
@shbach mmhh I can't really confirm this. I'm on Gnome 40 (Arch Linux) and if I select Dark or Light in sleeks settings, it just switches the color theme. 

Can you provide more details on what exactly you're doing? Are you just using the options in sleek or have you set the new theme selection to auto and then try to change something in the OS settings?

**Comment by shbach** [comment]
@ransome1 I have sleek set to auto. When I change the system theme from light to dark or vice versa I want sleek to update its theme accordingly without having to restart the app.

**Comment by ransome1** [comment]
@shbach how exactly do you switch the system theme in Gnome?

**Comment by shbach** [comment]
@ransome1 It depends on what version of Gnome you are on. If Gnome 42 you can use [the built-in setting](https://blogs.gnome.org/alexm/2021/10/04/dark-style-preference/
) under appearance. If on an earier version of Gnome you can install Gnome Tweaks and manually change it. Or you can use the [night theme switcher extension](https://gitlab.com/rmnvgr/nightthemeswitcher-gnome-shell-extension) to automate switching it depending on the time of day.
