### ISSUE TITLE
Add the ability to filter by date

### ISSUE THREAD

**Issue by mimmori** [ransome1/sleek#342]
**Did you check if a similar feature request has already been reported?**
Please do so first: https://github.com/ransome1/sleek/issues

yes

**Describe the solution you'd like**

It would be really useful to be able to quickly filter activities by their due date in the near future.
I believe the following filters are sufficient:
  - today;
  - tomorrow;
  - this week.

**Comment by Ecatonchiro** [comment]
I believe this is already implemented as part of the filter syntax https://github.com/ransome1/sleek/wiki/Filter-Expressions-for-Advanced-Search#due-date-comparison

**Comment by mimmori** [comment]
This is true, but it would be much more convenient to be able to do it faster from the predefined filters panel on the left (show filters -> B key)

**Comment by shbach** [comment]
More generally to implement this, I really think being able to [set saved filters](https://github.com/ransome1/sleek/pull/106) would be the best solution. That way people can customize to their needs.
