### ISSUE TITLE
Options to Hide Tags from being Displayed

### ISSUE THREAD

**Issue by ImperialSquid** [ransome1/sleek#346]
# Description
Adding some options related to hiding part of a task would be very useful in cases where the task comes with tags from another bit of software, due to the open-ended nature of todo.txt lots of different systems exist, all using slightly different tags or some systems make tags that aren't needed or useful in another (eg I have unique identifiers turned on in simpletask but they just become part of the title in sleek)

# Proposed Solution
Some ability to tell sleek not to display part of the task would be very useful (it would look like the filter part wasn't there essentially). There are two possible ways to go about this in my opinion. 

One user-friendly way would be to be able to give sleek a list of tags to ignore, in the above case I would tell sleek to ignore any "uuid" tags it sees.

A more powerful way would be to give it regex pattern(s) to ignore, this opens the door to more possibilities but is obviously less user friendly, in the above case the filter would be "uuid\:[^\s]*" to ignore the uuid tag and its value too.

As far as I know there are no alternative ways to go about this and it's a unique request

**Comment by chaotika** [comment]
Related: I made a PR that handles UUID tags: #371
