### ISSUE TITLE
Crash when start sleek on windows 10

### ISSUE THREAD

**Issue by mimmori** [ransome1/sleek#348]
**Is it an actual bug?**
yes

**Did you check if the bug has already been reported?**
yes

**Describe the bug**
Unable to start sleek. An error popup occur when click on executable.
Tried to install both from setup and portable version.

**To Reproduce**
Simple trying to start sleek

**Do you see any error entries in sleeks developer tools?**
The program does not open to get to the dedicated screen.

**Expected behavior**
Normal start as previous used version (1.1.7rc1).

**Screenshots**
![image](https://user-images.githubusercontent.com/2305819/160070912-656ba1dc-9c4c-46f6-a07a-00a2989a4e7e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version of sleek: 1.1.7
 - Source: Github

**Comment by ransome1** [comment]
@mimmori thanks for reporting this, I'll get my Windows VM running and be looking into it soon.

**Comment by ransome1** [comment]
@mimmori I think I found the issue and fixed it. Can you please double check the updated Windows files on a proper Windows machine? https://github.com/ransome1/sleek/releases/tag/v1.1.7

**Comment by mimmori** [comment]
just tried, fixed.
Thank you very much for the speed with which you solved
