### ISSUE TITLE
Tasks are not being sorted by due date

### ISSUE THREAD

**Issue by samuelznewton** [ransome1/sleek#35]
The readme lists the following feature: "Todos are sorted by due date within their priorities"

However, this does not seem to actually be the case.  As far as I can tell, tasks with due dates are always shown above tasks without them (which is desirable), but beyond that tasks are shown in the order of creation.

Steps to replicate: I currently have 5 tasks with due dates, added in the following order:

> Assignment 2 due:2021-01-31 +CS301
> CA2 due:2021-01-31 +CS301
> Specification document due:2021-02-03 +CS496
> Godot project due:2021-02-21 +CS301

At this point, I added several tasks without due dates before adding the task below.
> Go through RELS lectures due:2021-02-04 +RELS100

sleek has added the creation date 2021-01-31 to each of these tasks.

Expected behavior: Todos are sorted by due date within their priorities.  As there are no priorities, the final added task should be moved up to 4th in the list.
Actual behavior: The list stayed in the current order.  Restarting sleek did not change anything.

**Comment by ransome1** [comment]
Hi @samuelznewton , I think you might have found an inconsistency, that is correct.

But the idea of the desc sorting within the due dates is to have the closest due date (or the one you just missed) at the top of the list. Mostly because in my opinion the ones closest are the most relevant. So your first list is actually sorted as I intended it to be. But you're right the readme needs improvement.

About the start date if no due date is set. You're expectation is that the most recently created todo will be basically added at the bottom of the list, instead at the top (which is the case now)?

**Comment by samuelznewton** [comment]
What I expect is that an item which is due on February 4 will appear higher in the list than an item which is due on February 21 - and this is the behavior which the readme implies, and seems to be the behavior that you think is actually happening.

However, what is actually happening is that the items are being sorted first by _whether_ there is a due date, and then by when the tasks were _created,_ with the highest item on the list being the first one created and the lowest item being the last one created.

Basically, when you say
> the idea of the desc sorting within the due dates is to have the closest due date (or the one you just missed) at the top of the list. Mostly because in my opinion the ones closest are the most relevant.

You're exactly right, and I completely agree.  The most relevant items, and the most important to see at the top, are those that are soonest due, and those which are past due.  But this _isn't the behavior I'm seeing_.

As for your final note
> About the start date if no due date is set. You're expectation is that the most recently created todo will be basically added at the bottom of the list, instead at the top (which is the case now)?

What currently happens is that new tasks are added to the bottom of the list, and this is what I expect and what I want, with the exception that items with due dates should be sorted first and sorted by due date, as described above.

**Comment by ransome1** [comment]
Hi @samuelznewton. Could you check https://github.com/ransome1/sleek/releases/tag/v0.8.7-Alpha if the sorting is now consistent?

**Comment by samuelznewton** [comment]
Hello!  Sorry for my delay.

Unfortunately, nothing seems to have changed.  I loaded my todo.txt and it's still sorting the same way as before.
1st by priority
2nd by whether there is a due date
3rd by the order of the todo.txt file
Not at all by when the due date is

**Comment by ransome1** [comment]
Hi @samuelznewton . Let's stick to your initial example, which in the todo.txt file should look like this:
```
2021-01-31 Assignment 2 due:2021-01-31 +CS301
2021-01-31 CA2 due:2021-01-31 +CS301
2021-01-31 Specification document due:2021-02-03 +CS496
2021-01-31 Godot project due:2021-02-21 +CS301
2021-01-31 Go through RELS lectures due:2021-02-04 +RELS100
```

This leads to the following sorting within sleek (I used the 0.8.7 AppImage for this result)
![image](https://user-images.githubusercontent.com/11188741/106707223-29ef3b80-65f1-11eb-956a-a4dfacfd8a51.png)

That is the correct sorting according to my understanding.

Could you please provide a specific example and a corresponding output in sleek, where the issue still is evident?

**Comment by samuelznewton** [comment]
Well this is strange.  I just loaded up that file and got the same result.  But if I load back my current actual todo.txt file, I still get incorrect sorting.  Here's the full file, followed by the results.

```x 2021-02-01 2021-01-31 Assignment 2 due:2021-01-31 +CS301
x 2021-02-01 2021-01-31 CA2 due:2021-01-31 +CS301
2021-01-31 Specification document due:2021-02-03 +CS496
2021-01-31 Godot project due:2021-02-21 +CS301
2021-01-31 Network storage @BowlingGreen
2021-01-31 German
2021-01-31 Storage organization @BowlingGreen
2021-01-31 Inventory @BowlingGreen @Elizabethtown
2021-01-31 Budget
2021-01-31 Read about project management +Game @Kindle
2021-01-31 Learn Blender +Game
2021-01-31 Learn Unity +Game
2021-01-31 Learn music +Game
2021-01-31 Create concepts +Game
2021-01-31 Create specifications +Game
2021-01-31 Rework code +Picar
2021-01-31 Go through RELS lectures due:2021-02-04 +RELS100
x 2021-02-02 (A) 2021-01-31 Tire installation 10:00 due:2021-02-02 @WalmartGlasgow
(B) 2021-01-31 Think about what's next +WhatsNext
(B) 2021-01-31 Call the IRS
x 2021-02-01 (A) 2021-01-31 Put on spare tire
(B) 2021-02-01 Meet with ENGR491 at 18:00 due:2021-02-02 +ENGR491
```

![sleek1](https://user-images.githubusercontent.com/57228129/106775418-b78a5580-6608-11eb-9983-db7a936f967b.png)
![sleek2](https://user-images.githubusercontent.com/57228129/106775432-bbb67300-6608-11eb-99d2-eda0524013e5.png)

"Go through RELS lectures" is appearing after "Godot project", but that isn't right.

**Comment by ransome1** [comment]
@samuelznewton This example pointed me to a glitch, that is most likely responsible for the behavior. Could you check one of the new binaries here please? https://github.com/ransome1/sleek/releases/tag/v0.8.7

**Comment by samuelznewton** [comment]
That's got it!  Everything is sorted just as I would expect.  Thank you so much for your quick work on this!
