### ISSUE TITLE
Sort Issue – Not Chronologically by due date

### ISSUE THREAD

**Issue by p-beattie** [ransome1/sleek#350]
Hello,
I’m using Linux Mint Cinnamon 20.3.   I installed Sleek via the Software Manager. 
I am experiencing an issue with sorting of todo items in the GUI. 

Using Sleek’s GUI interface, I entered each item to make the sample todo.txt file (below).
I included m/dd/yyyy to each item so I could see due dates immediately.

Contents of todo.txt
```
Drain Pipe in White Room Ceiling 4/1/2022 due:2022-04-01 rec:3m @house
Almaguin News - renew 2/15/2023 due:2023-02-15 rec:y @fin
Dentist May12, 2022 5/12/2022 due:2022-05-12 @personal
Safety Deposit Box  1/1/2023 due:2023-01-01 rec:y @fin
Test Generators 4/1/2022 due:2022-04-01 rec:3m @house
Check Fridge - Water bucket 4/1/2022 due:2022-04-01 rec:2m @house
Virgin Mobile - exp Feb.9, 2023  2/9/2023 due:2023-02-08 rec:y
TFSA, Renew Instr by Feb 20 2/2/2023 due:2023-02-20 rec:y @fin
Township of Machar 8/1/2022 twice/year due:2022-08-01 rec:y @fin
Propane Inspection - 10yr pressure test 2/1/2031 due:2031-02-01 rec:10y @house
```

I can see in Sleek, that due dates and recurrence are recognized for all entries.

Here is the order in which Sleek displays the entries.
```
Drain Pipe in White Room Ceiling 4/1/2022 due:2022-04-01 rec:3m @house
Test Generators 4/1/2022 due:2022-04-01 rec:3m @house
Check Fridge - Water bucket 4/1/2022 due:2022-04-01 rec:2m @house
Township of Machar 8/1/2022 twice/year due:2022-08-01 rec:y @fin
TFSA, Renew Instr by Feb 20 2/2/2023 due:2023-02-20 rec:y @fin
Propane Inspection - 10yr pressure test 2/1/2031 due:2031-02-01 rec:10y @house
Safety Deposit Box  1/1/2023 due:2023-01-01 rec:y @fin
Dentist May12, 2022 5/12/2022 due:2022-05-12 @personal
Virgin Mobile - exp Feb.9, 2023  2/9/2023 due:2023-02-08 rec:y
Almaguin News - renew 2/15/2023 due:2023-02-15 rec:y @fin
```

I expected items to be sorted based on due date.  But that’s not what I see from row 5 onward. 
     2022-08-01, 2023-02-20, 2031-02-01,2023-01-01, 2022-05-12, 2023-02-08.

Reloading with hotkey “.” doesn’t change the order.  Anything else I can do to get chronological sorting by due date?

Regards, and thank you for your efforts.
Paul
Linux Mint 20.3 / Kernel: Linux 5.4.0-105-generic / Architecture: x86-64

**Comment by ransome1** [comment]
Hi @p-beattie . Thanks for reporting this.

Can you check if this behavior is still occuring in this pre-release https://github.com/ransome1/sleek/releases/tag/v1.1.8-rc.1?

**Comment by p-beattie** [comment]
Hi @ransome1 .  Thank you for the quick response.  The sort looks good now.   Best regards, Paul
