### ISSUE TITLE
Project / context selection using keys in autocomplete when creating a new task

### ISSUE THREAD

**Issue by mimmori** [ransome1/sleek#353]
**Is it an actual bug?**
it is a different behavior than the previous version (Sleek 1.1.6) which reduces its ease of use.

**Did you check if the bug has already been reported?**
Yes.

**Describe the bug**
With the latest versions of Sleek, a bug related to the self-completion of projects (+) and contexts (@) has been introduced.
In detail, during the creation of a new task, by typing the + or @ symbol all the projects and contexts are proposed correctly, but their selection is now only possible using the mouse and no longer with the tab and enter keys as before.
Sometimes trying to use the tab and enter keys the selected element is actually inserted but preceded by null.
The Sleek 1.1.6 version is the latest with the correct behavior.

**To Reproduce**
1. Start create new task (Ctrl + N)
2. Write "Sometimes" and add + at the end
3. Press Tab key to move on the element proposed and press enter to insert

**Expected behavior**
The tab key must move the cursor over the elements and the enter key inserts the selected item in the task.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version of sleek: 1.1.8-rc.1
 - Source: Github

**Comment by ransome1** [comment]
@mimmori thanks for pointing it out. I needed to rework the button a bit and missed to add the `href` attribute, which in fact disables the `Enter` function. This is going to be fixed in the next release.

**Comment by ransome1** [comment]
@mimmori could you please check if this still happens in https://github.com/ransome1/sleek/releases/tag/v1.1.8-rc.2?

Thanks!

**Comment by mimmori** [comment]
Problem solved with the latest version released.

As always, very fast.
Thanks!!!

**Comment by mimmori** [comment]
I still found a condition where it is not working properly.

The problem can be observed during the self-completion phase of projects / contexts and you start writing part of the word until only the desired element remains.
In that case, pressing tab and enter the element is inserted preceded by the text null.

**Comment by ransome1** [comment]
I can confirm this, I missed that case during testing. Thanks for checking it so precisely ❤️

**Comment by ransome1** [comment]
@mimmori this should be fixed in https://github.com/ransome1/sleek/releases/tag/v1.1.8-rc.3

**Comment by mimmori** [comment]
confirmed. Thanks
