### ISSUE TITLE
Use as template always add creation date

### ISSUE THREAD

**Issue by mimmori** [ransome1/sleek#354]
**Is it an actual bug?**
Yes, Minor

**Did you check if the bug has already been reported?**
Yes

**Describe the bug**
When you create a new task by taking one as a template, the software always adds the creation date, even if its insertion is globally disabled.

**To Reproduce**
1. Right click on a Task
2. Click on "Use as template"
3. See the presence of creation date

**Expected behavior**
I suggest adding the date, in the pre-filled text, according to the global application setting (default disabled)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version of sleek: 1.1.8-rc.2
 - Source: Github

**Comment by ransome1** [comment]
@mimmori you're right, this features wasn't respecting the default value of `appendCreationDate` yet, which will be changed in the next release.

**Comment by ransome1** [comment]
@mimmori also this should be fixed in https://github.com/ransome1/sleek/releases/tag/v1.1.8-rc.3

**Comment by mimmori** [comment]
confirmed. thanks
