### ISSUE TITLE
The hidden auto-update setting doesn't seem to work

### ISSUE THREAD

**Issue by andrei-a-papou** [ransome1/sleek#355]
**To Reproduce**
Install sleek 1.1.6, add `"autoUpdate":false` to `~/.config/sleek/user-preferences.json`. Sleek will download v1.1.7 then remove the 1.1.6 AppImage.

**Expected behavior**
Auto-update should be skipped (perhaps notify the user of new version, but not download or install it).

**Desktop**
 - OS: Debian 11.3
 - Version of sleek: sleek-1.1.6 and sleek-1.1.7
 - Source: Github, (AppImage)

**Comment by andrei-a-papou** [comment]
Write now I'm working around this by setting the immutable attr to the AppImage file.

**Comment by ransome1** [comment]
The `autoUpdate` option will be disabled per default in future releases. Instead AppImage and MacOS builds will have a dedicated options in settings. It's already included in https://github.com/ransome1/sleek/releases/tag/v1.1.8-rc.4 but cannot be tested yet, as pre-releases are excluded from the auto update function.

**Comment by andrei-a-papou** [comment]
thanks for the info, I'll be happy to test the 1.1.8 release once it's available!

**Comment by andrei-a-papou** [comment]
@ransome1 Seems to be working in latest releases, thank you!
