### ISSUE TITLE
Priority shortcuts stopped working with an upgrade to 1.1.7

### ISSUE THREAD

**Issue by andrei-a-papou** [ransome1/sleek#356]
The Alt-arrow shortcuts to set item priority stopped working. This is on Debian 11.3, sleek v1.1.7 (AppImage, form GitHub).

These shortcuts work fine in v1.1.6. Downgraded for now.

**Comment by ransome1** [comment]
@andrei-a-papou you're right. And right now I'm working on this. To make it more generic for all plattforms the priority shortcuts will change slightly. In future releases you will have to press Alt + Meta (Windows or Command key) and then the priority shortcut.

Shortcuts are always a bit tricky. Can you support me testing them once I push the next pre release?

**Comment by ransome1** [comment]
@andrei-a-papou can be tested in https://github.com/ransome1/sleek/releases/tag/v1.1.8-rc.5

**Comment by Bumpyride** [comment]
@ransome1  Just tested this with the latest v1.1.9 on Win10. It works but not quite as intended.
The new shortcut `WIN`+`ALT`+`DOWN` does open the priority list and the selection with `UP` or `DOWN` works.
Shortcuts `LEFT` or `RIGHT` to remove priority also work. But...  

- Opening the priority list with the shortcut and `DOWN` also inserts a due date, which happens to be 1 day in the past.
- Opening the priority list with the shortcut and `UP` also inserts a due date, which happens to be 1 day in the future.
- Scrolling the priorities up or down also changes the due date up or down by a day.
- Removing the priority `WIN`+`ALT`+`left/right` removes the priority **and** the due date, even if the due date was inserted separately.
- Assigning a priority directly `WIN`+`ALT`+ A-Z works and does not insert a due date but some priority letters collide with other system shortcuts. For example, `WIN`+`ALT`+`D` opens the Windows date/calendar panel instead.
- Shortcuts specifically for the due date, i.e. `CTRL`+`ALT`+...  are ok and work as intended.

I came accross this one while fighting with some other bugs but I will raise separate issues for those.

**Comment by andrei-a-papou** [comment]
@Bumpyride beat me to it, I can confirm everything above on Debian 11.3 (except the Windows calendar shortcut conflict, of course).

I will add that for me personally pressing Super + Alt + A for top priority seems very inconvenient ;( Alt + A can bit done with one hand by placing your thumb on the Alt key and hitting A with the ring finger. For Super + Alt + A you have to put the little finger on the Alt key, which makes it very hard to hit A with any other finger. 

I realize shortcuts are tricky, but is it possible to keep the old Alt shortcuts for priority? Or perhaps a JSON file to let advanced users override shortcuts? That would also solve https://github.com/ransome1/sleek/issues/332

**Comment by andrei-a-papou** [comment]
> Shortcuts are always a bit tricky. Can you support me testing them once I push the next pre release?

@ransome1 Absolutely! And I believe you're doing a very good job usability-wise in general. Which shortcuts are a big part of.

Because of the issue @Bumpyride described above, I have to stick to 1.1.6 for now. 

But you're right, shortcuts can be tricky in JS and across platforms, so I'm more than willing to help test things under Linux in future releases.

**Comment by Bumpyride** [comment]
Feedback based on v1.2.0-rc1: No change. Just FYI since I am logged in anyway...

**Comment by jiggie42** [comment]
I'm a new user, and keyboard shortcuts are certainly a thing that attracted me.  I came here to report this issue..because I did not scroll down the Shortcut page to see that it is indeed listed correctly there!

I would also agree with the original poster, requiring TWO modifier keys is certainly less convenient than one, but I understand they're tricky.  I haven't used it enough to feel as strongly, however.

EXISTING RELATED ISSUE within the built-in Help page (Windows 10, v1.1.9), it does not mention that you must use Win/Super in addition to Alt, as shown below

Thanks for the otherwise great little app!

![image](https://user-images.githubusercontent.com/9276385/172039828-b20ff3e5-af22-476a-94e6-f38d9880cd31.png)

**Comment by ransome1** [comment]
@jiggie42 @Bumpyride @andrei-a-papou hey guys, I'm afraid there will be changes to the shortcuts again, as I'm aiming for a setup that is consistant on all OS. Can I ask you guys, to join the conversation here: https://github.com/ransome1/sleek/issues/407

There is a pre-release (v1.3.1-rc.1) you can download and help me to improve.

**Comment by ransome1** [comment]
Please let me close here, in order to clean up the issue list. The documentation on the new keyboard shortcuts will be done, once #407 is fixed.
