### ISSUE TITLE
Open .md files instead of .txt files

### ISSUE THREAD

**Issue by roguefury** [ransome1/sleek#36]
Will it be possible to open .md files instead of .txt files?

**Comment by ransome1** [comment]
Hello @roguefury, I haven't thought about this. What would be the benefit of a markdown file?

**Comment by roguefury** [comment]
Hi,

So, I've been working on a workflow that connects with Obsidian (the knowledge/note taking) platform, and todo.txt files.  Obsidian views .md files, not .txt files.  Operationally, both are txt files.  SwiftoDo on iOS allows for both .txt and .md files to be used.

I'd like to store my todo file in the same folder as my Obsidian content.  This would allow me to edit the todo file in both Obsidian and Sleek.

So, it's not that I'm expecting markdown translation in sleek, rather I'd like to view the same file in several locations (Sleek, SwiftoDo, and Obsidian)

**Comment by ransome1** [comment]
Ok, I see. That sould not be a problem, I will add a basic .md support to the next release.

**Comment by roguefury** [comment]
Excellent!  Thank you!

**Comment by ransome1** [comment]
@roguefury The builds for Snap and Flathub are being generated right now and should be live within the next 30 minutes.

But also updated the binaries: https://github.com/ransome1/sleek/releases/tag/v0.8.7

Let me know if the .md support is working like expected.

**Comment by roguefury** [comment]
Ok, thanks.  I'll get back to it when I have a moment.

**Comment by roguefury** [comment]
Hi,

Sorry, I'm not super technical, but I do not see a MacOS build on the release page for 0.8.7.  Where can I find that?

**Comment by ransome1** [comment]
Hi @roguefury, sorry, I though you were on Linux, so I didn't build it. But tomorrow I will build the DMG file on my Mac and upload it.

**Comment by roguefury** [comment]
Thank you!

**Comment by ransome1** [comment]
@roguefury , the dmg has been added to the release page. Let me know, if you're having problems with the markdown files. I gave a brief test and it seems to work well.

**Comment by roguefury** [comment]
@ransome1 It works perfectly!  Awesome!  I can now see the file in both Obsidian and Sleek. 

I'm going to post a note over on [Obsidian Forums](https://forum.obsidian.md/)  about Sleek as another option for task management.

**Comment by ransome1** [comment]
Glad to hear :) I might also take a look at Obsidian, looks interesting.

**Comment by codeinabox** [comment]
I too am using Obsidian and I've tried opening my todo list though I've noticed it doesn't handle the Markdown check boxes ie 

```md
- [ ] Task
```

**Comment by ransome1** [comment]
> I too am using Obsidian and I've tried opening my todo list though I've noticed it doesn't handle the Markdown check boxes ie
> 
> ```lisp
> - [ ] Task
> ```

I'm afraid this has never been the scope of sleek. This app is based on the todo.txt syntax, which is not affiliated with markdown. Although sleek uses a markdown parser and is capable of opening .md files, it does not fully support markdown.

What would have been your expectations for sleek, when it opens an .md file, which inclludes `- [ ]`?
