### ISSUE TITLE
Link to and open local files by recognising system file protocols

### ISSUE THREAD

**Issue by Bumpyride** [ransome1/sleek#360]
**Did you check if a similar feature request has already been reported?**
I did check and relevant comments/comparisons are included below

**Is your feature request related to a problem? Please describe.**
Not related to a problem

**Describe the solution you'd like**
Sleek already supports the `HTTP/HTTPS` and `sendto:` protocols automatically, so that including a URL string or an email address in the todo text line will then show the link symbol next to it. Obviously, clicking on the symbol then opens the web page in the browser or a new email.

It would be really practical if in addition, Sleek could be extended to recognise something like a `file:` protocol where the link then opens a local file with its associated program (according to file ext). I imagine that the implementation could follow along the lines of the `due:` or `rec:` syntax, perhaps something like _file:c:\mydir\myfile.pdf_ or _file:"c:\mydir\file name with spaces.txt"_, or _file:/home/me/myfile.pdf_ under Linux/MacOS. As a bonus, if the file does not exist, activating the link could open the associated program with a blank document.

This enhancement would probably also take care of feature request [Notes for tasks #338](https://github.com/ransome1/sleek/issues/338) without using exernal dependencies. A note is simply a file linked to from Sleek.

**Describe alternatives you've considered**
A good example would be [Typora](https://typora.io/), a Markdown editor.  
Its syntax uses angle brackets \<file://myfile.ext\> or links [](file://file with spaces.ext).

**Comment by mimmori** [comment]
+1

**Comment by mshuflin** [comment]
+1 for this. Another example is Joplin, which uses this syntax joplin://x-callback-url/openNote?id=x1234567a

**Comment by comminutus** [comment]
+1 for this, as @mshuflin mentioned I'd also use it for joplin links.

**Comment by ransome1** [comment]
Unfortunately I don't have enough time to work on this at the moment. If any of you guys have knowledge in JavaScript and especially regular expressions, you can take a look at the library sleek uses, that converts the markdown into HTML. It's called [marked.js](https://marked.js.org/) and has built in extensibility. If someone can figure out, how to extend marked.js to support prefixes as `file` or `joplin`, I am happy to implement the solution.

**Comment by Bumpyride** [comment]
I just went under the hood of [draw.io](https://www.diagrams.net/) for a similiar use case. It turns out that it may be security settings preventing access to local file system. I'll fork this repo and see what I can do.
BTW, thanks for the recent updates and a great little program!

**Comment by mshuflin** [comment]
Still an issue

**Comment by mshuflin** [comment]
in Sleek 1.x, we could use markdown to make this happen, for example:

`[link to note](joplin://x-callback-url/openNote?id=x1234567a)`

In 2.x it appears it is not implemented yet

**Comment by mshuflin** [comment]
I wonder, would this and [#563](https://github.com/ransome1/sleek/issues/563) both be solved by implementing `marked` as mentioned [here](https://github.com/ransome1/sleek/discussions/562#discussioncomment-7458326)?

**Comment by ransome1** [comment]
> I wonder, would this and [#563](https://github.com/ransome1/sleek/issues/563) both be solved by implementing `marked` as mentioned [here](https://github.com/ransome1/sleek/discussions/562#discussioncomment-7458326)?

@mshuflin I think it does solve both. I already tried to implemented but had to realize, that the way the we are creating the rows in sleek is not compatible with how marked works. It will take quite some time to figure this out. That's why I decided to dedicate my time on other tasks, mostly bugfixing and refactoring. I will keep you guys posted, once this topic is being picked up again.

**Comment by ransome1** [comment]
@mshuflin @comminutus @Bumpyride @mimmori, the most recent pre-release now incorporates link detection and offers basic support for protocols beyond HTTPS.

Conventional links like `http://www.test.com` are now recognized, along with Markdown links such as `<http://www.test.com> or [Test](https://www.test.com)`.

Links to the file system function should work like `<file:///Users/USERNAME/Desktop/file.txt>`. The same applies to Joplin links: `<joplin://x-callback-url/openNote?id=x1234567a>`.

Further adjustments might be made to support different protocol links without requiring brackets or full Markdown syntax in upcoming releases.

Feel free to experiment with it and share your feedback on what works and what doesn't: https://github.com/ransome1/sleek/releases/tag/v2.0.9-rc.1

**Comment by mshuflin** [comment]
thanks for implementing this. Based on my testing,

what works:
- markdown formatting for `**bold**` and `_italics_`
- Conventional links
- Markdown links
- Joplin links (if enclosed by `< >`)

what does not work:
 - Joplin links in markdown links (e.g. `[test](<joplin://x-callback-url/openNote?id=x1234567a>)` nor  `[test](joplin://x-callback-url/openNote?id=x1234567a) `. In this case it looks like a link but does not open anything
 
Overall, I think it is working as expected. 

(in case it matters, Macos sonoma (M2), sleek v2.0.9-rc.1)

**Comment by Bumpyride** [comment]
Thanks for implementing from me, too. I can pretty much confirm what @mshuflin discovered, except that I didn't test Markdown text formatting.

I focused on the original issue, namely linking to local files, and I could only get the angle brackets `"<>"` with the "file://" protocol to work (under Windows 10), for example: `<file://C:\mydir\myfile.pdf>`
BTW, it does not seem to matter if two or three forward slashes follow the protocol.

However, Markdown links like `[My file](file://C:\mydir\myfile.pdf)` do not work with local files.
It will show "My file" as a link label (standard Markdown) but will not open the file.
Links to local files are now possible but it would be nice to be able to display a friendly label for the link.

Local file names that include spaces, for example `"c:\mydir\file name with spaces.txt"` do not work, regardless of protocol or link syntax, with or without quotes. I tried all sorts of variations.

Other protocols, like joplin://, cintanotes://, etc do work, provided the link is enclosed in angle brackets.

**Comment by skostojohn** [comment]
I am having issues with links to local files (e.g. `<file:///home/scott/file.txt>` - they are recognized as links but don't seem to do anything when clicked.  Using v2.0.14.  

Web links and links to other apps (Obsidian) seem to work fine.

Anyone have ideas as to what I might be doing wrong, or seeing the same behavior?

Thanks!
Scott
