### ISSUE TITLE
Dark theme text unreadable

### ISSUE THREAD

**Issue by mshuflin** [ransome1/sleek#361]
**Is it an actual bug?**
Yes
**Did you check if the bug has already been reported?**
Yes

**Describe the bug**
The text is unreadable in dark mode when adding a new task. It is dark grey, nearly black.

**To Reproduce**

1. turn on dark mode
2. press N to start adding a new task

**Expected behavior**
The text should be white

**Screenshots**
<img width="796" alt="Screen Shot 2022-04-07 at 8 03 41 AM" src="https://user-images.githubusercontent.com/53985056/162094659-2f6d9856-49cf-488a-9959-95dab783c4b9.png">

**Desktop (please complete the following information):**
 - OS: MacOS 12.21
 - Version of sleek: 1.1.8
 - Source: Github

**Comment by ransome1** [comment]
@mshuflin could you please take a look at https://github.com/ransome1/sleek/releases/tag/v1.1.9 if this fixes it for you?

Thanks for reporting it.

**Comment by mshuflin** [comment]
@ransome1 It is working as expected now. Thanks for fixing that!
