### ISSUE TITLE
Restoring completed task does not restore priority

### ISSUE THREAD

**Issue by Bumpyride** [ransome1/sleek#363]
**Did you check if the bug has already been reported?** I did...

**Describe the bug**
Marking a prioritised task as completed will remove the task from the active list in that prioritiy's group and convert the priority into a `pri:` control. With completed tasks set to visible, unmarking the task will restore it but without priority. The pri: control remains in the task text.

**To Reproduce**
1. Create a new task and assign a priority letter
2. Mark the task as completed
3. Unmark the task as not completed (incidentally, the tooltip on the marker box for completed tasks says "_In progress_".)
4. The task is restored without priority

**Do you see any error entries in sleeks developer tools?**
No errors, only Success and Info messages

**Expected behavior**
Task is restored to its original priority group and the `pri:[A-Z]` control string in the task text is removed.
Oh, while on the subject... Feature request: Ability to restore recurring tasks to their state with dates before having been marked as done - a bit like an "Undo" for recurring tasks...

**Desktop (please complete the following information):**
Sleek v.1.1.9 from Github Releases on Win10x64

**Comment by andrei-a-papou** [comment]
Same here, sleek 1.1.6 and upwards, Debian 11.3

**Comment by ransome1** [comment]
@Bumpyride @andrei-a-papou this is not a bug, it's a non standard todo.txt feature that hasn't been implemented yet. It is part of this pre release though: https://github.com/ransome1/sleek/releases/tag/v1.2.0-rc.1

Give it some testing if you find the time.

**Comment by GabrielMPhi** [comment]
> @Bumpyride @andrei-a-papou this is not a bug, it's a non standard todo.txt feature (or rather an enhancement of an already implemented feature) that hasn't been implemented yet. It is part of this pre release though: https://github.com/ransome1/sleek/releases/tag/v1.2.0-rc.1
> 
> Give it some testing if you find the time.

Good to know. I was expecting it to restore as is, but it's good to know that it's not a bug. Thanks. Still, It would be a good enhancement.

**Comment by Bumpyride** [comment]
@ransome1 @andrei-a-papou I finally managed to get around to test with v1.2.0-rc1

Heads up - this issue is **RESOLVED**!

I tried with several combinations and everything works as intended. Surprise bonus - restoring recurring tasks works, too. I thought that would have to be a separate enhancement request, due to the additional complexity.

**Comment by andrei-a-papou** [comment]
Works for me as well, thanks, @ransome1!
