### ISSUE TITLE
Enable keyboard navigation in tasklist even with filter side panel open

### ISSUE THREAD

**Issue by Bumpyride** [ransome1/sleek#364]
**Did you check if a similar feature request has already been reported?** Found nothing related

**Is your feature request related to a problem? Please describe.**
Open filter panel forces use of mouse in task list and slows down navigation
At present, the side panels take over the focus and up/down navigation in the tasklist is suspended.

**Describe the solution you'd like**
Keyboard shortcuts to switch between options/filter side panels and the task list, with up/down arrow navigation enabled.
BTW, closing the side panel restores normal keyboard navigation in the tasklist.

**Describe alternatives you've considered**
Tried with `TAB` and `SHIFT`+`TAB`.

**Comment by ransome1** [comment]
@Bumpyride I enabled the arrow up and down keys while the drawer is open. For navigation within the drawer you can use (Shift) Tab und Arrow left and right. Please feel free to give it proper testing: https://github.com/ransome1/sleek/releases/tag/v1.2.0-rc.1

**Comment by Bumpyride** [comment]
@ransome1 I tried it out and it works, sort-off.

While in the task list, and with the filters panel closed, pressing `CTRL`+`B` will open the panel and TAB and SHIFT+TAB, as well as Left and Right Arrow navigation works as expected, although a bit awkward when there are many Project and Context elements and one has to traverse through each one. The panel is now open and `UP` or `DOWN` will immediately focus the task list and allow normal scrolling. So far so good.

And now it gets interesting: I am in the task list, happily scrolling up and down, creating and editing tasks and then I press SHIFT+TAB to get back to the panel. Instead the cursor scrolls one task up in the task list. However, if I keep scrolling with TAB or SHIFT+TAB to either end of the list, eventually I will get back to the panel. Only by closing and reopening the filter panel (`CTRL`+`B` twice) can I go there directly.

This is more of a general usability/UX issue since the actual functionality works, although not in an ideal way.
Hope this helps.
