### ISSUE TITLE
Cannot quit on macOS

### ISSUE THREAD

**Issue by MeneDev** [ransome1/sleek#366]
**Describe the bug**
When I press quit though any way (menu, cmd+q, right click on dock) only the window closes. I always have to force quite the application, e.g. when shutting down the system.

**To Reproduce**
1. Open application
2. Try to quit application

**Do you see any error entries in sleeks developer tools?**
No

**Expected behavior**
Application should quit

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 12.1
 - Version of sleek 1.1.9
 - Source: brew

**Comment by ransome1** [comment]
@MeneDev thanks for reporting this. When this happens, is sleek responsive and do you see a menu item named `Quit`? I just double checked the brew installation and cannot reporoduce this. Command and Q closes sleek on my side.

**Comment by MeneDev** [comment]
Yes, sleek is responsive and still the focussed application (if that's how it's called on macOS; I can still see the sleek menu on the top of the screen)
I looked a bit further and it is the "Minimize to tray bar" option. When this is enabled, quitting will only close the window, not quit the application. I've disabled this now and that fixes it for me. (i.e. my system shuts down when I tell it to).
For me the expected behavior is: pressing the x on the window frame minimizes to tray, right-click on tray/menu -> quit will quit the application (but that's debatable) and when the system want to shut down it also quits the application.

**Comment by ransome1** [comment]
Generally asking, what is the expected behavior of a MacOS app that is being put in tray mode? Is there suppose to be a dock icon and a menu bar?

**Comment by mazimmer** [comment]
if it's in "tray mode" then there's supposed to be no dock icon on macOS - it's then a "menu bar item". When it shows its window, however, there are  examples of apps showing a menu bar and others that don't; depending on the usage. In case of sleek, I'd expect a menu bar whenever the window is visible.

**Comment by mazimmer** [comment]
no, 

> > I'd expect a menu bar whenever the window is visible.
> 
> In this case, with `menu bar` you mean a the `dock`, right?

No, I meant to write "I'd expect the menu to show whenever the window is visible", see attached image.
![Screenshot 2022-04-12 at 19 03 23](https://user-images.githubusercontent.com/4983700/163016135-cc30e734-a2c6-4f1f-b732-09507ee27cca.png)

Optionally, the icon could also show in the dock as long as the windows is visible, but both should be hidden when the window is hidden.

**Comment by ransome1** [comment]
@mazimmer @MeneDev could you please check if the tray behavior is now working as expected on MacOS? https://github.com/ransome1/sleek/releases/tag/v1.2.0-rc.3

**Comment by mazimmer** [comment]
@ransome1, closing the window makes the dock icon disappear, clicking the menu bar icon shows the window, dock icon and menu bar; so good for me

**Comment by MeneDev** [comment]
Also works for me!
