### ISSUE TITLE
Short cut for "new todo" is Ctrl-N instead of Cmd-N on macOS

### ISSUE THREAD

**Issue by mazimmer** [ransome1/sleek#367]
**Description**
On macOS, when typing "Cmd-N", nothing happens. "Ctrl-N" produces the "new todo" window.

**To Reproduce**
See description.

**Do you see any error entries in sleeks developer tools?**
No errors - Cmd-N is ignored

**Expected behavior**
Cmd-N opens the "new todo" modal.

**Desktop (please complete the following information):**
 - OS: macOS 10.15 and 11
 - any version of sleek so far
 - Source: Github

**Comment by ransome1** [comment]
@mazimmer the actual shortcut for opening the new todo window is just `N`. So technically it's a bug that `Ctrl + N` opens the window ;)

**Comment by ransome1** [comment]
From 2.x on the shortcut will change to Ctrl/Cmd + N
