### ISSUE TITLE
Sort by: Threshold date

### ISSUE THREAD

**Issue by amariusz** [ransome1/sleek#368]
**Did you check if a similar feature request has already been reported?**
I've suggested it few months ago in comment:
https://github.com/ransome1/sleek/issues/193#issuecomment-878349150
That issue is now closed.

**Is your feature request related to a problem? Please describe.**
I'd like to be able to order tasks by their availablity date. For example imagine there are some tasks which became available week ago, few days ago and today. I'd like to be able to sort the list so that tasks that become available today are shown above those that became available week ago. 

Note: I'm using `t:` and `rec:`, not `due:`.

**Describe the solution you'd like**
Add item `Threshold` to `Sort by` list in settings which sorts by `t:`. Probably the same logic as sorting by `due:` but inverted order.
Items without `t:` could be considered as if they had `t:` in distant future. They should be present at the top of the list. This is SimpleTask's behaviour.

**Describe alternatives you've considered**
One idea that comes to mind - keep single sort option but rename it from 'Due' to 'Due / threshold'. Add toggle option below "Sort by threshold instead of due".
In general it's possible to sort by threshold and then by due but in most cases it's probably not useful. Items should be grouped either by due (current Sleeks behaviour) or by threshold, but not both.

Other suggestion to consider from my previous comment (but not as useful ) - add supplemental sort option:

> Sort by: Threshold date in future
> meaning e.g. 0 for current entries, 1 for future entries

The idea here is to support a case with `Threshold date in the future` toggle set to ON. Without this option future tasks will be placed in the beginning of the list showing the most distant ones first. With this sorting option placed above `Threshold` option the resulting list would be more practical to use:
```
    - task1 <tasks without t starts here>
    - task2 
    - task3 t:today <available tasks start here>
    - task4 t:few days ago
    - task5 t:week ago    
    - task6 t:month from now <future tasks start here>
    - task7 t:in a few days
    - task8 t:tomorrow
```
Thanks for a great tool!

**Comment by aubreyz** [comment]
+1

**Comment by rsf20** [comment]
+1

**Comment by ransome1** [comment]
A first draft of this has been added to the latest developer preview of 2.0. I think we should keep this open.

**Comment by ransome1** [comment]
@amariusz @aubreyz @rsf20 @aisbergde can I ask you to check out the latest developer preview and see if this is working as expected? https://github.com/ransome1/sleek/releases/tag/v2.0.0-dev6

Please backup your data before playing around with it.

**Comment by amariusz** [comment]
Wow! I wasn't aware Sleek 2 preview is available to download. It looks very good!

Thanks for adding sorting by threshold feature. It's already functional. Based on my usage of SimpleTask some comments about what could be added come to my mind :
- Another sorting option "Threshold date in future" as mentioned in the description of this issue.
- Option to hide tasks in future ("Threshold date in the future" from Sleek 1 or "Show tasks with threshold date in future" in SimpleTask)

Also some "nice to haves" loosely related to this issue:
- Option to put tasks without t: at the top to the list. Sleek places them at the bottom. This would be more general option that applies to sorting by due date/contexts/projects etc.
- Another sorting option "Alphabetical" (as in SimpleTask)

Thanks again!

**Comment by amariusz** [comment]
Update: I've noticed that ticking off recurring items often leads to "No todos available". But that's probably some unrelated bug in preview.

**Comment by ransome1** [comment]
> Update: I've noticed that ticking off recurring items often leads to "No todos available". But that's probably some unrelated bug in preview.

Yep, that I also saw and I fixed it already. It should be available in the next developer preview.

**Comment by ransome1** [comment]
> Wow! I wasn't aware Sleek 2 preview is available to download. It looks very good!
> 
> Thanks for adding sorting by threshold feature. It's already functional. Based on my usage of SimpleTask some comments about what could be added come to my mind :
> 
>     * Another sorting option "Threshold date in future" as mentioned in the description of this issue.
> 
>     * Option to hide tasks in future ("Threshold date in the future" from Sleek 1 or "Show tasks with threshold date in future" in SimpleTask)
> 
> 
> Also some "nice to haves" loosely related to this issue:
> 
>     * Option to put tasks without t: at the top to the list. Sleek places them at the bottom. This would be more general option that applies to sorting by due date/contexts/projects etc.
> 
>     * Another sorting option "Alphabetical" (as in SimpleTask)
> 
> 
> Thanks again!

I will look into this soon. Both, the first two, are already features in sleek 1.3.1 and should be part of 2.0 as well, of course. I'll let you know.

**Comment by ransome1** [comment]
I added a filter to include or exclude todos with threshold dates in the future.

![Image](https://github.com/ransome1/sleek/assets/11188741/61b627f6-0b0c-44db-9f7c-2817c5f21497)

Over the course of this thread there are now many additional requests. I think it makes sense to collect transfer those tasks to a separate request and close this one. Because the initial `main requirement` is implemented as far as I see it.

**Comment by ransome1** [comment]
Also `todos with due date in the future` is now available as a setting: https://github.com/ransome1/sleek/releases/tag/v2.0.0-dev9

As the initial requirement of this request has been solved, I would like to close here. All additional requirements should have their own issues.

**Comment by amariusz** [comment]
Thanks, that's great! It seems to work fine.

I'm not sure about the utility of `todos with due date in the future`. I imagine it could be useful when 'due date' is used as 'do date' (so as a way to plan execution on specific day). Otherwise it doesn't seem like good productivity practice ;)

I'll create separate issue for sorting.
