### ISSUE TITLE
Sort by name / text without tags

### ISSUE THREAD

**Issue by jcz1** [ransome1/sleek#369]
Hello.

I think there is no way to sort by name (text without tags) of todo record. Is it possible to add it?

P.S. Thanks for sleek, great sw :-)

![sleek-sort](https://user-images.githubusercontent.com/10832330/163708135-630cbc1b-43a4-4285-975f-2b9df4e11e6c.png)

**Comment by mimmori** [comment]
+1

**Comment by mashkioya** [comment]
+1
