### ISSUE TITLE
Cannot build on linux. No build target: `build:linux`

### ISSUE THREAD

**Issue by skamansam** [ransome1/sleek#372]
**Is it an actual bug?**
Yes

**Did you check if the bug has already been reported?**
Yes

**Describe the bug**
Teh documentaion says to use `build:linux` on linux, but there is no such script listed in the `packages.json` file.

**To Reproduce**
1. Open the README and scroll to the section "Build sleek from source code"
2. Clone the repo and follow instructions in the README.

**Do you see any error entries in sleeks developer tools?**
No

**Expected behavior**
The command should run, and a comiled app should be built.

**Screenshots**
```
#> build:linux
yarn run v1.22.10
warning ../../package.json: No license field
error Command "build:linux" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Desktop (please complete the following information):**
 - OS:Fedora 35
 - Version of sleek: `master` branch
 - Source: Github

**Comment by metawindow** [comment]
+1 Ditto on Ubuntu 22.04 LTS, not surprisingly since there really is no build:linux script. Also, for anyone who barely touches nodejs, it would be nice if the readme mentioned the "yarn install --devDependencies" step.

**Comment by ransome1** [comment]
You're right. At some point the script had been removed from the package.json. I will include the necessary scrips with the next push.

As a workaround please add the script manually in the script section
`"build:linux": "yarn build:css && yarn build:pegjs && electron-builder -l --publish never",`

Or check this commit for reference: https://github.com/ransome1/sleek/blob/bb98fa6ec8a343270f7aef86b85dc6c49f8c390f/package.json

@metawindow what do you mean with devDependencies step?

**Comment by ransome1** [comment]
The scripts have been readded to `package.json` and can be used as stated in the readme file: https://github.com/ransome1/sleek/tree/master
