### ISSUE TITLE
User interface not working in Windows 21h2

### ISSUE THREAD

**Issue by comicsserg** [ransome1/sleek#373]
**To Reproduce**
1. Install the app from Microsoft Store on windows 21h2
2. Start the app
3. Only side buttons are visible but not working
4. Unable to create or use the app
5. trying hotkeys also not working

Open Developer mode with Ctrl + Shift + I
The only error visible there in the Console is:
Uncaught (in promise) Error: Error invoking remote method 'userData': No handler registered for 'userData'

When clicking on the buttons no new error comes is triggered

**Expected behavior**
A working app

**Screenshots**
![sleek_cp6907wXWj](https://user-images.githubusercontent.com/63783506/167578187-d72f3198-5fdd-4ac0-9df2-19e1e24a51a2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 21h2
 - Version of sleek 1.1.9.0
 - Source: Windows Store

**Comment by comicsserg** [comment]
Just did a small test: removed the 1.1.9 and installed version 1.1.4. And version 1.1.4 is working on the same computer

**Comment by DmDrMos** [comment]
The same situation in the Windows 11 21H2 with downloaded distributive from Microsoft Store.

**Comment by ransome1** [comment]
@comicsserg @DmDrMos sorry for checking in so late.

I only have access to a Windows 11 VM. Here I do have access to the Windows app store and I just installed the currently available sleek v1.2.7 (1.3.0 is currently in review and should be available too soon, btw).

I am able to start this release and the only issues I can see are interface problems. Two icons are missing. 

But unfortunately I cannot reproduce your initial issue. Can I ask you guys to install 1.2.7 from the store and re-check it? After starting sleek, please double check in `?` that 1.2.7 is installed.

**Comment by ransome1** [comment]
@comicsserg @DmDrMos 1.3.0 should be available in the app store as well by now. Any improvements on your sides?
