### ISSUE TITLE
Sleek Repeat From Due

### ISSUE THREAD

**Issue by nutnutwin** [ransome1/sleek#375]
Is it possible to repeat(Recurrence ) from Due Date, rather than Compelete Date? 

*If your proposal is more a rough idea than a precise description of a feature, please consider starting a discussion instead: Currently it is possible to have recurrent task from complete date
for example if I set due date to 0509(recurrence by day), and compelete on 0510, the next date would be 0511

**Did you check if a similar feature request has already been reported?**
Yes

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
sometimes I just like to have tasks repeat from due date
in previous case the new occurence should be from 0510(one day after current due)

**Describe alternatives you've considered**
nothing specific

**Comment by zerodat** [comment]
Yes, I think what you want is the "strict" recurrence "rec:+1d" which will make the next due date be computed relative to the previous due date, not the completion date.  See [Recurring todos (rec:) · ransome1/sleek Wiki](https://github.com/ransome1/sleek/wiki/Recurring-todos-(rec:)) for more explanation.

**Comment by nutnutwin** [comment]
@zerodat 
Hi, thank you for your reply. 
I tried and yes it worked. 
only problem: Recurring from Completeion(Default) and Strict Mode Cannot be told from GUI without clicking on the task
a small problem though

Thank you so much!
