### ISSUE TITLE
Sleek says it archives to done.txt, but actually archives to todo_done.txt

### ISSUE THREAD

**Issue by dragos240** [ransome1/sleek#378]
**Is it an actual bug?**
Yes

**Did you check if the bug has already been reported?**
Yes

**Describe the bug**
Sleek says it archives to `done.txt`, but actually archives to `todo_done.txt`

**To Reproduce**
1. Create a task
2. Complete the task
3. Archive the task, it will say it will write the task in `done.txt`
4. See that it in fact writes to `todo_done.txt`

**Do you see any error entries in sleeks developer tools?**
No errors as far as I can see

**Expected behavior**
`done.txt` was written to instead of `todo_done.txt`

**Screenshots**
Not applicable.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version of sleek 1.1.9
 - Source: Github

**Comment by ransome1** [comment]
@dragos240 In fact it archives to `NAMEOFYOURTODOFILE`_done.txt, so I will need to add some dynamic wording here. Thanks for pointing it out.

**Comment by nogasgofast** [comment]
I ran into this issue as well.

Personally I use done.txt, so it would really be great if we could change this as a setting. I expect there are a number of people that use todo.txt because there are a lot of options when it comes to integrating it on different platforms. But if this is a static setting it sort of hamstrings that compatibility. As done files are not really a part of the spec. 

But it's not really a show stopper for me. I use sleek because it's text is slightly bigger and easier to read.

**Comment by durgaswaroop** [comment]
@ransome1, In my case, no file is created. It says it moves to `done.txt`. It removes all the completed tasks from the todo.txt file, but no file is created anywhere. I searched the entire file system, but don't see any new `.txt` files created. Right now, it seems like those tasks are just gone. Is there a way to figure out where they got stored, if at all?

I am on Windows 10.

**Comment by ransome1** [comment]
I can't confirm this. I downloaded 1.2.9 from GitHub and the done.txt file being created in the same directory in which the actual todo file is located. 

Can you please check the developer console, if there are any errors related to this? Press the alt key once and the sun menu will appear. In there click on About and Toggle developer tools.

**Comment by durgaswaroop** [comment]
Looked at the developer console, but I do not see any errors in the console tab. But there is no log mentioning that a new file is being created, though.

**Comment by ransome1** [comment]
I assume the issue is the name of your folder, which contains a period. Maybe this breaks something on windows. I'll look into it tomorrow. 

Can you please try the rename the directory and remove the period character. I'm wondering if the issue would still occur.

**Comment by durgaswaroop** [comment]
Tried without the period in the name. It is working now! Windows doesn't seem to have any problem with the folder. Does the issue come from Javascript?

Also, is there anyway to get the completed todos that failed to get archived?

**Comment by durgaswaroop** [comment]
Looking at the code, I see this line is the cause. It is replacing the name in the entire file path string instead of doing just the filename. 
https://github.com/ransome1/sleek/blob/aad500c0d727294f2be0579b2a76e27394c9e291/src/js/helper.mjs#L169

**Comment by durgaswaroop** [comment]
I went ahead and created the PR. You can take a look - https://github.com/ransome1/sleek/pull/446

**Comment by ransome1** [comment]
@durgaswaroop amazing, thank you so much :) I'll take a look at it as soon as I am on a computer!
