### ISSUE TITLE
Drag & Drop E-Mail message does not show correct link

### ISSUE THREAD

**Issue by abo629** [ransome1/sleek#385]
<img width="459" alt="grafik" src="https://user-images.githubusercontent.com/106948261/172102969-c6ce9b6f-dad0-407b-8896-8a198925f99c.png">

**Comment by ransome1** [comment]
Hi @abo629. Generally thanks for your input, but I think this is nothing I would actually regard a bug report. Feel free to create a proper one, otherwise I'm going to close here.
