### ISSUE TITLE
Uncaught Exception TypeError when opening from the tray and minimizing

### ISSUE THREAD

**Issue by ChongChengAC** [ransome1/sleek#389]
**Describe the bug**
When I open it from the tray, I get the error `Cannot read properties of undefined (reading 'show')`, and the window contents won't load until I click OK. After clicking OK, the window content can be displayed normally. 

When I use the close button to minimize the window, I get the error `Cannot read properties of undefined (reading 'hide')`. Minimizing the window with the minimize button will not report an error.

**To Reproduce**
1, Launch sleek.
2. Press close button.
3. Open from tray.

**Do you see any error entries in sleeks developer tools?**
Yes:
![image](https://user-images.githubusercontent.com/63496547/173569676-df566513-f328-49c7-9247-73b1e0fbbf26.png)

**Expected behavior**
When opening sleek from the tray or minimizing the sleek window, there is no pop-up error

**Screenshots**
Opening from tray:
![image](https://user-images.githubusercontent.com/63496547/173570115-148dd84c-10f6-451f-871c-078d63fde3f5.png)

Minimizing via close button:
![image](https://user-images.githubusercontent.com/63496547/173568983-1a3584ff-f58d-4ac3-996a-3c617509549a.png)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux Xfce
 - Version of sleek 1.2.1-1
 - Source: Arch User Repository

**Comment by 5TDg9** [comment]
Same error here on a windows machine...

* OS: win 10
* Version:  sleek 1.2.1
* source: github

Error only appears when "minimize to tray" is activated in settings.

**Comment by emilBeBri** [comment]
affects me, too.
*meta*: when you see a bug that affects you too, do you write it like this in the comments, or do you only subscribe, or maybe give it a like? What is the norm?  Please help a newbie out! :)

**Comment by speedery** [comment]
the same error also.
OS: ubuntu 22.04
Version: sleek 1.2.0
source: snap store

**Comment by buscon** [comment]
Same error here:
OS: Mint 21 (it was the same on Mint 20.3)
Version: sleek 1.2.1
source: github
I started to see this error since version 1.2

**Comment by warmwaffles** [comment]
I'm also encountering this.

OS: Archlinux
WM: bspwm
Version: v1.2.1

**Comment by MostHated** [comment]
Getting this as well:

OS: Pop_OS
WM: Mutter
Version: v1.2.1

**Comment by p-beattie** [comment]
OS: Linux Mint 20.3
Sleek v.1.2.1  / Setting: [Minimize to the Tray Bar] = ON

Minimize Sleek -   results in Exception
![Minimize_Sleek_to_Tray_bar](https://user-images.githubusercontent.com/102430007/192154463-91d51b56-6521-493a-a055-442275622e35.png)
Restore from Tray bar - results in Exception
![Restore_Sleek(running)_from_Tray](https://user-images.githubusercontent.com/102430007/192154483-587a89b7-4ed0-4724-945d-5b3ab46d6f3c.png)

When I change Sleek Setting: [Minimize to the Tray Bar] => OFF
the Exception errors do not occur.

Regards,
Paul

**Comment by warmwaffles** [comment]
> When I change Sleek Setting: [Minimize to the Tray Bar] => OFF
> the Exception errors do not occur.

Same thing here.

**Comment by alexgarel** [comment]
This seems a bug from flatpak packaging. I had the bug and switch to snap  https://snapcraft.io/sleek and it works.

**Comment by warmwaffles** [comment]
Version I am running is from the [AUR](https://aur.archlinux.org/packages/sleek) builds from source.

**Comment by alexgarel** [comment]
> This seems a bug from flatpak packaging. I had the bug and switch to snap https://snapcraft.io/sleek and it works.

Sorry I was wrong, I got the issue on snap as well :sweat:  (even worst on snap, messages are not readable…)

**Comment by ransome1** [comment]
@alexgarel @warmwaffles @emilBeBri @5TDg9 @buscon unfortunately I don't have access to a Windows or Linux system in order to reproduce this issue. Though I found a bug, that might cause this behavior. Can you guys please take a quick look at this pre-release and give me a feedback if the issue still occurs on Windows and Linux systems? https://github.com/ransome1/sleek/releases/tag/v1.2.4-rc.2

**Comment by alexgarel** [comment]
@ransome1 indeed I tested and it seems ok for me.

**Comment by warmwaffles** [comment]
@ransome1 Thanks a ton for looking into this.

**Comment by ransome1** [comment]
> @ransome1 Thanks a ton for looking into this.

You're very welcome. 

The AUR update will take some time though as I currently don't have access to my Arch machine and my Mac M1 doesn't support VirtualBox anymore :(

**Comment by warmwaffles** [comment]
@ransome1 I haven't figured out how to send patch requests for an AUR package, otherwise, I'd just send it.

**Comment by ransome1** [comment]
If you give me your username on AUR, I can add you as co-maintainer.

You would then need to 
1. checkout the repo and pull it to your local machine: https://aur.archlinux.org/sleek.git
2. enter the directory 
3. update the `PKGBUILD` file and change `pkgver` to `1.2.4`
4. run `updpkgsums` in your arch command line (should be installed on your Arch already)
5. run `makepkg --printsrcinfo > .SRCINFO`
6. try to build it with `makepkg`
7. Commit to the repo `git commit -am "Updated checksums and sources for build 1.2.4"`
8. Push to the repo `git push`

I assume though you would first need to add a public ssh key to your AUR account. Do you know how this works?

**Comment by warmwaffles** [comment]
Username is `warmwaffles` there too.

> I assume though you would first need to add a public ssh key to your AUR account. Do you know how this works?

Yea I can put my ssh keys up.

Lemme clone it and play with it.

**Comment by ransome1** [comment]
@warmwaffles I added you as maintainer. Let's see if it works.

**Comment by warmwaffles** [comment]
Oh that's all it is. Super simple. It has been updated.

**Comment by ransome1** [comment]
Sweet, thanks a ton!

**Comment by warmwaffles** [comment]
@ransome1 can confirm this has been resolved on Archlinux. I do not get this exception anymore.

**Comment by ChongChengAC** [comment]
This issue has been fixed since v1.2.4. Thanks to @ransome1.
