### ISSUE TITLE
todo.txt file does not open in 0.9.0 alpha

### ISSUE THREAD

**Issue by velardevines** [ransome1/sleek#39]
Running Sleek on Google Chromebook Crostini. Might be a problem with write permission but I don't know how to determine the cause.  This is a new problem to 0.9.0 alpha. 

The Sleek todo.txt file does not open when Sleek starts up. The file will not open using the Open "toto.txt" button. I could create a new toto.txt file but then was unable to save an item to that file. 

--Bill

**Comment by ransome1** [comment]
Hey Bill.

Thanks a lot for taking a look at the alpha release. I just downloaded the AppImage and could not really reproduce your issue. But could you take a look into the "console" tab of the developer tools if you can see any errors? To open the Dev Tools on Linux, you simply push the Alt key and the menu will appear. In the menu you select "About" and then "Toggle Developer Tools". With the tools open, just reload the page, do whatever you did to provoke the error and check the list in Console tab, if an error appears.

**Comment by velardevines** [comment]
Hello,  

Apologies but I probably don't understand enough about Linux to help much.  I installed Sleek and other Linux applications by enabling Linux Crostini on a Chromebook. I use a few Terminal commands to install apps or download the .deb file and install the app. 

I can open a Terminal window but the Alt key does nothing. 

I can open a Console window from inside the Chrome browser but there are no Errors or Warnings created when I open Sleek and try to open a todo.txt file. So, I assume, this Chrome browser Console is different from the Linux Console so does not show information that will help you. 

When I googled developer tools or console in Crostini, there were no results that helped me understand how to run the Linux console in Crostini on a Chromebook.

Any other suggestions you can offer are welcome.  However, trying to explain to me what to do may not be productive and end up being a waste of your time - just my thought based on my limited knowledge of Linux.

--Bill

**Comment by ransome1** [comment]
Hey Bill. The developer tool are part of sleek as it is build with the Electron framework which utilizes Chromium, which includes the developer tools ;)

So you need to press the Alt key within sleek and a menu will appear. The result will look like this:
![Screenshot_20210208_194338](https://user-images.githubusercontent.com/11188741/107266619-11927d00-6a46-11eb-953e-fec8f33b857e.png)

With the developer tools open, you will propaly get an Error entry in that list on the right once you opened the file.

**Comment by velardevines** [comment]
VM5:36 Uncaught Error: Uncaught ReferenceError: _paq is not defined
    at EventEmitter.<anonymous> (<anonymous>:36:53)
    at EventEmitter.emit (VM4 sandbox_bundle.js:146)
    at Object.onMessage (VM4 sandbox_bundle.js:127)
(anonymous) @ VM5:36
emit @ VM4 sandbox_bundle.js:146
onMessage @ VM4 sandbox_bundle.js:127

**Comment by velardevines** [comment]
render.js:556 Uncaught ReferenceError: _paq is not defined
    at changeFile (render.js:556)
    at HTMLTableCellElement.cell1.onclick (render.js:579)
changeFile

**Comment by velardevines** [comment]
render.js:201 Uncaught ReferenceError: _paq is not defined
    at HTMLAnchorElement.el.onclick (render.js:201)
el.onclick	@	render.js:201

**Comment by velardevines** [comment]
Those errors were from the Console tab.

**Comment by ransome1** [comment]
Perfect, thanks a lot, I will try to reproduce and fix it :)

**Comment by ransome1** [comment]
@velardevines I could not reproduce it yet, but as your errors point out that a sandboxing module might be involved (which could actually let to the inability of sleek to access your file system), I turned it off. It's a long shot, but could you please give another try? https://github.com/ransome1/sleek/releases/tag/0.9.0-Alpha-2

**Comment by velardevines** [comment]
No change in Alpha 2. This is the error when Sleek loads:

Uncaught (in promise) ReferenceError: _paq is not defined
    at checkDismissedMessages (render.js:2386)
    at window.onload (render.js:2645)

**Comment by ransome1** [comment]
I'm afraid I can't reproduce the error. If you find some time I would like to ask you for three things:

1. Please double check the file name of the binary you downloaded. It should contain "Alpha-2", like in "sleek-0.9.0-Alpha-2.AppImage"
2. Could you share your user preferences file? It is located at "/home/{YOUR-USER-NAME}/.config/sleek/user-preferences.json". You can ttach it here or send it to me by mail ransome[AT]uber[DOT]space
3. after that, could you delete the whole folder "/home/{YOUR-USER-NAME}/.config/sleek/" and restart sleek?

**Comment by ransome1** [comment]
@velardevines. Although I havn't been able to reproduce your issue, here is another release with fixes anyway: https://github.com/ransome1/sleek/releases/tag/v0.9.0-Alpha-3

Maybe we're lucky and it's fixed.

**Comment by velardevines** [comment]
[user-preferences.json.txt](https://github.com/ransome1/sleek/files/5955771/user-preferences.json.txt)

**Comment by velardevines** [comment]
After deleting folder "/home/{YOUR-USER-NAME}/.config/sleek/" and restarting sleek version 0.9.0 Alpha 2 opens the todo.txt file and works as expected. Did not test very much however.   Will install Alpha 3 now. 

--Bill

**Comment by ransome1** [comment]
Hi @velardevines. Thanks for the config file. With it I was able to reproduce and fix it: https://github.com/ransome1/sleek/releases/tag/v0.9.0-Alpha-4

With this release you can actually put your old config back in place.

**Comment by velardevines** [comment]
Thank you @ransome1  for being very responsive.

**Comment by ransome1** [comment]
@velardevines as these issues are fixed, let me close here.
