### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by DmDrMos** [ransome1/sleek#393]
I have done Russian translation of the Sleek. But I don't know how to add translation file into the project on my own action. So, please, use translated interface file from https://drive.google.com/file/d/1k0uVyPMdlhy2x_-lKIOthkSR6BcWFDA1/view?usp=sharing (UTF-8 encoding), attached file  or json structure below. They are identical.

{
  "about": "О программе",
  "addAsTodo": "Создать задачу",
  "addTodo": "Добавить задачу",
  "addTodoContainerHeadline": "Нет задач",
  "addTodoContainerSubtitle": "Список пуст, добавим новые задачи?",
  "archive": "Архивировать",
  "autoUpdateHeadline": "Автоматическое обновление",
  "autoUpdateBody": "Загружена и установлена новая версия. Она будет использована после перезапуска.",
  "bdaily": "Каждый рабочий день",
  "bday": "рабочий день",
  "bday_plural": "рабочие дни",
  "cancel": "Отмена",
  "clear": "Очистить",
  "close": "Закрыть",
  "closeTabOrWindow": "Закрыть вкладку или окно (если оно с одной вкладкой)",
  "compactView": "Компактный вид",
  "completedTodos": "Завершенные",
  "contexts": "Контексты",
  "copy": "Копировать",
  "visibleTodosCopiedToClipboard": "Видимые задачи скопированы в буфер обмена",
  "copyVisibleTodosToClipboard": "Копировать видимые задачи в буфер обмена",
  "createFile": "Создать todo.txt",
  "cut": "Вырезать",
  "daily": "Ежедневно",
  "themeHeadline": "Вид",
  "day": "день",
  "day_plural": "дней",
  "delete": "Удалить",
  "devTools": "Переключить инструменты разработчика",
  "done": "Пометить ВЫПОЛНЕНО",
  "date": "Дата создания",
  "due": "Срок",
  "dueDate": "К дате",
  "dueFuture": "На будущее",
  "duePast": "Просрочено",
  "dueToday": "На сегодня",
  "dueTomorrow": "На завтра",
  "edit": "Редактировать",
  "editTodo": "Редактировать задачу",
  "errorEventLogging": "Вести лог ошибок и действий",
  "every": "Каждый",
  "file": "Файл",
  "find": "Найти",
  "formErrorWritingFile": "<strong>Ошибка:</strong> Изменения не записаны. Проверьте наличие файла todo.txt file exists и права на запись в него: ",
  "formInfoDuplicate": "Такая задача уже есть, дубликаты не будут записаны в файл todo.txt.",
  "formInfoIncomplete": "Неполный ввод, введите хотя бы текст (задачи).",
  "formInfoNoInput": "Введите задачу в текстовое поле. Если Вы затрудняетесь с синтаксисом, крактая справка по ссылке (на английском) <a href=\"https://github.com/todotxt/todo.txt\" target=\"_blank\">todo.txt syntax</a>.",
  "formSelectDueDate": "Не установлен срок",
  "todoTxtSyntax": "Используте синтаксис todo.txt (A) @context +project due: rec: h: t:",
  "function": "Функция",
  "help": "Помощь",
  "helpTab3Title": "Контексты и проекты",
  "helpTab4Title": "Даты",
  "recurrences": "Повторение",
  "helpTabContextsProjectsBody": "Если проект состоит из нескольких задач, такие задачи можно пометить знаком \"+\" за которым следует название проекта. Контексты определяются ситуациями, в которых могут быть выполнены задачи. В соотвествии с концепцией David Allen <a href=\"https://en.wikipedia.org/wiki/Getting_Things_Done\" target=\"_blank\">Getting Things Done</a>, \"контекст\" может быть дома, на работе, в магазине, по телефону, на компьютере, с определенной персоной. Для добавления контекста используется символ \"@\" с именем контекста. Больше информации по синтаксису todo.txt есть по ссылке <a href=\"https://github.com/todotxt/todo.txt\" target=\"_blank\">todo.txt</a>.<br><br>Имена проектов и контекстов должны писаться слитно, в одно слово с их символами. Число контекстов и проектов не ограничено.",
  "helpTabContextsProjectsTitle": "Добавление контекстов и проектов",
  "helpTabDatesBody1": "sleek автоматически добавляет дату начала задачи в момент создания. Если нужно изменить ее, укажите ее в задаче сразу после тега приоритета. Задачи с установленным сроком будут показаны в начале списка. Чем ближе дата выполнения или задача просрочена, тем выше она будет в списке. Задачи на сегодня и просроченные будут выделены красным и будут оставлены в начале списка. Чтобы добавить дату готовности напишите \"due:\" после чего напишите дату в формате <strong>YYYY-MM-DD (например, due:2021-03-07)</strong>. Также можно использовать виджет календаря.",
  "helpTabDatesBody2": "Даты можно задавать в терминах <strong>tomorrow</strong>, <strong>next Tuesday</strong> or <strong>end of February</strong>, которые будут конвертированы в форматированные даты. Подробности тут: <a href=\"https://sugarjs.com/dates/#/Parsing\" target=\"_blank\">полный спиок удобных названий для дат.</a>",
  "helpTabDatesTitle1": "Добавление дат",
  "helpTabDatesTitle2": "Удобные названия для дат",
  "helpTabKeyboardSubtitle1": "Когда задача промаркирована",
  "helpTabKeyboardSubtitle2": "Когда открыто окно редактирования/добавления задачи",
  "helpTabKeyboardTR7TD1": "Установить приоритет",
  "helpTabKeyboardTR10TD1": "Отправить задачу",
  "helpTabKeyboardTR13TD1": "Повысить/понизить приоритет",
  "helpTabKeyboardTR14TD1": "Удалить приоритет",
  "helpTabKeyboardTR15TD1": "Сдвинуть дату выполнения",
  "helpTabKeyboardTR16TD1": "Удалить дату выполения",
  "helpTabKeyboardTR17TD1": "Архивировать выполненные задачи в файл done.txt",
  "helpTabKeyboardTR25TD1": "Редактировать",
  "helpTabKeyboardTR26TD1": "Отметить Выполнено",
  "helpTabKeyboardTR27TD1": "Открыть контекст",
  "helpTabPrioritiesBody": "Важные задачи должны быть в начале списка. Напишите \"(A)\" в начале текста задачи, чтобы достичь этого. Кроме \"(A\") можно использовать все буквы от A до Z. Однако только A, B и C будут выделены цветом. Все остальные приоритеты будут иметь нейтральную серую пометку. Для установки приоритетов горячими клавишами, нажмите Alt + A до Z в окне добавления/редактирования задачи",
  "helpTabPrioritiesTitle": "Добавление приоритета",
  "helpTabRecurrencesBody1": "Если необходимо создать повторяющуюся задачу, укажите интервал повтороения, используя обозначение <strong>rec:</strong> (например, <strong>rec:d</strong> для того, чтобы повторять задачу ежедневно). Интерфейс sleek дает возможность установить атрибут rec: для задачи или можно сделать это, редактируя ее описание. Поддерживаются следующие значения <strong>d</strong> ежедневно, <strong>b</strong> по рабочим дням, <strong>w</strong> еженедельно, <strong>m</strong> ежемесячно, <strong>y</strong> ежегодно. Можно также установить иной интервал, например, <strong>rec:3m</strong> для повтора с интервалом в 3 месяца. <a href=\"https://github.com/ransome1/sleek/wiki/Recurring-todos-(rec:)\" target=\"_blank\">Тут более подробная информация</a>.",
  "helpTabRecurrencesTitle1": "Добавление повторов",
  "hiddenTodos": "Скрытая",
  "inProgress": "В работе",
  "invertSorting": "Изменить порядок сортировки",
  "language": "Язык",
  "messageLoggingBody": "Вы можете помочь проекту, согласившись отправлять обезличенные данные об ошибках и событиях в системе. В этом случае будет вестись журнал ошибок и моментов их возникновения. Вы можете разрешить функцию отправки журнала в настройках программы.",
  "messageShareBody": "Мы признательны за чесные отзывы на  <br><i class=\"fas fa-star\"></i>&nbsp;<a href=\"https://sourceforge.net/projects/sleek/reviews\" target=\"_blank\">SourceForge</a>, отчеты об ошибках на <i class=\"fab fa-github\"></i>&nbsp;<a href=\"https://github.com/ransome1/sleek/issues\" target=\"_blank\">Github</a> и рекомендации программы.",
  "messageShareTitle": "sleek <i class=\"fas fa-heart\"></i> вам",
  "month": "месяц",
  "month_plural": "месяцы",
  "monthly": "Ежемесячно",
  "noRecurrence": "Без повторов",
  "noResultContainerSubtitle": "Нет результатов с учетом установленных критериев поиска и фильтров",
  "noResults": "Нет результатов",
  "notifications": "Предупреждения",
  "of": "из",
  "onboardingContainerBtnOpen": "Выберите существующий todo.txt",
  "onboardingContainerSubtitle": "Начните с выбора <strong>имеющегося</strong> файла todo.txt или создайте <strong>новый</strong>.",
  "open": "Открыть",
  "openFile": "Открыть todo.txt",
  "paste": "Вставить",
  "priorities": "Приоритеты",
  "priority": "Приоритет",
  "projects": "Проекты",
  "printCurrentView": "Распечатать выведенный список",
  "reload": "Перезагрузить",
  "resetFilters": "Сбросить фильтры и поиск",
  "reviewSourceforge": "Страница sleek на SourceForge",
  "reviewWindowsStore": "Страница sleek в Windows Store",
  "reviewMacAppStore": "Страница sleek в Mac App Store",
  "save": "Сохранить",
  "search": "(A) Искать, используя синтаксис todo.txt с учетом @context +project due:",
  "select": "Выбрать",
  "selectFile": "Выбрать файл todo.txt",
  "selected": "Выбранные",
  "selectedFilters": "Установленные фильтры",
  "settings": "Настройки",
  "settingsTabAboutContribute": "sleek - программа с открытым кодом и каждый может внести вклад в ее улучшение",
  "settingsTabAboutCopyrightLicense": "Copyright и лицензия",
  "settingsTabAboutCopyrightLicenseBody": "Copyright (c) 2021 Robin Ahle. sleek распространяется по лицензии <a href=\"https://opensource.org/licenses/MIT\" target=\"_blank\">MIT license</a>. Полный текст ли доступен по ссылке <a href=\"https://github.com/ransome1/sleek/blob/master/LICENSE\" target=\"_blank\">LICENSE</a>.",
  "settingsTabAboutExternalLibraries": "Использованное ПО, которое я не разрабатывал",
  "settingsTabAboutPrivacy": "Политика защиты персональных данных",
  "settingsTabAboutPrivacyBody": "Мне не интересно, кто использует sleek, и я не буду собирать ненужные мне данные. Однако мне интересно, сколько людей с пользой применяют sleek, и, если пользователь явно подтвердил, то, каким образом используется sleek. Данные анонимизируются до отправки, затем отравляются на частный сервер Matomo с использованием шифрованного SSL-соединения. Подробнее в <a href=\"https://github.com/ransome1/sleek/blob/master/PRIVACY.md\" target=\"_blank\">Политике конфиденциальности</a>.",
  "settingsTabSettingsArchive": "Архивировать задачи",
  "settingsTabSettingsArchiveBody": "Завершенные задачи будут удалены их рабочего файла todo.txt и перемещены в файл done.txt. Если такого файла нет в текущей папке, то он будет создан.",
  "themeBody": "Если обычный интерфейс sleek слишком ярок на ваш вкус или для текущего рабочего окружения, темная тема может быть удачной альтернативой.",
  "settingsTabSettingsLanguageBody": "sleek автоматически устанавливает локализацию в зависимости от языка операционной системы. Если вам удобнее другой язык, его можно установить вручную.",
  "settingsTabSettingsLoggingBody": "Вы можете помочь этому проекту, разрешив автоматичесскую отсылку анонимизжированной информации об использовании sleek. Подробнее описано в <a href=\"https://github.com/ransome1/sleek/blob/master/PRIVACY.md\" target=\"_blank\">Политике нонфиденциальности</a>.",
  "settingsTabSettingsNotificationsBody": "sleek может посылать предупреждения о задачах на сегодня и завтра. Для этого программа должна работать.",
  "settingsTabSettingsTray": "Минимизировать в трей",
  "settingsTabSettingsTrayBody": "С этой настройкой sleek минимизируется в трей и не будет виден на панели задач.",
  "compactViewBody": "В компактном режиме интерфейс sleek занимает меньше места. Этот режим удобен для крупного увеличения экрана или для представления максимального числа задач.",
  "fileTabsBody": "Если sleek используется с несколькими файлами задач, то они будут добавлены в панель ярлыков для переключения между ними. Эта установка включает или выключает панель ярлыков.",
  "zoomBody": "С использованием масштабирования интерфейс sleek может быть увеличен или уменьшен в размере. Эта настройка удобна для подбора размера элементов интерфейса sleek для текущих настроек дисплея.",
  "shareFacebook": "Расскажите о sleek на Facebook",
  "shareLinkedin": "Расскажите о sleek в LinkedIn",
  "shareTwitter": "Расскажите о sleek в Twitter",
  "shortcuts": "Горячие клавиши",
  "sleekOnGithub": "sleek в Github",
  "sortBy": "Сортировать по",
  "sortByFile": "Порядок, как в файле",
  "sortCompletedLast": "Пометить ЗАВРШЕНО при окончании",
  "submitIssuesOnGithub": "Описать проблему на Github",
  "switchToSpecificFile": "Переключиться на определенный файл",
  "switchToNextFile": "К следующему файлу",
  "switchToPreviousFile": "К предыдущему файлу",
  "showHelp": "Показать справку",
  "today": "Сегодня",
  "todos": "Задачи",
  "todoCopiedToClipboard": "Задача в буфере обмена",
  "toggleCompletedTodos": "Показать/скрыть завершенные задачи",
  "toggleTheme": "Переключить темный режим",
  "toggleFilter": "Показать фильтры",
  "toggleDeferredTodos": "Показать/скрыть отложенные задачи",
  "tomorrow": "Завтра",
  "useAsTemplate": "Использовать как шаблон",
  "view": "Вид",
  "viewHeadlineAppView": "Вид приложения",
  "viewHeadlineFilterList": "Боковая панель фильтров",
  "viewHeadlineTodoList": "Список задач",
  "toggleShowEmptyFilters": "Сброшенные фильтры",
  "zoomHeadline": "Зум",
  "visibleTodos": "Видимые задачи",
  "week": "неделя",
  "week_plural": "недели",
  "weekly": "Еженедельно",
  "welcomeToSleek": "Добро пожаловать в sleek",
  "windowButtonCreateFile": "Создать файл todo.txt здесь",
  "windowButtonOpenFile": "Открыть",
  "windowFileformat": "Текстовый файл",
  "windowTitleCreateFile": "Создать todo.txt",
  "year": "год",
  "year_plural": "годы",
  "yearly": "Ежегодно",
  "archivingPrompt": "Все завершенные задачи будут перемещены в файл done.txt в этой же папке.",
  "confirm": "Подтвердить",
  "archivingCompletedTitle": "Архивирование завершено",
  "archivingCompletedBody": "Завершенные задачи успешно перемещены в ",
  "restartPrompt": "Для этих изменений sleek должен стартовать снова. Если это не произойдет, запустите программу вручную.",
  "deleteCategoryPrompt": "Этот фильтр будет безвозвратно удален из всех задач.",
  "modalBackgroundAttention": "Окно будет закрыто, а содержимое - очищено.",
  "deferredTodos": "Пороговая дата в будущем",
  "fileRemovalPrompt": "Это действие лишь удалить название из списка файлов, но сам файл на устройстве останется.",
  "fileTabsHeadline": "Ярлыки",
  "hint_priority": "Задачи отсортированы по приоритету <code>(A...Z)</code>",
  "hint_contexts": "Символ @ добавляет <code>@контекст</code> к задаче",
  "hint_projects": "<code>+проект</code> добавляется символом + (плюс)"
}
[translation.json.txt](https://github.com/ransome1/sleek/files/9027443/translation.json.txt)

**Comment by ransome1** [comment]
@DmDrMos thanks again for contributing the translations :) Could you please take a look at this pre-release, if the translations work well? https://github.com/ransome1/sleek/releases/tag/v1.2.4-rc.1

Also, could you translate the word `Russian`, as in the language, in to proper Russian? Google Translate says `Русский`, is that correct?

**Comment by DmDrMos** [comment]
It is OK at a glimpse. Thank you for your excellent work!!! I'll take a closer look when will be more free, probably in 2 weeks.

Yes, Google Translate is right: "Russian" is "Русский"

**Comment by ransome1** [comment]
Has been released with 1.2.5
