### ISSUE TITLE
Cannot acces network location (prepends/defaults to`/home/<user>/`) with 1.2.0 Snap on Ubuntu

### ISSUE THREAD

**Issue by gnbl** [ransome1/sleek#394]
Trying to open a path on a network share `smb://<server>/path/` (or nfs or afp) silently fails and defaults to `/home/user/` even when network shares have been accessed (mounted?) by "Files" (nautilus) previously (nothing shown in the Sidebar or "Other Locations").

Similarly, specifying a todo.txt file path on a share results in a "no such file" error `home/<user>/<protocol>://<server>/<path>/`.

There are not problems reported in the dev console.

V 1.2.0 from Snap Store on Ubuntu 22.04 LTS

**Comment by gnbl** [comment]
All Permissions granted (e.g. network access)

**Comment by ransome1** [comment]
Thanks for reporting this. Unfortunately I currently don't have access to my computer and can only start looking into this in October. I'll keep you posted when there is any progress.

**Comment by ransome1** [comment]
@gnbl I havn't manage to look into this yet. But I added a feature, which lets you drag and drop your file into the file window. I can't say if it changes anything for you, but you can at least give it a try: https://github.com/ransome1/sleek/releases/tag/v1.2.9-rc.2

**Comment by anderig** [comment]
Hi, I have a similar problem. I have a 2nd hard drive and alhough the directory shows up in the file picker when I click on it, it doesn't actually show the folder:
![image](https://github.com/ransome1/sleek/assets/95920280/4a9f6980-9882-4cf7-9459-50ab10e96826)
Here you can see that I have clicked on /Data but it is showing /home/ande in the folder tree but in fact it is showing the contents of "/" in the file listing window.

What is this drag and drop - I couldn't see how to get this work.
Thanks! It is a GREAT application.

Cheers,
Andrew

**Comment by ransome1** [comment]
> Hi, I have a similar problem. I have a 2nd hard drive and alhough the directory shows up in the file picker when I click on it, it doesn't actually show the folder: ![image](https://user-images.githubusercontent.com/95920280/278739242-4a9f6980-9882-4cf7-9459-50ab10e96826.png) Here you can see that I have clicked on /Data but it is showing /home/ande in the folder tree but in fact it is showing the contents of "/" in the file listing window.
> 
> What is this drag and drop - I couldn't see how to get this work. Thanks! It is a GREAT application.
> 
> Cheers, Andrew

Hi @anderig . What version are you on and through which channel did you install sleek?

**Comment by anderig** [comment]
Hi @ransome1 
thanks for the fast response!
I have 1.2.8 and get it via snap (snapcraft.io).
Do you think this is resolved in 1.3.1 which I see is available on flathub...
Not sure which channel you support more actively... Currently I am using snap more cos flatpaks seemed to chew up too much disk space...
I am on linuxmint latest release ("Linux Mint 21.1 Vera").
Wish you a great weekend!
Cheers
Andrew

**Comment by ransome1** [comment]
Hi @anderig. I'm currently [rewriting sleek](https://github.com/ransome1/sleek/discussions/501) and its latest version is almost production ready. Nothing changed function wise, but it's technically a new app. The latest pre-release is available in the Snapstore Edge-Channel. If you want to try it out, you can install it with this: `sudo snap install --edge sleek`

It is suppose to use the native file chooser of GTK and maybe this changes something. If not it is definitely some configuration issue during the building process we need to figure out.

**Comment by anderig** [comment]
Hi @ransome1 
PERFECT!!!!! It works like a dream. Thanks!!!!
So far looks like your edge version does all I need.
THANKYOU SO MUCH!!!!
Have a great Saturday night.
Cheers,
Andrew

**Comment by ransome1** [comment]
I'm very happy to hear that. @gnbl I hope this works for you too.
