### ISSUE TITLE
Add option to choose format of "keep priority on completion" for compatability with other todo.txt app

### ISSUE THREAD

**Issue by lindoman** [ransome1/sleek#395]
**Did you check if a similar feature request has already been reported?**
Yes

**Is your feature request related to a problem? Please describe.**
I am trying to use todo.txt on nextcloud, from a PC and from my android phone. The incompatibility of how each app treats "keep priority on completion" is frustrating, and although the guidance of todo.txt itself suggests saving priority on completion as a key:value pair, this format is inconvenient.

**Describe the solution you'd like**
I would like to have an option added which allows the priority to be kept as a letter in brackets after the completion date, before the creation date. At the moment, the task is completed in sleek like this:
`x 2022-07-09 2022-07-08 some priority B task I completed pri:B`
and I would like an option for the task to be completed like this instead, retaining the priority as it was originally:
`x 2022-07-09 (B) 2022-07-08 some priority B task I completed`

I appreciate the key:value pair is suggested to be done like this:
https://github.com/todotxt/todo.txt#rule-2-the-date-of-completion-appears-directly-after-the-x-separated-by-a-space
and I have raised a feature request in simpletask android which also looks at this issue (trying to make simpletask more compatible with how sleek might handle this in the next release candidate)
https://github.com/mpcjanssen/simpletask-android/issues/1176

Having said that, a completed task from simpletask android ends up looking like this in sleek:
![image](https://user-images.githubusercontent.com/38988995/178103266-c60f6b2a-c010-4148-9706-4dcb446b3821.png)
This already works well, because it appears completed, and still retains a rendition of the "priority"
Added benefit: the priority is already retained when you "untick" the completion checkbox:
![image](https://user-images.githubusercontent.com/38988995/178103283-a1b2c780-b0ef-4531-8856-c8190d4b46b1.png)

Given all of the above, I agree with smichel17:
https://github.com/mpcjanssen/simpletask-android/issues/1176#issuecomment-1155734888
I think the todo.txt key:value pair suggestion for recording priority is overly complicated in this situation, and I think the simpletask android developers got it right.

**Describe alternatives you've considered**
There is not a comprehensive alternative at the moment. The original implementation of todo.txt suggests that priority should not be kept on completion, but the ease with which tasks can be completed in sleek / simpletask (click of a button / checkbox) means that keeping the priority and restoring it instantly is almost a required feature.

**Comment by ransome1** [comment]
Thanks for suggesting this. Unfortunately I currently don't have access to my computer and can only start looking into this in October. I'll keep you posted when there is any progress.

**Comment by lindoman** [comment]
@ransome1 thanks, I might even get round to doing my own pull request for this, would that be ok with you?

**Comment by ransome1** [comment]
Absolutely, that would be highly appreciated! :)
