### ISSUE TITLE
Irresponsive new install MacOS

### ISSUE THREAD

**Issue by Giampieroo** [ransome1/sleek#397]
I've installed Sleek via the Mac App Store but the app is irresponsive. None of the buttons does anything and the console log displays:
_Uncaught (in promise) Error: Error invoking remote method 'userData': No handler registered for 'userData'_

![Schermafbeelding 2022-07-13 om 10 43 46](https://user-images.githubusercontent.com/34095470/178691874-2f734303-66fe-4bae-85a6-3f75e76fcaf9.png)

**Comment by ransome1** [comment]
Thanks for reporting this. Unfortunately I currently don't have access to my computer and can only start looking into this in October. I'll keep you posted when there is any progress.

**Comment by bluebirch** [comment]
Same issue on Mac OS X. Doesn't mater how I install Sleek. Haven't found a workaround.

**Comment by ransome1** [comment]
@mdisseny @bluebirch @Giampieroo it might be a long shot, but could you check this pre release (https://github.com/ransome1/sleek/releases/tag/v1.2.2-rc.3) and give me a quick heads up, if it changes anything?

**Comment by Giampieroo** [comment]
YES! I've installed sleek-1.2.2-rc.3-mac.dmg and it works. Thanks for the update 👍🏼

**Comment by mdisseny** [comment]
Many thanks for the update, now it works like a charm. God job!

**Comment by ransome1** [comment]
Fix has been released in 1.2.2, closing here for now.

**Comment by bluebirch** [comment]
> Fix has been released in 1.2.2, closing here for now.

When will this update hit Microsoft Store? Unfortunately, that's the only way I can install Sleek on my work laptop since all other installation sources are blocked.

**Comment by ransome1** [comment]
@bluebirch unfortunately not before next week as I don't have access to a Windows VM atm (VirtualBox doesn't work on my M1 Mac). If you're experiencing this issue, you can look up the `user-preferences.json` and manually chance the language setting to `en`. This should solve the issue as a workaround until the Windows release.
