### ISSUE TITLE
Set due date 

### ISSUE THREAD

**Issue by Saturo78** [ransome1/sleek#398]
In 1.2.1 there is an issue when changing the due date.

Steps to reproduce:
open a task and change the due date
open another task and open the date picker
The selected due date of the first task is selected in the date picker but not in the task. 
When you click on this date nothing happens.
You have to pick another date to change the due date.

**Comment by ransome1** [comment]
Thanks for reporting this. Unfortunately I currently don't have access to my computer and can only start looking into this in October. I'll keep you posted when there is any progress.

**Comment by zerodat** [comment]
@Saturo78 just letting you know that I am able to reproduce the issue you reported in 1.2.1.  The date picker is not cleared when you open another task.

**Comment by TriggerDingus** [comment]
I confirm as well. I came to Github to write up an issue report but it was already done here. I'm enclosing a screen capture that shows my date picker of the current task - it shows the due date I selected when updating a previous task but it doesn't show the due date of the currently-selected task.
![cap](https://user-images.githubusercontent.com/75340371/192355171-ff6bba38-26ad-4bbb-809d-c3e2aee796cd.png)

**Comment by ransome1** [comment]
> I currently work-around the issue by updating the date text field.

The issue at hand sounds to me like a visual problem, not a functional one. Are you expereincing any actual problems? If so, could you please elaborate a bit further?

**Comment by TriggerDingus** [comment]
> > I currently work-around the issue by updating the date text field.
> 
> The issue at hand sounds to me like a visual problem, not a functional one. Are you expereincing any actual problems? If so, could you please elaborate a bit further?

I'm not sure what you mean, so I put together this video:
[https://odysee.com/Sleek_Issue:5](Link)

**Comment by jcz1** [comment]
I think same issue is with threshold date. But this problem appears in some conditions only and i don't know exactly which.

**Comment by ransome1** [comment]
> > > I currently work-around the issue by updating the date text field.
> > 
> > 
> > The issue at hand sounds to me like a visual problem, not a functional one. Are you expereincing any actual problems? If so, could you please elaborate a bit further?
> 
> I'm not sure what you mean, so I put together this video: [Link](https://odysee.com/Sleek_Issue:5)

My apologies for only now looking at the video and your audio comment in it. Thanks so much for it, this really helped. Now I fully understand the issue. Let's see if I can figure out a solution for this.

**Comment by ransome1** [comment]
@jcz1 @TriggerDingus @Saturo78 @zerodat could you please check if this issue still persists in this pre-release? https://github.com/ransome1/sleek/releases/tag/v1.3.0-rc.1

**Comment by zerodat** [comment]
It works properly for me in 1.3.0-rc.1, @ransome1 .  Thank you!

**Comment by jcz1** [comment]
Yes, it's ok now. Thanks.

**Comment by ransome1** [comment]
I'm closing here as this issue should be resolved. Feel free to re-open if this is not the case. @Saturo78 thanks again for reporting. Please be so kind and close future issues proactively, if they have been resolved.

**Comment by TriggerDingus** [comment]
@ransome1 I've been waiting for v1.3.0 to get to Flathub but it hasn't made it there. Is it on the way?

**Comment by ransome1** [comment]
@TriggerDingus Yes it is, but we're having a couple of issues with the build process and are switching to a different approach. I cannot exactly say how long it is going to take. Hopefully within the next days.

**Comment by TriggerDingus** [comment]
> @TriggerDingus I switched to a more reliable building process for Flathub and v1.3.0 should now be available. Could you give me a quick feedback, if this new release works on your side?

Nice! Yes, I now have the latest version and the date issue is resolved.
