### ISSUE TITLE
error on return from sleep (The currently selected todo file was not found)

### ISSUE THREAD

**Issue by mshuflin** [ransome1/sleek#399]
on Mac OS, when I open the lid and log in, often Sleek gives the following error:
<img width="305" alt="Screen Shot 2022-07-30 at 9 55 00 AM" src="https://user-images.githubusercontent.com/53985056/181866071-e910682c-af24-4982-8fbb-43f7cae2f400.png">
The sidebar has only one icon 
<img width="48" alt="Screen Shot 2022-07-30 at 9 55 31 AM" src="https://user-images.githubusercontent.com/53985056/181866079-a327c823-5f79-43ea-9e58-1fa1d7116851.png">
though the todos are still visible (but not editable)
<img width="972" alt="Screen Shot 2022-07-30 at 9 55 38 AM" src="https://user-images.githubusercontent.com/53985056/181866096-142454bc-aa8e-4c89-a367-09e677c03da3.png">

To restore it, I have to click the "open folder" button, remove the todo.txt and add it again

Sleek version 1.19
MacOS 12.4
using Syncthing

**Comment by ransome1** [comment]
@mshuflin did you get sleek on the Apple app store, brew or from Github? Also, could you please check https://github.com/ransome1/sleek/releases/tag/v1.2.9-rc.1 if this still happens? I'm wondering how this can happen, as I have the exact same setup with Syncthing. Have you setup any specific settings in Syncthing?

**Comment by mshuflin** [comment]
I download the file from github. I am updating to v1.2.9-rc.1 and I will test it to see if it still happens and if I can figure out some reproduction steps. Nothing special is set up in syncthing (syncthing is on my laptop, phone, and server, all with basically default settings).

**Comment by mshuflin** [comment]
It took several days, but opening my macbook this morning, I got this error again. Anything else I can do to help isolate the error?

**Comment by mshuflin** [comment]
1.3.0-rc.1 this issue has not happened. I will close for now, but reopen if it recurs

**Comment by ransome1** [comment]
@mshuflin thanks for reporting  back!
