### ISSUE TITLE
Stacking / Multiple Filters

### ISSUE THREAD

**Issue by jason-mehmel** [ransome1/sleek#4]
I would love to see the ability to stack multiple filter options. For example: if I've got the @1_inbox context and the +car project, that I could select both and see only those tasks that match both.

It would be great if this stacking filter option extends beyond two, as well. Some tasks may use multiple filter options.

**Comment by ransome1** [comment]
Sounds good. As soon as I'll find some time, I will figure out how to solve that one.

**Comment by ransome1** [comment]
@jason-mehmel , I have no idea why I closed the issue, sorry I was tired I guess ;)

Please check v0.2.1: https://github.com/ransome1/sleek/releases/tag/v0.2.1

As already mentioned on Gitter I am unsure on how the filters should be adjusted once you narrow down the results. Let me know what you think.

**Comment by jason-mehmel** [comment]
Works great!

When you say unsure about how the filters should be adjusted, how do you mean? As in, adjusted in the tray? Right now they are highlighted and that works for me!

Took a look in your question on gitter and I think that the filters shrinking (as in, you only see the filters that still apply based on the other filters you've chosen) would be great!

Right now, if I choose another filter that doesn't apply within the filter I have, I get no results, which is okay... at least I can see that there is nothing that applies to both filters! That is an answer in and of itself.

But, for example, clicking on my Next Actions filter, and then seeing ONLY the project tags that apply to Next Actions, would be a great way to quickly see everything that lives in that Next Actions place, if that makes sense.

**Comment by ransome1** [comment]
@jason-mehmel Please check v0.2.2: https://github.com/ransome1/sleek/releases/tag/v0.2.2
