### ISSUE TITLE
0.9.0 tests

### ISSUE THREAD

**Issue by SteOtt** [ransome1/sleek#40]
Hi,
I did some tests with sleek 0.9.0 alpha on Kubuntu 20.04:
- Opening file works
- Creating file works
- Switching between files works
- Adding todos works
- Editing todos works
- Deleting todos works
- Checking todos works
- Viewing checked todos works (strg + h)
- Filter pane is correct
- Filtering todos with filter pane works
- switching dark/light mode works

Issues I've found:
- When filtering with the search line at the top: After entering one letter the text field looses focus (see video)
- Can I see the version of sleek somewhere in the program?

https://user-images.githubusercontent.com/17461591/107279291-24617d80-6a57-11eb-9803-95bfd092cbc9.mp4

**Comment by ransome1** [comment]
@SteOtt Thanks for the testing, it's highly appreciated. Also the video is very helpful. I'll take a look into it and fix the behavior. 

Also I will print the version code in sleeks console output in the next release.

**Comment by SteOtt** [comment]
I would expect to see the version code on the about screen... maybe you could print it there!?

**Comment by ransome1** [comment]
Sure, why not.

**Comment by ransome1** [comment]
@SteOtt , quick question: Do you get any errors thrown if you check the developer console within sleek?

**Comment by SteOtt** [comment]
@ransome1 I don't see any errors in the developer console. In the attached file I've copied it.

Today filtering in the search bar worked once without loosing focus. But the second time it lost focus after the first letter as yesterday... strange.
[Sleek_090_Log.txt](https://github.com/ransome1/sleek/files/5954116/Sleek_090_Log.txt)

**Comment by ransome1** [comment]
@SteOtt The focus issue should be fixed in this next alpha release: https://github.com/ransome1/sleek/releases/tag/v0.9.0-Alpha-3

Also the version number should now appear in the About tab.

**Comment by ransome1** [comment]
Both of your points are included here: https://github.com/ransome1/sleek/releases/tag/v0.9.0

Thanks again for your testing!
