### ISSUE TITLE
Can't archive (done.txt is not created) on Mac OS

### ISSUE THREAD

**Issue by naunan** [ransome1/sleek#400]
Sleek Version 1.2.1 (Github prebuilt version)
Mac OS 12.4

Steps to reproduce:
1. Create a task
2. Check task to mark it done
3. Click the "Archive" button on the task
4. Confirm the "All completed todos will be moved from this file to a done.txt file in the same directory" question with "Confirm" 

Result:
The question prompt will disappear and no done.txt file will be written.

Expected result:
done.txt should be written

Note:
Things I tried:
- the AppStore Version. There the archive button was missing completely.
- a different directory
- removal of all files in Library (basically reinstalling Sleek)
- setting permissions for full control of the drive in the Mac OS settings

**Comment by khangdx1998** [comment]
Same issue in Linux

**Comment by jminnamon** [comment]
Same issue in Windows 10

**Comment by CPUGPU** [comment]
I think it's looking for the done file to already exist.  I started sleek from the console and got this message when attempting to archive:

`Error occurred in handler for 'getContent': Error in getContent(): Error: ENOENT: no such file or directory, open '/mnt/linox/home/[redacted]/syncmobile/tasklists/todo_done.txt'`

I manually created "todo_done.txt" file and selected alt -> Todos -> Archive -> Confirm and all of the completed tasks were moved to the new file.  Also received this message in the console:

`Info: File /mnt/linox/home/[redacted]/syncmobile/tasklists/todo.txt has changed`

Repeated the process on another file with a different name.  Same steps, same results, same resolution.

The workaround until it's fixed is manually create the xxxx_done.txt file.

**Comment by ransome1** [comment]
@jminnamon @khangdx1998 @CPUGPU @naunan hey guys, thanks again for reporting this. Can I ask you to check this pre-release, if the error still occurs?

https://github.com/ransome1/sleek/releases/tag/v1.2.3-rc.2

**Comment by naunan** [comment]
@ransome1 works for me with this release! todo_done.txt with the expected contents is created. Also works for differently named todo lists.

**Comment by ransome1** [comment]
Has been released with https://github.com/ransome1/sleek/releases/tag/v1.2.3, I'm closing here.

**Comment by CPUGPU** [comment]
Confirmed working as expected.  Thank you!

**Comment by ransome1** [comment]
> But looks like a new display bug has appeared: Any task with priority now shows on two rows. I'll open an issue.

Yes please, that would be nice.
