### ISSUE TITLE
Option to enable/disable creation date of tasks

### ISSUE THREAD

**Issue by naunan** [ransome1/sleek#401]
At the moment (version 1.2.1) when creating a task, no creation date is added automatically. However, it is possible to add a creation date manually and sleek will use it for sorting.
It would be nice to have an option to always add the creation date automatically.

**Comment by ransome1** [comment]
There is an option for this: https://github.com/ransome1/sleek/wiki/Hidden-preferences,-custom-variables-and-command-line-parameters#append-start-date-on-todo-creation

It's currently broken actually, but fixed in the next release 1.2.9. Feel free to try it out.

**Comment by rzelnik** [comment]
I have appendStartDate set to true in my ~/.config/sleek/user-preferences.json. I created two testing tasks through both button in the left sidebar and text input in top position. No starting date was created.
Sleek version 1.3.0, manual deb install.

**Comment by Jamlee** [comment]
@rzelnik me too

**Comment by Jamlee** [comment]
@rzelnik @ransome1 i  try to fix it.

**Comment by ransome1** [comment]
Is being fixed in this bug report: https://github.com/ransome1/sleek/issues/508
