### ISSUE TITLE
Right click menu is hidden at the edge of screen and by start menu (w10)

### ISSUE THREAD

**Issue by engkel** [ransome1/sleek#403]
**Did you check if the bug has already been reported?**
Doesn't seems so.

**Describe the bug**
When right clicking on an item in the task list at the edge of the app, the right click menu appears but is partly hidden under the start menu and the edge of the screen making it impossible to act on items close to the edge of the screen.

**Do you see any error entries in sleeks developer tools?**
see screenshot - I don't think they are related though.

**Expected behavior**
I expected the right click menu to appear further up the screen to allow pressing the buttons of the right click menu.

**Screenshots**
Added

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version of sleek 1.1.9
 - Source: Windows Store
![sleek_fkGwvNdoKH](https://user-images.githubusercontent.com/47790315/182557636-dabe3486-1bf2-4054-ae89-520697c2a061.png)
![uwLuiNCnEr](https://user-images.githubusercontent.com/47790315/182557642-018996d9-dc90-4156-9a9a-f1db5cfffd57.png)

**Comment by ransome1** [comment]
Thanks for pointing it out, this issue applies to all releases and I haven't found the time yet to enhance this behaviour. It's in the roadmap now.

**Comment by engkel** [comment]
Yes, it works perfectly for me now. 👍
