### ISSUE TITLE
Shortcut for changing priority also changes the due date.

### ISSUE THREAD

**Issue by cstby** [ransome1/sleek#407]
Using Alt + Super + Arrow Up/Down changes both the task priority and task due date. The expected behavior is to change the task priority only.

I'm on Sleek 1.2.1 and Pop!_OS (Ubuntu) 22.04.

**Comment by ransome1** [comment]
@cstby thanks for reporting this, I'll look into it soon and keep you posted about the progress.

**Comment by ransome1** [comment]
@cstby can you tell me what OS you're in and if this still occurs in 1.2.8?

I'm asking because I'm having trouble reproducing it on a Mac.

**Comment by Maartyl** [comment]
Same here. Windows. Version: 1.2.7 from Microsoft Store.
- also, Alt+Win+{Left,Right} deletes due date.

**Comment by ransome1** [comment]
@Maartyl @cstby is it possible that on Windows and on popOS (what Desktop Environment is it running btw?) the combination `Super/Windows + Alt + Up/Down` is already occupied by the OS? 

I have a Windows 10 VM and Windows ignores the `Super + Alt + Up/Down` combination in sleek and instead splits the window size in half.

On my Ubuntu (with Gnome) the `Super + Alt + Up/Down` combination triggers Gnome Activity feature (that shows all windows).

So maybe it might be a better idea to switch the priority shortcuts from `Super/Windows + Alt + Up/Down` (Old) to `Super/Windows + Ctrl + Up/Down` (New).

Whereas the due date shortcut would remain on `Ctrl + Alt + Up/Down`.

What do you say?

**Comment by Maartyl** [comment]
I believe it's in general better to not use `Super/Windows` for application specific shortcuts.
- On Windows they are often bound.
- On Linux I use them for WM shortcuts.

`Windows + Ctrl + Up/Down` already has meaning on Windows, as it maximizes / unmaximizes / minimizes a window.

It's OK to use letters, like `Ctrl+W/S` for up down; `Alt+A..Z` for direct choice (if it's even worth that many shortcuts) and other `Ctr+` for more in the future if needed.

**Comment by ransome1** [comment]
@cstby @Maartyl so I hope I've found a generic approach to handle shortcuts the same on all OS. Can I ask you to check out this latest pre-release? https://github.com/ransome1/sleek/releases/tag/v1.3.1-rc.1

In this release the following shortcuts have been implemented:
Ctrl + Shift + Up = `Priority up`
Ctrl + Shift + Down = `Priority down`
Ctrl + Shift + (Right OR left) = `Priority removed`
Ctrl + Shift + (A to Z) = `Priority set directly`

Alt + Up = `Due date one day forwards`
Alt + Down = `Due date one day backwards`
Alt + (Right OR left) = `Due date removed`

Could you guys please give it proper testing and tell me if this works for you and if you're experiencing any side effects?

**Comment by ransome1** [comment]
> Alt + Up = `Due date one day forwards`
> Alt + Down = `Due date one day backwards`
> Alt + (Right OR left) = `Due date removed`

@cstby @Maartyl @CPUGPU realised, that holding down `alt` and using the arrow keys `right` and `left` on a Mac, is a user's standard behavior to mark whole words. Thus I suggest the due date shortcuts should also include `shift`, like the ones for priority. I hope this doesn't interfere with Linux or Windows standard behavior. If so, please let me know. 

The new shortcuts will be available in the next pre-release.
