### ISSUE TITLE
option to case sensitive sort context and project

### ISSUE THREAD

**Issue by aisbergde** [ransome1/sleek#410]
**Is your feature request related to a problem? Please describe.**

Because of the limits in todo.txt format, I use upper and lower case for different purposes and meanings. For example upper case projects are persons and lower case projects are "what to do". Uper case content are "meta content" like SomeDay, WaitingFor.

**Describe the solution you'd like**

Please add an option to sort context and project case sensitive (in the filter area and in the content area)

**Describe alternatives you've considered**

I have no idea

**Comment by ransome1** [comment]
@aisbergde quick question: Filtering, by using the filter buttons in the filter drawer, should be already working the way you're asking for. For instance you can have a context `WaitingFor` and one `waitingfor`. Both will be showing up separately and can be selected separately. Or are you experiencing anything else? 

As for the option of searching case sensitive, I am preparing a test build right now. It would be great if you could help out testing it.

**Comment by ransome1** [comment]
@aisbergde you can download the pre release for this feature here: https://github.com/ransome1/sleek/releases/tag/v1.2.3-rc.1
