### ISSUE TITLE
option to keep the content of task as it it, without reordering words inside the line

### ISSUE THREAD

**Issue by aisbergde** [ransome1/sleek#411]
**Is your feature request related to a problem? Please describe.**

My todo.txt is under source control because I use it on different devices. When I open the todo.txt in sleek then nearly all tasks are changed: some blanks are removed, context and projects are moved to the end of the task, date fields are switched (t: before due:)

In general, this could be OK, but I want to keep tasks as I created them. I want to control myself, if I want to reorder and "cleanup".

For example, I use task in this form:

`@aaa +dothis with +that, but also +check +this blablabla`

**Describe the solution you'd like**

Sleek should not touch my tasks, but keep them unchanged.
If I change a task, then it is fine to recreate the line and to put the contexts and project at the end, to reorder date fields and so on, but please keep the tasks which I don't change.

There should be an option to clean up automatically (es it does currently)
And there should be a button or action, to clean up the file manuelly or to clean up specific tasks

**Describe alternatives you've considered**
I have no idea

**Comment by aubreyz** [comment]
There are already other similar issues raised so you should have referred to and commented in those instead of raising a new one. However I agree that this is an extremely serious problem, and I would not be able to use the otherwise wonderful Sleek until it is resolved with the third party developer. Mangling tasks is just not on.

**Comment by aisbergde** [comment]
I did not search for "repositioning". In this case this issue can be closed, because it is a duplicate of #68
