### ISSUE TITLE
no any functionality works

### ISSUE THREAD

**Issue by amigo421** [ransome1/sleek#412]
Tried a few cases: RC, AppImage stable, deb.

![image](https://user-images.githubusercontent.com/3259933/192133961-adf4337b-16cf-4174-b667-b2a74443a685.png)

running app but clicking any button doesn't work.

and error on the closing
![image](https://user-images.githubusercontent.com/3259933/192133997-45464170-7725-4e18-82bc-4193425832a9.png)

**Comment by ransome1** [comment]
This might be related to https://github.com/ransome1/sleek/pull/405.

If I remember correctly you're on a system set to Russian right? In that case it was possible for the app to crash if it got in touch with a language code it didn't know, like `ru`.

Can you try this pre release? https://github.com/ransome1/sleek/releases/tag/v1.2.2-rc.3

It should set sleek to English as fallback language in case your system language is not yet supported by sleek.

**Comment by amigo421** [comment]
yes, works fine, thank you!
