### ISSUE TITLE
Can't use file inside a folder with a name ending in ".txt"

### ISSUE THREAD

**Issue by acyment** [ransome1/sleek#413]
When I try to navigate to open a file that lies inside a folder that has a name ending in ".txt" sleek tries to open the folder and then opens as a file the first file or folder that finds inside. If it is a .txt file, the file is correctly opened, but it cannot be edited.

I know it sounds like a convoluted use case, but I happen to use an iOS app called 2do.txt (https://github.com/sodenn/2do-txt) that only syncs with Dropbox. It automatically saves its todo.txt inside a folder called "2do.txt". I have only tried this in a Mac (Monterey 12.6).

**To Reproduce**
1. Create a folder name "~/2do.txt"
2. Open Sleek
3. Click on the "open file" icon
4. Click on "open todo.txt"
5. Navigate to folder "~/2do.txt"
6. Click on "open"

You should realize that the file window doesn't navigate inside the folder, but rather opens it as if it were a file.

**Expected behavior**
The file window should have simply shown that the folder "2do.txt" doesn't have any files inside (and leave the "open" button grayed)

**Desktop (please complete the following information):**
 - OS: MacOS 12.6
 - Version of sleek 1.2.1
 - Source: Homebrew

**Comment by ransome1** [comment]
@acyment thanks for reporting this. I added the issue to the backlog and get back to you as soon as there is news.

**Comment by acyment** [comment]
Perhaps [this](https://github.com/sodenn/2do-txt/commit/f8bc7d44d5e6e6618613c55242195819c2740290) can help you fix it

Cheers

**Comment by ransome1** [comment]
@acyment thanks for pointing it out, I'll take a look at it

**Comment by ransome1** [comment]
@acyment I'm afraid the fix at 2do.txt does not solve anything on our side. We're depending on Electrons `showOpenDialog` for which I use filters to limit selectable files to `.txt`, `.md` and `.done`. This is done to prevent sleek opening files it can't handle. 

If I remove this limitation you would be able to select a folder that contains a dot and select a file within it. But I'm not sure about the implications of this in terms of stability and security.

I only looked briefly into this, but over at Electron this issue has been discussed already but never solved: https://github.com/electron/electron/issues/11391

My take is that the issue needs to be solved somewhere between Apple and Electron. But I'm open to fix this, if we find a solid solution.

**Comment by acyment** [comment]
A workaround taken from 2do-txt is that you could also choose a file by dragging and dropping. If the feature were added to Sleek there would at least be a way to work in sync between the two apps (at least in my config). Tks for the hard work!On 30 Sep 2022, at 04:43, ransome ***@***.***> wrote:﻿
@acyment I'm afraid the fix at 2do.txt does not solve anything on our side. We're depending on Electrons showOpenDialog for which I use filters to limit selectable files to .txt, .md and .done. This is done to prevent sleek opening files it can't handle.
If I remove this limitation you would be able to select a folder that contains a dot and select a file within it. But I'm not sure about the implications of this in terms of stability and security.
I only looked briefly into this, but over at Electron this issue has been discussed already but never solved: electron/electron#11391
My take is that the issue needs to be solved somewhere between Apple and Electron. But I'm open to fix this, if we find a solid solution.

**Comment by ransome1** [comment]
A quick fix could be to select a random .txt file and then edit the `user-preferences.json`. That's sleek's config file, you can find under `/home/YOURUSERNAME/Library/Application Support/sleek`. In there you'll see the previously selected "random txt file". Try to change the path and make it point to your actual todo.txt file within the `todo.txt` folder. Let me know if this works for now.

**Comment by ransome1** [comment]
@acyment I added a drag and drop feature into sleek. Could you please give it a try and let me know, if this solves the issue at hand? https://github.com/ransome1/sleek/releases/tag/v1.2.9-rc.1

**Comment by acyment** [comment]
Solved! Tks!!!
