### ISSUE TITLE
Tasks with priority display on two lines

### ISSUE THREAD

**Issue by CPUGPU** [ransome1/sleek#415]
In version 1.2.1, tasks that have priority show on a single line:
![Screenshot_2022-10-02_19-00-05](https://user-images.githubusercontent.com/7144932/193480141-c63a124a-acbb-4092-847c-ff1de7ebf34e.jpg)

In version 1.2.3, the same tasks now have two rows:
![Screenshot_2022-10-02_18-59-33](https://user-images.githubusercontent.com/7144932/193480140-c15b336a-5b23-49e5-89f0-2669de3e85d1.jpg)

**To Reproduce**
1. Create tasks with priorities
2. See error

**Do you see any error entries in sleeks developer tools?**
There are two cookie errors in matomo.js, but they occur in both versions so I don't think they are relevant.

**Expected behavior**
Tasks should appear on one line if space allows.  

Note that when opening the developer tools, version 1.2.1 correctly formats longer tasks to be two lines, keeping task text in the left "block", and project and context in the right "block".  1.2.3 wraps the text and tags, but keeps the extra line at the top.  This screenshot from 1.2.1 is the expected behavior:
![Screenshot_2022-10-02_19-06-31](https://user-images.githubusercontent.com/7144932/193480398-40bf220f-a743-4a3b-a289-b9164e3f926b.png)

**Desktop:**
 - OS: Xubuntu 20.04.5 LTS x86_64
 - Version:  1.2.3
 - Source: Github Appimage (which is IMHO the best package.  I can have multiple versions on a machine no worries.)

**Comment by ransome1** [comment]
@CPUGPU thanks again for reporting this. I think I found a fix for this, available in the next release.

**Comment by ransome1** [comment]
@CPUGPU Could you please check if this issue stills persists in this pre-release? https://github.com/ransome1/sleek/releases/tag/v1.2.4-rc.1

**Comment by CPUGPU** [comment]
Fixed!  Thank you.  

![Screenshot_2022-10-03_07-20-06](https://user-images.githubusercontent.com/7144932/193565226-f5ec7f05-2f90-4fcf-99ab-3fda75f7f7ad.png)

![Screenshot_2022-10-03_07-20-25](https://user-images.githubusercontent.com/7144932/193565170-b86679b3-1f7c-4774-b410-4630613ff329.png)
