### ISSUE TITLE
Changes to tasks do not display in 0.9.0 Alpha 4 

### ISSUE THREAD

**Issue by velardevines** [ransome1/sleek#42]
Changes to tasks or new items are not displayed until Sleek is closed then opened again. 

To recreate, make a change to an item or create an item to see that changes will not be displayed.

**Comment by ransome1** [comment]
Hi @velardevines , I just double checked by downloading the AppImage from the release page and it's working well on my side.

Do you see any error entries in the console log?

**Comment by velardevines** [comment]
Figured out the problem. I was using a todo.txt file located on an SD card. If I use a todo.txt file located on the main computer memory then there are no errors.
