### ISSUE TITLE
All tasks duplicated when completing a recurring task

### ISSUE THREAD

**Issue by fusilli** [ransome1/sleek#420]
When completing a recurring task, all the other tasks are duplicated. 

**To Reproduce**

Mark a recurring task completed.

**Expected behavior**

Only the completed task gets duplicated.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Version of sleek: 1.2.3
 - Source: Snap Store

**Comment by ransome1** [comment]
@fusilli thanks for reporting this, I'm on it and pushing an update asap.

**Comment by fusilli** [comment]
Great! Thank you for your work!

**Comment by ransome1** [comment]
@fusilli Can I ask you to check this pre-releade real quick? https://github.com/ransome1/sleek/releases/tag/v1.2.4-rc.3

I'll prepare the full release in the meantime.

**Comment by fusilli** [comment]
I've tested na AppImage and now it works fine. Thanks again!

**Comment by ransome1** [comment]
Can we close here?

**Comment by fusilli** [comment]
Sure – the updated snap works as expected.
