### ISSUE TITLE
Todo text in UI turns to all lowercase when searching, then editing

### ISSUE THREAD

**Issue by jorgb** [ransome1/sleek#422]
**Describe the bug**
The edit field turns my task into a lower case version, 'destroying' all mixed case letters even priority

**To Reproduce**
- When I am in my todo.txt in Sleek, I search for a keyword, let's say "feature" using the finder.
- Then when I click the todo I found all the text inside the edit box is lowercase
- This results in projects and contexts that are double, for example +SoftwareProject turns into +softwareproject and even worse, (A) turns into (a) making it an invalid 
- Sometimes it is not obvious, and I click enter and it can mess up my priority which is disturbing.

**Do you see any error entries in sleeks developer tools?**
- No, it is a weird artifact and I do not expect the case to change from mixed (original) case to lowercase 

**Expected behavior**
- No change to my case sensitive todo item, it messes up all case even priority

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version of sleek 1.2.5
 - Installed with Snap

**Comment by ransome1** [comment]
@jorgb thank you for reporting this. I was able to reproduce this. I'm on it.

**Comment by jorgb** [comment]
Yes it seems to be solved!
Thank you for the quick fix.

**Comment by ransome1** [comment]
Released in 1.2.6
