### ISSUE TITLE
Search can only find lowercase letters

### ISSUE THREAD

**Issue by tomasdurham** [ransome1/sleek#423]
**Description**
I don't know if this is really a bug or a feature that should be fundamentally included. I noticed at some point that sleek can only find words with lowercase letters. 
For example, a task is written like this:
- [ ] call Marry tomorrow

and when I search for "Marry" or even "marry" in the search bar, sleek does not find the task. Currently all tasks must contain lowercase letters for sleek to find the tasks. 

**Expected behavior**
the search bar should be able to find all tasks, whether upper or lower case words.

**Desktop:**
 - OS: Kubuntu 22.04.1 LTS
 - Version of sleek 1.2.6
 - Source: Snap Store

**Comment by ransome1** [comment]
@tomasdurham could you please check ,if this issue has been resolved in 1.2.7? It should available on Snap within the next couple of hours.

You can also download a binary here: https://github.com/ransome1/sleek/releases/tag/v1.2.7
