### ISSUE TITLE
Search is inconsistent

### ISSUE THREAD

**Issue by TriggerDingus** [ransome1/sleek#426]
**Is it an actual bug?**
I believe so.

**Did you check if the bug has already been reported?**
Yes

**Describe the bug**
Searching is inconsistent, often not finding search text though it's confirmed the text exists in the file. 

**To Reproduce**
See linked video

**Do you see any error entries in sleeks developer tools?**
While invoking the bug, I see no NEW errors. There was an existing error in the log when I opened it:
![cap](https://user-images.githubusercontent.com/75340371/196497126-1d9508f1-9c2d-4dfd-ab3d-18cc06590156.png)

**Expected behavior**
Search terms filtered/found.

**Screenshots**
https://odysee.com/Kazam_screencast_00000:d

**Desktop (please complete the following information):**
 - OS: Pop!_OS 22.04 LTS
 - Version of sleek:  1.2.6
 - Source: Pop! Shop

**Comment by TriggerDingus** [comment]
**I'm attaching a console log file for your review:**

[console.txt](https://github.com/ransome1/sleek/files/9813565/console.txt)

**Comment by ransome1** [comment]
@TriggerDingus I think this has been fixed in 1.2.7, could you please give it a quick try?

**Comment by TriggerDingus** [comment]
Just downloaded and did a bunch of searches in 1.2.7 and it appears to be resolved. That makes life much easier. Much appreciated!
