### ISSUE TITLE
Task text deleted when selecting a Project / Context using autocomplete

### ISSUE THREAD

**Issue by mimmori** [ransome1/sleek#427]
**Is it an actual bug?**
Yes

**Did you check if the bug has already been reported?**
it is a new bug introduced with version 1.2.7

**Describe the bug**
The bug occurs while inserting a new task. In particular, it happens when you choose a project / context suggested in the autocompletion phase (move with tab and then enter key)

**To Reproduce**
1. Create ne task (N key)
2. add some initial text and then the sign "+" or "@"
3. Press tab to navigate to listed tags until the desired item is selected
4. Press Enter key to autocomplete
5. The Selected tag will be inserted but all the text will be cleared

**Do you see any error entries in sleeks developer tools?**
No

**Expected behavior**
Normal text completition

**Screenshots**
no need.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version of sleek: 1.2.7
 - Source: Github

**Comment by ransome1** [comment]
@mimmori Thanks for reporting this! I'm fixing it asap.

**Comment by ransome1** [comment]
Is fixed in https://github.com/ransome1/sleek/releases/tag/v1.2.8. Please feel free to close here, if you can confirm the fix.

**Comment by mimmori** [comment]
just tried. Fixed!

Thanks
