### ISSUE TITLE
Option to automatically add current filters to new items

### ISSUE THREAD

**Issue by gentlecolts** [ransome1/sleek#430]
**Is your feature request related to a problem? Please describe.**
When adding new items, often I want them to apply to my current visual context:  If I've currently filtered for items related to a project, for example, I often want new items added to be associated with that project.  This can become even more of a nuisance when multiple filters are applied.

**Describe the solution you'd like**
A checkbox for "Apply current filters" on the new todo dialog would be a potentially very valuable convenience feature.  Could be defaulted off for each new todo, or "remembered" from whatever was last used.

**Describe alternatives you've considered**
Another solution could be to have this be a setting instead of a per-item checkbox, although I worry this may introduce unintended tagging if not as explicit

**Comment by ransome1** [comment]
> A checkbox for "Apply current filters" on the new todo dialog would be a potentially very valuable convenience feature. Could be defaulted off for each new todo, or "remembered" from whatever was last used.

That would mean another interface element, which I generally am critical about as it potentially bloats the interface. So I think we need to figue out if this feature serves a lot of users.

> Another solution could be to have this be a setting instead of a per-item checkbox, although I worry this may introduce unintended tagging if not as explicit

This can be easily implemented. in fact I quickly wrote a prototype and it kind of works well. But this only works on projects and contexts as you can have several of those. How would an auto fill work for priorities?

**Comment by ransome1** [comment]
@gentlecolts I believe your alternative proposal overlaps with https://github.com/ransome1/sleek/issues/281 correct?

I did add a prototype for this into the latest pre-release. Feel free to give it a try: https://github.com/ransome1/sleek/releases/tag/v1.3.0-rc.1

You can post your feedback in 281, so we can collect it at one central point.

**Comment by gentlecolts** [comment]
I was only considering the use case of projects/contexts actually, as I don't personally use priorities much, that'd probably be enough for this requests I think!

**Comment by ransome1** [comment]
Still relevant for 2.x, not closing here.

**Comment by gentlecolts** [comment]
Wasn't this actually completed?
