### ISSUE TITLE
Sidebar tooltips "undefined" or missing

### ISSUE THREAD

**Issue by CPUGPU** [ransome1/sleek#436]
**Is it an actual bug?**
Yes, though minor and cosmetic.  I don't think "undefined" or blank would be intentional.

**Did you check if the bug has already been reported?**
Searching for "undefined" and "tooltip" revealed no existing issues.

**Describe the bug**
Mouseover the icons in the sidebar.  The "+" icon pops-up "Add a new todo" tooltip, the parameters icon shows "View"; both good.  However the filter icon shows "undefined" and the folder icon shows nothing.

**To Reproduce**
1. Mouseover the filter icon in the sidebar, pause, see the "undefined" tooltip.
2. Mouseover the folder icon, pause, see nothing.

**Do you see any error entries in sleeks developer tools?**
No obviously relevant errors.

**Expected behavior**
The filter icon should say "Filter"  (at least).
The folder icon should say "Manage Lists" or at least "Lists" or maybe "Files".

The problem look like "filter" is missing from src/locales/en/translation.json, and the "title" setAttribute is for navBtnOpenTodoFile is missing from src/js/navigation.mjs.  I've updated both of these in my fork, but can't get Yarn to install on my machine so I can't test them.  I can still submit the pull request.

**Screenshots**
![Peek 2022-11-05 16-19](https://user-images.githubusercontent.com/7144932/200139459-02e8e27c-9639-434a-b13b-a9064959a54b.gif)

**Desktop (please complete the following information):**
 - OS: xubuntu 20.04.5 LTS
 - Version of sleek:  1.2.9-rc.2
 - Source: Github Appimage

**Comment by ransome1** [comment]
@CPUGPU thanks for reporting this. Could you please check if this is solved in 1.2.9?

**Comment by CPUGPU** [comment]
Victory!  Thank you.
