### ISSUE TITLE
Seting to display contexts and projects inline

### ISSUE THREAD

**Issue by 14v** [ransome1/sleek#437]
There is a task, in txt looks like:
```
Access +kotlin code from +java @interview
```
In sleek it displayed 
```
Access code from [kotlin] [java] [interview]
```

Expected: there is a setting to change chips display to highlighted inline text.

**Comment by ransome1** [comment]
@14v im not sure if I fully understand this feature request.

But is it basically this here? https://github.com/ransome1/sleek/issues/68

**Comment by 14v** [comment]
Yes liked issue means the same. I see in comments there is an update on library sleek is dependent on, so current issue should be solved, right?

**Comment by ransome1** [comment]
@14v yes in theory it should. But as the library is being rewritten, there will be quite some work on our side to be done. So stay tuned :) I hope it is ok that I close this one. Would be good to have you join the discussion in #68, once there is progress on this issue.
