### ISSUE TITLE
Can't start Sleek 1.2.9 installed through snap

### ISSUE THREAD

**Issue by rzelnik** [ransome1/sleek#439]
After snap upgrade of Sleek to 1.2.9 I can't start it.

```
$ sleek
/snap/sleek/1096/snap/command-chain/desktop-launch: line 602: /snap/sleek/1096/sleek/sleek: Permission denied
/snap/sleek/1096/snap/command-chain/desktop-launch: line 602: exec: /snap/sleek/1096/sleek/sleek: cannot execute: Permission denied
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.10
 - Version of sleek: 1.2.9
 - Source: Snap Store

**Comment by ransome1** [comment]
I asked the Snap community for help as literally nothing really changed on sleeks side. 

For now I downgraded Snap to 1.2.8 and will let you know when there is a fix.

**Comment by comminutus** [comment]
I'm having the same issue

**Comment by ransome1** [comment]
@comminutus sorry for that, it could be a general issue with Snap and a specific Linux kernel version as suggested here: https://forum.snapcraft.io/t/snap-doesnt-start-anymore-permission-denied/32536

I will investigate if there is anything we can do our side.

**Comment by comminutus** [comment]
@ransome1 thanks. Its definitely odd, all of my other snaps work fine and version 1.2.8 doesn't exhibit the problem.

**Comment by jason-mehmel** [comment]
Commented on the Snap forum and also confirming the problem here! Using the .deb file for now.

**Comment by schmandr** [comment]
Any news on this issue? Today I upgraded to 1.3.1 (on Ubuntu 20.04) and I'm getting the same permission denied error. Could you maybe provide that older version in Snap store again?

**Comment by ransome1** [comment]
I downgraded to 1.2.8, which should be working. Unfortunately I haven't found any time to find a solution for this.

**Comment by schmandr** [comment]
This is still relevant. My OS installed updated versions of Sleek a couple of times over the last weeks, but none of them was able to start. I always needed to roll back to 1.2.8.

**Comment by ransome1** [comment]
@rzelnik @schmandr @jason-mehmel @comminutus hey guys. Can I ask you to try out the release in the edge channel? It contains the [current state of sleek 2.0](https://github.com/ransome1/sleek/discussions/501). It is not yet finished though but I'm already setting up the release channels for it.

Please feel free to share your feedback, if it works for you or not.

Install it like this: `sudo snap install --edge sleek`

Run it: `snap run sleek` (no sudo needed)

If it crashes please share what the output in your terminal is.

**Comment by ransome1** [comment]
@rzelnik @schmandr @jason-mehmel @comminutus 2.0.1 is ready for production and available in Snap. Please re-open, if this still happens.

**Comment by schmandr** [comment]
> @rzelnik @schmandr @jason-mehmel @comminutus 2.0.1 is ready for production and available in Snap. Please re-open, if this still happens.

I'm running v2.0.2 now, and it works flawlessly. Thanks a lot!
Sorry for not replying to your previous question.

**Comment by jason-mehmel** [comment]
Also apologies! The v2.0.2 is listed in sleek and opens fine!

**Comment by rzelnik** [comment]
Also apologies. :) I also confirm that v2.0.2 opens well.
