### ISSUE TITLE
Make the wiki more visible

### ISSUE THREAD

**Issue by lquenti** [ransome1/sleek#440]
I just realized that the wiki is actually used by going through some issues. Would you mind either
- setting it as the "website" for this repo or
- Linking it somewhere easily visible in the markdown?

I feel like I'm not the only one who probably missed it.

**Comment by rzelnik** [comment]
Good idea. Also a simple static [github-hosted](https://pages.github.com/) website would be useful - it would make app visibility and link building much easier.

**Comment by lquenti** [comment]
I don't see why this has an advantage over the wiki.

I'd actually just set the wiki name in this field here

![2022-11-08_14-48](https://user-images.githubusercontent.com/21225159/200581809-0889f820-5c79-4b95-a437-f7428c6b416a.png)

**Comment by ransome1** [comment]
@lquenti I agree with you, that the wiki isn't properly represented. It has been added as you proposed and I will also include it into the readme file. Thanks for pointing it out. 

> Good idea. Also a simple static [github-hosted](https://pages.github.com/) website would be useful - it would make app visibility and link building much easier.

Not a bad idea in general. But it would be another touchpoint, that needs to be taken care of. Maybe some day, if I have a bit more time, I'll take care of it. As for now the Github repo is a decent enough way to present the app.

**Comment by ransome1** [comment]
@lquenti hope you'Re fine with me closing this issue. If not, feel free to reopen.
