### ISSUE TITLE
Count of Tasks in Filter/Total Tasks

### ISSUE THREAD

**Issue by Saturo78** [ransome1/sleek#445]
I really liked the feature that when adding a filter, the filterline shows the count of tasks in the filter and total tasks.
In the new version i miss this feature. Has it gone or moved to another section?

**Comment by ransome1** [comment]
> I really liked the feature that when adding a filter, the filterline shows the count of tasks in the filter and total tasks.
> 
> In the new version i miss this feature. Has it gone or moved to another section?

If we're referring to the same thing, it should still be there. And it was never gone. Maybe you can send me a screenshot of what you mean?

**Comment by Saturo78** [comment]
![Sleek Filter](https://github.com/ransome1/sleek/assets/71584438/0cdc41a9-a9fd-45f5-8b44-7e0b9fbbdae1)

**Comment by ransome1** [comment]
This is being handled a bit differently now. The count of tasks in the todo file is now integrated in the search placeholder text. 
![Bildschirmfoto 2023-09-12 um 2 45 09 PM](https://github.com/ransome1/sleek/assets/11188741/23f79755-42da-4b03-8206-f3c582b36b7f)

Can be tested here: https://github.com/ransome1/sleek/releases/tag/v2.0.0-dev9
