### ISSUE TITLE
If Sleek window visible on second monitor, invisible when second monitor disconnected

### ISSUE THREAD

**Issue by axtens** [ransome1/sleek#447]
**Is it an actual bug?**
I believe it is a bug. Persuade me it's a feature.

**Did you check if the bug has already been reported?**
Yes, and couldn't see anything obvious

**Describe the bug**
If Sleek is launched in a multi-monitor environment, and its window is moved to another monitor and then all the secondary monitors are disconnected, Sleek continues to act as though connected to the secondary monitor, effectively hiding it from view. Previews of it are visible on Alt-Tab and Mouse-Hover on the taskbar icon but Sleek cannot be made to appear on the main monitor (in this case, my laptop's screen).

**To Reproduce**
 1. Open Sleek
 2. Move window to second monitor
 3. Disconnect second monitor
 4. Mouse-hover over Sleek icon on taskbar, see preview of Sleek window. Click on Sleek icon. Sleek does not appear.
 5. Alt-tab to Sleek. Sleek window *preview* appears. Release tab-key. Sleek does not appear.

**Do you see any error entries in sleeks developer tools?**
I can't see the Sleek window.

**Expected behavior**
I would expect Sleek to switch itself to the main monitor once it detects (or is informed by the O/S) that it is now running in a single-monitor environment.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version of sleek: 1.3.0
 - Source: Scoop

**Comment by CPUGPU** [comment]
Sure that's not a Window's bug?  I get the same problem with man programs on Win10 when I undock my laptop.

Hit Alt-space, then m, then any arrow key, then you will be able to move it to an active screen with the mouse.

**Comment by axtens** [comment]
Windows bug? Yeah, could be. I've just never had this problem before with
any other application.
