### ISSUE TITLE
Completed tasks are sometimes incorrectly parsed as open tasks

### ISSUE THREAD

**Issue by mattulbrich** [ransome1/sleek#449]
Closed tasks that do not have a completion date are parsed incorrectly. For instance, the task `x (A) 2023-01-01 Have a good year` should be considered completed, but it currently isn't:

![image](https://user-images.githubusercontent.com/17046629/211103293-33c97e5f-693e-4a9e-a622-63cc82214e00.png)

Apparently, same applies to tasks like `x Some task` that should be considered completed, but aren't.

I assume this is due to a bug in the version of jstodotxt that is used in sleek. I was not able to reproduce the problem with 1.0.0 of that library. The original commandline tool todo.sh and other tools I use can digest this input that is within the specs.

Wanted to mention that sleek does a great job as a frontend to todo.txt

**Is it an actual bug?** Yes

**Did you check if the bug has already been reported?** Yes. Not amongst the bug reports.

**Describe the bug** s. above

**To Reproduce**
1. Add a new task which is closed but without completion date (`x Closed item`)
2. It will appear as an open task 

**Do you see any error entries in sleeks developer tools?** n/a

**Expected behavior** The mentioned examples should be listed as completed tasks

**Screenshots** s.above inline

**Desktop (please complete the following information):**
 - Ubuntu 20.10
 - Version of sleek 1.3.1-rc3
 - Source: deb from github release

**Comment by mattulbrich** [comment]
probably related to #432.

**Comment by ransome1** [comment]
@mattulbrich can I ask you to check if this still happens in the developer preview of v2.x? It's not yet meant for productive use, so please backup your txt file. But it contains the latest alpha version of jsTodoTxt. Maybe this solves the issue at hand.

**Comment by mattulbrich** [comment]
Thanks for coming back on this issue.
I downloaded `sleek-2.0.0-dev3.AppImage` and the problem mentioned above does no longer arise.

**Comment by ransome1** [comment]
Lovely, thanks for your feedback.
