### ISSUE TITLE
Number on taskbar icon doesnt represent amount of unfinished tasks

### ISSUE THREAD

**Issue by qquq** [ransome1/sleek#451]
**Describe the bug**
I have 81 unfinished task in my todo.txt list, but on the taskbar the number shows 19. I counted my "A" priority tasks and it is 47. What does the number on the taskbar mean?

**To Reproduce**
Link sleek to todo.txt
start it
see number on taskbar

**Expected behavior**
to show correct amount of unfinished tasks (or what actually? - question)

**Screenshots**
![image](https://user-images.githubusercontent.com/33117021/213213856-12cdef61-2e4a-4246-aefb-68252ee900e9.png)
![image](https://user-images.githubusercontent.com/33117021/213215116-571df4f1-738e-4da6-9289-b4484e36f177.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version of sleek 1.3.0
 - Source: Windows Store

**Comment by ransome1** [comment]
@qquq the number refers to tasks that have a due date, which is today or lies in the past.

**Comment by qquq** [comment]
> @qquq the number refers to tasks that have a due date, which is today or lies in the past.

Thanks for clarification, my bad. Im afraid I havent found the feature description in the list of features, you could eventually add it if you have spare time. Cheers and thanks for great app!
