### ISSUE TITLE
multiple date picker windows don't close

### ISSUE THREAD

**Issue by rzw** [ransome1/sleek#452]
OS Win10
Sleek 1.3.0 (zip from Github)

Clicking on the clock icon of an item with due date multiple times will open multiple date picker windows/popups that cannot be closed by esc or date picking.

1. expected behaviour A: only one date picker window should be open at any given time
2. expected behaviour B: if A is unresolved the date pickers should close one after the other by escaping or date picking

Resolution at the moment: close and restart sleek

**Comment by gklingler** [comment]
Same problem here on Ubuntu 22.04, Version 1.3.1.
Additionally, each click on the close button on one of the open pickers it create a new task.
