### ISSUE TITLE
Feature Request: Pomodoro Timer

### ISSUE THREAD

**Issue by lamyergeier** [ransome1/sleek#459]
Integrate pomodoro timer like [JMoerman/Go-For-It: A stylish to-do list with built-in productivity timer.](https://github.com/JMoerman/Go-For-It)

**Comment by ransome1** [comment]
Maybe a good idea, but I cannot accept this as a feature request. Please either describe the requirements or open a discussion instead, if this is still a lose idea: https://github.com/ransome1/sleek/discussions
