### ISSUE TITLE
DMG Package for Release 0.9.1

### ISSUE THREAD

**Issue by kmf** [ransome1/sleek#46]
Not seeing a macOS Package.

**Comment by ransome1** [comment]
Hi @kmf .

I'm afraid that for the next two or three months I won't have a Mac at hand as I am not at home and only have my production machine (Linux). Therefor I can only build Windows and Linux releases and unfortunately no DMGs.

Version 0.9.1 so far is only a first pre release for a feature (compact) and does not contain any stability or security updates. As long as you are not actively involved in designing the compact view (see the other thread here on Github), the 0.9.1 is not really relevant for you and you can stick to 0.9.0.

As soon as we step up to 1.0 there will be Mac builds again.

**Comment by ransome1** [comment]
@kmf, fyi: Since I'm utilizing Github CI now to build the releases, there will be Mac buils with every new release.
