### ISSUE TITLE
Allow writing of threshold dates with friendly date names

### ISSUE THREAD

**Issue by loopernow** [ransome1/sleek#460]
**Is your feature request related to a problem? Please describe.**
Due dates can be entered quickly and easily with friendly date names like "tomorrow," "Wednesday," "next month," etc. Threshold dates, on the other hand, have to be entered in the precise format of YYYY-MM-DD.

**Describe the solution you'd like**
Allow threshold dates to be entered with friendly date names such as "tomorrow," "Wednesday," "next month," etc., just like due dates can.

**Comment by ransome1** [comment]
Hi @loopernow this has been added to the latest developer preview: https://github.com/ransome1/sleek/releases/tag/v2.0.0-dev5

Please feel free to provide some feedback, if this works as expected. Before testing it, please backup your todo.txt file.
