### ISSUE TITLE
Clicking on a threshold date and choosing a date in the date picker results in adding a due date to the task

### ISSUE THREAD

**Issue by loopernow** [ransome1/sleek#462]
Clicking on a threshold date and choosing a date in the date picker results in adding a due date to the task, rather than in updating the threshold date.

1. Create a task with a threshold date, such as "t:2023-02-06".
2. Click on the task to update it.
3. The threshold date will be listed in the dialog box with a clock symbol. Click on the threshold date or on the symbol.
4. Choose a date in the date picker.
5. The task will now have a due date that you selected. The threshold date remains unchanged.

No errors seen in the Developer Tools console.

**Expected behavior**
Clicking on the threshold date in the task dialog box and then choosing a date in the date picker should result in an updated threshold date.

**Screenshots**
This is the relevant portion of the task dialog box:
![image](https://user-images.githubusercontent.com/11263913/217011954-a131cf14-7419-469b-a979-7af2068ae769.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version of sleek: 1.3.0
 - Source: Github

**Comment by ransome1** [comment]
Thanks for the bug report. I'm currently afk but will look into it as soon as possible.

**Comment by loopernow** [comment]
@ransome1 No, I didn't see that! Thank you.

Now that I know that, the part that still seems bug-like to me is that I'm clicking on the clock icon for a Threshold date, but am taken to a calendar for a Due date.

I can see how maybe it is not a bug, though. It is up to you!

**Comment by aubreyz** [comment]
I am not using Slick right now but likely will do when it is mature enough (as simpletask on android). However I do follow the github thread avidly for that reason. With that in mind, this does seem like a bug to me (or at least is an interface issue that is likely to lead to errors).

**Comment by ransome1** [comment]
> @ransome1 No, I didn't see that! Thank you.
> 
> 
> 
> Now that I know that, the part that still seems bug-like to me is that I'm clicking on the clock icon for a Threshold date, but am taken to a calendar for a Due date.
> 
> 
> 
> I can see how maybe it is not a bug, though. It is up to you!

I'm currently rewriting sleek. You can check out the latest developer preview. It's not meant for actual production use yet, but will give you an idea on how the the due and threshold dates will be separated in the future. It's basically about separate Date-pickers for both dates.

**Comment by ransome1** [comment]
Will be dealt with in https://github.com/ransome1/sleek/issues/234

Let's close here.
