### ISSUE TITLE
Greyed Out Context Item in Sleek  1.3.0 on OSX Monterey 12.6.3

### ISSUE THREAD

**Issue by PackMeister** [ransome1/sleek#464]
Learning my way around Sleek and really starting to enjoy it.

However after learning about Contexts and Projects and reorganizing my ToDo List according I noticed I've one single CONTEXT Item that is always Greyed Out and Unclickable even after resetting filters and search.

When I hover over the greyed out contect item I get the Circle Icon with a Slash Through It.

Would like to remove this context item but don't know where or how to either locate it or remove it.

**Comment by ransome1** [comment]
Could you please open your todo.txt file and look for the line that contains this particular context? If you could share this todo here, I might be able to tell you what exactly makes it greyed out. 

One possible explanation can be, that you're working with a hidden todo: https://github.com/ransome1/sleek/wiki/Hidden-todos-(h:)

**Comment by ransome1** [comment]
Closing due to missing response
