### ISSUE TITLE
Show completion date for every task in more understandable format

### ISSUE THREAD

**Issue by ekaterina-o** [ransome1/sleek#466]
It would be great to see completion date as yesterday, week ago, two weeks ago, three weeks ago, month ago etc. for every task. It's a good alternative for calendar view and more understandable than date in ISO format.

**Comment by CPUGPU** [comment]
If this becomes a feature, please make it selectable in preferences.

I _much_ prefer ISO dates because they are visually easier for me to differentiate.  They are also more precise.  I want to know _exactly when_ last week a task was completed.
