### ISSUE TITLE
Renaming and deleting Contexts and Projects

### ISSUE THREAD

**Issue by HerrSersch** [ransome1/sleek#47]
It would be handy being able to rename or delete a Context or Project inside Sleek, which would then be applied to all affected tasks.

This could be implemented by right-clicking the desired item in the Filters menu, which would open a small menu that has an "Edit" option. Clicking this option would open a popup similar to the one for new tasks, where the item's name is already filled in and can be changed.

The menu would have three buttons: Cancel, Rename, Delete.
- Cancel closes the menu without appying any changes.
- Rename changes the name, updates all tasks and closes the menu.
- Delete removes the item from all tasks and closes the menu.

It would be helpful to display the old name on top or as the menu's title while this menu is open. Like "Renaming [current Project name]", so if the user clears the input field he still knows which item he is renaming.

Renaming an item to a name that already exists should be allowed, as this would simply assign the previously existing item to the affected tasks.

**Comment by ransome1** [comment]
@HerrSersch, definetly useful, no doubt. Also it might not be too complex, but still quite some work. I added it to sleeks backlog, it might be the next feature to be implemented when I find the time, which is rare right now.

Until then any help is welcome.

**Comment by ransome1** [comment]
@HerrSersch, I don't have a solution for your feature request at this point, but for the meantime and in case you work a lot with contexts and projects, I would like to point out release v0.9.9 (https://github.com/ransome1/sleek/releases). Here you can now group and sort your todo list by contexts and projects. Let me know if this is a useful feature to you.

**Comment by ransome1** [comment]
Hi @HerrSersch, although it is still in active development, I would appreciate your feedback on this feature so far: https://github.com/ransome1/sleek/releases/tag/v1.0.5-1

Please backup your data before giving this a try.

**Comment by HerrSersch** [comment]
This is amazing, thank you very much :) It's easy to use and works well.

When I rename something for the first time in a new sleek session it looks like sleek quickly closes and reopens the project - all UI elements disappear and then reappear. This does not happen anymore when I rename something again in the same session. You probably do this on purpose and I don't think it's a big deal.

The renaming itself works correctly, I didn't lose any data and everything was renamed correctly. I tested it on open tasks, closed tasks and hidden tasks and closed and restarted sleek multiple times just to make sure.

The only problem I could find is that it's possible to enter an empty string in the rename box. When you do this, the context or project will be removed from all tasks that use it, and these tasks will have an @ or + character added to the end of their description.

**Comment by ransome1** [comment]
@HerrSersch , thanks for your feedback! I'll look into both things tomorrow and try to fix them.

**Comment by ransome1** [comment]
@HerrSersch, both points should be fixed and have been released with https://github.com/ransome1/sleek/releases/tag/v1.0.5. Could you please check it and close this issue, if we're done here? Thanks.
