### ISSUE TITLE
snap build 1113 cannot execute - exec: /snap/sleek/1113/sleek/sleek: cannot execute: Permission denied

### ISSUE THREAD

**Issue by medvejonok79** [ransome1/sleek#471]
root@XXXXXX:/snap/sleek/1113# ll
total 4
drwxr-xr-x 9 root root  124 mars   5 15:49 ./
drwxr-xr-x 4 root root 4096 mars   7 12:01 ../
drwxr-xr-x 5 root root   56 mars   5 15:49 data-dir/
drwxr-xr-x 2 root root    3 mars   5 15:49 gnome-platform/
drwxr-xr-x 3 root root   39 mars   5 15:49 lib/
drwxr-xr-x 4 root root   56 mars   5 15:49 meta/
**drwx------ 5 root root  457 mars   5 15:49 sleek/**
drwxr-xr-x 3 root root   79 mars   5 15:49 snap/
drwxr-xr-x 4 root root   39 mars   5 15:49 usr/

This issue has been encountered by other people on this thread 
https://forum.snapcraft.io/t/snap-doesnt-start-anymore-permission-denied/32536

The problem seems to be that the snap build does not have correct rights set on the sleek folder.

snap    2.58.2
snapd   2.58.2
series  16
ubuntu  22.04
kernel  5.15.0-60-generic

**Comment by ransome1** [comment]
This is being discussed in another issue already.

I downgraded to snap again to the last working version.
