### ISSUE TITLE
Sleek memory leak?

### ISSUE THREAD

**Issue by stianmandarin** [ransome1/sleek#472]
**Is it an actual bug?**
I think so. Sleek uses high amounts of ram.

**Did you check if the bug has already been reported?**
Yes

**Describe the bug**
Sleek uses high amounts of ram 

**To Reproduce**
1. Run Sleek and check it's memory usage
2. When Sleek has been running for a day or two, its memory usage has gone from around 140mb to sometimes over 1gb (screenshot)

**Do you see any error entries in sleeks developer tools?**
`There was an error setting cookie `_pk_id.3.4209`. Please check domain and path.` Doubt it's related.

**Expected behavior**
Consistent memory usage.

**Screenshots**
See [https://imgur.com/a/dtLnCZD](https://imgur.com/a/dtLnCZD)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Sleek: 1.3.1
 - Source: Github (deb)

**Comment by ransome1** [comment]
@stianmandarin I'm not sure if this is a memory leak. sleek is based on Electron. It contains a headless Chromium browser and thus is heavier on the ressources than native apps. 

But I'll have an eye on this.

**Comment by ww-9** [comment]
@ransome1, it's definitely a memory leak. In my case, sleek starts with 100mb of memory and then goes up to 500 or more. This should not be the case.

**Comment by Bleskocvok** [comment]
Yeah, I agree it's most likely a memory leak. I have left `sleek` open for a few hours today and it's memory usage has creeped up to 2GB (and I only noticed because my game was lagging).
`sleek` version: 1.3.0

![image](https://github.com/themefisher/sleek/assets/52820901/2e85e646-88ad-4226-bff2-bc1f32585af1)

**Comment by ransome1** [comment]
I'm currently rewriting large chunks of sleek and will try my best to make sure to fix.

**Comment by ww-9** [comment]
@ransome1 I only tested for 10 hours, but the memory consumption results are impressive. <50mb overall. Thanks!

**Comment by ransome1** [comment]
Was it just running in the background or were you actually working with it, adding new files, reloading it, adding, editing and removing todos?

**Comment by ww-9** [comment]
There was a little bit of basic use too, but most of the time in the background.

**Comment by ransome1** [comment]
I'm closing here, because I think the new implementation should have solved this issue. If this occurs in the future again, we can reopen here.
