### ISSUE TITLE
Inconsistent behaviour: the View menu only closes when clicking certain elements

### ISSUE THREAD

**Issue by HerrSersch** [ransome1/sleek#48]
The View menu in the top right corner only closes when some types of elements are clicked, but stays open for other types. For example it closes when a task is clicked, but stays open when the button for adding new tasks is clicked. On the other hand it also closes when the task adding menu is closed.

This kind of menu feels like it should close immediately when _anything_ else is clicked, even when a background click on a surface like the free space on the left in the filter area is performed.

**Comment by ransome1** [comment]
@HerrSersch . I fully agree and will fix it in the next release.

**Comment by ransome1** [comment]
Fixed in https://github.com/ransome1/sleek/releases/tag/v0.9.2

**Comment by HerrSersch** [comment]
Tested on Win7, works very nicely. Thank you!
