### ISSUE TITLE
Entries starting with numbers followed by a period render under the checkbox

### ISSUE THREAD

**Issue by thecnoNSMB** [ransome1/sleek#480]
**Describe the bug**
See title and screenshot.

**To Reproduce**
Simply create a todo matching the description, or use [test todo.txt](https://github.com/ransome1/sleek/files/11149114/test.todo.txt).

**Do you see any error entries in sleeks developer tools?**
No

**Expected behavior**
I expect the second entry to render with the same offset as the first, though it's possible I'm colliding with some todo.txt syntax I'm not aware of.

**Screenshots**
![image](https://user-images.githubusercontent.com/7275663/229809573-add6e123-4912-4526-a409-d17d4710d0be.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version of sleek: 1.3.1
 - Source: Github

**Comment by ransome1** [comment]
@thecnoNSMB could you please check if this still occurs in this pre release? https://github.com/ransome1/sleek/releases/tag/v1.3.2-rc.1

**Comment by thecnoNSMB** [comment]
The issue appears to be fixed, thanks!
