### ISSUE TITLE
sleek doesn't care about URL arguments

### ISSUE THREAD

**Issue by auroraanna** [ransome1/sleek#482]
**Is it an actual bug?**
Yes, if I interpreted https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#exec-variables correctly.

**Did you check if the bug has already been reported?**
No, I didn't find an issue about it.

**Describe the bug**
The .desktop file's `Exec=sleek %U` says that sleek can open URLs in the arguments but it just doesn't care at all about them. No output in the console related to them.

**To Reproduce**
1. ```bash
   sleek https://github.com/ransome1/sleek
   ```

**Do you see any error entries in sleeks developer tools?**
Could not open developer tools with CTRL + SHIFT + I.

**Expected behavior**
sleek does something with those URLs like opening them if they are todo.txt files.

**Desktop (please complete the following information):**
 - OS: [NixOS 23.05.20230406.0e19daa (Stoat) x86_64]
 - Version of sleek [1.3.1]
 - Source: Flathub

**Comment by ransome1** [comment]
@auroraanna Maybe a copy and paste mistake. sleek is not suppose to open a URL, when you open it like you do in your example. If you remove the `%U` from the desktop file, does sleek still open? I have currently no access to a Linux system

**Comment by auroraanna** [comment]
yes, sleek still opens without

**Comment by ransome1** [comment]
clearly `incompetence`
