### ISSUE TITLE
Sleek freezes, then crashes, leaves behind 0-byte ToDo.txt file

### ISSUE THREAD

**Issue by TriggerDingus** [ransome1/sleek#484]
**Is it an actual bug?**
Yes

**Did you check if the bug has already been reported?**
Yes

**Describe the bug**
This has occurred twice now for me, each time on a different machine and a few weeks between each incident. Luckily, I keep daily backups and can restore my ToDo.txt file when it occurs though it can be a challenge to recall what was added/completed during the day.
I've been using Sleek for a year or so (don't recall exactly-could be more) this seems to be rare, but it is scary because you know when the Sleek screen freezes for more than a couple seconds it's going to crash and leave behind a 0-byte ToDo.txt file.
I can't reproduce this issue at-will because it occurs simply while using the application and while doing nothing of note. I may be completing an item, adding an item, whatever - the app just freezes for an extended period (10 seconds or more, maybe) before crashing and leaving behind the empty ToDo.txt file.
My file is about 4400 lines, 356kb in size. I don't know that this is big/small/average - Sleek doesn't seem to have any issues with it except for these 2 rare occurrences that I describe here.

**To Reproduce**
See above 

**Do you see any error entries in sleeks developer tools?**
See attached screen shot.
![cap1](https://user-images.githubusercontent.com/75340371/234634383-e9a60ce0-e8d2-4a24-bc56-e750ef895775.png)

**Expected behavior**
N/A

**Screenshots**
Attached

**Desktop (please complete the following information):**
 - OS: Pop! 22.04
 - Version of sleek: 1.3.1
 - Source: Pop! Shop

**Comment by ransome1** [comment]
@TriggerDingus 2.0.0 has been released on GitHub. This issue should be addressed in that release. If it still occurs, let's re-open here.
