### ISSUE TITLE
Creation date must be specified if completion date is

### ISSUE THREAD

**Issue by callegar** [ransome1/sleek#486]
**Is it an actual bug?**

I believe that `sleek` intends to be compatible with the `todo.txt` syntax. If so, this is a bug.

**Did you check if the bug has already been reported?**

Checked

**Describe the bug**

The `todo.txt` specification found on https://github.com/todotxt/todo.txt says that *creation date must be specified if completion date is*. See the following illustration:

![specification](https://github.com/todotxt/todo.txt/raw/master/description.svg)

**To Reproduce**
1. Add a task
2. Mark it as completed
3. A completion date is added, but no creation date is there.

**Do you see any error entries in sleeks developer tools?**

N/A

**Expected behavior**

When creating a task, sleek should add a creation date, so that when the task is marked as completed the creation date is there together with the completion date.

**Screenshots**

N/A

**Desktop (please complete the following information):**
 - OS: Linux, manjaro and ubuntu 22.04 (flatpak client)
 - Version of sleek 1.3.1
 - Source: Flathub

**Comment by aubreyz** [comment]
I definitely don't want creation dates imposed on me. 

Can you not add a creation date if you want that: https://github.com/ransome1/sleek/wiki/Hidden-preferences,-custom-variables-and-command-line-parameters#append-start-date-on-todo-creation

**Comment by callegar** [comment]
If there is a specification for the `todo.txt` format, then IMHO sleek should have a default behavior consistent with it. I understand that using a *dialect* of the `todo.txt` specification may be convenient, but probably should not be the default. I also understand that the specification itself is rather ambiguous (as illustrated in https://github.com/todotxt/todo.txt/issues/70) and that *de facto* standards exist possibly deviating from the specs, but ignoring the spec will not help it become more robust and correct.

The `user-preferences.json` file location is misterious in linux (flatpak).

The default with the creation date does not seem the documented one.

**Comment by aubreyz** [comment]
Yes but the spec is not that there has to be a creation date. It is up to the user to have created a creation date if they want a later want a completion date.  So not making a creation date is consistent with the spec.

**Comment by callegar** [comment]
In this case, `sleek` should not create a completion date, but currently it does unconditionally. If there is no creation date and no completion date, the possibility of setting recurrence should also be disabled, I think.

**Comment by aubreyz** [comment]
Fair enough. The spec does seem odd though - I cannot see why a completion date should not be permitted if there is no creatio date -- that seems completely arbitrary and unnecessary.

**Comment by callegar** [comment]
> that seems completely arbitrary and unnecessary

I think that it is because otherwise having a single date it would be impossible to know if it is a creation date or a completion date.

**Comment by clach04** [comment]
I agree, the image contradicts the text. I believe the text file is clear on the rules for dates and should be used as primary source, see https://github.com/todotxt/todo.txt#rule-2-the-date-of-completion-appears-directly-after-the-x-separated-by-a-space 

* **Completion** dates are **required**
* *Creation* dates are *optional*

**Comment by callegar** [comment]
You are probably right, but English text is not the best tool to specify a formal grammar and is always going to be ambiguous and subject to some interpretation (e.g. would a tool only using the key:value format and never the parenthesis based notation to express priority be within the golden standard? If in a non completed task I specify a priority with `(...)` and then again with `pri:..` is it OK? And if they do not agree?).

The very conclusion "completion dates are required, creation dates are optional" appears a quite reasonable extrapolation from the text, but the text never says so explicitly :-(

I fear that with this loose specification there are always going to multiple not fully interoperable dialects of `todo.txt`. Maybe, at least formalizing one and giving a name to it could be a good thing (just like people caring about correct interoperability refer to "GitHub Markdown " or "CommonMark Markdown" or "Pandoc Markdown", because Markdown...)

Personally, I would like to have the creation dates for tasks, because it is always easy to transform a text file removing some information, but augmenting it later to add some missing piece is impossible. It is also a pain I have to write these dates manually at every task creation, so I wish bug 474 and bug 401 could get fixed. It is always a matter of personal usage practice what is best, so I am totally happy about having this under an option (after it is fixed, promoting it to not being hidden would help, though).

Incidentally,  I also find it rather inelegant that you need to use two different ways to specify priority depending on whether the task is completed or not. Personally I would not dislike a dialect allowing `x (A) 2023-05-01 ...` enabled under an option.

Incidentally it seems weird that the rationale about almost every aspect of the specification seems to be *natural sorting*, given that this is a computer related standard, so the only important thing would be to make it easy to isolate the individual fields of the record, so that you can sort based on any field in any order with plain text manipulation tools.

**Comment by rzw** [comment]
> I think that it is because otherwise having a single date it would be impossible to know if it is a creation date or a completion date.

Not really. First date after x is completion date since completion dates are required
