### ISSUE TITLE
Provide some minimal `git` integration

### ISSUE THREAD

**Issue by callegar** [ransome1/sleek#489]
**Did you check if a similar feature request has already been reported?**

Checked, not reported

**Is your feature request related to a problem? Please describe.**

Keeping old versions of the tasks (in case some task is accidentally deleted), easing synchronization of tasks among multiple computers.

**Describe the solution you'd like**

`todo.txt` files are line based text files. This is the ideal format for taking diffs and for storing in a revision control system, such as `git`. Would be great to have some form of `git` integration modeled after what is offered in the pass password manager (https://www.passwordstore.org/) and its QtPass frontend (https://github.com/IJHack/QtPass).

This would work as follows:

1. When `sleek` realizes that a configured todo file is in a directory under `git` control (i.e., with a `.git` subdir) and that `git` is available, activate `git` integration
2. When `git` integration is active if a todo file in a directory under revision control is modified, perform a commit in that dir. Alternatively, provide a commit button for the user to manually commit the file being worked upon to `git`
3. Provide a pull and a push button, resulting in `git pull` and `git push`.

**Comment by mimmori** [comment]
+1

**Comment by callegar** [comment]
Unclear to me whether this will automatically be closed also in the sleek 2.x backlog. Please, keep it open there.

**Comment by ransome1** [comment]
Your comment should be enough to keep it open.

**Comment by andrei-a-papou** [comment]
At least for Unix-like systems, an easy solution is to use https://github.com/gitwatch/gitwatch. Not sure, but it should  work with Cygwin/WSL/Git Bash/etc.

Also Syncthing can be quickly configured to keep a bunch of backups (might be enough in many cases -- and this is what I'm using right now.)

**Comment by callegar** [comment]
Most important: has the existence of the issue spotted in arch been excluded in other distros using OCaml 5.x?
