### ISSUE TITLE
Suggestion: Clear a button's focus when the button is pressed

### ISSUE THREAD

**Issue by HerrSersch** [ransome1/sleek#49]
There are some buttons that become focused when pressed, which results in an outline around the button. This can look odd, especially for on/off toggle buttons.

Locations where this happens and probably shouldn't (you might disagree with some of them):
- the Show filters button at the top
- the View menu button
- the two switches inside the View menu
- switches in the settings
- the Toggle dark mode button

**Comment by HerrSersch** [comment]
Another problem related to this that I just noticed: the tabs at the top of the Help and Settings menu are focused as well and get a blue outline. The bottom part of this outline disappears when the Sleek window has a very small vertical size close to or equal to the allowed min size.

**Comment by ransome1** [comment]
@HerrSersch, feel free to check 0.9.2 and give it some testing: https://github.com/ransome1/sleek/releases/tag/v0.9.2

**Comment by HerrSersch** [comment]
Thank you for this super fast fix. It might seem like a minor thing, but at least for me the UI feels much more polished now :) I tested 0.9.2 and couldn't find any buttons that show the old behaviour from 0.9.1.

**Comment by ransome1** [comment]
You're welcome :)
