### ISSUE TITLE
Add `pct:` custom tag (or something similar) to keep track of progress

### ISSUE THREAD

**Issue by callegar** [ransome1/sleek#490]
**Did you check if a similar feature request has already been reported?**

Checked, not reported.

**Is your feature request related to a problem? Please describe.**

I think that it would be great to have the option to use a custom tag (e.g. `pct:`) to keep track of progress on tasks on which activity had to be interrupted. I do not know if other `todo.txt` task managers have something similar or if they have agreed on the tag name. In case, it would be great to take inspiration from them.

**Describe the solution you'd like**

Support a custom tag (e.g., `pct:`) to keep track of progress on a task on which activity had to be interrupted. In the example `pct:` would stand for percentage.

When a task has the filed, sleek should show a completion indicator (either merely reporting the percentage or showing a progress bar).

On completion, the field should be removed.

**Comment by ransome1** [comment]
Sorry for my late reply. I'm currently rewriting large chunks of sleeks, to make it more maintainable. While doing so, this should be a low hanging fruit. I'll add it to the backlog. It will take time though, as there is plenty of technical depth to take care of first.

**Comment by callegar** [comment]
Thanks for the update!
