### ISSUE TITLE
[Windows] Parameter is incorrect

### ISSUE THREAD

**Issue by onCTi** [ransome1/sleek#493]
![image](https://github.com/ransome1/sleek/assets/66562409/a99525ec-39b1-4884-b19a-e70381932dbe)

**Describe the bug**
installed the app on my work computer through the microsoft store. When I try to open the app, the error above pops up. Cannot proceed further. 

**To Reproduce**
1. Go to 'microsoft store'
2. Click on 'get sleek'
3. Click 'open'
5. See error

**Do you see any error entries in sleeks developer tools?**
cant get that far.

**Expected behavior**
App opening

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version of sleek: 1.3.1.0
 - Source:  Windows Store

**Comment by ransome1** [comment]
@onCTi can you please check if this still happens in v2.0.1, which should be available in Windows store now.

**Comment by ransome1** [comment]
Feel free to re-open, if this still occurs.
