### ISSUE TITLE
Todo aging

### ISSUE THREAD

**Issue by nov1n** [ransome1/sleek#494]
It would be useful to have support for todo aging similar to Trello's [card aging power-up](https://trello.com/power-ups/55a5d917446f517774210012).

The idea is that it should be possible to see at a glance (e.g. by fading them based on how long a todo has been left undone) which ones need some attention.

**Comment by ransome1** [comment]
@nov1n you mean to basically compare the creation date of a todo with the current date and based on the time difference between both, coloring them?

I don't use trello, so I don't know how this is being done over there. From what I can see in your link, it looks like users need to define their understanding of what makes a todo aged, correct?

**Comment by nov1n** [comment]
Yes, by default the plugin fades the opacity of the cards, but the visual feedback can be anything.

The main goal is to prevent to-do's from staying in a list too long. I don't think it's necessary to include cards with a due / threshold date in the future, as these have some action planned.

In addition, I could think of a filter to display stale to-do's to help clean up your list.
