### ISSUE TITLE
Ctrl-Alt-Del on Windows deletes an item from the to-do list

### ISSUE THREAD

**Issue by idavi-bcs** [ransome1/sleek#499]
**Describe the bug**
When Sleek is in the foreground, and I press Ctrl+Alt+Delete on my Windows workstation to lock the screen, an item is deleted from my todo list.

I expect this bug was probably introduced in #409.  Because Sleek lacks an Undo feature (as far as I can tell), this is particularly destructive -- I often don't even know what got deleted, and there's no record of it in todo.txt or todo_done.txt.  It had to happen a number of times before I figured out what was going on.

**To Reproduce**
1. Open Sleek 1.3.1 on Windows.
2. Add at least one item.
3. Press Ctrl+Alt+Delete.
4. Note that a todo item has been deleted.

**Do you see any error entries in sleeks developer tools?**
N/A

**Expected behavior**
I expect items to be deleted only when Delete is pressed without modifier keys, as introduced in #409.  As Ctrl+Alt+Del is a system-level shortcut, it should not trigger application actions.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version of sleek 1.3.1
 - Source: Github

**Comment by ransome1** [comment]
@idavi-bcs this should not be an issue any longer in `2.0.0`.
