### ISSUE TITLE
Copy paste of items (links and plain text) macOS

### ISSUE THREAD

**Issue by indiewelt** [ransome1/sleek#50]
Hi - I encountered something which is I think a bug. Pasting of text content is not possible on the Mac Version. When I press CMD+V or try to right click into the field nothing happens. I tested it side by side with other clients on Mac e.g. TodotxtMac where I don't have this issue. Do you know what could be causing this behaviour? 
I am using version 0.9.0 on macOS big sur latest update.

**Comment by ransome1** [comment]
Hi @indiewelt . Thanks for submitting the issue. I could not reproduce it on either Linux or Windows, but I did some digging and learned, that for MacOS I need to do some extra steps, before copy and and pasting will be working. I will fix it in the next release. Only problem is, that I won't get my hands on an Apple machine for the next two months at least and therefor won't be able to build new releases.

But what I do is labeling this issue with "help wanted" and maybe some Mac user can build the next release for me and add it to the next release.

**Comment by intrepidsilence** [comment]
I am willing to help by building the release. Contact me and we can get it done.

**Comment by ransome1** [comment]
@intrepidsilence . That would be great. Do you know how it works?

If not:
1. Install NPM: https://www.npmjs.com/get-npm
2. Fork sleek and pull the master branch **or** simply download the master branch as a zip here on Github and extract it
2. Open the package.json file and change this line `"dist": "electron-builder -wl --publish always",` to "dist": `"electron-builder -m --publish never",`
3. Use terminal and switch into sleeks folder and `run npm dist`

That should build the .dmg file. If that worked we can figure out if the fix worked and upload it here.

**Comment by intrepidsilence** [comment]
Are you sure `npm dist` is correct? That does not seem to work.

**Comment by ransome1** [comment]
sorry, my mistake, it's `npm run dist`

**Comment by intrepidsilence** [comment]
Looks like I need electron-builder, too.  Looking now...

**Comment by ransome1** [comment]
Try a `npm install`, it should install electron builder if I'm not mistaking

**Comment by intrepidsilence** [comment]
Yes, that worked but apparently it is too new - what version of EB do I need?

**Comment by ransome1** [comment]
I'm building with 22.9.1

**Comment by intrepidsilence** [comment]
Bingo!  How would you like me to get you the build dmg?

**Comment by intrepidsilence** [comment]
I have performed initial tests and everything seems to be working, including pasting into an editor field.

**Comment by ransome1** [comment]
I was writing to ask you for quick test :)

It won't propably work, but can you try to upload the dmg to a comment here? It will propably clash by it's file size. You could upload it to some file hoster like wetransfer and send me the link.

**Comment by intrepidsilence** [comment]
Yep, it is too big. Looking for a good method now...

**Comment by intrepidsilence** [comment]
wetransfer needs a TO email address. Is there one you can share here?

**Comment by ransome1** [comment]
you can use ransome@uber.space

**Comment by intrepidsilence** [comment]
Sent!

**Comment by ransome1** [comment]
Hi @indiewelt, thanks to @intrepidsilence we now have a MacOS build in which the copy&paste of text should be working: https://github.com/ransome1/sleek/releases/download/v0.9.3/sleek-0.9.3.dmg

**Comment by indiewelt** [comment]
Hi @ransome1 and @intrepidsilence  -  Thank you two so much - I just tested it and it works. It was amazing to see how you solved it in no time. I don't understand what this behaviour has caused but I am happy that it works now. Have a nice weekend.

**Comment by intrepidsilence** [comment]
Just happy that I was able to help out.
