### ISSUE TITLE
Recurring Task Recurrence Anomaly

### ISSUE THREAD

**Issue by qalisto** [ransome1/sleek#502]
VER:  1.3.1 (and also just prior ver)

**Did you check if the bug has already been reported?**
NONE FOUND

**Describe the bug**

Upon producing a New Entry window, at any random interval, the Window produces an unwanted / unselected "Every 3 Months" as a recurrence instead of the expect "No recurrence" 

Upon Esc / cancellation of window and second try using "n" ... the anomaly is *not* there.  It is a normal "No recurrence" default.

**To Reproduce**
initiate any "new entry" method,  key: "n" or click "+", etc.

Observe Data Entry Window bearing "Every 3 Months"

**Do you see any error entries in sleeks developer tools?**

Unable to open this panel.

**Expected behavior**
see above

**Screenshots**
  Simply imagine an entry window with  "Every 3 Months"  active at the get-go
  
**Desktop (please complete the following information):**

System:
  Kernel: 5.10.0-23-amd64 x86_64 bits: 64 compiler: gcc v: 10.2.1 
  Desktop: Xfce 4.18.1 tk: Gtk 3.24.24 info: xfce4-panel wm: xfwm 4.18.0 vt: 7 
  dm: LightDM 1.26.0 Distro: MX-21.3_x64 Wildflower January 15  2023 
  base: Debian GNU/Linux 11 (bullseye) 
Machine:
  Type: Desktop Mobo: ASRock model: H170M-ITX/DL serial: <filter> 
  UEFI: American Megatrends v: P7.10 date: 10/26/2016 
CPU:
  Info: Quad Core model: Intel Core i7-6700 bits: 64 type: MT MCP 
  arch: Skylake-S rev: 3 cache: L2: 8 MiB 
  flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx 
  bogomips: 54398 
  Speed: 800 MHz min/max: 800/4000 MHz Core speeds (MHz): 1: 800 2: 800 3: 800 
  4: 800 5: 800 6: 800 7: 801 8: 800 
Info:
  Processes: 507 Uptime: 3d 23h 5m wakeups: 5 Memory: 31.03 GiB 
  used: 16.3 GiB (52.5%) Init: SysVinit v: 2.96 runlevel: 5 default: 5 
  Compilers: gcc: 10.2.1 alt: 10 Shell: Bash v: 5.1.4 
  running-in: xfce4-terminal inxi: 3.3.06 

 - Source: Flathub,  Installed 16 Jul 2023
 
 ---------------------------------------------------
 Befuddled.  :(

**Comment by ransome1** [comment]
@qalisto Thank you for reporting this. Could you check, if this still happens in the current developer preview of 2.0? https://github.com/ransome1/sleek/releases/tag/v2.0.0-dev3

**Comment by qalisto** [comment]
my goodness!  on the same (prev. ref'd) sys cfg, using an "Execute-Enabled" v 2.0 d3 "AppImage" 80% of function attempts freeze.  Cannot open new file, nor Options, nor reload, nor reset.  But v 1.3 upon relaunch exhibit no issues other than the ref'd 3 Month Recurrence persistence.

**Comment by ransome1** [comment]
> my goodness! on the same (prev. ref'd) sys cfg, using an "Execute-Enabled" v 2.0 d3 "AppImage" 80% of function attempts freeze. Cannot open new file, nor Options, nor reload, nor reset. But v 1.3 upon relaunch exhibit no issues other than the ref'd 3 Month Recurrence persistence.

You are aware of that this is an early developer preview and that many parts of the app are still missing? 

> Cannot open new file, nor Options, nor reload, nor reset
Feel free to share more details, it's hard to guess what's going wrong on your side.

> 2.0 as appimage = unusable :O
As described in the release notes, it's not meant for daily use, it's for developers to get onboarded and receive constructive feedback on it.

**Comment by qalisto** [comment]
MORE ANOMALOUS BEHAVIORAL DATA:

(Note: thanks for clarifying Dev Rls characteristics.  I thought it perhaps contained all prior working functions except improvements.)

I just noticed that when I open some notes that indicate they have some Recurrence setting, will, upon Opening, show that actually, the Text that should cause that indication while Closed - is *absent*.

So, my worries about unwanted Recurrences may not be warranted, but that there is a bug that shows a Closed entry falsely representing that there is some internal "rc:xx".

I observed this across all Recurrence time-spans.  Thus, we cant be certain of whether the task is actually going to Recur, if created that way unless each task is opened for audit.

Strange.##

**Comment by ransome1** [comment]
> MORE ANOMALOUS BEHAVIORAL DATA:
> 
> 
> 
> (Note: thanks for clarifying Dev Rls characteristics.  I thought it perhaps contained all prior working functions except improvements.)
> 
> 
> 
> I just noticed that when I open some notes that indicate they have some Recurrence setting, will, upon Opening, show that actually, the Text that should cause that indication while Closed - is *absent*.
> 
> 
> 
> So, my worries about unwanted Recurrences may not be warranted, but that there is a bug that shows a Closed entry falsely representing that there is some internal "rc:xx".
> 
> 
> 
> I observed this across all Recurrence time-spans.  Thus, we cant be certain of whether the task is actually going to Recur, if created that way unless each task is opened for audit.
> 
> 
> 
> Strange.##

I read your text a couple of times but I have to admit, I don't understand it. Maybe there is something lost in translation on my side. Maybe it helps if you add some screenshots to your description.

Also, are you referring to v1.3.1 or any of the developer previews?

**Comment by ransome1** [comment]
@qalisto this thread is confusing me. Can you please summarize the actual issue for me again based on the latest developer preview. Does it occur here: https://github.com/ransome1/sleek/releases/tag/v2.0.0-dev5

**Comment by ransome1** [comment]
Closing due to lack of response. Feel free to reopen, if this still occurs in latest developer preview.
