### ISSUE TITLE
Projects as Kanban Boards

### ISSUE THREAD

**Issue by AaronKnowls** [ransome1/sleek#506]
**Is your feature request related to a problem? Please describe.**
On big projects, having a more precise, useful, practical way of prioritizing and sorting tasks.

**Describe the solution you'd like**
A way to show boards for tasks, where columns could be apply by using @contexts (columns for example as @doing, @next, @done) or even some other character prefix.

**Describe alternatives you've considered**
I tried using the KanbanTxt python script, but using the magnificent sleek with be much efficient.

Thank you so much for this amazing software. I use it everyday. Thank you thank you thank you.

**Comment by ransome1** [comment]
Hi @AaronKnowls . This sounds like a large feature. I myself will probably not working on it. But there might be contributers who would. In any case I think it makes sense to close this request and start a discussion about this beforehand. Without precise requirements, nobody will pick up on it.
