### ISSUE TITLE
CAlDAV synchronization

### ISSUE THREAD

**Issue by ecxod** [ransome1/sleek#507]
Interfaces are more important than the software

it needs a caldav synchronization

**Comment by ransome1** [comment]
Might be relevant. But if I put in countless of hours into developing this app, you can put in more than 10 seconds in writing a proper feature request. Feel free to do that, otherwise I'll close here.

**Comment by CPUGPU** [comment]
I think doing anything other than accessing files using the filesystem is really outside the scope of the project.  There are other ready-made tools for synchronizing text files across systems and networks.

**Comment by warmwaffles** [comment]
Do one thing, and do it well.
