### ISSUE TITLE
Reduce size of filters section

### ISSUE THREAD

**Issue by AaronKnowls** [ransome1/sleek#509]
**Describe the bug**
When reducing the size of the filters section, the new size gets lost once you release the mouse button, and goes back to its default state. 

**To Reproduce**
1. Go to 'icons left bar'
2. Click on 'filters'
3. Try to resize it by dragging from the middle line to the left and release the mouse button

**Expected behavior**
Allowing to make that left filters section smaller (allowing even just one project, context per line)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version of sleek 1.3.1
 - Source: Github

**Comment by ransome1** [comment]
Hi @AaronKnowls thanks for your bug report. I am rewriting sleek a the moment. This part of sleek has already been rewritten and I would like to ask you for feedback. Does this bug also occur in the latest developer preview of sleek? https://github.com/ransome1/sleek/releases/tag/v2.0.0-dev5

Please backup your todo data, as this is still a version in development.

**Comment by ransome1** [comment]
> It does work!
> 
> 
> 
> I love the new location of the view modes inside the filters section.
> 
> 
> 
> Thank you, @ransome1!

Thank you :)
