### ISSUE TITLE
Archiving todos gives an error, finished todos are deleted but not saved

### ISSUE THREAD

**Issue by HerrSersch** [ransome1/sleek#51]
Trying to archive todos in 0.9.2 gives me the following error message on Win7 and Linux Mint Cinnamon 20.1:

![archive error](https://user-images.githubusercontent.com/35151158/109729196-cccab380-7bb7-11eb-883f-7a899c62341c.png)

All finished todos are erased from the project but not backed up in a done.txt. I tried creating a done.txt manually and out of curiosity also renamed my todo document to todo.txt, but to no avail.

**Comment by ransome1** [comment]
Hi @HerrSersch, that should be fixed in 0.9.3, could you check it please? https://github.com/ransome1/sleek/releases/tag/v0.9.3

**Comment by HerrSersch** [comment]
Fix confirmed on Mint Cinnamon 20.1 for the .AppImage, .deb and flatpak version. Thank you :)

The error message is gone on Win7 and Win10, but no done.txt is created. An existing done.txt is also not updated.

**Comment by ransome1** [comment]
@HerrSersch, could you please take a look at this release, if the issue remains? https://github.com/ransome1/sleek/releases/tag/v0.9.4-Beta

**Comment by HerrSersch** [comment]
I've tested it on Win7 and Win10, it works on both systems now. Thank you :)

**Comment by ransome1** [comment]
Awesome, thanks :)
