### ISSUE TITLE
Anchor windows with tabs at the top instead of centering them vertically to avoid jumping headings

### ISSUE THREAD

**Issue by HerrSersch** [ransome1/sleek#52]
The About and Settings popup menus are currently centered vertically on the screen. They grow and shrink evenly when the content size changes. This is visually appealing, but introdues the problem of jumping headings. This makes quick switching between tabs difficult, as in addition to moving the mouse cursor left and right one has to move up and down too.

![align windows at the top](https://user-images.githubusercontent.com/35151158/109731061-dace0380-7bba-11eb-916e-49f51229a36d.png)

**Comment by ransome1** [comment]
I have no objection, it's implemented in 0.9.3: https://github.com/ransome1/sleek/releases/tag/v0.9.3

**Comment by HerrSersch** [comment]
Thank you, that's much better :) The effect is fully gone when sleek's window is big enough to fit the entire content in it. There's a bit of jumping left when the window is smaller and requires scrolling. I believe this is a different issue than the original one, because it's probably not related to the content window's alignment:

https://user-images.githubusercontent.com/35151158/109937280-0510e580-7ccf-11eb-8153-cecd005fde7d.mp4

This is more of a visual thing though, it doesn't impact usability anymore.

**Comment by ransome1** [comment]
@HerrSersch, that should be fixed now in https://github.com/ransome1/sleek/releases/tag/v0.9.4

**Comment by HerrSersch** [comment]
I can confirm that it is, thank you :)
