### ISSUE TITLE
AppImage not starting on Debian Sid

### ISSUE THREAD

**Issue by Doc73** [ransome1/sleek#520]
## Bug Report

**App Version:** sleek-1.3.1.AppImage

**Platform:** Debian Sid

**Installation Method:** Direct Download

**Bug Description:**
```
$ ./sleek-1.3.1.AppImage 
dlopen(): error loading libfuse.so.2

AppImages require FUSE to run. 
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
```
`libfuse2` is still available in repos, but the default is `libfuse3-3`

**Steps to Reproduce:**
See above

**Expected Behavior:**
App starting

**Actual Behavior:**
App doesn't start

**System Information:**
- OS Version: Debian Sid
- Processor: Intel® Core™ i5-8250U × 8
- RAM: 8GB
- Graphics Card: Intel® UHD Graphics 620 (KBL GT2)

**Reproducibility:**
- Works in Debian Stable, not in Debian Sid (I did no tests on other linux systems)

**Impact:**
- ?

**Comment by ransome1** [comment]
Thanks for the report. Can I ask you to check the AppImage of the latest developer preview of v2.0? https://github.com/ransome1/sleek/releases/tag/v2.0.0-dev9

It's built based on significant new dependencies. I'm curious if the issue persists.

**Comment by Doc73** [comment]
@ransome1 
Same issue with v. 2.0

**Comment by ransome1** [comment]
mmhh I dont know. But if it runs on Debian Stable and asks for FUSE to be required but not found on Debian Sid, doesn't it indicate that there is something missing on Debian Sid? I wouldn't know how to fix this in sleek.

**Comment by Doc73** [comment]
@ransome1 
Yes, I think that it is missing `libfuse2`, replaced by `libfuse3-3`.
`libfuse2` is still available in Debian Sid repositories: [https://packages.debian.org/it/sid/libfuse2](https://packages.debian.org/it/sid/libfuse2)

Here its history: [https://tracker.debian.org/pkg/fuse](https://tracker.debian.org/pkg/fuse)

The question is: how long will it be available?

**Comment by Doc73** [comment]
Ok! This is not a bug strictly speaking.

I don't know if an AppImage can be build to work with `fuse3`. If so, consider what is best to do, otherwise, please close this bug report,

Cf. [https://docs.appimage.org/user-guide/troubleshooting/fuse.html](https://docs.appimage.org/user-guide/troubleshooting/fuse.html)

Many thanks in any case,
Domenico

**Comment by ransome1** [comment]
I'm not actively deploying FUSE so I assume it's a dependency Electron Builder (within my building pipeline this creates all the releases of sleek) use to build the AppImage. There is probably nothing I can actively do about it. But if anybody proves me wrong I'm happy to adjust sleek. But as for now I hope you understand I can't make research on this a priority for me. I'm happy to keep your report in the backlog though.

**Comment by Doc73** [comment]
@ransome1 
Yes, sure! I understand!
In the meantime, I can confirm that installing `libfuse2` solves everything.
We'll see what the future holds for us. :smile:

**Comment by ransome1** [comment]
@Doc73 shall we close here? I don't think there is anything I can do about it.

**Comment by Doc73** [comment]
Yes! You can close this issue.
If you want, you could add somewhere here the suggestion to install `libfuse2`.
When one day `libfuse2` will be completely missing from the repositories, well!... then we'll see whot to do! :smile:
