### ISSUE TITLE
Serious rendering issues for todo items with URLs

### ISSUE THREAD

**Issue by essenciary** [ransome1/sleek#524]
## Bug Report

**IMPORTANT:**
Please follow this template strictly when reporting bugs. Providing detailed and accurate information helps the development team to understand and address the issue effectively.

**App Version:** [Enter app version here]
1.3.1 (would help to place the About in the expected menu on macOS, otherwise it's hard to find)

**Platform:** [Windows / macOS / Linux]
macOS

**Installation Method:** [App Store / Direct Download / Other]
App Store

**Bug Description:**
UI flickers continuously 

**Steps to Reproduce:**
Create a todo item with the following content: 
```
(E) FastAPI research +🧠 @research 
https://fastapi.tiangolo.com 
https://fastapi.tiangolo.com/tutorial/
```

**Expected Behavior:**
UI not to flicker 

**Actual Behavior:**
See attached gif

**Additional Information:**
See attached gif

**Screenshots:**
![2023-09-19 09 01 49](https://github.com/ransome1/sleek/assets/11292378/3f06d2c0-2e8c-4464-ac80-51b40904d7ad)

**System Information:**
- OS Version: macOS 14.0
- Processor: M2 Pro
- RAM: 16GB

**Reproducibility:**
- Sometimes

**Impact:**
- Major

**Workaround:**
- Poke at it random by scrolling the list, resizing the window.

**Comment by ransome1** [comment]
Thanks for the report. Looks like it's connected to the "extract title from website" feature. Something I'm not really sure I want to keep alive in the future tbh. You can disable it in the settings.

I'm currently rewriting sleek and I'm not sure if I want to stick to this feature.

**Comment by essenciary** [comment]
Got it, thanks for the info, I'll disable it.

**Comment by ransome1** [comment]
I decided not to adapt this feature into 2.x. And since there is no further development in 1.3.x, I'll close here. Hope you don't mind.
