### ISSUE TITLE
Alternative Menu for Navigation using Alt Keys returns Errors when executing commands

### ISSUE THREAD

**Issue by DhominickJ** [ransome1/sleek#527]
## Bug Report

**IMPORTANT:**
Please follow this template strictly when reporting bugs. Providing detailed and accurate information helps the development team to understand and address the issue effectively.

**App Version:** 1.3.1

**Platform:** Windows

**Installation Method:** Winget

**Bug Description:**
Using the electron alternative navigation menu for using keyboard only, I encountered a bug when I used the alt menu. It returns a strange bug about a condition not executing an event. Included below is a screenshot of such action. Thank you for your hard work on this app, I really appreciate it. :)

**Steps to Reproduce:**
1. Press alt button.
2. Navigate the action bar
3. Press File and create a new task
4. Returns error

**Expected Behavior:**
Open up a menu to enter and create a new task.

**Actual Behavior:**
Returns an error.

**Additional Information:**
None

**Screenshots:**
[If applicable, include screenshots that demonstrate the bug.]

**System Information:**
- OS Version: Windows 11
- Processor: Ryzen 3 5300U
- RAM: 6gb ram
- Graphics Card: Integrated Graphics

**Reproducibility:**
- Always

**Impact:**
- Moderate

**Workaround:**
Not using the alternative menu.
![Screenshot 2023-09-28 101016](https://github.com/ransome1/sleek/assets/124448401/eaab147a-0e5e-4eb3-8df2-c645f577c62a)

**Comment by ransome1** [comment]
Thanks for reporting sleek is currently being rewritten. I'll make sure this doesn't happen in the upcoming 2.0. If you want to contribute to the testing of the current state of the rewrite, please feel free: https://github.com/ransome1/sleek/releases/tag/v2.0.0-dev14

It's a preview, not all features have been re-implemented yet.

**Comment by DhominickJ** [comment]
Thank you for your kind reply. I'll try to help with something if given the chance to. :)
