### ISSUE TITLE
Priority on new tasks is broken in 2.0.0-dev13

### ISSUE THREAD

**Issue by swantzter** [ransome1/sleek#528]
## Bug Report

**IMPORTANT:**
Please follow this template strictly when reporting bugs. Providing detailed and accurate information helps the development team to understand and address the issue effectively.

**App Version:** 2.0.0-dev13

**Platform:** Windows

**Installation Method:** Direct Download

**Bug Description:**
a) Writing priority in the "main" input field clears the input field
b) Setting priority using the dropdown adds duplicate priority to the "main" input field

**Steps to Reproduce:**

a)

1. Open the dialog to create a new task
2. Type "(A) "
3. The input field will be cleared

b)

1. Open the dialog to create a new task
2. Select priority A in the priority dropdown
3. The input field will be filled in with "(A) (A) "

**Expected Behavior:**
a) The input field is not cleared and I can continue typing the TODO
b) Only one (A) should be prepended

**Actual Behavior:**
a) The input field is cleared, (and the priority dropdown is not changed)
b) The input field is prepended with "(A) (A) "

**Additional Information:**

**Screenshots:**

**System Information:**
- OS Version: Windows 11
- Processor: Intel Core i7
- RAM: 32GB
- Graphics Card: NVIDIA GeForce GTX 1650 Ti

**Reproducibility:**
- Always

**Impact:**
- Major

**Workaround:**

**Comment by ransome1** [comment]
This is fixed by now, but let me to way more refactoring. Should be available in the next developer preview.

**Comment by ransome1** [comment]
@swantzter same here: https://github.com/ransome1/sleek/releases/tag/v2.0.0-dev14

**Comment by swantzter** [comment]
-dev14 solves this

I note that it would be neat if the priority dropdown updated based on what you type in the input field, similar to how the input field updates if you change the priority dropdown, but that's separate from this bug

**Comment by ransome1** [comment]
@swantzter I agree, could be low priority enhancement. But if that will be implemented, the same thing must apply to all other available attributes. Feel free to open up a feature request and I'm happy to add it to the backlog.
