### ISSUE TITLE
Settings and filters are not persisted across updates

### ISSUE THREAD

**Issue by swantzter** [ransome1/sleek#529]
## Bug Report

**IMPORTANT:**
Please follow this template strictly when reporting bugs. Providing detailed and accurate information helps the development team to understand and address the issue effectively.

**App Version:** 2.0.0-dev-9, 2.0.0-dev10, 2.0.0-dev11, 2.0.0-dev12, 2.0.0-dev13

**Platform:** Windows

**Installation Method:** Direct Download

**Bug Description:**
After installing a new version using the `sleek-2.0.0-<version>-win-Setup.exe` my settings and filters revert to the defaults

**Steps to Reproduce:**
1. Change theme in settings
2. Enable "append creation date when todo is created" in settings
3. Disable "Completed todos" in filters
4. Update sleek from say 2.0.0-dev12 to 2.0.0-dev13

**Expected Behavior:**
My settings and filters will persist

**Actual Behavior:**
The settings and filters are reverted to their defaults

**Additional Information:**

**Screenshots:**

**System Information:**
- OS Version: Windows 11
- Processor: Intel Core i7
- RAM: 32GB
- Graphics Card: NVIDIA GeForce GTX 1650 Ti

**Reproducibility:**
- Always

**Impact:**
- Moderate

**Workaround:**
Manually fix the settings

**Comment by ransome1** [comment]
This is not a bug, it is a temporary function of the development versions. With each update a new set of configurations will be created, in order to avoid conflicts. When 2.0 goes into production, this will be deactivated.
