### ISSUE TITLE
Dark mode is not saved

### ISSUE THREAD

**Issue by gerroon** [ransome1/sleek#53]
Hi

I keep setting it to the dark mode (both in the left bar and in the settings) but it keeps going back to the light theme during the next start. 

I am using it on Debian Testing, Flatpak, v0.9.0

thanks

**Comment by ransome1** [comment]
Hi @gerroon . Could you please update to 0.9.2 (should be available now) and tell me if the problem is solved for you?

**Comment by gerroon** [comment]
Hi

It seems to start with the dark mode, thanks for the fix.
