### ISSUE TITLE
sleek v2 regresses behaviour of friendly dates

### ISSUE THREAD

**Issue by gdarcy** [ransome1/sleek#535]
## Bug Report

**IMPORTANT:**
Please follow this template strictly when reporting bugs. Providing detailed and accurate information helps the development team to understand and address the issue effectively.

**App Version:** v2.0.0-dev12

**Platform:** Windows

**Installation Method:** Direct Download

**Bug Description:**
When adding a date by day name, days earlier in the week are interpreted as the date earlier in the week rather than the date in the following week.

**Steps to Reproduce:**
1. Specify a date (verified with due and threshold) by naming the day of the week as a day that has already passed (note that SugarJS considers that the week starts on Sunday)
2. Observe that the actual date selected is a date that has already passed.

**Expected Behavior:**
The ambiguous date should be interpreted as a future date. This was previously addressed against #199 in sleek v1.x.

**Actual Behavior:**
The ambiguous date is currently interpreted as being in the current week regardless of whether that is a past or future date.

**Reproducibility:**
- Always

**Impact:**
- Minor

**Comment by ransome1** [comment]
@gdarcy has been released as part of https://github.com/ransome1/sleek/releases/tag/v2.0.0-dev15. Could you please check if it works on your side as expected?

**Comment by ransome1** [comment]
Thanks again for being attentive and providing the PR.
