### ISSUE TITLE
Entries with threshold date not showing when "future due" tasks option is switched off

### ISSUE THREAD

**Issue by akusel** [ransome1/sleek#537]
## Bug Report

**IMPORTANT:**
Please follow this template strictly when reporting bugs. Providing detailed and accurate information helps the development team to understand and address the issue effectively.

**App Version:** 1.3.1-1

**Platform:** Arch Linux

**Installation Method:** AUR

**Bug Description:**
Deferred tasks with a due date are only shown, when the option to show future due tasks and the "deferred date" option are both set. This means, I cannot make sleek show only those tasks where the threshold date has passed without showing all future due tasks.

**Steps to Reproduce:**
1. Make a new task with "t:" set to today's date and "due:" set to one week later.
2. In the settings side panel switch the option "due in future" (or similar – I use the german version: "In der Zukunft fällig") off, but switch the "deferred date" option on.

**Expected Behavior:**
The newly created task should show up, while any tasks with a future due and/or threshold date should stay hidden.

**Actual Behavior:**
The newly created task does not show up.

**System Information:**
- OS Version: Arch Linux 6.4.12-arch1-1-surface
- Processor: Intel Pentium Gold
- RAM: 8 GB
- Graphics Card: onboard

**Reproducibility:**
- Always

**Impact:**
- Major

**Comment by ransome1** [comment]
@akusel I'm not sure if I understand the bug. in your use case, why should the todo show up?

In settings you define two things:
1. Don't show todos with due date in the future (this alone already should hide your new todo, since it has a due date set in the future)
2. Show todos with threshold date in the future (this also should hide your todo, since you set the threshold date to today)

Or do I simply not understand the issue at hand?

**Comment by akusel** [comment]
Thanks for the reply!
I guess, I was just confused about what the filter settings mean, then.
Basically, I just want any tasks to stay hidden until the threshold date has arrived or passed. I now see, that I can achieve this by switching "Due in the future" on and "Threshold date in the future" off.
