### ISSUE TITLE
Recurring task completion generates a Creation date on the new task when it shouldn't

### ISSUE THREAD

**Issue by Piscean** [ransome1/sleek#539]
## Bug Report

**IMPORTANT:**
Please follow this template strictly when reporting bugs. Providing detailed and accurate information helps the development team to understand and address the issue effectively.

**App Version:** [2.0.0-dev13]

**Platform:** [Windows]

**Installation Method:** [Direct Download]

**Bug Description:**
 The Settings dialog says "Append creation date when todo is created".  I have that turned off.  When I complete a recurring task, the newly created task has the creation date at the front of the task.

**Steps to Reproduce:**
1. Turn Append creation date off in settings
2. Create a daily recurring event
--> Verify the creation date wasn't prepended
3. Complete that task
--> Check the todo.txt file and you'll see the task now has a creation date prepended.

**Expected Behavior:**
When a recurring task is completed, the newly created future task should not have the creation date, since I have that setting turned off in Settings.

**Actual Behavior:**
All future tasks will have the creation date

**Additional Information:**
- [Include any additional information that might be relevant to the bug, such as error messages or console logs.]

**Screenshots:**
[If applicable, include screenshots that demonstrate the bug.]

**System Information:**
- OS Version: Windows 10 and 11
- Processor: Intel
- RAM: 16GB & 64GB
- Graphics Card: Intel(R) Iris(R) Xe Graphics Family, Intel Corporation compatible

**Reproducibility:**
- [Always]

**Impact:**
- [Moderate]

**Workaround:**
None

**Comment by ransome1** [comment]
@Piscean could you please check if this still occurs in https://github.com/ransome1/sleek/releases/tag/v2.0.0-dev15?

**Comment by Piscean** [comment]
Okay, that makes sense.  Thank you.  Please consider this solved and close the bug.

Eric
________________________________
