### ISSUE TITLE
minimize after launching sleek (either via setting or command-line option)

### ISSUE THREAD

**Issue by bughunter2** [ransome1/sleek#541]
## Feature Request

**Description:**
Add a --minimize command-line option, or similar, so the program minimizes itself during initialization.
Alternatively, this functionality may be provided via sleek's settings screen.
Or both.

**Use Case:**
Be able to start the program minimized. This way, users can, for example, let the program start minimized after logging on via an autostart script they use, so the program can for example start showing notifications while the user continues to do other things.

**Implementation Details:**
See description above, and see below for additional context.

**Additional Context:**
On Windows, at the moment, the program can already be started minimized by creating a shortcut and adjusting the parameters. So it appears the program already honors the 'nShowCmd' in WinMain().

But, sometimes, a user may want to launch Sleek via an old-fashioned .bat file.
Or..., maybe they use Linux and want to launch Sleek via an .sh script.

In those cases, it may be nice to have a command-line option that tells Sleek to minimize itself during initialization.

That way users can do this:

```
#!/bin/sh
exec /path/to/sleek --minimize
```

Consider this a nice-to-have, not must-have.

**Comment by andrei-a-papou** [comment]
+1 for CLI option
