### ISSUE TITLE
Recurring tasks no longer get a priority

### ISSUE THREAD

**Issue by gdarcy** [ransome1/sleek#543]
## Bug Report

**IMPORTANT:**
Please follow this template strictly when reporting bugs. Providing detailed and accurate information helps the development team to understand and address the issue effectively.

**App Version:** sleek-v2.0.0-dev15

**Platform:** Windows

**Installation Method:** Direct Download

**Bug Description:**
When a task which has recurrence is completed, the newly-created task doesn't have a priority set.

**Steps to Reproduce:**
1. Create a task with both a recurrence and a priority set
2. Complete the task
3. Observe the newly-created task

**Expected Behavior:**
The newly-created task should have the same priority as the previous task in the recurrence.

**Actual Behavior:**
As of -dev15, the newly-created task has the "pri:" extension set at the end of the string, but doesn't have the priority set.

**Additional Information:**
- This is caused directly by the change to address #538, and as noted in that issue, fixing this will currently leave the pri: extension in place on the newly-created task due to the parser limitation.

**Reproducibility:**
- Always

**Impact:**
- Moderate

**Workaround:**
The current workaround is to remember to update the priority manually on every recurring task after it's been cycled.

**Comment by ransome1** [comment]
@gdarcy has been released with https://github.com/ransome1/sleek/releases/tag/v2.0.0-dev16
