### ISSUE TITLE
Enable storing the created date by default

### ISSUE THREAD

**Issue by DeflateAwning** [ransome1/sleek#546]
## Feature Request

**Description:**
Created dates for new tasks don't appear to be stored currently. It would be nice if they were stored.

**Comment by DeflateAwning** [comment]
It appears that they're stored, but I can't figure out where to enable that feature, and I think it should be enabled by default 

https://github.com/ransome1/sleek/wiki/Available-todo.txt-attributes-and-extensions#creation-dates

**Comment by ransome1** [comment]
Hi @DeflateAwning what exactly do you mean with being stored? Are you using 1.3.1 or one of the latest developer previews?

**Comment by DeflateAwning** [comment]
I'm on the 1.3.1 flatpack. I mean stored in the todo.txt file as a field right after the priority

**Comment by ransome1** [comment]
There is no further development in 1.3.1, because sleek is currently being rewritten. In the latest developer preview there is a setting to enable this behavior.

I remember that once this function was default and there was quite some pushback in either an issue or a discussion on GitHub,

**Comment by DeflateAwning** [comment]
I'll concede that the default maybe doesn't matter that much as long as it can be enabled
