### ISSUE TITLE
Add building/running instructions to README, add developer preview info

### ISSUE THREAD

**Issue by DeflateAwning** [ransome1/sleek#547]
Please add building/running instructions to the README. 

I want to try the new devloper preview, but it's not mentioned at all in the README.

**Comment by ransome1** [comment]
Hi @DeflateAwning . Please check the release page on GitHub for the developer previews and if you want to build sleek yourself, this is described in the sleek wiki.

**Comment by DeflateAwning** [comment]
Build instructions should be linked from the README if they're in the wiki. You link to other parts of the wiki in the README, so why not build instructions?

**Comment by ransome1** [comment]
I don't consider them important enough for the common sleek user. The build instructions become important if you want to become a contributer. The CONTRIBUTING.md contains all these information.
