### ISSUE TITLE
Archiving tasks whose description contains a comma breaks the archive file

### ISSUE THREAD

**Issue by callegar** [ransome1/sleek#549]
## Bug Report

**App Version:**

1.3.1

**Platform:** [Windows / macOS / Linux]

Linux

**Installation Method:** [App Store / Direct Download / Other]

appimage

**Bug Description:**

When you archive a task containing a command, the task is archived incorrectly, and a linebreak is substituted for the comma, so breaking the format of the todo file.

I realize that a new version of sleek is under active development, but this is a major flaw causing data loss.

**Steps to Reproduce:**
1. Enter a task with a comma (e.g. `foo, bar`).
2. Mark it as complete
3. Archive it

**Expected Behavior:**

The completed task is archived

**Actual Behavior:**

Sleek writes two lines for this entry in the archive file, one up to the comma and one for the rest of the text after the comma

**Additional Information:**
- [Include any additional information that might be relevant to the bug, such as error messages or console logs.]

**Screenshots:**
[If applicable, include screenshots that demonstrate the bug.]

**System Information:**
- OS Version: [e.g., Windows 10, macOS Monterey, Ubuntu 20.04]
- Processor: [e.g., Intel Core i5, AMD Ryzen 7]
- RAM: [e.g., 8GB, 16GB]
- Graphics Card: [e.g., NVIDIA GeForce GTX 1650, AMD Radeon RX 5600]

**Reproducibility:**
- Always

**Impact:**
- Major

**Workaround:**
[If you found any temporary workaround for the bug, please mention it here.]

**Comment by ransome1** [comment]
With the release of 2.0.0 this should be obsolete. Thanks for reporting it though, please keep on supporting this project.
