### ISSUE TITLE
Feature request: Option to change sorting order from priority to due date

### ISSUE THREAD

**Issue by Rudy96** [ransome1/sleek#55]
Currently the sorting order is by priority and inside the priority sorting is by due date. I in contrary prefer sorting by due date and then by priority. So i can see all tasks on one concrete day ordered by priority. It would be nice, if this sorting order could be integrated as an option, too. Maybe with a button to change between both orders.

**Comment by ransome1** [comment]
Hi @Rudy96. Thanks for your suggestion. 

I added the idea to my feature backlog and will work on it after 1.0 has been released. Up until the 1.0 I will only fix bugs and work on stability. I'll let you know when there is progress.

@all: If anybody wants to throw in a PR in the meantime, feel free.

**Comment by ransome1** [comment]
Hi @Rudy96.

I'm trying to understand how to implement it properly. Would you say a grouping of items, like it is done now with the priority rows A to Z, for the same due day is useful? 

For instance if you would take a look at my todo list, you would see that there is rarely more than one todo on the same due day, but lot's of todos on different due days. Like this mostly each todo would be framed by a grouping element. 

What do you think?

**Comment by Rudy96** [comment]
Hi @ransome1.

Yes, I think that it's useful. At least for me and the way I use my todo list. I usually have 4 to maybe 10 items on the same due day but not so many different due dates. On my actual list for example I have 7 tasks for today, 3 for tomorrow, 6 on sunday, 4 on monday and no more entries for the distant future.

So grouping all tasks for one due day by a headline like its done with the priority rows seems good. And I would suggest a separate headline for all tasks without due dates. To show the priority of each task you can put the letter (A, B, ...) in front of the task title. 

Example:

**2021-03-05**
A example task
A example task
B example task

**2021-03-06**
A example task
B example task
C example task

**2021-03-09**
A example task

**no due date**
A example task
B example task

**Comment by shulist** [comment]
Sorting and grouping are intrinsically tied together and need to be available. It would be great to be able to sort on any field 

> (date [Creation, Threshold, Due, Completion], Context, Project, Priority, Completed, Alphabetical, File order [unsorted]),

 and then group on any one of those. Also in doing that it would also be useful to allow for the hiding of tags to clean up displayed grouped lists.

**Comment by ransome1** [comment]
@Rudy96, is there any good use case in having single due date groups for todos, that lie in the past already? 
![image](https://user-images.githubusercontent.com/11188741/110353840-cfa22a00-8037-11eb-8e14-9af97cce0638.png)

With a lot of overdue todos or a lot of completed todos with given due date, this view really is problematic.

To benefit the user interface I was thinking about grouping all items with a due date before today, starting yesterday, into one single group and putting it at the end of the list. 

I'm not sure on this and would appreciate your input.

**Comment by Rudy96** [comment]
Yes. I think it's consistent to have a group for each day even it they lie in the past. So you can see how far they are in the past (it's only one day or a month). 

And yes, the done tasks are disturbing in the list. For this already done tasks a possibility is to put them to the end of the list (after the tasks group without due dates). Either all in one group "done" or in a separate group with the due date (so you maybe have some due date groups twice; one for open tasks and one for done tasks). For me they aren't important anymore when they are done. And from time to time I archive them, so they aren't many.

P.S.: The layout looks nice.

**Comment by ransome1** [comment]
@Rudy96 , I published a pre-release that already includes the function itself, but still needs refinement on the user interface.

Please feel free and give it some testing: https://github.com/ransome1/sleek/releases/tag/v0.9.4-Alpha

**Comment by shulist** [comment]
In the view with  [completed] selected and [sort by priority] the completed tasks should be grouped at bottom. 	Would it be possible to sort and group by any tag? E.g. Project, Context etc. (See my note above.)

**Comment by ransome1** [comment]
@shulist it sure is possible, but it's a lot of work and as this is a private project my ressources are limited. As the backlog is growing from day to day I'm focusing on the most critical enhancements and bugfixes and features I would actually use myself too. Sorting by tags could be useful to some, but for me filtering by tags does the job. 

Please feel free to open a separate feature request and we can add it to the backlog. Maybe somebody who supports your idea will work on it before I'm able to do it, which at the moment can take some time unfortunately.
