### ISSUE TITLE
2.0.0-dev16 release doesn't have an icon on Linux build

### ISSUE THREAD

**Issue by DeflateAwning** [ransome1/sleek#550]
## Bug Report

**IMPORTANT:**
Please follow this template strictly when reporting bugs. Providing detailed and accurate information helps the development team to understand and address the issue effectively.

**App Version:** 2.0.0-dev16

**Platform:** Linux (Linux Mint 22, Cinamon desktop)

**Installation Method:** GitHub Releases

**Bug Description:**
The icon in the main application bar (not the minimized system tray, but the place open applications go) does not appear. It makes it very tough to open/use Sleek.

**Comment by ransome1** [comment]
@DeflateAwning which release did you download?

**Comment by DeflateAwning** [comment]
The deb

**Comment by ransome1** [comment]
@DeflateAwning could you please check if the icon is back in dev 17? I was only able to check the AppImage. Here it worked, can't vouch for the other Linux releases though.

**Comment by DeflateAwning** [comment]
Just tested. Same issue as before (no logo). I also tested the AppImage, and it also doesn't have a logo for me.

**Comment by ransome1** [comment]
This is what the AppImage looks like on my Arch Linux with XFCE:
![image](https://github.com/ransome1/sleek/assets/11188741/2f418104-e6b6-45b3-8447-84ace9760a9c)

![image](https://github.com/ransome1/sleek/assets/11188741/25d9b8ee-ca7f-4fd8-a636-3ee86a631f74)

![image](https://github.com/ransome1/sleek/assets/11188741/7942efd4-60b6-4bb2-acc5-f0c9f0a463ea)

Can you please share more details on where the logo is missing?

**Comment by ransome1** [comment]
As confirmed in #552 this has most likely been solved.

**Comment by DeflateAwning** [comment]
I can confirm that this is fixed in `sleek_2.0.0-dev20_amd64.deb`. Thanks for fixing it!
