### ISSUE TITLE
option to show shared contexts seperately.

### ISSUE THREAD

**Issue by smellymoo** [ransome1/sleek#559]
## Feature Request

when you have an item with multi @ contexts, it always puts them into their own section which is super annoying, simpletask which is my todo.txt editor for my phone allows you to have them show up under both contexts that they list.

TLDR:

if something has 2+ @ contexts, just list it under both, rather than making a combined group. Best would be a settings option to choose between both behaviours.

**Comment by ransome1** [comment]
Hi @smellymoo . I don't understand what this feature request is about. Can you please help more precise and share examples from Simpletask?

**Comment by smellymoo** [comment]
I am unsure if I am using the right word. But when you have a list item, you can put "@" or "+" as category or sub category.

When you give something 2 different "@" categories, it creates a new category just for ones that have both tags. It would be better if it showed up in both categories.

And for users that like it like this, if it had a option to switch mode :). Thank you, love you work, tried the new 2.0 version and it worked well, I will continue to point out any issues.
