### ISSUE TITLE
Add markdown support

### ISSUE THREAD

**Issue by TriggerDingus** [ransome1/sleek#563]
**App Version:** 2.0.1

**Platform:** Linux

**Installation Method:** Flathub

**Bug Description:**
Before the rewrite, I would occasionally tag important ToDos with ** to bold them or ## to italicize them. For example:
![image](https://github.com/ransome1/sleek/assets/75340371/a70f21c2-0b0c-4e7c-a524-a9568128b09d)

In this case, the item should get created with an absolute date of 1 day from today, in bold lettering. 

The issue is the the ** and ## tags are treated differently in the rewrite in that they are created as part of the task description instead of the tag that they are meant to be. For example, here's a capture of this task created with standard-face font instead of bold or the ## for italics:
![image](https://github.com/ransome1/sleek/assets/75340371/7c29e0e7-9b67-470f-96ce-136fe43f974a)

**Comment by ransome1** [comment]
If this is just about the markdown formatting, it will be released as part of one of the next releases. I think this (the implementation of `marked`, which is the markdown parser I would like to use) is one of [few things left](https://github.com/ransome1/sleek/discussions/562#discussioncomment-7458326), to restore the full functionality of `v1.3.1`.

**Comment by TriggerDingus** [comment]
Yes, I believe this is just the markdown.

**Comment by mshuflin** [comment]
still an issue

**Comment by ransome1** [comment]
@mshuflin @TriggerDingus I added markdown support in the latest pre-release: https://github.com/ransome1/sleek/releases/tag/v2.0.9-rc.1

I would appreciate some testing, if you'll find some time for it.

**Comment by TriggerDingus** [comment]
> @mshuflin @TriggerDingus I added markdown support in the latest pre-release: https://github.com/ransome1/sleek/releases/tag/v2.0.9-rc.1
> 
> I would appreciate some testing, if you'll find some time for it.

Just saw this call to action - sorry for late reply.
I'd be happy to test but I'll be honest and say I did a bunch of Google-fu and I can't figure out how to install/test this pre-release from Github. Consider me Joe-user who knows enough be dangerous, but that's about it.

**Comment by ransome1** [comment]
I think the easiest way on Linux would be to simply download the AppImage release: https://github.com/ransome1/sleek/releases/download/v2.0.9-rc.2/sleek-2.0.9-rc.2.AppImage

**Comment by ransome1** [comment]
@TriggerDingus you might want to rather check https://github.com/ransome1/sleek/releases/tag/v2.0.9-rc.4, since this release contains more minor improvements.

**Comment by TriggerDingus** [comment]
> @TriggerDingus you might want to rather check https://github.com/ransome1/sleek/releases/tag/v2.0.9-rc.4, since this release contains more minor improvements.

I just sat down to do some testing, so perfect timing. Thx

**Comment by TriggerDingus** [comment]
Using: v2.0.9-rc.4
I think this functionality is working again! I noticed that italics are evoked with single * instead of the double # as they were in the pre-rewrite version but that's certainly not an issue - I just had to discover the difference.

![image](https://github.com/ransome1/sleek/assets/75340371/3678c602-bbd8-44d4-969b-ca2480dd392d)
![image](https://github.com/ransome1/sleek/assets/75340371/81f0c559-ed25-4af1-9b06-0307e9c91498)

**Comment by TriggerDingus** [comment]
Saw the update roll into production. Thanks!

**Comment by ransome1** [comment]
@TriggerDingus in the rewrite we're moving away from the old markdown parser to a new one and it is possible, this new parser works slightly differently. Although, of course, it shouldn't, since markdown is a standard a cording to my knowledge.

**Comment by ransome1** [comment]
According to this page, italics are being evoked by using * or _, and # seems to be reserved for triggering headlines: https://www.markdownguide.org/basic-syntax/

If you were able to use # for italics, it seems like a flaw in the old parser if you ask me. I'm a bit puzzled too.
