### ISSUE TITLE
Sleek icon pixelated in Flatpak installation

### ISSUE THREAD

**Issue by TriggerDingus** [ransome1/sleek#566]
**Description:**
Just a minor heads-up.
The new release (v2.0.1) currently provides an icon that appears slightly pixelated.
Here's a screen capture of my dash, for reference:
![image](https://github.com/ransome1/sleek/assets/75340371/4b595f40-ce6a-45fa-b955-b9ffa6e4354b)

Rel: v2.0.1
Linux Flatpak installation
Pop!_OS 22.04

**Comment by ransome1** [comment]
What desktop environment are you using?

**Comment by TriggerDingus** [comment]
Gnome 42.9

**Comment by TriggerDingus** [comment]
![image](https://github.com/ransome1/sleek/assets/75340371/588ee212-8fc7-42c6-9052-98624ea2c99e)
![image](https://github.com/ransome1/sleek/assets/75340371/ee65ee98-89d2-4dc4-a9ef-63490d4afe7c)

Here's a couple captures of my dock so you can see Sleek in context with others. It looks like my current version of Sleek is v2.0.8.
It still appears pixelated on my end.

**Comment by ransome1** [comment]
@TriggerDingus thanks for sharing. It really looks nasty. I'll set up a VM and try to fix it.

**Comment by ransome1** [comment]
@TriggerDingus can you please check this test release and tell me if the icon is still pixelated on your end?

Install it with: `flatpak install https://dl.flathub.org/build-repo/78244/com.github.ransome1.sleek.flatpakref`

**Comment by TriggerDingus** [comment]
I installed the test release in a GNOME virtual machine which should yield the same result as installing to my production host. It looks mucho better:

![image](https://github.com/ransome1/sleek/assets/75340371/90c6f0a1-aa53-486a-a9b7-bae3688db53a)

**Comment by TriggerDingus** [comment]
It isn't pixelated in the Apps panel any longer, either:
![image](https://github.com/ransome1/sleek/assets/75340371/1afd9c80-d267-481c-a77c-54e90fd09e0b)

**Comment by ransome1** [comment]
Glad to hear it works. I will include the fix in the next release. Again, Thanks for reporting this.

**Comment by TriggerDingus** [comment]
Just received the latest production release on my production box. Fixed!
![image](https://github.com/ransome1/sleek/assets/75340371/53b266c5-8fba-4a50-bb7f-658152ae022e)
