### ISSUE TITLE
New settings option: Add task opens advanced dialog

### ISSUE THREAD

**Issue by lrq3000** [ransome1/sleek#567]
## Feature Request

**Description:**
Currently the only way to add a new task (via Sleek) is to enter the new task description in the search bar, then click the "Add task" button that appears near the search button.

The issue is that there is no GUI to format the task: the user must either type everything by hand, or must first input a draft of the task, then search for it, then open it in edit mode to see the advanced task dialog.

This is especially necessary for users like me who use a lot of tags or tags with special characters, then autocompletion or a way to select from a dialog is very necessary.

**Implementation Details:**
It would be great if we could have an option in the settings to enable that clicking the "Add task" button opens the advanced task edition dialog. With this, users could then choose a hybrid mode of input where they can draft the task description by typing, and later select tags, priority etc by clicking in the advanced edition dialog.

Technically how this could be done is that by clicking the "Add task" button, the task can be added as is currently done, but then the Task Edition dialog could be opened to further edit it. This way, if the user cancels the dialog, this would be identical to the current behavior, the task would stay in place as-is. So technically, when "Add task" is clicked, an if statement could check if the option is enabled, and if yes, open the just added task in the Task Edition dialog.

I guess this implementation would be easier as otherwise the Edition dialog would have to be allowed to show tasks that do not exist yet...

**Comment by ransome1** [comment]
@lrq3000 why not using the todo dialog to add a new task?
![Bildschirmfoto 2023-11-03 um 11 29 08 AM](https://github.com/ransome1/sleek/assets/11188741/98b6d67b-a269-4429-8632-fc99adbfb692)

**Comment by lrq3000** [comment]
This is exactly what I would like to do but how can I open it?

**Comment by ransome1** [comment]
You can either click the + button in the left navigation bar or use the keyboard shortcut CTRL + N.

Makes me wonder if the + icon in the navigation might not be as understandable as I thought.

Where would you have expected this function and how should it have looked like for you to associate the creation of a new todo with it?

**Comment by lrq3000** [comment]
OMG 😅 I'm so sorry I did not see it before. Well this explains why no one else suggested this before 😅

No it's ok, I guess it's just that I expected that since I could add tasks from the search bar, that it was the only way.

So I leave it up to you to ponder whether you want to implement what I suggested so as to make the search bar the one-stop-shop for interacting with your app, or you can close as completed anyway as there is another way around that fulfills the same purpose with one additional click :-)

Thank you very vey much!

**Comment by andrei-a-papou** [comment]
For what it's worth, it wasn't immediately obvious to me either what the plus button meant. Does it add a new todo or a new todo.txt file, for example? 

At least on Linux, there aren't any tooltips when you hover the mouse over the vertical toolbar buttons. So you are not 1000% what happens unless you click that button.

@ransome1 Would you consider adding button tooltips? Or perhaps some onboarding button call-outs on first launch, to educate new users what the buttons do (with an option to not show them a second time).

**Comment by lrq3000** [comment]
Tooltips or tutorial would be good for me too!

**Comment by ransome1** [comment]
Given the simplicity of the interface, if we need an onboarding to explain how to create a todo in a todo app, something is really wrong with the design. Maybe a different logo should be discussed and maybe even tool tips, if really necessary. 

Tool tips come with the big drawback, that they need to be maintained and translated. If we add a tool tip to the `add` button, we need to do this for all the other interface items as well. For 15 languages each so far. And for some a simple `add` is enough, some might be asking for `add a new todo`. 

As for the icon, we are using the [MUI icon set](https://mui.com/material-ui/material-icons/). It contains a couple of icon suitable for the task at hand, but none of them really convinced me yet. For example:

<img width="62" alt="Bildschirmfoto 2023-11-20 um 8 42 59 PM" src="https://github.com/ransome1/sleek/assets/11188741/595319dc-ea12-43fb-bf54-477a9afed6da">
<img width="55" alt="Bildschirmfoto 2023-11-20 um 8 45 13 PM" src="https://github.com/ransome1/sleek/assets/11188741/0288b7b5-bfa7-46ac-952c-36ffdc984808">

Howver I'm still confused, that a plus icon can be misunderstood for creating a new todo.

**Comment by andrei-a-papou** [comment]
> If we need an onboarding to explain how to create a todo in a todo app, something is really wrong with the design

IMHO this language may be a bit too strong, but I certainly see the larger point :) For the record, I think generally sleek has a great UX, so kudos to you.

> Tool tips come with the big drawback, that they need to be maintained and translated.

Good point, plus you don't see them immediately anyway so not sure if they would really help things all that much. 

Frankly, now that the first impression is gone it's hard for me to see the issue with the current button. Perhaps the plus icon is a bit too thin and since it's close to the much brighter sleek logo box, it gets overshadowed a bit.  Just a thought.
