### ISSUE TITLE
Change font size (Scaling)

### ISSUE THREAD

**Issue by intrepidsilence** [ransome1/sleek#57]
It would be great to be able to set the font size and face. 
It would also be nice to be able to change the size with keyboard shortcuts.

**Comment by shulist** [comment]
@ransome1 I think this important as I use Sleek on a laptop with an UHD display and it consumes way too much real estate (at its smallest it takes up almost half of my screen width and is mostly blank space). Could Sleek be set to use the current font/sizing set by the user in windows. Or at least have the option to do so? Also could the window size be made user adjustable by the user.

**Comment by ransome1** [comment]
@shulist, @intrepidsilence, just fyi I'm working on an option to increase and decrease the font-size which will also scale the interface in general. I will implement + and - buttons as well as keyboard shortcuts.

@shulist, I will ask you for some testing on your UHD display as right now I am far way from home for some time, staring at a 13 inch display.

The font face though will remain Free Sans as it is part of sleeks identity, which sounds weird but is true ;)

**Comment by ransome1** [comment]
@shulist, @intrepidsilence (@Tobida, @plagasul, you might be interested in this feature too), I built a first draft on the scaling feature: https://github.com/ransome1/sleek/releases/tag/v0.9.7-Alpha

It is placed in the "view" menue:
![image](https://user-images.githubusercontent.com/11188741/111911632-a5ecf800-8a66-11eb-9706-733ccbe9c957.png)

This feature does not only scale the font size, but also the whole structure, so everything stays where it is suppose to. @intrepidsilence, keyboard shortcuts are available too.

Please feel free to give it proper testing, your feedback is much appreciated!

**Comment by shulist** [comment]
@ransome1 I think this is a significant improvement in the direction that had been mentioned above. While I don't have my UHD laptop with me currently (I will test it there also), I did look at the Sv0.9.7 on a regular desktop and have the following comments:
1) Would it not be better to just use the whatever default font that the user has set?  I take a lot of time selecting the best font for me and when an app arbitrarily changes it, it usually not a better choice.  I have set the font size to what I would want but for instance the font you've chosen "washes out" in the purple background, making it difficult to read. I have to tell you that personally for me "Free Sans" is not a highly readable font.
2) The window scaling problem is still there. I cannot size the window to a size that is appropriate for me. It seems you have set the minimum window size and of course I cannot get it to be any smaller. For me at the smallest size the window is mostly empty space and way too large for my screen layout and liking.  See attached photo. For comparison in the image I have included the todotxt.net application (Font is Verdana 10) I had used in the past--that's the size it typically is on my screen.
![SleekScreen](https://user-images.githubusercontent.com/6595819/111998497-6ff55580-8af2-11eb-8591-54b41d73cdb3.png)

3) At the larger font sizes and the smallest window size the "View" option is hidden.
4) While it might not be intended, in the View menu, the "Zoom" option gives you the impression that the <+> & <-> keys should adjust the sizing, but they do not.

**Comment by shulist** [comment]
@ransome1 Sorry I just read that you had changed the title of this to limit it to be about Fonts sizing and scaling. Do you want me to move my comments about window scaling to another thread?

**Comment by intrepidsilence** [comment]
@ransome1 I can confirm that font scaling is working on the macos version. However, I would really like it to change the padding in each line as well. The interface is very pretty but also very inefficient at using the available space, even with a smaller font. Is that something that can change as well?

**Comment by ransome1** [comment]
@intrepidsilence, are you using the compact view at the same time?

**Comment by intrepidsilence** [comment]
@ransome1 Compact View is better but still not as tight as I would like to see. Maybe add and Ultra Compact mode?  :)

**Comment by intrepidsilence** [comment]
@ransome1 No problem. Thanks very much for the font sizing addition.  Makes a big difference!

**Comment by ransome1** [comment]
> @ransome1 Sorry I just read that you had changed the title of this to limit it to be about Fonts sizing and scaling. Do you want me to move my comments about window scaling to another thread?

Yes, it would be good to have single issues for different things to keep track.

**Comment by ransome1** [comment]
`While it might not be intended, in the View menu, the "Zoom" option gives you the impression that the <+> & <-> keys should adjust the sizing, but they do not.`
@shulist: A little follow up here: What sizing are you referring to?

**Comment by intrepidsilence** [comment]
@shulist Did you mean that it gives the impression that the keyboard versions of those keys will control the size? I did not get that impression from it but others might I guess. 

It would certainly be good to have keyboard shortcuts for zooming in and out and best if they matched the Chrome/Firefox version of those keys.

**Comment by intrepidsilence** [comment]
@shulist - it just occurred to me but are you color-blind? If so, that could explain the difficulty seeing the font on the colored bubbles.  

Either way, @ransome1 even if @shulist is not color-blind, this is definitely something to take into consideration, and perhaps make a color-blind mode.
