### ISSUE TITLE
Tab completion for contexts and projects in new task window

### ISSUE THREAD

**Issue by stephprobst** [ransome1/sleek#572]
## Feature Request

**Description:**
In Sleek 1.* there was tab completion when adding topics or projects to a task. It would be great to have that again.

**Implementation Details:**
When typing `@` in the new task text box, a selection of the previously used contexts gets displayed. Now the user should be able to hit the tab button to auto-complete with the first entry from this list. Then the user should be able to hit enter to save the task. This would drastically speed up the workflow of adding new tasks.

![image](https://github.com/ransome1/sleek/assets/20990315/32a99cd2-d3d3-44e1-a325-ad5212b266d8)

**Comment by ransome1** [comment]
@stephprobst this happens because the React component (react-autosuggest) does not support Tab out of the box and I havn't been able to find a work around for this. The supported keyboard shortcut is to use the `Arrow Down` and `Up` keys.

**Comment by ransome1** [comment]
@stephprobst Actually I kind of fixed this after all. If you use the autocomplete feature to narrow down the results to 1 and then hit tab key, sleek will add the suggestion to the text field. However, if you only narrow it down to 2 or more results, hitting the tab key does not have any effect. Here I simply cannot find a solution in the `react-autosuggest` component.

**Comment by stephprobst** [comment]
@ransome1 : Great. That's definitely helpful and should solve the issue for me. Thanks!

**Comment by ransome1** [comment]
Please re-open, if it is not working as expected.
