### ISSUE TITLE
File tabs not shown

### ISSUE THREAD

**Issue by cu186** [ransome1/sleek#574]
## Bug Report

**App Version:** [sleek v2.0.2]

**Platform:** [Linux, flatpak]

**Installation Method:** [flathub]

**Bug Description:**
can't show file tabs

**Steps to Reproduce:**
click view menu, click toggle file tabs,  nothing happen.

**Additional Information:**
appimage version works as expected, but flatpak version doesn't.

**Screenshots:**
![截图 2023-11-08 00-26-24](https://github.com/ransome1/sleek/assets/150170071/0164b0c0-e1a8-4c88-8c20-5da33ff9c420)

**Comment by ransome1** [comment]
It's still there. You just need to hide the search bar ;)

But you're not the first user having issues with this. I might need to give this some thought.

**Comment by cu186** [comment]
I think one of them can lie on the bottom file bar or search bar.

**Comment by ransome1** [comment]
This could be a way to deal with it, if file tabs and search are shown:
<img width="1125" alt="Bildschirmfoto 2023-11-20 um 8 52 10 PM" src="https://github.com/ransome1/sleek/assets/11188741/fea5435c-4ee5-46f9-9e15-728612289b36">

with the filetabs hidden: 
<img width="1125" alt="Bildschirmfoto 2023-11-20 um 8 57 47 PM" src="https://github.com/ransome1/sleek/assets/11188741/783abff0-7fc0-4d4d-bd22-ebf6426009a5">

**Comment by cu186** [comment]
search bar is long, enough to add other feature,  It’s a bit wasteful to just search for keywords, for example always show "quick add the content" as a default item in the result-drop-down list, This way, users can easily create a shopping list.

**Comment by cu186** [comment]
Just a suggestion

**Comment by cu186** [comment]
Great, problem solved.
