### ISSUE TITLE
updating todo item shows @category selection

### ISSUE THREAD

**Issue by smellymoo** [ransome1/sleek#576]
## Bug Report

**IMPORTANT:**
Please follow this template strictly when reporting bugs. Providing detailed and accurate information helps the development team to understand and address the issue effectively.

**App Version:** 2.0.2

**Platform:** Linux (fedora 38)

**Installation Method:** flatpack?

**Bug Description:**
when you edit a todo, it shows the popup menu of the @category selector

**Expected Behavior:**
only show this if you are typing a new @ symbol

**Comment by ransome1** [comment]
@smellymoo can you please check either [2.0.3 stable](https://github.com/ransome1/sleek/releases/tag/v2.0.3) or the latest [pre-release](https://github.com/ransome1/sleek/releases/tag/v2.0.4-rc.1) and give me a quick feedback, if this still occurs?

**Comment by ransome1** [comment]
Fixed, closing due to a lack of response.
