### ISSUE TITLE
Not clear that archive file can be configured

### ISSUE THREAD

**Issue by callegar** [ransome1/sleek#577]
## Bug Report

**IMPORTANT:**
Please follow this template strictly when reporting bugs. Providing detailed and accurate information helps the development team to understand and address the issue effectively.

**App Version:** 2.02

**Platform:** Linux

**Installation Method:** Appimage

**Bug Description:**

There is a little inconsistency: when archiving completed todos, the app says the archiving will happen in the *configured* archive file, but this seems not to be configurable (yet).

**Comment by ransome1** [comment]
Right click on the file tab will give you the option to define your custom done file for each todo file.

**Comment by callegar** [comment]
Great! Missed that! Thanks and sorry for the noise

**Comment by ransome1** [comment]
The way archiving works, or more the process of how the archiving file is defined, has changed fundamentally. This has been discussed in a parallel issue. I am going to close here for now.
