### ISSUE TITLE
Slow Text Entry when creating or editing a task

### ISSUE THREAD

**Issue by jason-mehmel** [ransome1/sleek#579]
## Bug Report

**IMPORTANT:**
Please follow this template strictly when reporting bugs. Providing detailed and accurate information helps the development team to understand and address the issue effectively.

**App Version:** v2.0.2

**Platform:** Linux

**Installation Method:** Snap

**Bug Description:**

Upon loading up Sleek and trying to enter a new task, Sleek responded with an extreme delay. A 1 or 2 seconds between typing and seeing the letters.

Same behavior when opening a new task.

Note, I have 800 lines in my todo.txt (if that overhead is part of the problem)

[Provide a clear and concise description of the bug you encountered.]

**Steps to Reproduce:**
1. [List the steps to reproduce the bug. Be as specific as possible.]

Open Sleek. Use keyboard shortcut or clicking the add task button. Typing task.

**Expected Behavior:**
[Explain what you expected to happen.]

Immediately responsive text entry.

**Actual Behavior:**
[Explain what actually happened.]

Delayed text entry

**Additional Information:**
- [Include any additional information that might be relevant to the bug, such as error messages or console logs.]

**Screenshots:**
[If applicable, include screenshots that demonstrate the bug.]

**Comment by callegar** [comment]
Experiencing the same. Unless you are on a really fast machine task entry can get very slow. Namely: current ryzen laptop is percievably slow but usable, older haswell laptop is a bit of a pain.

**Comment by jason-mehmel** [comment]
I'll also note that I'm also running _sleek1.3.0_ as the last version I was using before snap caused some problems.

That version isn't having problems with the exact same size text files!

(If text file size is a concern.)

**Comment by ransome1** [comment]
@jason-mehmel @callegar can you please check this pre-release in your environment and provide a quick feedback, if the issue here still occurs?

https://github.com/ransome1/sleek/releases/tag/v2.0.3-rc.1

I created a fake todo list with 1.500 todos and ran this pre-release on a 2015 i3 Thinkpad. The difference between 2.0.2 2.0.3-rc.1 is huge on this device. I'm curious about your environments.

**Comment by callegar** [comment]
The 2.0.3 RC1 release appears to be faster, thanks! As soon as I am on my slower machine, I'll double check that it is fast enough even for it.

**Comment by jason-mehmel** [comment]
It's definitely much faster!

I am noticing a slight amount of delay when entering text, but nothing compared to previous. The delay I'm noticing is something that I can live with!

**Comment by ransome1** [comment]
> It's definitely much faster!
> 
> I am noticing a slight amount of delay when entering text, but nothing compared to previous. The delay I'm noticing is something that I can live with!

Do you notice that delay also while typing in the search bar? And may I ask on what kind of hardware you're on? Rather on the outdated or more modern side?

**Comment by jason-mehmel** [comment]
I don't think there's a delay in the search bar!

And the very slight delay I'm noticing maybe isn't there? I've tried just spamming the keys and I _think_ it's slightly slower then typing in a text field like this one on github, but I can't verify that!

It's not causing any kind of delay that would interrupt my ability to use the program.

The laptop is about 5 years old I think? Main stats below.


-Computer-
Processor		: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
Memory		: 16263MB (16GB)
Operating System: BunsenLabs GNU/Linux 11 (Beryllium)
