### ISSUE TITLE
Feature Request: Archiving to a single done.txt file is problematic

### ISSUE THREAD

**Issue by shulist** [ransome1/sleek#58]
I utilize many todo.txt files for various projects. The ability to archive is important, but dumping all of my completed items in one done.txt file is just creating a new painful complication. What I would suggest is that the archive process follow the naming convention of the current file and add a "done" on the end.

For example you are archiving **my_todo.txt** and the archive file created becomes **my_todo_done.txt**

**Comment by ransome1** [comment]
@shulist, please feel free to give it a proper testing: https://github.com/ransome1/sleek/releases/tag/v0.9.4-Beta

**Comment by shulist** [comment]
@ransome1 tested this in Sleek 0.9.4 Beta and all seems good. I've tested with all sorts for long convoluted filenames and it worked great. **Thanks for the very fast response** to this item.
