### ISSUE TITLE
[Windows] Tray icon pixelated and menu always visible

### ISSUE THREAD

**Issue by ransome1** [ransome1/sleek#582]
Hi,

I used Sleek on Windows 10 before the update and am still using it after the update.

Very superficial feedback here:
- The favicon type logo is pixelated 
- I think it was possible to hide the menu bar previously, but now it isn't.

I hope some of that is useful. Sleek is great, thanks so much for developing this!

Fred

_Originally posted by @fredofredofred in https://github.com/ransome1/sleek/discussions/562#discussioncomment-7481273_

**Comment by ransome1** [comment]
@fredofredofred the pixelation issue should be resolved in this pre-release, please feel free to give it a quick test: https://github.com/ransome1/sleek/releases/tag/v2.0.3-rc.2

**Comment by fredofredofred** [comment]
I just downloaded and ran sleek-2.0.3-rc.2-win.exe

The icon on the .exe file looks smooth.

However the icon which appears on the taskbar and top left of the window still looks pixellated.

The screenshot of the taskbar has the current version from the Microsoft Store running next to sleek-2.0.3-rc.2-win.exe. On my other computer I re-installed the previous version 1.3.1 which doesn't have this issue (as a temporary measure).

I hope that's helpful.

Fred

![Screenshot 2023-11-23 210351](https://github.com/ransome1/sleek/assets/149969915/07cd9df0-661d-4111-8ede-038bb8feaa80)
![Screenshot 2023-11-23 210048](https://github.com/ransome1/sleek/assets/149969915/22fefa2b-1e7b-4efa-8101-01054e561522)
![Screenshot 2023-11-23 210727](https://github.com/ransome1/sleek/assets/149969915/ce0d426b-1a75-41e9-b4f6-f10f3e391b3b)

**Comment by fredofredofred** [comment]
Top screenshot is the .exe file, the next one is showing the icon on corner of the window, the bottom is the task bar.

**Comment by ransome1** [comment]
@fredofredofred can you check, if this still happens in this pre-release? https://github.com/ransome1/sleek/releases/tag/v2.0.3-rc.3

**Comment by andrei-a-papou** [comment]
@ransome1 thanks for hiding the menu bar on Linux, I was about to report this

**Comment by fredofredofred** [comment]
@ransome1 

Logos look good everywhere and the menu is gone, but it appears when I press 'Alt'.
![Screenshot 2023-11-26 205157](https://github.com/ransome1/sleek/assets/149969915/82e22e69-5b43-48de-a704-b06954836227)

So it all looks good to me.

**Comment by ransome1** [comment]
> Logos look good everywhere and the menu is gone, but it appears when I press 'Alt'.

That's actually the old behavior of sleek v1.3.1 and had been explicitly requested in another issue. I kind of support this behavior, since it makes the app looks significantly more tidy.

But as for the issue at hand, I'm closing here. Feel free to re-open, if you think there is still stuff to do.
