### ISSUE TITLE
Openening the done file in sleek and archiving it, deletes its content

### ISSUE THREAD

**Issue by ransome1** [ransome1/sleek#585]
Well, I just had a major issue.
All the content of the todo.txt file seems to have been overwritten with the content of the done.txt file, except the few last lines.

I am not 100% sure of exactly what I was doing when it happened, I believe I was just marking a task as complete.
The whole list suddenly turned grey with completed tasks, which was weird because they were all archived to done.txt a few minutes before.
All the uncompleted tasks (70+) were gone (I checked the contents of the txt file itself).
The contents of todo.txt and done.txt are now exactly the same, the few last lines that are missing from todo.txt are the tasks I marked as completed last.

What happened, I have no clue.
Nothing special in my setup, except maybe that the folder where the txt files are stored is synced to the cloud (nextcloud), so there is a weak but real possibility that this is a sync issue.
Happy to open another thread if this one is not appropriate.

EDIT : there was a weird error a few minutes before when I attempted to archive completed todos. Don't remember the exact terms but it asked in red that I open "done.txt", which was already open. I closed done.txt, reopened it and the archive action worked then.

Thanks,
N

_Originally posted by @djihz in https://github.com/ransome1/sleek/discussions/562#discussioncomment-7498110_

**Comment by ransome1** [comment]
@djihz this should not be happening any more in the latest pre-release: https://github.com/ransome1/sleek/releases/tag/v2.0.3-rc.5

I would appreciate your feedback.

**Comment by djihz** [comment]
Thank you for following up.
Although I kept on using sleek daily this did not happen again.
I will install the update now and report back if anything happens.

**Comment by ransome1** [comment]
Feel free to re-open this thread, if it actually keeps occurring. Thanks for pointing it out.
