### ISSUE TITLE
Disable spellchecking or fully support it

### ISSUE THREAD

**Issue by ransome1** [ransome1/sleek#586]
Spellchecking: when creating/editing a task the text seems to be spellchecked ("wrong" words underlined with red dots). I see no option to display suggestions, accept or reject them, and no setting to disable spellchecking entirely.

_Originally posted by @djihz in https://github.com/ransome1/sleek/discussions/562#discussioncomment-7475507_

**Comment by callegar** [comment]
In some countries it is also common to keep the UI elements (menus, etc.) in English. The rationale is that if you are in a country whose language is not widely speak you may want UI elements and error messages in English to be able to find significant results when googling about them. Hence, it would be great to decouple the todo file language choice from the ui language choice.
