### ISSUE TITLE
Date recognition too strict

### ISSUE THREAD

**Issue by chris-asdf** [ransome1/sleek#589]
Hi,

Background : in my language/country Jan is a name but also used as an abbreviation for the Month January.
When creating a Task with the Text "Jan" in it, sleek creates a Task with 2024-01-01 instead of the expected string. My locale of sleek us set to English and I'm using v.2.0.2 on win10.

The replacement of Jan makes sense to me, but it's counterproductive for my case. Is it intended btw.

All the Best
Chris

**Comment by ransome1** [comment]
Hi @chris-asdf . Thanks for your report. If you suspect a bug, can I ask you to use the bug report template? It's otherwise really hard for me to keep the backlog meaningful and tidy.

**Comment by chris-asdf** [comment]
Hi,

Sorry for the delay, different things got higher priority. 

I can't really say it's a bug, because it could be also a feature to recognise this abbreviation.
But if you prefer it to handle this as a bug, can you give me a hint how to edit this issue accordingly? Or should I create a new?

All the Best,
Chris

**Comment by ransome1** [comment]
Hi Chris.

I can't tell neither if it is a bug. Mostly because there are simply not enough details in this issue. It will help if you use the bug template and describe as detailed as possible the current behavior (which you suspect to be a bug) and what you would have expected instead. I added the bug template to your issue. Feel free to refine it and if it is a bug, we will re-open this issue.

**Comment by chris-asdf** [comment]
Hi,

I updated the description, but I can't add the bug label (at least I've no Idea how 😉)

If this still doesn't contain all the info you need, just let me know.

I'll also give the newest release a try, but the changes mentioned seem not to be related to this...

Thanks for your time and effort
Chris

**Comment by ransome1** [comment]
Hi Chris, I still cannot work with the bug report.

<img width="1270" alt="Bildschirmfoto 2023-12-18 um 11 56 55 PM" src="https://github.com/ransome1/sleek/assets/11188741/5cb32020-3561-4ffb-bb82-641ad87833ce">

Maybe we should start with the language your system is set to.

**Comment by chris-asdf** [comment]
Hi,

I retried today and interestingly I also couldn't reproduce it.
For completeness my system language is german de(DE) and sleek is set to English. 

I hope this was something wind00w$ was throwing at me and it vanished with some updates.

Thanks again for your time, the next time I'll make screenshots immediately 😉

All the best
Chris

**Comment by ransome1** [comment]
Quick question, since you are or Windows: Were you experiencing any performance issues with the last (pre-) releases? And if so, can I ask you to download the [latest pre-release](https://github.com/ransome1/sleek/releases/tag/v2.0.4-rc.3) and check, if those are still present?

**Comment by chris-asdf** [comment]
Hi,

> Quick question, since you are or Windows: Were you experiencing any performance issues with the last (pre-) releases? And if so, can I ask you to download the [latest pre-release](https://github.com/ransome1/sleek/releases/tag/v2.0.4-rc.3) and check, if those are still present?

The next time I'll get my hands on a windows PC will be next year. Then I would glad to give it (or any subsequent version) a try.

All the best,
Chris
