### ISSUE TITLE
Feature Request: Place file name in Window Title

### ISSUE THREAD

**Issue by shulist** [ransome1/sleek#59]
On Win10 the Sleek window only has "Sleek" in the tile bar. For those of us who open multiple Sleek windows it makes more sense to have the filename displaying in the windows title bar.

**Comment by ransome1** [comment]
Same here: https://github.com/ransome1/sleek/releases/tag/v0.9.4-Beta

**Comment by shulist** [comment]
@ransome1 OK so it looks great and works with all my long convoluted files referred in #58. **Terrific work again.**
