### ISSUE TITLE
Win + D shortcut on Linux seems problematic

### ISSUE THREAD

**Issue by andrei-a-papou** [ransome1/sleek#591]
## Bug Report

**App Version:** 2.0.2

**Platform:** Linux, Debian 11, Xfce

**Installation Method:** AppImage from GitHub

**Bug Description:**
`Win + D` ("hide app") shortcut doesn't work on my machine, in fact, the `Win` modifier doesn't even register (see screenshot):
![image](https://github.com/ransome1/sleek/assets/30468319/19d0c286-6c22-40ee-a1df-260cd1f63a78)

There's no conflict with window manager's keybindings on my machine, but I imagine some people do use `Win + D` to toggle desktop (a-la Windows).

In addition, clicking the `Hide` menu item doesn't do anything either.

Personally, I would remove this functionality on Linux as it is rather trivial to implement with third-party apps (e.g. `jumpapp`) or a bit of scripting (using `wmctrl` or similar.) That would also ensure there's no conflict with window manager's key bindings.

**Comment by andrei-a-papou** [comment]
@ransome1 Yes, under Windows Win + D is a hardcoded thing, to show/hide desktop. I can confirm this on Window 7, for Windows 10 and 11 see this link: https://support.microsoft.com/en-us/windows/keyboard-shortcuts-in-windows-dcc61a57-8ff0-cffe-9796-cb9706c75eec#WindowsVersion=Windows_10

**Comment by ransome1** [comment]
Ok, I will remove this function for Windows and Linux in the next release. Thanks for pointing this out.

**Comment by andrei-a-papou** [comment]
no problem!

**Comment by ransome1** [comment]
@andrei-a-papou the keyboard shortcut for hiding the window should be removed on Linux and Windows in this pre-release: https://github.com/ransome1/sleek/releases/tag/v2.0.3-rc.4

**Comment by andrei-a-papou** [comment]
Just tested, the menu item's gone, thank you!
