### ISSUE TITLE
Wrong label for menu item ("Reveal in Finder")

### ISSUE THREAD

**Issue by andrei-a-papou** [ransome1/sleek#592]
## Bug Report

**App Version:** 2.0.2

**Platform:** Linux

**Installation Method:** AppImage from GitHub

**Bug Description:**
The menu item "Reveal in Finder" works for macOS but not for Linux as there's no Finder app. I think "Reveal in file manager" is what it should say.

![image](https://github.com/ransome1/sleek/assets/30468319/d5af1f47-b4f9-4de7-9c02-128202c1518b)

**Comment by ransome1** [comment]
I agree.

**Comment by ransome1** [comment]
@andrei-a-papou the wording has changed in this pre-release: https://github.com/ransome1/sleek/releases/tag/v2.0.3-rc.4

**Comment by andrei-a-papou** [comment]
@ransome1  tested, looks great, thank you!

**Comment by ransome1** [comment]
@andrei-a-papou Thanks for your feedback.
