### ISSUE TITLE
Ctrl+N doesn't work with Cyrillic keyboard layouts

### ISSUE THREAD

**Issue by andrei-a-papou** [ransome1/sleek#597]
## Bug Report

**IMPORTANT:**
Please follow this template strictly when reporting bugs. Providing detailed and accurate information helps the development team to understand and address the issue effectively.

**App Version:** 2.0.2 as well as latest RCs

**Platform:** Linux

**Installation Method:** AppImage

**Bug Description:**
Ctrl+N doesn't do anything unless the keyboard layout is US. Tested with Bulgarian keyboard layout as well as the Russian one. I imagine other Cyrillic layouts won't work either. Interestingly, Ctrl+F works fine regardless of layout. Something funny with Ctrl+N?

**Steps to Reproduce:**
1. Switch to a Cyrillic layout 
2. Press Ctrl+N

**Expected Behavior:**
New todo dialog should pop up

**Actual Behavior:**
Nothing happens

**Comment by ransome1** [comment]
When I switch my input language to Russian, the `N` key becomes `т`. If I now add this character to the function responsible for catching and handling the keyboard shortcut, the `Ctrl & N` shortcut works. I can add this to the next release, but it doesn't feel like a clean solution :/

**Comment by andrei-a-papou** [comment]
I think this workaround is way better than nothing, so I would be grateful for it. I'm curious though as to why e. g. Ctrl + B works in both Latin and Cyrillic layouts, but Ctrl + N doesn't?

**Comment by ransome1** [comment]
@andrei-a-papou it has been released as part of 2.0.5. Could you please give me a feedback if it works as expected?

**Comment by andrei-a-papou** [comment]
Works now, thank you!
