### ISSUE TITLE
Filter tray sorting alphanumerically

### ISSUE THREAD

**Issue by jason-mehmel** [ransome1/sleek#6]
Sorting filters in the filter tray **either** by amount of tasks using those contexts/projects, **or** sorting them alphanumerically. (In the other systems I've used, they sort them alphanumerically, so I've got some 'top level' contexts like [at]1_inbox because then it's the first thing I see on Simpletask Android or on some of the other apps I've used.

**Comment by ransome1** [comment]
So far all your suggestions made sense, keep on doing that! :) Thanks to Stackoverflow I found a simple method to accomplish that, please check v0.2.3 for alphanumeric sorting of the filters: https://github.com/ransome1/sleek/releases/tag/v0.2.3

The updated filter logic of v0.2.2 is of course also included.
