### ISSUE TITLE
Feature Request: Add date added for new tasks

### ISSUE THREAD

**Issue by samexev** [ransome1/sleek#60]
It would be good if the app can automatically add creation date for TODOs.

**Comment by ransome1** [comment]
This happens already. Otherwise can you please explain your request with a little more detail please?

**Comment by samexev** [comment]
It does, sorry, not sure why it didn't happens sometimes. Please delete this.

**Comment by samexev** [comment]
When I tried, the date was added. I will keep an eye on it and report if I catch it.
