### ISSUE TITLE
Dark Theme Nonfunctional

### ISSUE THREAD

**Issue by TurboTiger** [ransome1/sleek#600]
## Bug Report

**App Version:**
2.0.2

**Platform:** 
Windows 10

**Installation Method:** 
Microsoft App Store

**Bug Description:**
In Sleek's Settings, selecting dark theme has no effect.

**Steps to Reproduce:**
1. Go to Settings > Theme, Select "Dark"

**Expected Behavior:**
Selecting dark theme should cause dark theme to be applied.

**Actual Behavior:**
Selecting dark theme has no effect.  App continues to use light theme.

**Additional Information:**
Dark theme used to work fine in the past.

**Screenshots:**
[If applicable, include screenshots that demonstrate the bug.]

**Comment by ransome1** [comment]
@TurboTiger I'm afraid I do not have any access to a Windows machine right now and will not have it for quite some time.

Are you able to somehow start the app from a terminal? That will give you the output of the main process of sleek. Maybe it provides us with an error message.

On macOS and Linux it works perfectly well and I am wondering if this is a general Windows bug or a MS App store specific one.

**Comment by ransome1** [comment]
@swantzter since @TurboTiger isn't responding; Do you by any chance have access to a Windows system and if so can I ask you to check if you can confirm this?

**Comment by swantzter** [comment]
@ransome1 I did a clean install on a new computer and can confirm this is #530.
Opening it for the first time on a system with dark mode set will give you the window frame in dark mode and the sleek contents in light mode. switching to light mode and then dark mode in settings will get it to dark mode proper

**Comment by ransome1** [comment]
@swantzter @TurboTiger I slightly tweaked the feature again. Is there any improvement on your sides? https://github.com/ransome1/sleek/releases/tag/v2.0.4-rc.2

@swantzter also: Are you on Windows as well and can give it a try on it?

**Comment by swantzter** [comment]
I'll try to remember it if I boot my secondary machine soon, about to go on vacation so might keep away from computers a bit. It only occurs until you've done the work-around I've described in #530 once, then it'll work as intended forever so I'll have to reinstall sleek on that machine

**Comment by swantzter** [comment]
@ransome1 I think this is working now. I tried reinstalling and removing all appdata and it worked on first boot

**Comment by ransome1** [comment]
with 2.0.4 this issue should also not occur any longer, when switching between versions.

https://github.com/ransome1/sleek/releases/tag/v2.0.4
