### ISSUE TITLE
[macOS] use of cmd+tab causes sleek to behave as if the cmd key is permanently depressed.

### ISSUE THREAD

**Issue by djihz** [ransome1/sleek#608]
## Bug Report

**App Version:** 2.0.3 rc5, bug was already present in 2.0.2.

**Platform:** macOS 14.0

**Installation Method:** Direct Download

**Bug Description:**
Calling the application switcher [cmd+tab] to switch to another open application while in Sleek causes it to behave as if your finger is still pressing the cmd key when you switch back to it:
- The crossed eye icon is displayed over any label in the drawer on mouse over.
- If you click on the label in this state, Sleek hides the corresponding tasks and the icon is permanently displayed over the label (not just on mouse over). 
- Clicking a second time on the same label does not unhide the correponding tasks nor remove the icon.

You are, in effect, stuck in "hiding mode".
To bring sleek back to expected behavior, you just have to press cmd once.

**Steps to Reproduce:**
1. While in Sleek, press cmd+tab to switch to another open application.
2. Switch back to Sleek (the method does not matter: it doesn't have to be the application switcher)
3. Mouse over any label in the drawer: the crossed eye icon will appear, as if you were still pressing the cmd key.
4. To go back to normal, press the cmd key once.

Note: if you switch to another app, switch back to sleek, press cmd then switch again to **the same** app, sleek behaves normally when you return to it.

**Expected Behavior:**
Expected behavior is the default one, when no modifier key is pressed:
- On mouse over: no icon over label.
- On click: task list only displays entries corresponding to the label.

**Comment by ransome1** [comment]
@djihz I hope this pre-release solves the described issue: https://github.com/ransome1/sleek/releases/tag/v2.0.4-rc.2

**Comment by djihz** [comment]
Indeed it looks like it does.
Thank you !
