### ISSUE TITLE
On software version updates, the settings are erased

### ISSUE THREAD

**Issue by DeflateAwning** [ransome1/sleek#610]
## Bug Report

**App Version:** 2.0.2 (and during the update to every previous version)

**Platform:** Linux and Windows

**Installation Method:** GitHub Release

**Bug Description:**
Settings (like "Append creation date...") always get erased when an update is performed. It'd be nice not to have to worry about updates erasing these settings. 

It might not have been a priority before, but having a settings migration procedure would be awesome now that there are v2 "stable" releases.

**Steps to Reproduce:**
1. Change a setting.
2. Update.
3. See that the settings are erased.

**Expected Behavior:**
Settings not be reset to default.

**Actual Behavior:**
Settings get reset to default.

**Additional Information:**
Happens cross-platfrom and on every version update.

**Comment by ransome1** [comment]
With 2.0.1 the migration has been implemented. I just double checked it by downloading 2.0.1 from GitHub, starting and configuring it and then doing the update to 2.0.2. The update is done by just deleting 2.0.1 and downloading 2.0.2. All settings persisted on my end (macOS).

`Happens cross-platfrom and on every version update.`
Can you please provide more details on how you update. What versions you use and so forth.

**Comment by DeflateAwning** [comment]
Hmm this upgrade was from 2.0.0 to 2.0.2. Do you expect it would've upgraded well? Perhaps I won't have the issue next upgrade.

**Comment by ransome1** [comment]
mmhh, I also tried the jump from 2.0.0 to 2.0.2 just now and it upgraded without loosing the settings.

**Comment by DeflateAwning** [comment]
Hmm, was on Linux Mint, installed via the .deb I believe. 

Perhaps we can leave it for now, and I'll provide a better repro if it happens again.

Feel free to close the issue if you'd prefer, and I can re-open one next time. I'm not certain I didn't imagine it happening.

**Comment by DeflateAwning** [comment]
Just upgraded from 2.0.2 to 2.0.3, and did not have this issue. Sorry for the false alarm!

**Comment by ransome1** [comment]
> Sorry for the false alarm!

No worries :)
