### ISSUE TITLE
"forbidden-sandbox-reinit" on MAS installation

### ISSUE THREAD

**Issue by albertobissacco** [ransome1/sleek#619]
## Bug Report

**IMPORTANT:**
Please follow this template strictly when reporting bugs. Providing detailed and accurate information helps the development team to understand and address the issue effectively.

**App Version:** 2.0.3

**Platform:** macOS 10.13.6

**Installation Method:** App Store

**Bug Description:**
I can't open the app because it crashes after 3 seconds

**Steps to Reproduce:**
1. Install via Apple App Store
2. click the app

**Expected Behavior:**
it should works :)

**Actual Behavior:**
[Explain what actually happened.]

**Additional Information:**
- [Include any additional information that might be relevant to the bug, such as error messages or console logs.]

**Screenshots:**
[If applicable, include screenshots that demonstrate the bug.]

**Comment by ransome1** [comment]
@albertobissacco I can't reproduce this bug report. It runs without issues on my Mac installed from MAS. Can you please provide details. Crash reports for at least something to work on.

<img width="1291" alt="Bildschirmfoto 2023-12-20 um 2 56 24 PM" src="https://github.com/ransome1/sleek/assets/11188741/928fb4d1-2f2b-44e3-880a-f15c6cbc2385">

**Comment by albertobissacco** [comment]
https://github.com/ransome1/sleek/assets/189348/d88a8dc0-2188-400b-a218-2e0e4a55b809


![Screen Shot 2023-12-20 at 15 44 46](https://github.com/ransome1/sleek/assets/189348/6e1d5cc6-5c19-4883-8099-51e95eca1fcd)

this is what i found. I'll take a look at it if i can find something more to share

**Comment by ransome1** [comment]
Ok, looks like some sandbox issue. To be certain about it, can you download the same release from GitHub and does this work on your system? https://github.com/ransome1/sleek/releases/tag/v2.0.3

**Comment by ransome1** [comment]
Also, before doing this, can you check your settings, if macOS asks you for particular permissions for sleek, that havn't been granted yet?

**Comment by albertobissacco** [comment]
The app from Github works!
the one from the app store it didn't ask me for any particular permissions; i tried to disable the firewall but nothing changed.
I'm happy that the one from Github works :)

**Comment by ransome1** [comment]
Does the `forbidden-sandbox-reinit` crash entry contain a crash report?

**Comment by albertobissacco** [comment]
i don't know how to recover or see that report because i used a guest user and i think everything has been deleted

**Comment by ransome1** [comment]
Version 2.0.4 is in review by Apple right now. Please feel free to test it, once it has been release and let me know, if this still occurs.

**Comment by ransome1** [comment]
@albertobissacco please re-open if this occurs again. it should really not happen, since Apple does some basic manual testing themselves, before they approve it for distribution. But of course, your bug report tells a different story.
