### ISSUE TITLE
File Open 

### ISSUE THREAD

**Issue by shulist** [ransome1/sleek#62]
The button [Open todo.txt] on the [file open tab] should first take you to the current directory of the active file, if that is not established then the default of user's home directory is OK.

**Comment by ransome1** [comment]
@shulist, this has been added already in v0.9.9. It is also available in v1.0.0. Please share your feedback if this is working as expected and feel free to close the thread here.

**Comment by shulist** [comment]
@ransome1 that is great. It works well. I like the file list as it is not too long and does indicate the currently open file. 

The only suggestion I'd make it to change the wording on the "Open todo.txt" to "Open folder" as it more closely aligns with what you are actually doing.
