### ISSUE TITLE
Toggle visibility of creation (and solve?) date

### ISSUE THREAD

**Issue by thefoster** [ransome1/sleek#621]
## Feature Request

**Description:**
Currently the creation date is not displayed at all (which is a good default).
But it would be helpful to make the visibility as an option to toggle, e.g. in case you want to sort the tasks by creation time.

**Comment by ransome1** [comment]
@thefoster I need more details here. The creation date is already an available attribute, which can be used for filtering and sorting.

<img width="586" alt="Screenshot 2024-02-10 at 11 22 45 AM" src="https://github.com/ransome1/sleek/assets/11188741/6949e725-63e4-4709-85e7-15a33c8b0d42">

**Comment by ransome1** [comment]
Due to lack of response, I will close here. Feel free to re-open if this is still relevant.

**Comment by thefoster** [comment]
In the sort order the creation date is only displayed when set as first sorting item and just per day, not per item.
The suggested toggle referred to all items (per row) to show the creation date or not.
