### ISSUE TITLE
Right to Left Languages Support

### ISSUE THREAD

**Issue by gabilevi** [ransome1/sleek#624]
When entering a new task in a right-to-left language, it appears as a reversed sentence. For instance, in Hebrew, "Clean the floor of the house" is displayed as "house the of floor the clean." Changing the interface to right-to-left can also prove beneficial.
todo.txt appears to right in utf8 so, the development should be made in the app itself.

**Comment by ransome1** [comment]
@gabilevi could you please use the Feature Request template? Thanks.

**Comment by baruchiro** [comment]
It is a bug, not a feature.

It is caused because every word in a task is wrapped with a `div`, so the `div`s are sorted with the app direction, and blocks the natural RTL support.

![image](https://github.com/ransome1/sleek/assets/17686879/2d8d7070-7bb8-4550-a1e2-75350f33cb85)

**Comment by ransome1** [comment]
@baruchiro @gabilevi while implementing a markdown parser into sleek, the structure of single rows changed a bit. I'm not sure if this solves the issue at hand, but it can't hurt to try it out on your ends: https://github.com/ransome1/sleek/releases/tag/v2.0.9-rc.1

**Comment by ransome1** [comment]
What does it mean to properly implement RTL support into an application? Is it just about reverting the direction in the input elements?

**Comment by ransome1** [comment]
@gabilevi @baruchiro Please feel free to check this pre-release, if the issues described here are being covered: https://github.com/ransome1/sleek/releases/tag/v2.0.9-rc.4

I will merge these changes into the next stable release, unless you tell me not to.

**Comment by gabilevi** [comment]
it's working ! Looking forward for the next stable release. Thanks for supporting and easing our tasks board!
