### ISSUE TITLE
Fixes needed for keyboard shortcut info on wiki?

### ISSUE THREAD

**Issue by andrei-a-papou** [ransome1/sleek#628]
Some info on keyboard shortcuts appears to be wrong:

![image](https://github.com/ransome1/sleek/assets/30468319/1456bbbf-c905-40fb-ba8a-20ccbc5ec6c2)

1. "Hide sleek" and "Hide application window" -- do these refer to the same thing? 
2. Ctrl + D is listed as a shortcut for "Hide application window" under Linux, but it has no effect and I think it was removed
3. Ctrl + H is listed twice for macOS, for two different actions: "Toggle completed" and "Hide sleek"

**Comment by ransome1** [comment]
@andrei-a-papou should be corrected now.
