### ISSUE TITLE
Help link is not opened in external browser under Linux

### ISSUE THREAD

**Issue by andrei-a-papou** [ransome1/sleek#629]
Clicking the little question mark icon under _Settings_ opens the link in an Electron window itself, instead of the default browser. Opening links under _Help_ in the main menu works fine. This is under Linux, sleek 2.0.5, AppImage

Here's the screenshot:
![image](https://github.com/ransome1/sleek/assets/30468319/02c96100-7e1c-4405-817e-ac60bf88b7fa)

**Comment by ransome1** [comment]
@andrei-a-papou this should have been fixed in https://github.com/ransome1/sleek/releases/tag/v2.0.6. Please feel free to close here, if you can confirm this.

**Comment by andrei-a-papou** [comment]
@ransome1 links are indeed opened in system browser now, but the option is also simultaneously enabled 

![image](https://github.com/ransome1/sleek/assets/30468319/630aca07-a458-468a-9731-8b92de0b4da8)

**Comment by ransome1** [comment]
@andrei-a-papou that has been fixed in the last commit and will be part of the next release.

**Comment by andrei-a-papou** [comment]
Thanks, works in latest RC!
