### ISSUE TITLE
Simplify entering and adding multi-line tasks

### ISSUE THREAD

**Issue by HerrSersch** [ransome1/sleek#63]
When adding a new task, the user currently has two choices:

1. Enter a single-line task. Pressing Enter creates the task.
2. Clicking the multi-line double arrow. Enter now creates a new line, but the task can't be added by pressing Enter anymore.

I suggest using one of two behaviours that many messaging apps use instead:

1. Enter adds the task. Shift+Enter adds a new line.
2. Enter adds a new line. Ctrl + Enter adds the task.

I think the first option is more widespread (for example Discord, Slack and Steam use it) but I've seen the second one too, I believe back in the days of ICQ, though I'm not sure. There could be an option in the options menu to select one of the two as default, depending on personal preference.

**Comment by ransome1** [comment]
I gave it some thought. While messaging app users might be familiar with this abnormal behavior of a textarea, I am not sure if this is what most users would want or expect from a content app. Though if more users would be interested in this feature, I would consider developing it as an option, activated in settings. 

As a temporary workaround I could remove the tabindex from the recurrence picker, which is not a frequently used function. Like this, from the textarea you could press the tabulator key twice and then enter to submit the todo.

I am working on the tabindex next anyway and it would be an easy quickwin.

**Comment by ransome1** [comment]
@HerrSersch. Sorry, I misread your post. Your suggestion number 2 absolutely makes sense. I implemented it and it will be part of the 0.9.7 release tomorrow.

**Comment by ransome1** [comment]
@HerrSersch. The new shortcut can be tested in 0.9.7: https://github.com/ransome1/sleek/releases/tag/v0.9.7

**Comment by HerrSersch** [comment]
Thank you very much, it works well and feels nice :)

**Comment by ransome1** [comment]
Cool and again thanks for the suggestions, really speeds up things if you bulk create todos.

**Comment by TangentFoxy** [comment]
As multiple people have pointed out in discussions (#724 #807), using option 2 here is against what is most expected.

While it would take some adjusting for people already familiar with sleek, it would also make it more user-friendly for new people if this decision was switched to option 1. (While I cannot be certain, it is likely that most users don't even use multi-line input, and how it works now screws with them.)
