### ISSUE TITLE
Some improvements to option descriptions?

### ISSUE THREAD

**Issue by andrei-a-papou** [ransome1/sleek#632]
Under options, I would propose some improvements for option descriptions:

1. "Allow Matomo Analysis" -> "Allow Matomo analytics" (The word "analytics" would be a better term for the kind of tool Matomo is, just like Google Analytics. However, with Google Analytics the latter word is part of the name, so it's capitalized. Not so with Matomo, so "analytics" should be lowercase.)

2. Alternatively, the option could simply say "Allow telemetry" or "Send anonymous usage data", or something along those lines. I'm afraid not many people know what Matomo even is :)

3. I think the option "Each row in the text field creates a separate to-do item" should read "Each row in the text field creates a separate todo item". This way the app uses "todo" and not "to-do" everywhere (such as in menus).

4. I'm also not sure it's clear what "in the text field" refers to. Perhaps it could be rephrased to something like "Multi-line text creates separate todos", what do you think?

**Comment by ransome1** [comment]
@andrei-a-papou I think I agree with all 4 proposals, sounds good. I'm going to add these to the next release. Thanks!

**Comment by ransome1** [comment]
@andrei-a-papou I added the proposed changes to 2.0.7.

**Comment by andrei-a-papou** [comment]
@ransome1 Thank you, looks good!
