### ISSUE TITLE
Drawer size can be negative is then stuck

### ISSUE THREAD

**Issue by ransome1** [ransome1/sleek#633]
> Have you tried deactivating animations? There is now a setting in the interface. You might need to restart the application.

Yes, I have tried. Some animations are evidently gone but performance wise I'm not observing any significant difference.

> This is interesting. How do you achieve this? On my end I cannot drag the drawer this far to the left.

While dragging the edge and shrinking the drawe UI resizes up to about 300 pixels(?). After this point resizing stops, but I if I continue dragging terminal reports lower values and then negative ones.

_Originally posted by @amariusz in https://github.com/ransome1/sleek/issues/615#issuecomment-1890865821_

**Comment by ransome1** [comment]
@amariusz should be fixed in https://github.com/ransome1/sleek/releases/tag/v2.0.7-rc.4

**Comment by amariusz** [comment]
Unfortunately it's not much better. Looking at the terminal `drawerWidth` values stop decreasing after reaching about 170, so negative values are no longer an issue (or a symptom).  Minimal drawer width seems to be 300 pixels. Terminal may indicate lower values of `drawerWidth` but UI stays the same. If I release mouse button with `drawerWidth` below 300 it seems to be stuck again.

This time however I've noticed that it's possible to get it unstuck without changing `config.json`. It's sufficient to grab the edge and drag it to the right without any UI reaction for about 130 pixels (300-170) and then it's moving again.

It's not a big deal, just confusing.
