### ISSUE TITLE
Add version number to Settings popup

### ISSUE THREAD

**Issue by DeflateAwning** [ransome1/sleek#635]
### What problem does it solve? ###
It will allow me to find what version I have installed.

### Impact on the interface ###
Could add it to the bottom of the Settings pane. I'm sure it's somewhere else already currently, but I can't find it in an intuitive spot; this seems like a good intuitive spot to add the release version number.

~~An alternative would be in an "About" menu.~~ I just found the "About" menu in the bar at the top. That might actually be good enough.

**Comment by ransome1** [comment]
@DeflateAwning feel free to close the issue, if it is not needed anymore.
