### ISSUE TITLE
autocomplete fails to show those contexts/projects that currently visible todo items don't contain

### ISSUE THREAD

**Issue by bughunter2** [ransome1/sleek#637]
**App Version:** 2.0.6

**Platform:** Linux

**Installation Method:** Direct Download

**Bug Description:**
When editing a todo item, the autocomplete for @ and + only shows contexts and projects that are currently used in the set of visible todo items. That is: if you've unchecked the 'Due date in the future' filter, autocomplete refuses to autocomplete context or projects that only exist in todo items that aren't currently shown.

**Steps to Reproduce:**
See bug description.

**Expected Behavior:**
See bug description.

**Actual Behavior:**
See bug description.

**Comment by ransome1** [comment]
@bughunter2 could you check if this still happens in this pre-release? https://github.com/ransome1/sleek/releases/tag/v2.0.9-rc.4

**Comment by bughunter2** [comment]
Still happens I'm afraid. I'll attach the todo.txt file and some screenshots:

```
foobar +ProjectFoo
foobar +ProjectBar due:2050-01-01
```

If we allow Sleek to show future todo items, it all looks fine:
![Screenshot_2024-02-09_19-41-07](https://github.com/ransome1/sleek/assets/16524/053d026d-f2c7-4b00-b8ff-d5f5fd01b85c)

But if we don't, we can reproduce the problem like so:
![Screenshot_2024-02-09_19-41-27](https://github.com/ransome1/sleek/assets/16524/997fe3b5-4c51-4a6e-b454-9f86000b73eb)

**Comment by ransome1** [comment]
@bughunter2 you're right, something went wrong with merging the changes into that release :/ They should however be integrated in the v2.0.9 release: https://github.com/ransome1/sleek/releases/tag/v2.0.9

**Comment by bughunter2** [comment]
That fixed it. Hurrah :smiley:
