### ISSUE TITLE
help button "?" is not accesible

### ISSUE THREAD

**Issue by eterX** [ransome1/sleek#638]
## Bug Report

**App Version:** 2.0.6

**Platform:** Linux, Ubuntu 22.04.3 LTS

**Installation Method:** [.deb](https://github.com/ransome1/sleek/releases/download/v2.0.6/sleek_2.0.6_amd64.deb) 

**Bug Description:**
help button "?" is not accesible (missing or overlapped by collapse bar "<" )

**Steps to Reproduce:**
1. download [.deb](https://github.com/ransome1/sleek/releases/download/v2.0.6/sleek_2.0.6_amd64.deb) 
2. dpkg -i sleek_2.0.6_amd64.deb

**Expected Behavior:**
access shortcut cheatsheet through the help button

**Actual Behavior:**
button not showed

**Screenshots:** 
![image](https://github.com/ransome1/sleek/assets/6190461/883d03b7-67db-4d7d-85f7-fc5023503913)

**Comment by ransome1** [comment]
@eterX actually there is no help section within sleek anymore and therefore this button does not exist in sleek 2.x. The single point of truth for documenting sleek is the wiki on GitHub. If you press the alt key sleeks window menu should open. Here you find a help section, which contains links to the most important support topics.

**Comment by eterX** [comment]
Hi @ransome1 
You are absolutely right! Thanks for taking the time to explain
