### ISSUE TITLE
Recurrence broken in v0.9.4-beta

### ISSUE THREAD

**Issue by velardevines** [ransome1/sleek#64]
Future todos are not created for recurring todos. Create an item with due date of today and to recur daily (or weekly or monthly). Save the item. Mark it done. A new future item is not created. 

Running the deb installation on chromebook crostini. 

--Bill

**Comment by ransome1** [comment]
Hi @velardevines . Do you experience the same issue in https://github.com/ransome1/sleek/releases/tag/v0.9.5-Alpha as well?

**Comment by velardevines** [comment]
Hello @ransome1 - This problem is fixed in v0.9.5-Alpha.
