### ISSUE TITLE
Weird overlap on search bar over tabs

### ISSUE THREAD

**Issue by DeflateAwning** [ransome1/sleek#640]
### Important ###
Please follow this template strictly when reporting bugs. 

**App Version:** v2.0.7 release

**Platform:** Windows

**Installation Method:** Installer from GitHub

**Bug Description:**
Weird overlap (see image). The search bar's margin overlaps the tabs at the top
![image](https://github.com/ransome1/sleek/assets/11021263/5425ee32-5769-472c-9502-dc96ae1eb840)

**Steps to Reproduce:**
1. Open Sleek with many tabs.
2. See issue.

Problem persists after showing/hiding the search bar with the search button in the top-right corner.

**Comment by ransome1** [comment]
@DeflateAwning Thanks for reporting. Should be fixed in 2.0.8. Feel free to close here if you can confirm.

**Comment by DeflateAwning** [comment]
Looks good to me, thanks!
