### ISSUE TITLE
Archive

### ISSUE THREAD

**Issue by gerroon** [ransome1/sleek#65]
Hi

I think it would be very beneficial if there is a way to archive the current todo in the same folder(or under a subfolder) and empty it afterwards so the todo.txt starts clean.

**Comment by ransome1** [comment]
Hi @gerroon. I am not sure if I understand this requirement, could you please be more specific?

Also did you see that there is an archiving function that moves completed todos into a done.txt file?

**Comment by gerroon** [comment]
Hi

I was more thinking like dated done.txt (so has versioning based on months ) maybe. 

I am not seeing done.txt option myself here.

thanks

**Comment by velardevines** [comment]
Hello @gerroon, Maybe I do not understand what you are asking. 

Does the Archive feature in Setting meet your needs?  

![image](https://user-images.githubusercontent.com/13563674/111653741-bfbfde00-87cd-11eb-832e-01e585e6d993.png)

**Comment by ransome1** [comment]
@gerroon. I'm sorry but I think without any clear and detailed description of the idea, we can only do guesswork.

**Comment by gerroon** [comment]
I have not used the done.txt method but I assume it will become a one giant done.txt file after couple years of using this method. What I am asking is maybe more like done.txt but done_022021.txt (feb_2021) so that one can distinguish the dones per month. Splitting a giant done.txt is harder then a merging bunch of them later.

thanks

**Comment by ransome1** [comment]
Ok, now I understand. I think it's not a bad idea, yet a very specific use case only few users would actually make use of. Also it raises quite some conceptual questions and therefor would consume a significant amount of developing hours.

If this is a common use case for you, you can workaround this by making use of the archiving function, which moves the completed todos of your "todo.txt" to a "todo_done.txt" file and after this happens, you just rename the "todo_done.txt" file each month one time to something like "2021_03_todo_done.txt".

**Comment by velardevines** [comment]
Excuse me for interjecting again. I accomplish something like @gerroon is requesting by opening the done.txt file then pressing Ctrl-F and enter a search term like "x 2021-02".  This displays all the done tasks for February 2021.

**Comment by ransome1** [comment]
Simple but effective

**Comment by ransome1** [comment]
@gerroon, I hope the workaround @velardevines suggested works for you. As for the feature I think I won't invest any effort in it and therefor will close this feature request.

But sleek is open source and if you have skills in JavaScript, you can work on this feature and contribute it to the project.

**Comment by aleksfadini** [comment]
Has this feature disappeared? I cannot find the archive button anymore in settings.

**Comment by velardevines** [comment]
Shortcut key for Archive feature is A.

**Comment by ransome1** [comment]
@velardevines thanks!

@aleksfadini also if you show completed todos there is a button in each completed item, that will trigger the archiving process. It's also in the main native menu that shows when you press the Alt key.
