### ISSUE TITLE
Anything after "due:xxx" or t:yyy" not shown in list view

### ISSUE THREAD

**Issue by rzw** [ransome1/sleek#657]
## Bug Report

**App Version:** 2.0.9 RC1

**Platform:** Windows 10

**Installation Method:** portable (zip)

**Expected Behavior:**
No matter what the order everything should be shown (description, context, project, due date, threshold etc)

**Actual Behavior:**
Apart from threshold, anything after the due tag is hidden
Anything after threshold is hidden

**Steps to Reproduce:**
Just enter a new event starting with "due:" or "t:"

**Screenshots:**
![image](https://github.com/ransome1/sleek/assets/1249327/c3ed2378-eac8-44c0-9848-a90c3af84036)

**Comment by ransome1** [comment]
@rzw this has been caused by the new markdown parser and is already fixed. It should work as expected in the next pre-release. However, thanks for reporting this.

**Comment by ransome1** [comment]
@rzw could you please check this pre-release, if the bug has been fixed: https://github.com/ransome1/sleek/releases/tag/v2.0.9-rc.2

**Comment by rzw** [comment]
I have switched to RC3. In regard to this bug all is fine (see image below in comparison to bug report. Thank you very much for your continuing efforts.

![image](https://github.com/ransome1/sleek/assets/1249327/bd921816-4369-49ac-8cc4-0a731e132b7e)

**Comment by ransome1** [comment]
Glad to hear, thanks for the reply.
