### ISSUE TITLE
[Snap, Flatpak] Switch to GtkFileChooserNative

### ISSUE THREAD

**Issue by hideosnes** [ransome1/sleek#66]
Would it be possible to add networking rights (on Ubuntu) to be able to access a mounted server. 

I mounted my server on Ubuntu as a drive and it would be amazing to allow colleagues to interact with the ToDo-File there in order to allow several people to manipulate a single ToDo.txt - as in several people can use a joint TodoList.

It would be quite easy, since all sleek needs to do is being able to 'see' mounted servers in 'Files' and communicate with them via the built-in ftp client of Ubuntu. Quite easily sleek could communicate with different people via Google Drive, Dropbox, FTP, etc...

**Comment by ransome1** [comment]
Hi @hideosnes. Do you download sleek from Snap Store?

**Comment by hideosnes** [comment]
Wow, that was a prompt answer :D - thanks for that. I used the Ubuntu Software App.

**Comment by ransome1** [comment]
Hi @hideosnes. Can you tell how your network shares get mounted, my guess is you mount them in /mnt/? When sleek opens your file explorer, what exactly can you see and select?

**Comment by ransome1** [comment]
Also I'm trying to figure out what the source of sleek in the Ubuntu Software App is (I'm on Arch Linux and have no Ubuntu at hand) is. sleek is published in the new Ubuntu (Canonical to be more precise) Store which is called Snap Store. Right now I am assuming the Ubuntu Software App uses Snap Stores apps (Snaps) as sources.

Anyhow, I added a new interface "removeable-media" (https://snapcraft.io/docs/supported-interfaces) to sleek's Snap beta-version. It is suppose to show mounts under /mnt/ and "media". In case your network shares are mounted there, this could provide you with access to those.

To install the beta version of sleek, you need to have **Snap Store** installed, which you can do using the Ubuntu Software App I guess. And then you just open up your terminal and type `sudo snap install --edge sleek`. If this works, feel free to give me a short feedback if it works.

**Comment by hideosnes** [comment]
Alright, I think I figured a few things out:

The Ubuntu Software App is the 'original' Version of the Snap Store - both are developed and maintained by Canonical. I'm using Ubuntu 18 and I think they developed the Snap Store for a more recent version of Ubuntu, however it is still possible to use the it on U18.

I was able to use `sudo snap install --edge sleek` ( though I had to remove my installed version of sleek :D beforehand ) and installed version 0.9.6 (snap store lists 0.9.5 as the latest) so I'm pretty sure I'm using the correct version.

Upon opening sleek I was able to add my old todo.txt (Just to mention, should the question arise: I had to rename the text file I created with sleek and add ".txt" manually because otherwise it wouldn't show up in the file-selector) and still, neither the mounted Google Drive (via Online Accounts) nor the server show up; only my local files stored on my HD (See attached screenshots)

However, I don't think the "removeable-media" is the right interface as it deals with USB devices and physical or virtual HDs (which might be quite useful in any case). From here on I can only speculate that its maybe the "network-manager" interface. It would make sense according to Ubuntu-Reference, though in the snapcraft-docs it doesn't say anything more specific.

I got curious, so I added a question in the snapcraft-forum. I'll keep you updated if that's alright with you.

![sleek-selection](https://user-images.githubusercontent.com/61743691/111905131-7d570500-8a4a-11eb-92e3-76cc16bffe77.png)
![ubuntu-files](https://user-images.githubusercontent.com/61743691/111905132-7f20c880-8a4a-11eb-8910-060e59edb94f.png)

**Comment by ransome1** [comment]
@hideosnes, cool thanks, keep me posted! This might be nice little improvement for many users.

Reading your last comment, I am also considering to enhance sleek on the file creation process. If user don't add a file extension like .txt or .md, sleek can add a .txt per default.

**Comment by ransome1** [comment]
As discussed here https://forum.snapcraft.io/t/question-supported-interface-for-online-accounts-or-mounted-servers/23470/9, until Electron is able to provide the GtkFileChooserNative API (https://github.com/electron/electron/pull/19159), we can't do anything on our side.

Once they finish the enhancement, I will adapt it.

**Comment by hideosnes** [comment]
Thanks a lot! I'll be looking forward to it.

**Comment by ransome1** [comment]
@hideosnes I updated the Snap build process and [since the rewrite of sleek](https://github.com/ransome1/sleek/discussions/501) updates all dependencies, we might want to check if there is a change here. Can you take a quick look if the latest pre-release change anything on your side? You can install it with this: `sudo snap install --edge sleek`

**Comment by ransome1** [comment]
Should be also available in 2.0.2 in stable channel.
