### ISSUE TITLE
When filtering, allow hiding projects that have no open items

### ISSUE THREAD

**Issue by lfrankel** [ransome1/sleek#67]
I use my todo.txt in addition to our company's Jira, as a private tracker where I can put whatever notes and issues relate to a ticket I'm working on without bothering everyone on Jira. I use the Jira ticket number for the Project.

It would be very nice, in the project filter dialog, to be able to hide projects that have no remaining open items. Sometimes it's useful to be able to find ones related to old Jira tickets that I've already closed, but usually I only want to filter to ones that are still open.

I can't tell just by looking at the list which HD-2219, HD-2269, HD-2276, HD-2285, HD-2295 and HD-2296 are, and it'd be super duper useful if I could get it to only list ones that still have incomplete tasks.

**Comment by ransome1** [comment]
Hi @lfrankel, please help me understand: For instance you have a project "HD-2219" and one "HD-2220". Only "HD-2220" has 1 open todo, while "HD-2219" has 0 open and 1 that is close. Like this
![image](https://user-images.githubusercontent.com/11188741/111953201-99a87f80-8ae6-11eb-9c8d-d6845e480144.png)

And you're aiming to hide the "HD-2219" from the filter drawer (I assume you're referring to the side bar and not the suggestion container that opens while you're typing)?

**Comment by lfrankel** [comment]
Yes, you've got it exactly right! :D

**Comment by ransome1** [comment]
I don't know if it is an option for your workflow, but you can hide the completed todos (CMD or Strg + H, or using the "View"-Container) and it will not only hide the todos, but also the projects that have no incomplete todos anymore:
![image](https://user-images.githubusercontent.com/11188741/111955001-3835e000-8ae9-11eb-8564-2e46fede7d9b.png)

**Comment by lfrankel** [comment]
That works too. Thanks!
