### ISSUE TITLE
a Context remaining greyed out in filter menu

### ISSUE THREAD

**Issue by jason-mehmel** [ransome1/sleek#671]
### Important ###
Please follow this template strictly when reporting bugs. 

Reports that do not adhere to this template will not be addressed and will be closed.

**App Version:** Enter the version number, e.g., 1.2.3

2.0.11

**Platform:** Linux

**Installation Method:** Snap

**Expected Behavior:**
Explain what you expected to happen.

I had used a context, and then reset the filters. I expected all of the contexts in the filter menu to become available.

**Actual Behavior:**
Explain what actually happened.

When I tried to reset the filters, one of the contexts remained greyed out.

I can click the context inside one of the task lines, and filter that way, but this is less than optimal!

**Steps to Reproduce:**

(I can't 'reproduce' it since the error is persistent. I do have to different todo.txt tabs open, and they do have different contexts. I have tried resetting everything via `ctrl-0` but the context in question remains greyed out.)

(I have tried quitting and restarting the application, as well as unlinking and re-linking the todo.txt files.)

**Screenshots:**
If applicable, include screenshots that demonstrate the bug.

![Screenshot_2024-02-29_12-36-39](https://github.com/ransome1/sleek/assets/3622823/4d53011e-70da-421d-b471-a98c269b87c1)

**Comment by ransome1** [comment]
@jason-mehmel is there any filter (see filter tab in the drawer) enabled, which could hide todos? Without an example, it is hard to reproduce this.
