### ISSUE TITLE
sleek is often loosing the files

### ISSUE THREAD

**Issue by aisbergde** [ransome1/sleek#675]
### Important ###
Please follow this template strictly when reporting bugs. 

Reports that do not adhere to this template will not be addressed and will be closed.

**App Version:** information not available in the app

**Platform:** Windows

**Installation Method:** App Store

**Expected Behavior:**
File should stay "active" in sleek.

**Actual Behavior:**
sleek is often loosing the files. And then I need to open the file again. sleek also doesn't remember anything. I just get:
![image](https://github.com/ransome1/sleek/assets/9020187/2414ad1c-1f37-49b7-8689-e9e1c785d539)

Also the done.txt will lost.

**Steps to Reproduce:**

it is hard to reproduce, it just happens. I installed sleek today from the app store and it happened several times. Sometimes the file keeps for some hours, sometimes keep looses the file after some minutes.

The files are located in a folder, which is synchronized with my Synology NAS using "Synology Drive"

**Screenshots:**
see above

I used sleek in the past on another PC and it worked fine.

**Comment by ransome1** [comment]
This is most likely connected to the file sync. 

If for example your file sync works in a way that it removes and file and then re-adds it, and there is a gap between those two events, sleeks file watcher (chokidar) understands this as an unlink event rather than a change event. And this then removes the file.

I will add a hidden setting in the next release, that let you decide the threshold time in ms. chokidars default is 100ms, I will lift it to 1000ms as a default and you can play around with it by adding this setting `fileWatcherAtomic`. It accepts an integer.

**Comment by RobLW** [comment]
> This is most likely connected to the file sync.
> 
> If for example your file sync works in a way that it removes and file and then re-adds it, and there is a gap between those two events, sleeks file watcher (chokidar) understands this as an unlink event rather than a change event. And this then removes the file.
> 
> I will add a hidden setting in the next release, that let you decide the threshold time in ms. chokidars default is 100ms, I will lift it to 1000ms as a default and you can play around with it by adding this setting `fileWatcherAtomic`. It accepts an integer.

Sorry if the answer to this question is obvious.
When you say you'll add a hidden setting, where will we need to go in order to alter it please?

I'm also experiencing this problem with files stored on my local drive.
Thanks, really looking forward to the next release.

**Comment by ransome1** [comment]
@RobLW I have not yet found the time to create a new pre-release. Once this has been released you can add the setting ([described here](https://github.com/ransome1/sleek/wiki/Settings#filewatcheratomic)) in the config.json file, which is located in your user data folder. This link helps you finding it: https://github.com/ransome1/sleek/wiki/User-data-folder-location

**Comment by ransome1** [comment]
@RobLW @aisbergde this setting can be tested in the latest [pre-release](https://github.com/ransome1/sleek/releases/tag/v2.0.12-rc.4). Let me know, if this can solve the issue at hand.

**Comment by aisbergde** [comment]
I could not reproduce the issue in the last few days. There was one day, when it happened several times, and there are other days, where the connection is stable.

**Comment by ransome1** [comment]
If this happens in v2.0.12 despite the new settings, feel free to report back here.
