### ISSUE TITLE
Change "Done" button to "Mark as Done"

### ISSUE THREAD

**Issue by intrepidsilence** [ransome1/sleek#69]
Not sure if others have experienced this but when I am busy and trying to 'get things done' I see the Done button and click it to finish editing an item, which of course is wrong. I wonder if changing the verbiage on this button would help prevent it?

Thanks!

**Comment by ransome1** [comment]
Good one, didn't even come to my mind. Will add this and the necessary translations to the next release.

**Comment by intrepidsilence** [comment]
Thanks!

**Comment by ransome1** [comment]
Hi @intrepidsilence. Fyi, if you want to test it, it is already included in https://github.com/ransome1/sleek/releases/tag/v0.9.7-Beta

**Comment by intrepidsilence** [comment]
Nice!  I will check it out.  You rock!

**Comment by intrepidsilence** [comment]
Works as advertised and I think it adds clarity.
