### ISSUE TITLE
Failure in parsing Context tags

### ISSUE THREAD

**Issue by ykis-0-0** [ransome1/sleek#691]
## Bug Report

**App Version:** v2.0.12

**Platform:** Windows

**Installation Method:** App Store

**Expected Behavior:**
sleek should successfully parse todo.txt as follows

```text
2024-03-27 @prjtest Test Project
```

**Actual Behavior:**
sleek completely fails to parse with a popup mentioning
>"Cannot read properties of undefined (reading 'includes')"

![image](https://github.com/ransome1/sleek/assets/64165725/3c4d2edb-dbe6-4221-9d61-953ebabc4c5c)

**Steps to Reproduce:**
1. Prepare the `todo.txt` above
2. Open the `todo.txt` with sleek
3. Observe the unexpected behavior.

**Screenshots:**
If applicable, include screenshots that demonstrate the bug.

**Comment by ransome1** [comment]
@ykis-0-0 I created a todo based on your example and it works without the error. We had something similar a couple of days ago. But it was related to attribute filters. When this happens, are there any attributes selected (in the Attribute tab in drawer)?

**Comment by ykis-0-0** [comment]
Hi, sorry for the late reply.

You're right that there are some updates to the file that invalidated the attribute selectors. A 'Reset Filters' brought the Application back to working state.

Thank you for your help, and may I close this issue as fixed 😄
