### ISSUE TITLE
Autocomplete or Suggested for existing contexts and projects

### ISSUE THREAD

**Issue by jason-mehmel** [ransome1/sleek#7]
Another bit of functionality!

When I create a new task, I'm probably going to assign it to [at]Inbox, and maybe a project if I already know it applies. But because everything is case-sensitive, a typo could lead to problems.

It would be great if either (or both) things could happen:

- When I start typing an @ or a + it will provide me a list of all the contexts or projects that apply to whatever I've typed after that. (For example, if I had +car and +carpark, it would show me those two, because they fit what I'd already started typing) I could then select the filter option that I want, either by selecting it with mouse or arrow keys, or maybe by tab-completing it, or both? (Selecting is probably easiest)

- When a new task is being made, or a current one edited, there was a context and project button to use to apply each of them.

The lists for both of these should be sorted alphanumerically, however they appear!

Let me know how that sounds!

**Comment by ransome1** [comment]
Thanks @jason-mehmel.

- #1 (the type ahead for context and projects) is already on my list, though it might take some time before I can finish that one as it's not trivial and needs some testing.
- As for #2 I am not sure what exactly it means, could you explain it a little further to me please?

**Comment by jason-mehmel** [comment]
I can imagine that Number 1 might take some doing! I'm happy to be a research assistant. I might not know how to implement what I'm reading, but I'm a good searcher! I'm relatively techy with a tiny bit of programming, so given good criteria I might be able to dig something up!

As for Number 2, that means having a section in the New or Edit task window that would show all the available filters, grouped by context and project, sorted alphanumerically. Clicking on those filter options would add the context or tag to the new or edited task line.

(The main goal here is to both save typing common context and projects and to ensure that the risk of a typo is avoided.)

**Comment by ransome1** [comment]
Ah I see. What if we combine these two things? For instance as soon as you start typing an "@" or "+", a list of either contexts or projects would appear below the input field and this list would narrow down the more chars you type after at or plus until you hit the space button?

**Comment by ransome1** [comment]
Plus if you find a nice example on how others implemented it, that would be lovely. Maybe it helps to find the most user friendly solution.

**Comment by jason-mehmel** [comment]
> Ah I see. What if we combine these two things? For instance as soon as you start typing an "@" or "+", a list of either contexts or projects would appear below the input field and this list would narrow down the more chars you type after at or plus until you hit the space button?

This is exactly what I mean, actually! Would you be able to select the context or project by using the arrow keys to navigate?

An example of another app that's implemented this is Qtodotxt. https://github.com/QTodoTxt/QTodoTxt

(There's also a QTodoTxt2, I haven't tried it!)

I think yours is visually more elegant and also yours is doing the process we talked about: removing filter options that don't apply to the remainder of the list as you begin selecting filters.

**Comment by ransome1** [comment]
@jason-mehmel : I created a little prototype of the idea and before I continue spending time into development, I wanted to ask for your opinion. There is a test version in the Snap edge channel, you could download: `snap install --edge sleek`

Looking forward hearing your feedback.

**Comment by jason-mehmel** [comment]
Let me give it a try!

Question though: when I tried that command in my terminal, it told me Sleek was already installed. I'm going to try uninstalling it and then that command to see if I that works!

**Comment by jason-mehmel** [comment]
Okay, that wasn't a question. But it did work! Uninstalling and then executing your command got me the edge channel version.

And it works! It's great! As soon as I type [at] or [+] I see the available options, and it reduces as I type if anything fits those criteria.

I can also tab my way to the options and select them that way, meaning I don't have to take my hands off the keyboard to enter! Great!

Also! I tested typing the name of the option without selecting it, and no problems there. I also was able to type a new option that wasn't included in the options. (For example, I have +tech as a project. I typed +tech and saw the option, but kept typing +techtesting and created a new project tag.)

This is great. I'm very happy with this!

Is there anything else on this functionality that you'd like me to test?

**Comment by ransome1** [comment]
Glad it's useful to you. The best testing would propably be just using the app in your daily life and let me know what works and what does not. Appreciate your feedback! I will do some code clean up in the next couple of days and push the feature to a proper release.

**Comment by jason-mehmel** [comment]
Will do! I'll let you know if I think of any more enhancements or find problems.
