### ISSUE TITLE
Human readable date missing for "in a couple of months"

### ISSUE THREAD

**Issue by RichardJECooke** [ransome1/sleek#701]
## Bug Report

This entry:

```
2024-04-22 haircut due:2024-06-01 rec:40d
```

Has a blank due date if human readable dates are on.

**App Version:** not shown in app

**Platform:**  Linux

**Installation Method:** flathub

**Comment by ransome1** [comment]
@RichardJECooke thanks for reporting this. Could you check if this still happens in the latest pre-release? https://github.com/ransome1/sleek/releases/tag/v2.0.14-rc.1
