### ISSUE TITLE
What is Pomodoro index? 

### ISSUE THREAD

**Issue by konstantin83** [ransome1/sleek#705]
Hi! Thank you for the interesting software, I think I will use it a lot ))
But is there any Docs?
For example I have no clue what is `pomodoro` index in this context and how does `due` and `t` dates work? In other todo apps there is a due date and a reminder time. But here I couldn't figure it out at the start. Also I know what is a pomodoro approach, but what means pomodoro index and how it is used here?

**Comment by ransome1** [comment]
Hello @konstantin83 , please use the discussions for questions. This area is for bug reports and feature requests.

In regards to your question; There is not yet an actual function behind it: https://github.com/ransome1/sleek/wiki/Available-todo.txt-attributes-and-extensions#pomodoro-timer

**Comment by amariusz** [comment]
I like the fact that one can repurpose pm: numeric attribute with custom meaning and have an ability to filter or sort by it. It may still be useful in current form.
