### ISSUE TITLE
Sign the app in Windows and macos with valid developer credentials

### ISSUE THREAD

**Issue by intrepidsilence** [ransome1/sleek#73]
**Is your feature request related to a problem? Please describe.**
It would be great if the app was signed so that the OS does not try to prevent it from running. At least for the official builds.

**Describe the solution you'd like**
Signed binary distributions.

**Describe alternatives you've considered**
Forcing the OS to accept the app works but is not a full solution since it does not allow the app to be remote-switch killed if the repo gets corrupted/compromised.

**Additional context**
NA

**Comment by ransome1** [comment]
Hi @intrepidsilence, signed Windows releases can be downloaded via the Windows Store. 

I can check if I can somehow sign the .exe file on Github with the same credentials as well.

The problem with MacOS is that I dont have a Mac at hand right now and there is a yearly developer fee. The more users sleek gets, the more likely it will be that at some point I might give Apple my little money ;)

**Comment by intrepidsilence** [comment]
Yep, figured. $100 isn't too bad.  And I did not know it was on the Windows Store, so good on you. Thanks

**Comment by intrepidsilence** [comment]
One more comment on this: You need a patreon.  ;)
