### ISSUE TITLE
ToDoTxt.txt that contains all elements of the Specification for testing

### ISSUE THREAD

**Issue by shulist** [ransome1/sleek#74]
@ransome1 In order to test the various applications using  ToDoTxt.txt files I created a test file and have provided it for the the use of Sleek. I think it is complete and it includes the 4 types of recurring tasks that Sleek supports.

**Comment by ransome1** [comment]
Thanks for the file, it has been placed in the assets: https://github.com/ransome1/sleek/blob/master/assets/test.txt
