### ISSUE TITLE
Support for hidden tasks (Call for testing)

### ISSUE THREAD

**Issue by ransome1** [ransome1/sleek#76]
**Is your feature request related to a problem? Please describe.**
As a sleek user I would like to have contexts and projects available as filters and entries in the suggestion container (while typing a new todo) even when there are no actual tasks with the necessary attributes in the todo list.

**Describe the solution**
- Add h:1 to a todo will hide the todo in the list
- Filters and suggestion entries will use the attributes of the hidden todo anyway
- The hidden todo will not be counted in the filter bubble
- Hidden todos can be shown or hidden using a toggle, placed in view container

**Feature is commonly used in other todo.txt apps, for example**
- https://gitlab.gnome.org/GNOME/gnome-todo/-/issues/85
- https://swiftodoapp.com/

**Comment by ransome1** [comment]
# Call for testing
The hidden task feature has been implemented. And although it sounded simple, it brought more complexity with it than I expected. The feature needs testing now and I would really appreciate your feedback.

The hidden task feature is used to hide single tasks but still let their projects and contexts be shown in the filter list and suggestion box, which can be really useful.

To mark a todo as hidden a simple `h:1` has to appended, that carries all the attributes you want to show in the filters. An example:
`h:1 Contexts: @@agendas, @@anywhere, @@calls, @@computer, @@errands, @@home, @@office` 

By default this todo will be hidden but creates the filters:
![image](https://user-images.githubusercontent.com/11188741/112731375-1b5d3a80-8f37-11eb-9415-de883adc9396.png)

To manage the placeholder todos, you need to check the toggle in the view container. The toggle only appears if there is at least one hidden todo:
![image](https://user-images.githubusercontent.com/11188741/112731383-2e700a80-8f37-11eb-842a-2193028b175f.png)

You can now add todos and assign these attributes, which let the count move up:
![image](https://user-images.githubusercontent.com/11188741/112731426-72fba600-8f37-11eb-99ba-a7ffb41989cb.png)

Also the empty filters appear in the suggestion box:
![image](https://user-images.githubusercontent.com/11188741/112731442-89096680-8f37-11eb-8b24-a6bc3d1d0d4e.png)

**Comment by HerrSersch** [comment]
This feature is already proving very useful to me, thanks a lot for adding it :)

I could find two bugs:

1. It's possible to add tasks with the `h:1` tag that contain nothing else except for this tag, or contain only `h:1` plus your projects and contexts like `h:1 @bug @feature`. You then end up with a task that does not show up even if you enable `Hidden todos`. The only way to edit or delete this ghost task is by using a text editor.

sleek should understand that `h:1` is not sufficient for a task description and show the warning text that you usually get when you try to add a task without text.

2. sleek does not notice if there are duplicated hidden tasks. You can add a task like `h:1 Contexts @bug @feature` multiple times without the duplicate warning you would get for regular tasks.

**Comment by ransome1** [comment]
Hi @HerrSersch. Thank you for your feedback. I found the problem and fixed it. The fix will be part of the next release.

**Comment by ransome1** [comment]
Testing completed and fixes will be deployed in 0.9.9
