### ISSUE TITLE
File System doesn't display properly in the Snap version.

### ISSUE THREAD

**Issue by shmu26** [ransome1/sleek#77]
Kubuntu 20.04
I installed the Snap version, and tried to open my todo.txt file, which is in my Home folder.
I was not able to open it because the file system is represented by a bunch of meaningless rectangular boxes, instead of folders and files.

**Comment by ransome1** [comment]
Hi @shmu26. Version 0.9.7 (Revision 311) has just been released in Snap store. Are you experiencing the same problems with that release?

**Comment by ransome1** [comment]
Closed due to lack of response from author
