### ISSUE TITLE
Resizing the flatpak app

### ISSUE THREAD

**Issue by shmu26** [ransome1/sleek#78]
Kubuntu 20.04

1 It would be nice if the Flatpak version could be more resizable. The smallest possible window is still pretty big. The Snap version is much more resizable.

2 Maybe an option to choose font size?

3 I am excited about this great app. Thanks!

**Comment by ransome1** [comment]
Hi @shmu26, both the latest Flatpak and Snap releases are in the building process right now. If you check again in a couple of hours you should see 0.9.7, which propably solves a couple of your issues.

If not I would need to ask you to be more precise about the issues.

**Comment by ransome1** [comment]
@shmu26, the Flatpak update has been release and you can check it out.

**Comment by ransome1** [comment]
Can't reproduce it and author does not reply.
