### ISSUE TITLE
Remember window state

### ISSUE THREAD

**Issue by intrepidsilence** [ransome1/sleek#79]
**Is your feature request related to a problem? Please describe.**
After closing and re-opening the application the window state (size, location, maximized/not) is not remembered and restored.

**Describe the solution you'd like**
Remember and restore the window state on re-open.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by ransome1** [comment]
@intrepidsilence. This function has already been implemented a while ago and is working on my side.

In general it is helpful, if you as much and precise detail as possible on the issue as well as on your OS, version of sleek and so on.

**Comment by intrepidsilence** [comment]
Yes, sorry.  The feature is sort-of working in Windows 10 but not fully. When I close the window and it was maximized and re-open it it is not maximized.

**Comment by ransome1** [comment]
Are you using the .exe file of release v0.9.7 or the most recent version from Windows Store?

**Comment by intrepidsilence** [comment]
I might still be using the beta of 0.9.7 of the exe. Let me update and try it again to verify.

**Comment by ransome1** [comment]
Ok let me know. Tonight I will check my Windows 10 VM if I can reproduce the problem.

**Comment by intrepidsilence** [comment]
Validated the problem exists with Windows 10 and 0.9.7 release ver.  Remember that a maximized window is not the same as a window that happens to be the full size of the screen. Be sure to look at the maximization icon to be sure it is overlapping boxes rather than one box. One box = unmaximized, overlapping = maximized

**Comment by ransome1** [comment]
@intrepidsilence , could you please check this very early Alpha? https://github.com/ransome1/sleek/releases/tag/v0.9.8-Alpha
It contains some adjustments, that were necessary for Windows. Now the window size, window position and fullscreen should be remembered by sleek.

Also on a side note: Can I ask you if you're experiencing trouble with sleeks font on Windows 10 for you?

**Comment by intrepidsilence** [comment]
Trying it now. What about the font should I be testing?

**Comment by intrepidsilence** [comment]
Bingo - window maximize works.

Happy to look for font issues with more detail. Without what to look for I don't see anything glaringly wrong. By I am in the US so we don't use many special characters. :)

**Comment by intrepidsilence** [comment]
Fogot to say "thank you". 

Thank you.

**Comment by ransome1** [comment]
You're welcome ;)

About the font, another Windows user is having issues (https://github.com/ransome1/sleek/issues/71#issuecomment-804292117) with the readability of the font that is used in sleek (FreeSans) and I just wanted to know if others are experiencing similar issues. I think he is having problems reading white text on lila background, maybe in combination with the new zoom function.

**Comment by ransome1** [comment]
Released as part of https://github.com/ransome1/sleek/releases/tag/v0.9.8
