### ISSUE TITLE
[Flatpak] Warnings and non critical errors on Flatpak (ARM64 architecture)

### ISSUE THREAD

**Issue by velardevines** [ransome1/sleek#81]
Hello @ransome1, thanks for suggesting to try the Flatpak install in issue #80. 

Sleek installed and does run using Flatpak. It starts with the following error:

$ flatpak run com.github.ransome1.sleek
[3 zypak-helper] Error retrieving supports property: org.freedesktop.DBus.Error.InvalidArgs: No such property “supports”
[3 zypak-helper] Portal v4 is not available
Success: Language set to: en

However, the good news it Sleek does run even though a little slow which might be because the ARM processor is now very fast.  Sleek runs fast enough to be useable. 

I have not used Sleek extensively on the ARM machine but all functions I tried do work properly.

**Comment by ransome1** [comment]
Happy to hear it works for you now :)

There is little information on those two errors on the interwebs, but from what I find, I can assume it is nothing critical. And has long as sleek can read and write your txt file and also write your settings to it's config file, you should be good to go.

**Comment by velardevines** [comment]
It seems I spoke too soon. Sleek app hung and must be force closed. Errors showing in the Terminal are below:  

$ flatpak run com.github.ransome1.sleek
[3 zypak-helper] Error retrieving supports property: org.freedesktop.DBus.Error.InvalidArgs: No such property “supports”
[3 zypak-helper] Portal v4 is not available
Success: Language set to: en

(sleek:3): libnotify-WARNING **: 15:30:56.435: Failed to connect to proxy

(sleek:3): libnotify-WARNING **: 15:31:21.463: Failed to connect to proxy

(sleek:3): libnotify-WARNING **: 15:31:46.500: Failed to connect to proxy
[11 zypak-sandbox] Dropping 0x16f21250 (3) because of connection closed
[11 zypak-sandbox] Host is gone, preparing to exit...
[11 zypak-sandbox] Quitting Zygote...
wrayhnm@penguin:~$

**Comment by velardevines** [comment]
I'm unable to explain what is happening or what is causing the issue. Sometimes Sleek hangs but if I let it sit for 2-3 minutes then Sleek wakes up and is again functional. During the time Sleek is hung up, these three messages appear in the Terminal window:

(sleek:3): libnotify-WARNING **: 15:59:22.898: Failed to connect to proxy

(sleek:3): libnotify-WARNING **: 15:59:47.926: Failed to connect to proxy

(sleek:3): libnotify-WARNING **: 16:00:12.956: Failed to connect to proxy

 Anyway, this may not be a priority to fix immediately since few people may want to use Sleek on ARM machines. I have a workaround by using SimpleTask for now. 

Here is the full contents of the Terminal window during this session with Sleek|:

wrayhnm@penguin:~$ flatpak run com.github.ransome1.sleek
[3 zypak-helper] Error retrieving supports property: org.freedesktop.DBus.Error.InvalidArgs: No such property “supports”
[3 zypak-helper] Portal v4 is not available
Success: Language set to: en
Info: File has changed

(sleek:3): libnotify-WARNING **: 15:59:22.898: Failed to connect to proxy

(sleek:3): libnotify-WARNING **: 15:59:47.926: Failed to connect to proxy

(sleek:3): libnotify-WARNING **: 16:00:12.956: Failed to connect to proxy
Info: File has changed
Info: File has changed
Info: File has changed
Info: File has changed
Info: File has changed
[11 zypak-sandbox] Dropping 0x28c61250 (3) because of connection closed
[11 zypak-sandbox] Host is gone, preparing to exit...
[11 zypak-sandbox] Quitting Zygote...
wrayhnm@penguin:~$

**Comment by ransome1** [comment]
@velardevines, regarding the lagging/hanging up, I am reading (https://www.alionet.org/index.php?topic=805.0) that libnotify (that throws the warning) can be the cause for it. So what you can try is to deactivate notifications in sleeks settings. 

The zypak errors seem to be quite common even among other apps like Riot (https://www.alionet.org/index.php?topic=805.0). I'm following development on those issues and hopefully find a fix for it at some point.

**Comment by ransome1** [comment]
Also can you provide me with the output of 
`flatpak run -v com.github.ransome1.sleek`

**Comment by velardevines** [comment]
@ransome1, Deactivating Notifications in Settings solves the libnotify Warning problem. Thanks for suggesting that fix. Here is output after Notifications were turned off:

![Screenshot 2021-03-25 11 33 19 AM](https://user-images.githubusercontent.com/13563674/112520102-af28de00-8d60-11eb-8c19-aaf8b733f27c.png)

And here are results of running Sleek with -v parameter:

![Screenshot 2021-03-25 11 47 37 AM](https://user-images.githubusercontent.com/13563674/112520476-1181de80-8d61-11eb-9af1-9b6dc915bff1.png)
