### ISSUE TITLE
Context and project auto completion breaks after saving anything

### ISSUE THREAD

**Issue by HerrSersch** [ransome1/sleek#82]
**Describe the bug**
This bug started appearing in the 0.9.7-beta. Auto completion for projects and contexts does no longer happen after a new task has been added and saved or an existing task has been edited and saved.

**To Reproduce**
1. Restart sleek
2. Make sure you have at least one context available for auto completion. If you haven't, add a new task with a new context and restart sleek, then proceed with step 3
3. Add a new task and press @ to bring up the context suggestions. You will see the context suggestions
5. Save the task. It doesn't matter if you have selected and added one of the contexts or not
6. Now either edit one of the existing tasks or add a new one and bring up the context suggestions again by pressing @
7. There are no more suggestions until you restart sleek

**Additional info**
This seems to be triggered by saving any changes. The bug does only occur if you save changes to a task or save a task you want to add. If you cancel any edits or cancel adding a task the bug does not occur until you save anything. 

**OS**
I could observe it on Win7 and Mint Cinnamon, flatpak and appimage.

**Comment by ransome1** [comment]
@HerrSersch, thanks for your bug report. I tried to reproduce it the way you described it but wasn't able to. Though yesterday, at least for the latest v0.9.7, I was able to break the auto completion by switching between input field and textarea. That I did fix and it should not appear in https://github.com/ransome1/sleek/releases/tag/v0.9.8-Alpha

Could you please do me a favor and open the AppImage of v0.9.8 (do not delete any of your preferences) and check if the error still persists?

**Comment by HerrSersch** [comment]
This is weird, I can't reproduce it on Mint Cinnamon anymore; maybe I was mixing things up. I also don't have the bug on Win10 with the latest v0.9.8-Alpha. Maybe it's specific to Win7.

I've recorded a video with Win7 that shows it working with v0.9.7-Alpha and then the non-working behavior in v0.9.7 and v0.9.8-Alpha. From 1min 15sec onwards you can see that it does not happen if I cancel the dialogue.

https://user-images.githubusercontent.com/35151158/112555902-5f323180-8dc9-11eb-8d00-8cbf9c437d84.mp4

**Comment by HerrSersch** [comment]
I've made some new observations and believe this bug is triggered by expanding the task edit box to multiline input with the arrow icon. I can't test this on Win7 right now, but the same thing I've shown in the video happens on Mint Cinnamon too as soon as the input box is switched to multiline.

I was already wondering, because I could have sworn I had seen this on Mint today too. When you tried to reproduce it on your end you might not have had your edit box expanded and the bug didn't happen.

**Comment by ransome1** [comment]
@HerrSersch  it is possible, that the exe file was not based on the excact code than the AppImage. I rebuild the exe and am curious, if this fixes the problem for you on Windows 7: https://github.com/ransome1/sleek/releases/download/v0.9.8-Alpha/sleek.0.9.8-Alpha.exe

**Comment by HerrSersch** [comment]
Yes, it's fixed now. Thanks a lot, once again :)

**Comment by ransome1** [comment]
Released as part of https://github.com/ransome1/sleek/releases/tag/v0.9.8
