### ISSUE TITLE
Some GUI enhancements

### ISSUE THREAD

**Issue by asitemade4u** [ransome1/sleek#84]
First and foremost, **THANKS** for this amazing software that keeps improving!
I have been using Sleek for the past weeks in a Debian10 Environment, using the Flatpak version and find it outstanding.

Two little GUI things I would love see enhanced though:
- I use Sleek on the side of VSCode and like it to be very thin in order not to take too much screen space. When reducing its width, there is **too much margin on the right side** because of the "View" label on top:

![Screenshot-20210327-105139](https://user-images.githubusercontent.com/11460106/112724625-a7954080-8eea-11eb-886d-70eed374f285.png)

- Would it be possible to leave the **Search Zone** displayed at all time, notably when the (long) list below is scrolled down? That would be very helpful when a long list of bugs is displayed on screen.

Thanks again.
S.

**Comment by ransome1** [comment]
Hi @asitemade4u. Thanks for your suggestion, which sounds useful. I will look into it and will let you know when I found some time to improve it.

**Comment by ransome1** [comment]
Hi @asitemade4u.

I added some refinement to the visualisation of the table and the search bar and you can check those changes in v0.9.9: https://github.com/ransome1/sleek/releases/tag/v0.9.9

I would appreciate your support by testing these changes in your production environment.

**Comment by asitemade4u** [comment]
I will of course as Sleek is my main project management tool! Thanks.

Are they implemented in the Flatpak version (the one I use)?

**Comment by ransome1** [comment]
The Flatpak version (watch out for v0.9.9) has just been built and should be on your computer in a couple of hours.

**Comment by asitemade4u** [comment]
Hi and bravo !

  * I LOVE the sticky search bar on top
  * The collapse button of the sidebar is great too. Eventually I would
    even recommend having an auto-collapse system that would save some
    clicks.
  * I also like the new Settings button and specially the Order by:
    Contexts.

So far, so VERY good. Thanks !

S.

PS. I have some improvement ideas for the filtering system but it can 
wait -- basically being able to select several projects or contexts by 
clicking with a modifier key, same as in qToDo.

**Comment by ransome1** [comment]
Thanks, @asitemade4u. If you have any further suggestions on how to improve the GUI, feel free to open up new feature requests and help me improve the UX.
