### ISSUE TITLE
Add "business day(s)" for recurrence

### ISSUE THREAD

**Issue by Moonbase59** [ransome1/sleek#85]
**Is your feature request related to a problem? Please describe.**
Some other `todo.txt` applications support `b` (business days; Mon-Fri) for recurring events, as in `rec:1b` or `rec:+2b`. I find this quite useful and use it relatively often.

**Describe the solution you'd like**
I’d be grateful if sleek could support `b` for business days, so if I had the entries:
```text
2021-03-27 Test 1: business day rec:1b
```
and
```text
2021-03-27 Test 2: business day rec:1b due:2021-03-27
```
and mark them "Done" on 2021-03-27, it would create these new entries:
```text
2021-03-27 Test 1: business day rec:1b due:2021-03-29
2021-03-27 Test 2: business day rec:1b due:2021-03-29
```
The first variant would create a new `due:` date field implied by the "Done" date (an extension to the standard), the second a regular new entry.

**Describe alternatives you've considered**
—

**Additional context**
For some countries that have Saturday as a work day, it might be advantageous to have a program setting like "Workdays are Mon-Fri" and "Workdays are Mon-Sat".

**Comment by ransome1** [comment]
@Moonbase59 has been released with https://github.com/ransome1/sleek/releases/tag/v1.0.5. I havn't heard from you in a while, so I'm closing.

**Comment by Moonbase59** [comment]
Thanks! Yep, I’ve been active in so many other projects, sorry for the delay.
