### ISSUE TITLE
Please provide the ability to hide tasks due in the future

### ISSUE THREAD

**Issue by Bursus** [ransome1/sleek#86]
It would be very helpful to be able to hide tasks which are due in the future (i.e. to only see tasks which are past due, due today, or with no due date). I currently have a couple dozen recurring tasks, which makes it a bit challenging to quickly see what I need to focus on today, since I need to scroll down to the bottom of the list to see tasks without due dates, and scroll to the top to see those past due or due today.

Thanks so much for creating such a useful application! This is exactly the type of todo.txt application I've been looking for. :)

**Comment by ransome1** [comment]
Hi @Bursus . I am not 100% sure if I understand the issue you're experiencing. I assume you sort the list by due date and not by priority? Like this the todos most likely to be due today or already due in the past are placed at the top of the list. And isn't this what you would like?

**Comment by Bursus** [comment]
Hi @ransome1 . Thanks so much for getting back to me about this! I apologize that I wasn't clearer in my original comment. 

You're correct. I'm sorting the list by due date. The issue I'm facing is that I often have several tasks which can be tackled at any point in time (i.e. which have no due date at all). I also have several recurring tasks due in the future, which I usually don't need to think about until they become due (e.g. tasks reminding me to water plants on certain days, tasks reminding me to file my hours at the end of the month, etc.). 

Since I usually can't act on those types of tasks until their due date, they end up creating quite a bit of visual noise between the tasks which are overdue/due today, and those which have no due date at all, which are at the very bottom of the list.

For example, I might have five tasks due today, 30 tasks due at some point in the future, and 20 tasks which I can tackle at any point in time. When I sort by due date, I see those five tasks which I need to get done today at the top, which is great. Once I finish those though, if I then want to tackle some other tasks, I have to scroll through those 30 future tasks before getting to the ones which I can act on right away.

So, I think what I'm essentially trying to get at is that it would be convenient to be able to filter the list based on any of the following criteria:

1. Tasks which are overdue
2. Tasks which are due today
3. Tasks which are due in the future
4. Tasks which have no due date

With that kind of filtering ability, if I just want to focus on what I can do right now, I'd choose to filter based on #1, #2, and #4. If I wanted to get a sense of all my upcoming commitments, I could then also filter by #3 to see those tasks which are coming my way in the next several days/weeks, which would be a much longer list.

I hope that helps to clarify, and thanks again so much for reaching back out!

**Comment by ransome1** [comment]
Hi @Bursus.

Part of v0.9.9 are three toggles in the new view drawer (a new icon in the navigation will toggle it) that can show or hide todos with due dates today, in the past or in the future. Please feel free to give it some proper testing: https://github.com/ransome1/sleek/releases/tag/v0.9.9

**Comment by Bursus** [comment]
Hi @ransome1.

Thank you! I just downloaded the latest version and tested out various scenarios. Everything seems to be working flawlessly. This was exactly what I had in mind. :)
