### ISSUE TITLE
Time based alert for tasks

### ISSUE THREAD

**Issue by TheAmalShibu** [ransome1/sleek#87]
It would be really great to have a time based alert for particular tasks, like an alert for a scheduled meeting or an alert for something important to do at mentioned time.

The project is great, totally loved it :)

**Comment by ransome1** [comment]
Hi @TheAmalShibu. Even though this feature is not part of the common todo.txt syntax, I like the idea. I added it to the backlog of v1.x.

If you like you can help out doing the conceptual ground work. We need to figure out how we would add it to the todo.txt syntax and how it needs to look like on the interface. 

Also other todo.txt apps already have it implemented and we should research on it to avoid unnecessary work that has already been done elsewhere.

**Comment by dragos240** [comment]
I really like this program. It would be nice to extend the `due:` syntax to support time as well. Look at the ISO format: `YYYY-MM-DDTHH:mm`. You could use that kind of syntax for this with either just a time (by searching for the lack of dashes), a date (without colons) or both (searching for `T` in the string)

**Comment by bluebirch** [comment]
> Look at the ISO format: `YYYY-MM-DDTHH:mm`. You could use that kind of syntax for this with either just a time (by searching for the lack of dashes), a date (without colons) or both (searching for `T` in the string)

Unfortunately, that would break compatibility with other todo.txt apps that also use the `due:` field. I don't know of any other todo.txt apps that use this, so perhaps the best way is to add a Sleek-specific `time:` field or something similar?
