### ISSUE TITLE
[Flatpak] Create and Open Dialog is Not Showing Files/Symlinks from mounted devices

### ISSUE THREAD

**Issue by brianmassen** [ransome1/sleek#89]
**Problem.**
My Documents directory is on a second disk drive, so I have a symlink in my Home directory to Documents. When I try to either create a file or open a file no symlinks appear in the list making it impossible to reach my Documents directory. Also I can't see the mnt directory in the root location so I can't get at my Documents directory that way either.

**To Reproduce**

1. Create s symlink in your home directory pointing to a directory on another drive.
2. Open Sleek and click on create todo.txt.
3. Try to find the target directory via eiher symlink or the mnt directory.

**Expected behavior**
I would expect to see my Documents appear in my Home directory as with any other program.

**Desktop (please complete the following information):**
 - OS: MX-Linux
 - Browser Firefox
 - Version Sleek 0.9.8 (from the MX flathub repo)

**Additional context**
My Documents syncs with my server as a backup so that is where I need the todo.txt file to live.

**Comment by ransome1** [comment]
Hi @brianmassen.

Are you experiencing the same issue with for instance the AppImage (https://github.com/ransome1/sleek/releases/tag/v0.9.9) or the Snap Store release as well?

**Comment by brianmassen** [comment]
I will try the appimage but I can’t run snaps on MX-Linux as snap requires systemd, MX is systemd free.

I’ll let you know what happens.

Brian

**Comment by ransome1** [comment]
Thanks. 

I hope not, but it could be related to https://github.com/ransome1/sleek/issues/66. If that's the case we need to wait until the Electron framework has been enhanced, before we can switch to the portal compatible file chooser.

**Comment by brianmassen** [comment]
I have tried the appimage but can't get it to run, I think its a sandboxing problem with MX-Linux though.

I've installed Sleek from the github .deb download and it runs perfectly. I can see both my Documents and the mnt directories.

If I can be of any further help please let me know

Brian

**Comment by ransome1** [comment]
This issue will be further worked on here, once Electron is ready to provide this function: https://github.com/ransome1/sleek/issues/66
