### ISSUE TITLE
Feature Request: multiple todo.txt files

### ISSUE THREAD

**Issue by fabiansiegel** [ransome1/sleek#9]
I am working with multiple todo.txt files, because I am using that to collaborate other people by syncing it via dropbox.
I would be awesome if switching todo.txt-files would be easier e.g. by having a history of these files.

Thanks a lot for this really nice frontend.

**Comment by ransome1** [comment]
Sounds good, I'll take a look into it. Would you be willing to give it some testing when it's ready?

**Comment by fabiansiegel** [comment]
sure

**Comment by maheshsundaram** [comment]
Hi @ransome1 ! I just found this project - I have been looking for a good todo.txt interface for my laptop for a while and I really like sleek - it really lives up to it's name. 

Anyways, I also use multiple todo.txt files, so I would be willing to test it as well - and if you have a general idea of how you'd like to implement it, or want to pair on it, I'd be glad to help.

**Comment by ransome1** [comment]
What about something like this.

Click on
![Image](https://imgur.com/Oz0jyL9.png)
Would open a window
![Image](https://imgur.com/LvRreqQ.png)
Where you can choose all todo.txt files you selected so far. You would be able to add more files and delete old ones.

UI wise it is nothing fancy yet, but it would get the job done at least for a first release. What do you think?

**Comment by ransome1** [comment]
@fabiansiegel , @maheshsundaram , feel free to take a look at 0.6.0. It has a basic implementation of the screenshot above: https://github.com/ransome1/sleek/releases/tag/v0.6.0

**Comment by fabiansiegel** [comment]
very nice, perfect for me.

I only have one suggestion: the "create new file" only appears if there are no todo.txt files selected, i.e. at the beginning. Once you have one selected, you cannot create a new one.

**Comment by maheshsundaram** [comment]
Looks great!

**Comment by ransome1** [comment]
@fabiansiegel , I added the create file function to the new window. And also you are now able to name your todo file as you wish. Until now it was only possible to literally create one "todo.txt" file, which wouldn't make sense anymore after multiple selection of todo files is now possible.

Please give it some testing and in the meantime I will clean up a bit, before I will release it.

**Comment by fabiansiegel** [comment]
very awesome. It's working without a hitch.
