### ISSUE TITLE
Tasks which only have a project and no context do not appear in the task list (0.9.9)

### ISSUE THREAD

**Issue by samuelznewton** [ransome1/sleek#90]
**Describe the bug**
I just updated to 0.9.9, and many todos are missing entirely.  I haven't done a thorough check, but it seems that the missing todos all have an associated project, but no associated context.

**To Reproduce**
1. open the attached todo.txt file in sleek
[todo.txt](https://github.com/ransome1/sleek/files/6274037/todo.txt)

**Expected behavior**
I expected to see more or less what I've seen for awhile now, a list of all of my todos sorted first by priority, second by completion status, and third by due date.

**Screenshots**
![image](https://user-images.githubusercontent.com/57228129/113923389-1a859d80-97ae-11eb-995a-40e9912310bf.png)
![image](https://user-images.githubusercontent.com/57228129/113923421-24a79c00-97ae-11eb-9279-6531cb4015a6.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: uhhhh what? this is a desktop application
 - Version 20.10

**Comment by samuelznewton** [comment]
Major props to you on having all versions available in so many formats, though.  It is incredibly easy for me to simply use the 0.9.8 AppImage for now. :)

**Comment by ransome1** [comment]
Hi @samuelznewton. Besides completed todos not being sorted at the end (which I would not consider "totally broken"), I don't really understand the issue. I opened your todo.txt file and all of the todos are present. My list looks like the screenshots you attached. Can you describe the issue a bit more please?

**Comment by samuelznewton** [comment]
I'm sorry, you're right, "totally broken" was overstated and uncalled for.  I was very stressed when I wrote that, and I sincerely apologize.

With that said, I would be glad to clarify.

This would probably be better described as two separate issues.  I'll move the one about completed todos being sorted to the end to a new issue and link that shortly.  Here, I'll clarify the other issue.

In the linked todo.txt file, the following lines are all absent when viewed in Sleek:
1, 2, 3, 4, 11, 12, 13, 14, 15, 16, 17, 19....... there are a lot of lines in the file to compare, and doing so is tedious and time-consuming, but it appears to me that any line which has an associated project (e.g. +CS301, +Game) but not an associated context (e.g. @Kindle, @BowlingGreen) is absent in Sleek.  If a line has both a context and a project, a context and no project, or neither, it is visible.

I tried looking at the filter menu to see if there was some sort of filter applied, but my understanding of that menu is that no filters were applied -- at the very least, I believe I understood what the buttons did and that none of them got me any closer to seeing the missing todos.  This very much seems like a filter-related issue, but as far as I can tell (and I could be wrong), it seems like a filter bug.

**Comment by samuelznewton** [comment]
New bug report for the sorting issue [here](https://github.com/ransome1/sleek/issues/91)

**Comment by ransome1** [comment]
@samuelznewton, as for the context bug I found that the third party library, that parses your input into proper todo.txt object, was having difficulties parsing todos that had projects only. I updated the library and it seems to be working, can you please check if the update solves your issue?

https://github.com/ransome1/sleek/releases/tag/v0.9.9-Alpha

**Comment by samuelznewton** [comment]
Yes, as far as I can tell, all todos are showing up in 0.9.9-Alpha, and the issue seems to be fixed.  Thank you! :)

Question: should issues on GitHub generally be closed by the one who opened them (me, in this case) or the one who fixed them (you, in this case)?  I'm fairly new to GitHub, sorry if this is a dumb question.

**Comment by ransome1** [comment]
I don't think it's a dumb question.

In my opinion it should be the person who brought up the bug or the feature request, because he or she can verify best, if the developer did a proper job. So feel free :)

**Comment by samuelznewton** [comment]
Well I think you did a great job, as always. :)
