### ISSUE TITLE
Completed todos no longer sorted to the bottom of the list (0.9.9)

### ISSUE THREAD

**Issue by samuelznewton** [ransome1/sleek#91]
**Describe the bug**
This is not necessarily a bug -- it may have been intentionally removed, in which case this would be a request to add the feature back.  But I'm guessing it's a bug.

As suggested in the title, I'd like for completed todos to be sorted to the bottom of the todo list, as they were in previous versions such as 0.9.8.

**To Reproduce**
1. Open a todo list with due dates, and some completed todos spread throughout.
2. The completed todos will appear based on their due dates.

**Expected behavior**
Completed todos should appear out of the way at the bottom of the list.  Perhaps there could be a setting to toggle this behavior, if people prefer the 0.9.9 behavior.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.10

**Additional context**
Originally reported [here](https://github.com/ransome1/sleek/issues/90)

**Comment by ransome1** [comment]
Hi @samuelznewton, please check https://github.com/ransome1/sleek/releases/tag/v0.9.9-Beta

As default todos will be sorted at the bottom of the todo list. A toggle can be used to change this and sort completed todos inline with the incompleted todos. 

Please give it a try and some testing.

**Comment by samuelznewton** [comment]
The sorting seems to be working as you've described, thank you! :)
I'll use 0.9.9-Beta normally for awhile, and I'll let you know if anything weird happens.
Thank you for your quick work!
