### ISSUE TITLE
when launching : failed to load module "Failed to load module "canberra-gtk-module"

### ISSUE THREAD

**Issue by jason-mehmel** [ransome1/sleek#93]
**Describe the bug**

The program does not launch, in the terminal I receive the error:

```
Gtk-Message: 13:56:42.235: Failed to load module "canberra-gtk-module"
Gtk-Message: 13:56:42.237: Failed to load module "canberra-gtk-module"
Aborted (core dumped)
```

I am running the version installed through snap, Ubuntu Linux 20.04

**To Reproduce**
1. Go to the terminal
2. type 'sleek'
3. See error

**Expected behavior**

Sleek would launch!

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Ubuntu Linux 20.04]
 - Version [0.9.9]

**Additional context**
I checked my repositories, and I'm fairly certain I have the canberra gtk module.

**Comment by ransome1** [comment]
Hello @jason-mehmel.

The "canberra-gtk-module" message is something that popped up from day one and according to my research it is a harmless message that doesn't affect sleek. 

The Snap is running well on my system, but I am not on Ubuntu. Nevertheless I changed something on the build process which might be related. It is undone now and has been pushed to Snap Store as revision 346. Can you please update and let me know what happens?

**Comment by jason-mehmel** [comment]
Interesting! I refreshed and now I'm getting a new error message, in a
window. Attached!

I was away from using Sleek for a few weeks so maybe I'm behind on a few
versions, apologies for not catching it sooner!

~Jason
pronouns: he / him / his
***@***.*** | www.jasonmehmel.com

**Comment by jason-mehmel** [comment]
Attachment coming!

**Comment by ransome1** [comment]
@jason-mehmel, I already saw the error in the latest Snap and pushed the fix for it. Can you please check if it is gone after the recent update?

**Comment by jason-mehmel** [comment]
I will forgo the attachment!

I updated my snap and Sleek is opening again!

Since I'm running the terminal, I did notice this message:

```
(sleek:337221): dbind-WARNING **: 23:36:49.125: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Success: Language set to: en

```
I'm not sure what this means exactly, if there's an accessibility feature that isn't loading or something, but the app appears to be operating cleanly for me.

**Comment by ransome1** [comment]
From what I found out googling it, it seems to be another harmless warning, at least that is what has been reported in the Telegram apps' issues section.

Are you experiencing any issues with sleek after the update?

**Comment by jason-mehmel** [comment]
Not so far! It appears to be operating normally now. I'll keep an eye on it!

(And I'm very slowly getting to my promise of help docs assistance! Some
unexpected mental health challenges sidelined me from January to now.)

~Jason
pronouns: he / him / his
***@***.*** | www.jasonmehmel.com
