### ISSUE TITLE
URLs in Markdown format are not recognized

### ISSUE THREAD

**Issue by asitemade4u** [ransome1/sleek#94]
- Plain Web URLs are well recognized by Sleek: an arrow is appended to the line
- But links expressed in standard Markdown format: `[title](url)` are not recognized which seems illogical to me -- often, users switch between Sleek and a text editor such as VS Code, and their text format of choice is probably going to be Markdown.

**Comment by ransome1** [comment]
@asitemade4u I implemented a markdown parser that will interpret some markdown which is compatible with sleeks interface. Mainly links and emphasis like bold and italic. 

It will be released in v1.0.0 in the next couple of days.

**Comment by asitemade4u** [comment]
Thanks, works very well in version 0.99.
