### ISSUE TITLE
Add build instructions to README.md

### ISSUE THREAD

**Issue by tommyalatalo** [ransome1/sleek#96]
There are no instructions for how to build sleek from source in the repo.
I'm not familiar with the code and would appreciate a simple how-to on building the binary.

**Comment by ransome1** [comment]
@tommyalatalo, no problem, I will add it to the readme in the next release.

**Comment by ransome1** [comment]
Before I add the instructions to the readme, can you please help me and try to build sleek according to these steps?

### Build sleek from source code
1. Setup <a href="https://docs.github.com/en/github/getting-started-with-github/set-up-git">Git</a> and <a href="https://nodejs.org/">node.js</a>
2. Fork sleek `git clone https://github.com/ransome1/sleek.git` and cd into sleeks directory
3. Install dependencies `npm install`
4. Build sleek `npm run dist` (Binaries will be put into the `dist` folder)

If step 3 doesn't install electron builder, let me know. It will need to be installed separately then
4. Install electron-builder `npm install electron-builder --save-dev`

**Comment by tommyalatalo** [comment]
The build does seem to work, however I wonder if there is a command to only build specific binaries, instead of all of them as `npm run dist` does?

**Comment by ransome1** [comment]
It's all setup in the package.json. If you want to build for MacOS only for instance, you would add a script line like this:
` "mac": "electron-builder -m --publish never",`

The -m stand for Mac and you would build it with `npm run mac`. Together with the configuration above, it would build a dmg archive. 

If you want to build for Windows only there is already a script inside. Just run `npm run win`

**Comment by ransome1** [comment]
Btw. did you need to install electron-builder separately or was it sufficient to just do steps 1 to 4?

**Comment by ransome1** [comment]
Has been added.

**Comment by tommyalatalo** [comment]
I didn't need to add electron-builder separately, it seems to get installed when you run `npm install`

**Comment by ransome1** [comment]
perfect, I will remove that extra command from the readme then. Thanks for your feedback.
