### ISSUE TITLE
Define secondary sort order for remainder items from primary sort

### ISSUE THREAD

**Issue by tommyalatalo** [ransome1/sleek#97]
When selecting to sort by priority I noticed that the sorting for items without a priority is a bit odd.
All items that don't have priorities are listed in the **reverse** order that they appear in the todo.txt file.
Is this by design? I feel like it would make more sense to have the non-prioritized items appear in the same order that they are listed in todo.txt, not in the reverse order.

Could a setting be added for this perhaps? There seems to be a valid use case here for selecting a secondary sort order for items without priority when sorting by priority, or for items without due date/project/context when sorting on those.

Even without a setting like above I think the default should be set to display the remainder items as they appear in todo.txt instead of altering their order as sleek does now.

**Comment by ransome1** [comment]
I don't see the need for another setting for this edge case, imo there already too many. 

But I agree with you on the "natural sorting" method according to the order in the file, which will be integrated in 1.0.3.

**Comment by tommyalatalo** [comment]
Yeah I agree with keeping it simple, following the order in the file would still give one control over the order by editing it, so that's a perfectly valid solution.

**Comment by ransome1** [comment]
Hi @tommyalatalo. This behavior is added to the development version of v1.0.3 (https://github.com/ransome1/sleek/releases/tag/v1.0.3). Please feel free to give it a look and let me know if it works as expected.

**Comment by ransome1** [comment]
@tommyalatalo , does the sorting work as expected in v1.0.3?

**Comment by tommyalatalo** [comment]
Yeah, sorry, I missed your reply here, the sorting looked like it followed the file order when I checked it.
